from .labels import the_labels_dict
from .ngrams import the_entity_ngrams
from .parents import the_parents_dict
from .patterns import the_patterns_dict
from .rel_defines_kb import the_rel_defines_dict
from .rel_implies_kb import the_rel_implies_dict
from .rel_infinitive_kb import the_rel_infinitive_dict
from .rel_owns_kb import the_rel_owns_dict
from .rel_parts_kb import the_rel_parts_dict
from .rel_produces_kb import the_rel_produces_dict
from .rel_requires_kb import the_rel_requires_dict
from .rel_runson_kb import the_rel_runson_dict
from .rel_similarity_kb import the_rel_similarity_dict
from .rel_versions_kb import the_rel_versions_dict
from .reverse_synonym import the_reverse_synonym_dict
from .seealso import the_seealso_dict
from .synonym import the_synonyms_dict
