
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_parents_dict = {
    '4-aminobutyrate transaminase': ['enzyme'],
    'a amoebozoa': ['species'],
    'a parasites': ['symbiosis'],
    'a parasitic alveolates': ['parasitic twin'],
    'a phosphoryl group': ['phosphorus monoxide'],
    'a single-celled eukaryotes': ['organism'],
    'a small cytokines': ['small protein'],
    'a vaccine to help the immune system develop protection': ['immune system'],
    'abbvie': ['company'],
    'abnormal growth': ['growth'],
    'acetone': ['organic compound'],
    'acetone–butanol–ethanol fermentation': ['process'],
    'acid': ['chemical compound', 'ion'],
    'acidic': ['oxide'],
    'acidic compound': ['compound'],
    'acidic oxide': ['oxide'],
    'acids': ['oxide'],
    'acoelomorph': ['phylum'],
    'acoelomorpha': ['phylum'],
    'acoelomorphs': ['phylum'],
    'acpd': ['chemical compound'],
    'active site': ['enzyme'],
    'activity': ['root'],
    'adaptive immune system': ['immune system'],
    'adc': ['biopharmaceutical drug'],
    'adenine': ['nucleobase'],
    'adenylate kinase': ['phosphotransferase'],
    'adherence': ['process'],
    'adherence medicine': ['process'],
    'adoption': ['root'],
    'agent': ['root'],
    'agonist': ['chemical substance'],
    'agriculture': ['science'],
    'alanine': ['amino acid'],
    'albumin': ['globular protein'],
    'alcohol': ['organic compound'],
    'alcohols': ['organic compound'],
    'algae': ['organism'],
    'alignment': ['free java implementations'],
    'alkylating agent': ['chemotherapeutic agent'],
    'alternative splicing': ['regulation of gene expression'],
    'alveolate': ['protist'],
    'alveolates': ['protist'],
    'amebae': ['polyphyly'],
    'amide': [   'algorithms for calculating variance',
                 'compound',
                 'ion',
                 'organic compound'],
    'amidicity': ['algorithms for calculating variance'],
    'amination': ['process'],
    'amine': ['compound'],
    'amines': ['compound', 'coordination complex', 'organic compound'],
    'amino': ['compound', 'organic compound', 'process'],
    'amino acid': ['organic compound'],
    'aminoacyl trna synthetase': ['enzyme'],
    'ammine': ['coordination complex'],
    'ammonia': ['nitrogen'],
    'ammonium': ['root'],
    'amoeba': ['unicellular organism'],
    'amoebae': ['polyphyly', 'unicellular organism'],
    'amoebozoa': ['species'],
    "an organism's dna": ['enzyme'],
    'anabolic': ['metabolic pathway'],
    'anabolic steroid': ['root'],
    'anabolism': ['metabolic pathway'],
    'analysis': ['study'],
    'anatomy': ['root'],
    'androgen': ['steroid hormone'],
    'androgens': ['steroid hormone'],
    'angiogenin': ['protein'],
    'animal': [   'flowering plant',
                  'multicelluar organism',
                  'multicellular organism'],
    'animals': ['multicelluar organism', 'multicellular organism'],
    'animation': ["newton's method in optimization"],
    'anime': ["newton's method in optimization"],
    'anise': ['flowering plant'],
    'anoikis': ['programmed cell death'],
    'ant': ['eusociality'],
    'anthracycline': ['chemotherapeutic agent'],
    'anthropology': ['scientific method'],
    'anti-metastatic': ['breast cancer'],
    'anti-metastatic activity': ['programmed cell death'],
    'anti-pd1 therapy': ['immunotherapy'],
    'anti-tumor': ['cancer treatment'],
    'antibiotic': ['drug'],
    'antibody': ['protein'],
    'antibody-drug conjugate': ['biopharmaceutical drug'],
    'antigen-presenting cell': ['cell'],
    'antimicrobial substance active against bacteria': ['drug'],
    'antioxidant': ['compound'],
    'apicomplexa': ['balantidium coli', 'phylum'],
    'archaeol': ['membrane'],
    'archaeon': ['membrane'],
    'art': ['eusociality'],
    'artifact': ['root'],
    'ascomycota': ['phylum'],
    'aspartate': ['4-aminobutyrate transaminase'],
    'aspartate kinase': ['enzyme'],
    'aspartate transaminase': ['4-aminobutyrate transaminase'],
    'aspartokinase': ['enzyme'],
    'assay': ['investigative journalism'],
    'assays': ['investigative journalism'],
    'atom': ['immediate constituent analysis', 'natural philosophy'],
    'atomic mass': ['root'],
    'atomism': ['natural philosophy'],
    'atoms': ['immediate constituent analysis', 'natural philosophy'],
    'atp synthase': ['enzyme'],
    'axillary lymph nodes': ['lymph node'],
    'b cell': ['white blood cell'],
    'bacteria': ['cell', 'prokaryotic microorganism'],
    'bacterial display': ['protein engineering'],
    'bacterial transcription': ['process'],
    'bacterium': ['proteobacteria'],
    'balantidiasis': ['protozoan infection'],
    'balantidium coli': ['parasitic twin'],
    'basal cell carcinoma': ['skin cancer'],
    'base pair': ['unit'],
    'basic structural': ['methodology'],
    'behavioral or mental pattern': ['disease'],
    'benign cancer': ['cancer'],
    'biochemicals': ['process flow diagram'],
    'biochemistry': ['process flow diagram'],
    'bioinformatics': ['interdisciplinarity'],
    'biological cell': ['anatomy', 'structuralism'],
    'biological process': ['process'],
    'biological process by': ['process'],
    'biology': ['natural science'],
    'biomolecule': ['molecule'],
    'biomolecules': ['molecule'],
    'biopharmaceutical drug': ['pharmaceutical drug'],
    'blood': ['body fluid'],
    'blood cell': ['cell'],
    'blood sample': ['clinical sample'],
    'body fluid': ['fluid'],
    'body water': ['root'],
    'bonding electron': ['root'],
    'both proteins': ['biomolecule', 'nutrient'],
    'bradford protein assay': ['assay'],
    'branched-chain alpha-keto acid dehydrogenase complex': [   'protein '
                                                                'quaternary '
                                                                'structure'],
    'brand drug': ['drug'],
    'brand price': ['price'],
    'brand price decrease': ['brand price', 'price decrease'],
    'brand price increase': ['brand price', 'price increase'],
    'breaking a complex topic or substance into smaller': ['study'],
    'breaking down': ['bow down'],
    'breast cancer': ['cancer'],
    'bright field microscopy': ['optical microscopy'],
    'business': [],
    'butanol': ['alcohol'],
    'by cells to increase or decrease the': ['blood cell', 'cell'],
    'cancer': ['disease'],
    'cancer cell': ['cell'],
    'cancer detection': ['detection'],
    'cancer immunotherapy': ['immunotherapy'],
    'cancer model': ['root'],
    'cancer treatment': ['treatment'],
    'capacitor': ['device'],
    'capacitors': ['device'],
    'carbene': ['molecule'],
    'carbohydrate': ['biomolecule'],
    'carbohydrate metabolism': ['process'],
    'carbohydrates': ['biomolecule'],
    'carbon': ['molecule', 'periodic table'],
    'carboximidate': ['organic compound'],
    'carcinoma mouse models': ['neuroendocrine tumor'],
    'cartesian coordinate system': ['coordinate system'],
    'cartesian coordinates': ['coordinate system'],
    'casein': ['phosphoprotein'],
    'catabolism': ['metabolic pathway'],
    'catalase': ['enzyme'],
    'catalysed': ['enzyme'],
    'catalyst': ['numb'],
    'catalysts': ['numb'],
    'catalyze': ['fusion power'],
    'catalyzing': ['fusion power'],
    'causes of cancer': ['disease'],
    'cdna': ['molecular cloning'],
    'cdna library': ['molecular cloning'],
    'cefalexin': ['antibiotic'],
    'cell': ['anatomy', 'structuralism'],
    'cell adhesion': ['process'],
    'cell biology': ['biology'],
    'cell component': ['root'],
    'cell culture': ['process'],
    'cell cycle': ['cell component'],
    'cell membrane': ['biological membrane'],
    'cell or unicellular organism': ['organism'],
    'cellular compartment': ['cell component'],
    'cellular compartments': ['cell component'],
    'cercozoa': ['eukaryote'],
    'chalcogen': ['the chemical brothers'],
    'chaperome': ['proteomics'],
    'chaperone': ['protein'],
    'chaperones': ['proteomics'],
    'charophyta': ['cyanobacteria'],
    'chemical': ['matter', 'substance'],
    'chemical bond': ['bonding electron'],
    'chemical compound': ['chemical substance', 'compound'],
    'chemical conformation': ['stereoisomerism'],
    'chemical element': ['atom'],
    'chemical element with the symbol o atomic number it is_a member': [   'chemical '
                                                                           'element'],
    'chemical elements': ['atom'],
    'chemical energy': ['energy'],
    'chemical reaction': ['process'],
    'chemical reaction in': ['process'],
    'chemical substance': ['matter', 'substance'],
    'chemokine': ['cytokine'],
    'chemosynthesis': ['biological warfare'],
    'chemotherapeutic agent': ['drug'],
    'chemotherapy': ['cancer treatment'],
    'chevrotain': ['ungulate'],
    'chimera ': ['protein'],
    'chimeric antigen receptor t cell': ['t cell'],
    'chloroplast dna': ['dna'],
    'cholera': ['infection'],
    'chromosome': ['nucleic acid sequence'],
    'chromosomes': ['nucleic acid sequence'],
    'ciliate': ['protozoa'],
    'ciliates': ['protozoa'],
    'cis-regulatory element': ['non coding dna'],
    'clade': ['organism'],
    'clinical sample': ['sample'],
    'clinical study': ['pharmaceutical formulation', 'study'],
    'clinical study design': ['pharmaceutical formulation', 'study'],
    'cloned': ['process'],
    'cloning': ['process'],
    'collagen': ['protein'],
    'colon cancer': ['cancer'],
    'colon carcinoma': ['cancer'],
    'colonial green algae': ['xenoturbellids'],
    'colorectal cancer': ['cancer'],
    'commonly prescribed': ['antibiotic'],
    'company': ['root'],
    'compound': ['root'],
    'computation': ['calculation'],
    'computer': ['activity', 'calculation', 'designing women'],
    'computer programming': ['designing women'],
    'computer science': ['process'],
    'computing': ['activity', 'designing women'],
    'condition': ['root'],
    'conformational isomerism': ['stereoisomerism'],
    'connective tissue': ['mai basic four'],
    'conoid': ['ruled surface'],
    'conosa': ['amoebozoa'],
    'conserved': ['sequence'],
    'conserved sequence': ['sequence'],
    'considered': ['ruled surface'],
    'coordinate system': ['system'],
    'crab-eating macaque': ['primate'],
    'cribriform morphology': ['morphology'],
    'cross-coupling reaction': ['reaction'],
    'crude lysate': ['breaking down'],
    'cryoelectron microscopy': ['cryogenic electron microscopy'],
    'crystal': ['process', 'standard linear solid model'],
    'crystallization': ['process'],
    'cud': ['food'],
    'cyanobacteria': ['phylum'],
    'cytokine': ['small protein'],
    'cytoplasm': ['cell component'],
    'cytoskeletal disruptor': ['chemotherapeutic agent'],
    'cytoskeletal motor proteins': ['molecular motor'],
    'cytosol': ['cell component'],
    'cytotoxic activity': ['activity'],
    'cytotoxic t cell': ['t cell'],
    'cytotoxicity': ['toxic'],
    'd nits': ['physical organization'],
    'd proteome balance': ['large-scale brain networks'],
    'd silurian period': ['geological period'],
    'data': ['individual'],
    'daunorubicin': ['anthracycline'],
    'daytona prototype': ['auto racing'],
    'dehydration': ['body water'],
    'demo1': ['activity'],
    'denaturation': ['process'],
    'deoxyribonucleic acid molecule with part or all': ['structure'],
    'deoxyribonucleotide': ['monomer'],
    'deoxyribonucleotides': ['monomer'],
    'detection': ['analysis'],
    'device': ['root'],
    'diabetes': ['metabolic disorder'],
    'diet': ['eating'],
    'dietary fiber': ['food'],
    'dieting': ['eating'],
    'dirigent protein': ['protein'],
    'disaccharide': ['glycosidic bond'],
    'disease': ['condition'],
    'distributed computing': ['computer science'],
    'disulfide bond': ['protein'],
    'disulfide bond formation protein b': ['protein'],
    'dna': ['gene', 'molecular cloning', 'molecule', 'polymer', 'protein'],
    'dna polymerase': ['enzyme'],
    'dna repair': ['process'],
    'dna replication': ['biological warfare'],
    'dna sequence': ['scientific instrument'],
    'dna sequencer': ['scientific instrument'],
    'dna-binding protein': ['protein'],
    'dnaa': ['protein'],
    'dnah': ['gene'],
    'dnai': ['protein'],
    'dnan': ['gene'],
    'dnax': ['gene'],
    'downregulation and upregulation': ['process'],
    'doxorubicin': ['anthracycline'],
    'drug': ['chemical substance'],
    'dual polarisation interferometry': ['analytical technique'],
    'dual-polarization interferometry': ['analytical technique'],
    'ductal morphology': ['morphology'],
    'dynein': ['motor protein'],
    'earth': ['planet'],
    'eating': ['food'],
    'echinamoebidae': ['amoebozoa'],
    'edestin': ['cud'],
    'elastin': ['protein'],
    'electromagnetism': ['physics'],
    'elemental analysis': ['process'],
    'encodes': ['scientific method'],
    'endogenous': ['process'],
    'endogeny': ['process'],
    'endonuclease': ['enzyme'],
    'endoplasmic reticulum': ['organelle'],
    'energy': ['quantitative research'],
    'entity': ['root'],
    'enzyme': ['protein'],
    'enzyme found': ['protein'],
    'enzyme kinetics': ['study'],
    'eosin': ['fluorescent acidic compound', 'histologic stain'],
    'epigenetics': ['study'],
    'epirubicin': ['anthracycline'],
    'epothilone': ['chemotherapeutic agent'],
    'essential amino': ['amino acid'],
    'essential amino acid': ['amino acid'],
    'essential amino acids': ['amino acid'],
    'essential fatty acid': ['fatty acid'],
    'essential nutrients for the human body': ['substance'],
    'ester': ['organic compound'],
    'ethanol': ['chemical compound', 'chemical formula'],
    'ethanol fermentation': ['biological process'],
    'ethenol': ['alcohol'],
    'ethynol': ['alcohol'],
    'eukaryote': ['organism'],
    'eukaryotes': ['organism'],
    'eukaryotic': ['process'],
    'eukaryotic organelle': ['cell component'],
    'eukaryotic transcription': ['process'],
    'evolutionarily conserved protein domain': ['conserved sequence'],
    'exocrine gland': ['gland'],
    'experimental system': ['root'],
    'expiration': ['activity'],
    'extremophile': ['organism'],
    'extremophilic': ['organism'],
    'fact': ['root'],
    'fermentation': ['metabolism'],
    'filtration': ['root'],
    'flabellinia': ['amoebozoa'],
    'fluid': ['anatomy', 'substance'],
    'fluids': ['anatomy', 'substance'],
    'fluorescent acidic compound': ['acidic compound'],
    'for molecules': ['electric charge'],
    'force': ['interaction'],
    'form': ['interaction'],
    'fourier-transform infrared spectroscopy': ['spectroscopy'],
    'fusion protein': ['protein'],
    'gamete': ['ploidy'],
    'gencode': ['scientific method'],
    'gene': ['biology'],
    'generic drug': ['drug'],
    'genes': ['biology'],
    'genetic disorder': ['disease'],
    'genetics': ['biology'],
    'genome sequencing': ['process'],
    'genus': ['taxonomic rank'],
    'geologic period': ['time'],
    'geological period': ['time'],
    'geometry': ['mathematics'],
    'gland': ['anatomy'],
    'gland structure': ['structure'],
    'gleason grading system': ['grading system'],
    'glycine': ['amino acid'],
    'glycines': ['amino acid'],
    'glycosylamine': ['biochemistry'],
    'glycosylamines': ['biochemistry'],
    'gold': ['symbol'],
    'grading system': ['system'],
    'gram-negative bacteria': ['bacteria'],
    'gram-negative proteobacteria': ['gram-negative bacteria', 'phylum'],
    'green algae': ['xenoturbellids'],
    'growth': ['activity'],
    'hair removal': ['methodology'],
    'haploid cell': ['cell'],
    'head lice infestation': ['national institutes of technology'],
    'health science': ['science'],
    'healthy cell': ['cell'],
    'hematological': ['body fluid'],
    'hematoxylin': ['chemical compound', 'histologic stain'],
    'heritable phenotype changes': ['study'],
    'heterokont': ['eukaryote'],
    'heterokontae': ['very important person'],
    'heterokonts': ['very important person'],
    'highly-digestible': ['food'],
    'histologic stain': ['stain'],
    'histology': ['study'],
    'histopathological image': ['image'],
    'histopathology': ['pathology'],
    'horse': ['root'],
    'human': ['animal'],
    'humans': ['animal'],
    'hushing': ['ancient history'],
    'hydrogen': ['atomic mass'],
    'hydrolysis': ['chemical reaction'],
    'idarubicin': ['anthracycline'],
    'il-15 receptor': ['type i cytokine receptor'],
    'il-15rα': ['interleukin'],
    'illness': ['condition'],
    'image': ['artifact'],
    'image analysis': ['analysis'],
    'images': ['artifact'],
    'imidate': ['organic compound'],
    'immune response': ['response'],
    'immune system': ['root'],
    'immunology': ['biology'],
    'immunotherapy': ['root'],
    'in vivo': ['study'],
    'individual entity': ['entity', 'weak entity'],
    'infectious disease': ['disease'],
    'inflammation': ['personal protective equipment'],
    'inflammatory chemokines': ['cytokine'],
    'innate immune system': ['adaptive immune system', 'immune system'],
    'instrument': ['methodology'],
    'instrumentalism': ['methodology'],
    'interleukin': ['cytokine'],
    'interleukin 15': ['interleukin'],
    'interleukin 2': ['interleukin'],
    'interleukin-15 receptor': ['type i cytokine receptor'],
    'interleukin-2': ['interleukin'],
    'investment': ['root'],
    'ion': ['atoms in molecules'],
    'ions': ['atoms in molecules'],
    'iso': ['iso 6344'],
    'iso 8601': ['iso 6344'],
    'isobutanol': ['structural formula'],
    'isobutyl': ['alkyl nitrites'],
    'isobutyl nitrite': ['alkyl nitrites'],
    'jaligner': ['free java implementations'],
    'kinase': ['enzyme'],
    'large biomolecules': ['molecule'],
    'laser': ['device'],
    'lead': ['symbol'],
    'leads': ['symbol'],
    'legume': ['plant'],
    'legumin': ['meat glue'],
    'levacetylmethadol': ['opiod'],
    'lewis lung carcinoma': ['neuroendocrine tumor'],
    'lice': ['national institutes of technology'],
    'life': ['national institutes of technology'],
    'ligand': ['ion'],
    'ligase': ['enzyme'],
    'linguistics': ['scientific method'],
    'lipid': ['biomolecule'],
    'lipid bilayer': ['membrane'],
    'lipid layer': ['membrane'],
    'lipids': ['biomolecule'],
    'liver': ['organ'],
    'lives': ['national institutes of technology'],
    'living': ['organ'],
    'lobosa': ['taxonomic rank'],
    'lobose': ['taxonomic rank'],
    'lung cancer': ['cancer'],
    'lymph node': ['organ'],
    'lymphocyte': ['white blood cell'],
    'lymphocytes': ['white blood cell'],
    'lysis': ['breaking down'],
    'machine': ['device'],
    'macromolecule': ['molecule'],
    'main core membrane': ['cell component'],
    'male gamete': ['ploidy'],
    'male reproductive system': ['reproductive system'],
    'malignant cancer': ['cancer'],
    'malignant cell': ['cell'],
    'malignant prostate cell': ['malignant cell', 'prostate cell'],
    'maser': ['device'],
    'mass': ['measurement'],
    'material': ['monism'],
    'materialism': ['monism'],
    'matter': ['substance'],
    'meat glue': ['substance'],
    'mechanics': ['physics'],
    'mechanisms': ['chemical formula'],
    'medical device': ['device'],
    'medical devices': ['device'],
    'medical image': ['image'],
    'medical image analysis': ['image analysis', 'medical image'],
    'medical study': ['study'],
    'medication': ['drug'],
    'medicine': ['science'],
    'melanoma': ['cancer'],
    'membrane': ['cell component'],
    'membrane-bound organelle': ['cell component'],
    'memory cd8 t cell': ['t cell'],
    'memory t cell': ['t cell'],
    'mental disorder': ['disease'],
    'mental illness': ['disease'],
    'metal ammine complex': ['coordination complex'],
    'metastatic breast cancer': ['breast cancer'],
    'methabol': ['androgen'],
    'methadol': ['opiod'],
    'methane': ['chemical formula'],
    'methanol': ['androgen', 'chemical formula', 'opiod'],
    'methionine': ['essential amino acid'],
    'microfiltration': ['filtration'],
    'microorganism': ['organism'],
    'microorganisms': ['organism'],
    'microscope': ['medical device', 'study'],
    'microscopic organism': ['organism'],
    'microscopy': ['study'],
    'microsoft exchange server': ['list of mail server software'],
    'microtubule': ['tubulin'],
    'microtubules': ['tubulin'],
    'mitochondria': ['dna'],
    'mitochondrial': ['dna'],
    'mitochondrial dna': ['dna'],
    'mitosis': ['cell cycle'],
    'mitoxantrone': ['anthracycline'],
    'mold': ['fungus'],
    'molds': ['fungus'],
    'molecule': ['electric charge'],
    'molecules': ['electric charge'],
    'monitoring': ['activity'],
    'monomer': ['molecule'],
    'monomers': ['molecule'],
    'morphology': ['situation'],
    'motor protein': ['molecular motor'],
    'mouse model': ['experimental system'],
    'mouse model of colorectal and intestinal cancer': ['experimental system'],
    'mouse tumor models': ['cancer model'],
    'multi-subunit': ['number'],
    'multicelluar organism': ['organism'],
    'multicellular eukaryotic organisms': ['organism'],
    'multicellular organism': ['organism'],
    'muon-catalyzed fusion': ['fusion power'],
    'muscle': ['soft tissue'],
    'national institutes of technology': ['physical organization'],
    'native metal': ['metal'],
    'natural': ['bernard malamud'],
    'natural killer cell': ['cytotoxic t cell'],
    'natural or synthetic steroid hormone': ['steroid'],
    'nature': ['bernard malamud', 'the natural'],
    'nbpf15': ['protein'],
    'neoplasm': ['abnormal posturing'],
    'neoplasms': ['abnormal posturing'],
    'neuroendocrine tumor': ['neoplasm'],
    'neutron': ['subatomic particle'],
    'nitrate': ['ammonium'],
    'nitrite': ['ammonium'],
    'nitrogen': ['symbol'],
    'nitrogen-containing biological compounds': ['symbol'],
    'non coding dna': ['pfu dna polymerase'],
    'noncoding dna': ['pfu dna polymerase'],
    'nuclease': ['enzyme'],
    'nucleic acid sequence': ['structure'],
    'nucleobase': ['nitrogen'],
    'nucleobases': ['nitrogen'],
    'nucleoside': ['glycosylamine'],
    'nucleosides': ['glycosylamine', 'molecule'],
    'nucleotide': ['molecule'],
    'nucleotides': ['glycosylamine', 'molecule'],
    'nutrient': ['substance'],
    'nutrients': ['substance'],
    'obesity': ['disease'],
    'odor': ['thing'],
    'officer': ['united states armed forces'],
    'opiod': ['drug'],
    'optical microscopy': ['microscopy'],
    'optics': ['physics'],
    'organ': ['anatomy'],
    'organ only': ['anatomy'],
    'organelle': ['cell component'],
    'organelles': ['cell component'],
    'organism': ['entity', 'weak entity'],
    'organism with optimal': ['organism'],
    'organisms': ['entity', 'weak entity'],
    'organization': ['entity', 'weak entity'],
    'oxidant': ['compound'],
    'oxidation': ['chemical compound', 'dietary fiber'],
    'oxide': ['chemical compound'],
    'oxides': ['chemical compound'],
    'oxidized': ['dietary fiber'],
    'oxidized cellulose': ['dietary fiber'],
    'oxidoreductase': ['enzyme'],
    'oxoacid': ['chemical compound'],
    'oxygen': ['period 6 element'],
    'oxymetholone': ['androgen'],
    'pain': [],
    'pancreas': ['organ'],
    'pancreatitis': ['condition'],
    'parasitic': ['process', 'result'],
    'parasitic alveolates': ['parasitic twin'],
    'parasitic twin': ['process', 'result'],
    'parasitism': ['symbiosis'],
    'particular abnormal condition': ['condition'],
    'patent': ['root'],
    'patent expiration': ['expiration'],
    'pathogen': ['agent'],
    'pathogenic bacteria': ['bacteria', 'pathogen'],
    'pathogens': ['agent'],
    'pathology': ['medical study'],
    'patient adherence': ['process'],
    'patient derived xenograft': ['cancer model'],
    'patient monitoring': ['monitoring'],
    'pd-1': ['protein'],
    'pd-l1': ['protein'],
    'pediculosis': ['head lice infestation'],
    'pelvis': ['root'],
    'peptide': ['peptidomimetic'],
    'peptides': ['peptidomimetic'],
    'peptoid': ['peptidomimetic'],
    'period': ['process'],
    'period 6 element': ['chemical element'],
    'periodization': ['process'],
    'peripheral blood lymphocyte': ['lymphocyte'],
    'peripheral blood lymphocytes': ['lymphocyte'],
    'pfu dna polymerase': ['enzyme'],
    'ph': ['scale'],
    'pharmaceutical drug': ['drug'],
    'pharmaceutical formulation': ['process'],
    'pharmaceutical science': ['science'],
    'pharmaceutical sciences': ['science'],
    'pharmacodynamic': ['study'],
    'pharmacodynamics': ['study'],
    'pharmacology': ['pharmacy'],
    'pharmacy': ['science'],
    'phosphate': ['chemical substance'],
    'phosphoprotein': ['protein'],
    'phosphoproteins': ['protein'],
    'phosphoryl group': ['phosphorus monoxide'],
    'phosphorylation': ['phosphoryl group'],
    'phosphotransferase': ['enzyme'],
    'photosynthesis': ['process'],
    'phototransduction': ['transduction'],
    'phylum': ['taxonomic rank'],
    'physical object': ['matter'],
    'physical organization': ['organization'],
    'physiology': ['scientific method'],
    'planula': ['motility'],
    'plastid': ['organelle'],
    'plastids': ['organelle'],
    'ploidy': ['cell'],
    'poison': ['substance'],
    'poisonous substance produced': ['substance'],
    'polymer': ['molecule'],
    'polymerase': ['enzyme'],
    'polymeric molecule': ['molecule'],
    'polynucleotide': ['biopolymer'],
    'polyphyly': ['root'],
    'positive-sense single-stranded rna virus': ['virus'],
    'price': ['root'],
    'price decrease': ['price'],
    'price increase': ['price'],
    'primate': ['root'],
    'process': ['root'],
    'product promotion': ['promotion'],
    'program': ['designing women'],
    'prokaryote': ['unicellular organism'],
    'prokaryotes': ['process', 'unicellular organism'],
    'prokaryotic': ['process'],
    'prokaryotic microorganism': ['microorganism'],
    'prokaryotic translation': ['process'],
    'promotion': ['root'],
    'prostate': ['exocrine gland'],
    'prostate cancer': ['cancer'],
    'prostate cell': ['cell'],
    'prostate histopathology': ['histopathology'],
    'prostate histopathology image': [   'histopathological image',
                                         'prostate histopathology'],
    'prostate pathology': ['pathology'],
    'prostatectomy specimen': ['specimen'],
    'protein': ['biomolecule', 'nutrient'],
    'protein domain': ['conserved sequence'],
    'protein quaternary structure': ['number'],
    'protein substance analogous to the': ['substance'],
    'proteinogenic amino acid': ['amino acid'],
    'proteins': ['biomolecule', 'nutrient'],
    'proteobacteria': ['gram-negative bacteria', 'phylum'],
    'proteomics': ['large-scale brain networks'],
    'proteostasis': ['concept'],
    'proteus': ['proteobacteria'],
    'protist': ['root'],
    'proton': ['subatomic particle'],
    'protonated': ['proton'],
    'protonation': ['proton'],
    'protons': ['subatomic particle'],
    'protozoan': ['parasitic disease'],
    'protozoan infection': ['parasitic disease'],
    'protozoans': ['parasitic disease'],
    'psychology': ['science'],
    'pyridoxal phosphate -dependent transaminase enzyme': ['enzyme'],
    'pyrococcus furiosus': ['extremophile'],
    'quaternary structure': ['number'],
    'reaction': ['activity'],
    'receptor': ['chemical structure'],
    'redox': ['chemical reaction'],
    'regulated process during gene expression': ['white blood cell'],
    'regulation of gene expression': ['white blood cell'],
    'regulatory t cell': ['t cell'],
    'remote patient monitoring': ['monitoring'],
    'renca renal cell': ['process'],
    'repeated': ['thermal'],
    'report': ['root'],
    'reporter gene': ['gene'],
    'reproduction': ['biological process'],
    'reproductive system': ['sex organ'],
    'reptation': ['thermal'],
    'research investment': ['investment'],
    'resonance': ['electric power conversion'],
    'resonant': ['electric power conversion'],
    'resonant converter': ['electric power conversion'],
    'response': ['activity'],
    'restriction enzyme': ['enzyme'],
    'retinoid': ['chemotherapeutic agent'],
    'ribonuclease': ['nuclease'],
    'ribonuclease a': ['nuclease'],
    'ribonuclease inhibitor': ['acidic oxide'],
    'ribonucleases': ['nuclease'],
    'rli-15': ['interleukin'],
    'rna': ['enzyme', 'molecule', 'polymer'],
    'rna molecule': ['polymer'],
    'rna splicing': ['post-transcriptional modification'],
    'rna-dependent rna polymerase': ['enzyme'],
    'ruled surface': ['root'],
    'ruminant': ['mammal'],
    'rush': ['ancient history'],
    'sample': ['artifact'],
    'scale': ['root'],
    'scalp': ['pelvis'],
    'scanning machine': ['machine'],
    'schizophrenia': ['mental disorder'],
    'science': ['science and technology'],
    'science and technology': ['topic'],
    'scientific instrument': ['device'],
    'selective barrier': ['cell component'],
    'sequence': ['root'],
    'series': ['proteinogenic amino acid'],
    'serine': ['proteinogenic amino acid'],
    'sex organ': ['organ'],
    'silurian': ['geological period'],
    'situation': ['root'],
    'skeleton': ['structure'],
    'skin cancer': ['cancer'],
    'slide': ['artifact'],
    'small 123 amino acid protein': ['biomolecule', 'nutrient'],
    'small infectious agent': ['agent'],
    'small protein': ['protein'],
    'societies': ['individual'],
    'society': ['individual'],
    'sociology': ['society'],
    'solvent': ['substance'],
    'space': [],
    'specialized subunit': ['cell component'],
    'specimen': ['artifact'],
    'spectroscopy': ['study'],
    'sperm': ['cell'],
    'spermatozoa': ['sperm'],
    'spermatozoon': ['sperm'],
    'stain': ['compound'],
    'starch': ['carbohydrate'],
    'state': ['root'],
    'stereoisomerism': ['isomer'],
    'steroid hormone': ['steroid'],
    'structural formula': ['root'],
    'structuralism': ['methodology'],
    'structure': ['arrangement'],
    'study': ['root'],
    'subatomic particle': ['particle'],
    'subphylum': ['taxonomic rank'],
    'substance': ['matter', 'root'],
    'succession of base-pairs': ['structure'],
    'sugar': ['hair removal'],
    'sugaring': ['hair removal'],
    'sulfur oxoacid': ['chemical compound'],
    'superagonist': ['agonist'],
    'sushi domain': ['protein domain'],
    'sushi+ domain': ['protein domain'],
    'symbiosis': ['root'],
    'system of sex organs': ['organ'],
    'systematic enterprise': ['topic'],
    't cell': ['lymphocyte'],
    'taxonomic rank': ['root'],
    'testate amoebae': ['polyphyly'],
    'testosterone': ['transgender hormone therapy'],
    'the catalyst': ['numb'],
    'the cells': ['anatomy', 'structuralism'],
    'the natural': ['bernard malamud'],
    'the only extant members': ['ungulate'],
    'thermodynamics': ['physics'],
    'time': ['root'],
    'tissue': ['anatomy'],
    'tissues with similar functions': ['anatomy'],
    'topic': ['root'],
    'toxic': ['condition'],
    'toxicant': ['substance'],
    'toxicants': ['substance'],
    'toxin': ['poison', 'substance'],
    'toxins': ['poison'],
    'transaminase': ['enzyme'],
    'transaminases': ['enzyme'],
    'transcriptome': ['rna', 'rna-dependent rna polymerase'],
    'transmembrane receptors expressed on the': ['t cell'],
    'transmission electron cryomicroscopy': ['cryogenic electron microscopy'],
    'treatment': ['activity'],
    'trial phase': ['clinical study design'],
    'trna': ['enzyme'],
    'troubleshoot': ['problem solving'],
    'troubleshooting': ['problem solving'],
    'tumor': ['neoplasm'],
    'tumor cell': ['cell'],
    'two main immunity strategies': ['immune system'],
    'type i cytokine receptor': ['chimeric antigen receptor t cell'],
    'type of agonist': ['chemical substance'],
    'ultrasound': ['image'],
    'ungulate': ['animal'],
    'unicellular organism': ['organism'],
    'unit': ['root'],
    'universe': ['space'],
    'urosporidae': ['balantidium coli'],
    'ustilaginomycotina': ['basidiomycota'],
    'vaccination': ['adaptive immune system'],
    'vaccine': ['biopharmaceutical drug'],
    'vacuolaria': ['cell cycle'],
    'vacuole': ['organelle'],
    'vahlkampfiidae': ['percolozoa'],
    'valrubicin': ['anthracycline'],
    'vampyrellidea': ['eukaryote'],
    'vannellidae': ['amoebozoa'],
    'vannellina': ['amoebozoa'],
    'variosea': ['amoebozoa'],
    'varipodida': ['amoebozoa'],
    'vaucheriales': ['very important person'],
    'vault': ['organelle'],
    'vermamoebidae': ['amoebozoa'],
    'verrucomicrobia': ['bacteria'],
    'vetches': ['flowering plant'],
    'vexilliferidae': ['amoebozoa'],
    'vicia': ['flowering plant'],
    'viral eukaryogenesis': ['hypothesis'],
    'virus': ['pathogen'],
    'viruses': ['pathogen'],
    'visual phototransduction': ['transduction'],
    'volvox carteri': ['green algae'],
    'voromonadidae': ['organism'],
    'voromonas': ['alveolate'],
    'wasp': ['insect'],
    'wasps': ['insect'],
    'water': ['inorganic compound'],
    'water-insoluble': ['food'],
    'wavelength': ['measurement'],
    'wavelengths': ['measurement'],
    'wax': ['tobymac'],
    'way': ['tobymac'],
    'weak entity': ['entity'],
    'white blood cell': ['blood cell', 'cell'],
    'whole genome sequencing': ['process'],
    'world': ['planet earth'],
    'xenacoelomorpha': ['bilateria'],
    'xylonomycetes': ['phylum'],
    'yeast': ['eukaryotic transcription'],
    'yeasts': ['eukaryotic transcription'],
    'yellow-green algae': ['very important person'],
    'zosterophyll': ['silurian'],
    'zosterophyllopsida': ['silurian'],
    'zygnematophyceae': ['green algae'],
    'zygocystinae': ['parasitism'],
    'zygomycota': ['phylum'],
    'ɑ-amino acid': ['amino acid'],
    'α-methylfentanyl': ['opiod'],
    'γ-oryzanol': ['lipid']}
