
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_patterns_dict = {
    '-definition_limit': ['-definition+limit'],
    '1952_novel_about_baseball_by_bernard_malamud': [   '1952+novel+about+baseball+by+bernard+malamud'],
    '1998_american_computer_animated_adventure_comedy_film_directed_by_eric_darnell': [   '1998+american+computer+animated+adventure+comedy+film+directed+by+eric+darnell'],
    '4-aminobutyrate_transaminase': ['4-aminobutyrate+transaminase'],
    'a_amoebozoa': ['a+amoebozoa'],
    'a_chemical_compounds_based_upon_the_molecular_structure_r-ono': [   'a+chemical+compounds+based+upon+the+molecular+structure+r-ono'],
    'a_constituent_divided_by_the_total': [   'a+constituent+divided+by+the+total'],
    'a_diverse': ['a+diverse'],
    'a_medical_condition_to_become_progressively_worse': [   'a+medical+condition+to+become+progressively+worse'],
    'a_molecular_motors': ['a+molecular+motors'],
    'a_old_world_tailless_simians': ['a+old+world+tailless+simians'],
    'a_parasites': ['a+parasites'],
    'a_parasitic_alveolates': ['a+parasitic+alveolates'],
    'a_phosphoryl_group': ['a+phosphoryl+group'],
    'a_sensory_stimulus': ['a+sensory+stimulus'],
    'a_single-celled_eukaryotes': ['a+single-celled+eukaryotes'],
    'a_small_cytokines': ['a+small+cytokines'],
    'a_substance_by_an_organism': ['a+substance+by+an+organism'],
    'a_vaccine_to_help_the_immune_system_develop_protection': [   'a+vaccine+to+help+the+immune+system+develop+protection'],
    'a_very_short_digit_sequence_to_reach_specific_telephone_numbers': [   'a+very+short+digit+sequence+to+reach+specific+telephone+numbers'],
    'abbreviated': ['abbreviated'],
    'abbreviated_dialing': ['abbreviated+dialing'],
    'abbreviation_a_chemical_element': ['abbreviation+a+chemical+element'],
    'abbvie': ['abbvie'],
    'abnormal': ['abnormal'],
    'abnormal_growth': ['abnormal+growth'],
    'abnormal_posturing': ['abnormal+posturing'],
    'about_14_flowering_plants': ['about+14+flowering+plants'],
    'absorbance': ['absorbance'],
    'acceleration': ['acceleration'],
    'acetoin': ['acetoin'],
    'acetone': ['acetone'],
    'acetone–butanol–ethanol_fermentation': [   'acetone–butanol–ethanol+fermentation'],
    'acetyl': ['acetyl'],
    'acetyl_group': ['acetyl+group'],
    'acetylation': ['acetylation'],
    'acid': ['acid'],
    'acidic': ['acidic'],
    'acidic_compound': ['acidic+compound'],
    'acidic_oxide': ['acidic+oxide'],
    'acidity': ['acidity'],
    'acidity_regulator': ['acidity+regulator'],
    'acids': ['acids'],
    'acoelomorph': ['acoelomorph'],
    'acoelomorpha': ['acoelomorpha'],
    'acoelomorphs': ['acoelomorphs'],
    'acpd': ['acpd'],
    'active_site': ['active+site'],
    'activity': ['activity'],
    'acute_proliferative_glomerulonephritis': [   'acute+proliferative+glomerulonephritis'],
    'acyl': ['acyl'],
    'acyl_group': ['acyl+group'],
    'acylation': ['acylation'],
    'adaptation': ['adaptation'],
    'adapted': ['adapted'],
    'adaptive_immune_system': ['adaptive+immune+system'],
    'adc': ['adc'],
    'adding_an_acyl_group_to_a_compound': [   'adding+an+acyl+group+to+a+compound'],
    'adding_an_aminoacyl_group_to_a_compound': [   'adding+an+aminoacyl+group+to+a+compound'],
    'adenine': ['adenine'],
    'adenosine': ['adenosine'],
    'adenylate_kinase': ['adenylate+kinase'],
    'adherence': ['adherence'],
    'adherence_medicine': ['adherence+medicine'],
    'adoption': ['adoption'],
    'adsorbed': ['adsorbed'],
    'aerobic_respiration': ['aerobic+respiration'],
    'affection': ['affection'],
    'affective': ['affective'],
    'affects': ['affects'],
    'agent': ['agent'],
    'aging': ['aging'],
    'agonist': ['agonist'],
    'agricultural_robot': ['agricultural+robot'],
    'agriculture': ['agriculture'],
    'alanine': ['alanine'],
    'albumin': ['albumin'],
    'alcohol': ['alcohol'],
    'alcohols': ['alcohols'],
    'algae': ['algae'],
    'algorithm': ['algorithm'],
    'algorithms_calculating_variance': ['algorithms+calculating+variance'],
    'alignment': ['alignment'],
    'alkyl_nitrite': ['alkyl+nitrite'],
    'alkyl_nitrites': ['alkyl+nitrites'],
    'alkylating_agent': ['alkylating+agent'],
    'alternative_splicing': ['alternative+splicing'],
    'alveolate': ['alveolate'],
    'alveolates': ['alveolates'],
    'alveolates_isolated': ['alveolates+isolated'],
    'amebae': ['amebae'],
    'amide': ['amide'],
    'amides': ['amides'],
    'amidicity': ['amidicity'],
    'aminal': ['aminal'],
    'amination': ['amination'],
    'amine': ['amine'],
    'amines': ['amines'],
    'amino': ['amino'],
    'amino_acid': ['amino+acid'],
    'aminoacyl': ['aminoacyl'],
    'aminoacyl_trna_synthetase': ['aminoacyl+trna+synthetase'],
    'aminoacylation': ['aminoacylation'],
    'ammine': ['ammine'],
    'ammonia': ['ammonia'],
    'ammonium': ['ammonium'],
    'amoeba': ['amoeba'],
    'amoebae': ['amoebae'],
    'amoeboid': ['amoeboid'],
    'amoeboid_movement': ['amoeboid+movement'],
    'amoebozoa': ['amoebozoa'],
    'amplification': ['amplification'],
    'amplifier': ['amplifier'],
    'an_armed_forces_or_uniformed_service_who_holds_a_authority': [   'an+armed+forces+or+uniformed+service+who+holds+a+authority'],
    'an_important': ['an+important'],
    "an_organism's_body_tissues_by_disease-causing_agents": [   "an+organism's+body+tissues+by+disease-causing+agents"],
    "an_organism's_dna": ["an+organism's+dna"],
    'an_organism_to_move_independently': ['an+organism+to+move+independently'],
    'anabolic': ['anabolic'],
    'anabolic_steroid': ['anabolic+steroid'],
    'anabolism': ['anabolism'],
    'anaerobic_respiration': ['anaerobic+respiration'],
    'analgesic': ['analgesic'],
    'analysis': ['analysis'],
    'analytical_technique': ['analytical+technique'],
    'anatomy': ['anatomy'],
    'ancestor': ['ancestor'],
    'ancient': ['ancient'],
    'ancient_history': ['ancient+history'],
    'androgen': ['androgen'],
    'androgens': ['androgens'],
    'angiogenin': ['angiogenin'],
    'angle_between_two_intersecting_planes': [   'angle+between+two+intersecting+planes'],
    'animal': ['animal'],
    'animals': ['animals'],
    'animals_bilateral_symmetry_as_an_embryo': [   'animals+bilateral+symmetry+as+an+embryo'],
    'animation': ['animation'],
    'animator': ['animator'],
    'anime': ['anime'],
    'anise': ['anise'],
    'anoikis': ['anoikis'],
    'anomer': ['anomer'],
    'anoxygenic_photosynthesis': ['anoxygenic+photosynthesis'],
    'ant': ['ant'],
    'anthracycline': ['anthracycline'],
    'anthropology': ['anthropology'],
    'anti-metastatic': ['anti-metastatic'],
    'anti-metastatic_activity': ['anti-metastatic+activity'],
    'anti-pd1_therapy': ['anti-pd1+therapy'],
    'anti-tumor': ['anti-tumor'],
    'antibiotic': ['antibiotic'],
    'antibody': ['antibody'],
    'antibody-drug_conjugate': ['antibody-drug+conjugate'],
    'antigen-presenting_cell': ['antigen-presenting+cell'],
    'antimicrobial_substance_active_against_bacteria': [   'antimicrobial+substance+active+against+bacteria'],
    'antioxidant': ['antioxidant'],
    'ants': ['ants'],
    'antz': ['antz'],
    'any_economy': ['any+economy'],
    'ape': ['ape'],
    'apes': ['apes'],
    'apicomplexa': ['apicomplexa'],
    'archaea': ['archaea'],
    'archaeol': ['archaeol'],
    'archaeon': ['archaeon'],
    'are': ['are'],
    'arrangement': ['arrangement'],
    'art': ['art'],
    'artifact': ['artifact'],
    'artisans_or_merchants_who_oversee_the': [   'artisans+or+merchants+who+oversee+the'],
    'artist_who_creates_multiple_images': [   'artist+who+creates+multiple+images'],
    'ascomycota': ['ascomycota'],
    'aspartate': ['aspartate'],
    'aspartate_kinase': ['aspartate+kinase'],
    'aspartate_transaminase': ['aspartate+transaminase'],
    'aspartokinase': ['aspartokinase'],
    'assay': ['assay'],
    'assays': ['assays'],
    'astronomical_body_orbiting_a_star_or_stellar_remnant': [   'astronomical+body+orbiting+a+star+or+stellar+remnant'],
    'atom': ['atom'],
    'atom_or_molecule': ['atom+or+molecule'],
    'atomic_mass': ['atomic+mass'],
    'atomism': ['atomism'],
    'atoms': ['atoms'],
    'atoms_in_molecules': ['atoms+in+molecules'],
    'atp_synthase': ['atp+synthase'],
    'authority': ['authority'],
    'auto_racing': ['auto+racing'],
    'axe': ['axe'],
    'axillary_lymph_nodes': ['axillary+lymph+nodes'],
    'azide': ['azide'],
    'b16_melanoma': ['b16+melanoma'],
    'b16f10': ['b16f10'],
    'b_cell': ['b+cell'],
    'bacteria': ['bacteria'],
    'bacterial_display': ['bacterial+display'],
    'bacterial_transcription': ['bacterial+transcription'],
    'bacterium': ['bacterium'],
    'balantidiasis': ['balantidiasis'],
    'balantidium_coli': ['balantidium+coli'],
    'basal_cell_carcinoma': ['basal+cell+carcinoma'],
    'base_pair': ['base+pair'],
    'basic_structural': ['basic+structural'],
    'basidiomycota': ['basidiomycota'],
    'battle_cisterna': ['battle+cisterna'],
    'bean': ['bean'],
    'beans': ['beans'],
    'bechdel_test': ['bechdel+test'],
    'bee': ['bee'],
    'beef_aging': ['beef+aging'],
    'bees': ['bees'],
    'behavioral_or_mental_pattern': ['behavioral+or+mental+pattern'],
    'bell-shaped_ciliates': ['bell-shaped+ciliates'],
    'benign_cancer': ['benign+cancer'],
    'bernard_malamud': ['bernard+malamud'],
    'beta_sheet': ['beta+sheet'],
    'bibcode': ['bibcode'],
    'big_five_personality_traits': ['big+five+personality+traits'],
    'bilateria': ['bilateria'],
    'bilaterians': ['bilaterians'],
    'binding_site': ['binding+site'],
    'biochemicals': ['biochemicals'],
    'biochemistry': ['biochemistry'],
    'biogenesis': ['biogenesis'],
    'bioinformatics': ['bioinformatics'],
    'biological_cell': ['biological+cell'],
    'biological_membrane': ['biological+membrane'],
    'biological_process': ['biological+process'],
    'biological_process_by': ['biological+process+by'],
    'biological_processes_common_to_most_eukaryotic_cells_by': [   'biological+processes+common+to+most+eukaryotic+cells+by'],
    'biological_system': ['biological+system'],
    'biological_warfare': ['biological+warfare'],
    'biologically_active_organic_compound_four_rings_arranged': [   'biologically+active+organic+compound+four+rings+arranged'],
    'biology': ['biology'],
    'biomolecule': ['biomolecule'],
    'biomolecules': ['biomolecules'],
    'biopharmaceutical_drug': ['biopharmaceutical+drug'],
    'biopolymer': ['biopolymer'],
    'biosynthesis': ['biosynthesis'],
    'blood': ['blood'],
    'blood_cell': ['blood+cell'],
    'blood_cellular_components': ['blood+cellular+components'],
    'blood_sample': ['blood+sample'],
    'body_fluid': ['body+fluid'],
    'body_water': ['body+water'],
    'bonding_electron': ['bonding+electron'],
    'book_by_english_natural_philosopher_isaac_newton': [   'book+by+english+natural+philosopher+isaac+newton'],
    'both_proteins': ['both+proteins'],
    'bovina': ['bovina'],
    'bow_down': ['bow+down'],
    'bradford_protein_assay': ['bradford+protein+assay'],
    'branched-chain_alpha-keto_acid_dehydrogenase_complex': [   'branched-chain+alpha-keto+acid+dehydrogenase+complex'],
    'branching_diagram_or_tree_showing_the_evolutionary_relationships_among_various_biological_species_or_other_entities—their_phylogeny_—based_upon_similarities': [   'branching+diagram+or+tree+showing+the+evolutionary+relationships+among+various+biological+species+or+other+entities—their+phylogeny+—based+upon+similarities'],
    'brand_drug': ['brand+drug'],
    'brand_price': ['brand+price', 'brand+pricing_info'],
    'brand_price_decrease': [   'brand+price+decrease',
                                'brand_price+decrease',
                                'pricing_info+decrease'],
    'brand_price_increase': [   'brand+price+increase',
                                'brand_price+increase',
                                'pricing_info+increase'],
    'breaking_a_complex_topic_or_substance_into_smaller': [   'breaking+a+complex+topic+or+substance+into+smaller'],
    'breaking_down': ['breaking+down'],
    'breast_cancer': ['breast+cancer'],
    'bright_field_microscopy': ['bright+field+microscopy'],
    'bringing_a_new_pharmaceutical_drug_to_the_market_once_a_lead_compound_has_been_identified_through_the': [   'bringing+a+new+pharmaceutical+drug+to+the+market+once+a+lead+compound+has+been+identified+through+the'],
    'british_firms': ['british+firms'],
    'building': ['building'],
    'business': ['business'],
    'butanol': ['butanol'],
    'by_cells_to_increase_or_decrease_the': [   'by+cells+to+increase+or+decrease+the'],
    'calculation': ['calculation'],
    'california_gold_rush': ['california+gold+rush'],
    'cancer': ['cancer'],
    'cancer_cell': ['cancer+cell'],
    'cancer_detection': ['cancer+detection'],
    'cancer_immunotherapy': ['cancer+immunotherapy'],
    'cancer_model': ['cancer+model'],
    'cancer_treatment': ['cancer+treatment'],
    'capacitor': ['capacitor'],
    'capacitors': ['capacitors'],
    'carbene': ['carbene'],
    'carbohydrate': ['carbohydrate'],
    'carbohydrate_metabolism': ['carbohydrate+metabolism'],
    'carbohydrates': ['carbohydrates'],
    'carbon': ['carbon'],
    'carboximidate': ['carboximidate'],
    'carboxylic_acid_a_long_aliphatic_chain': [   'carboxylic+acid+a+long+aliphatic+chain'],
    'carcinoma_mouse_models': ['carcinoma+mouse+models'],
    'cartesian_coordinate_system': ['cartesian+coordinate+system'],
    'cartesian_coordinates': ['cartesian+coordinates'],
    'casein': ['casein'],
    'catabolism': ['catabolism'],
    'catalase': ['catalase'],
    'catalysed': ['catalysed'],
    'catalyst': ['catalyst'],
    'catalysts': ['catalysts'],
    'catalytic_α': ['catalytic+α'],
    'catalyze': ['catalyze'],
    'catalyzing': ['catalyzing'],
    'causes_cancer': ['causes+cancer'],
    'cdna': ['cdna'],
    'cdna_library': ['cdna+library'],
    'cefalexin': ['cefalexin'],
    'cell': ['cell'],
    'cell_adhesion': ['cell+adhesion'],
    'cell_biology': ['cell+biology'],
    'cell_component': ['cell+component'],
    'cell_culture': ['cell+culture'],
    'cell_cycle': ['cell+cycle'],
    'cell_membrane': ['cell+membrane'],
    'cell_nucleus': ['cell+nucleus'],
    'cell_or_unicellular_organism': ['cell+or+unicellular+organism'],
    'celled': ['celled'],
    'cellular_compartment': ['cellular+compartment'],
    'cellular_compartments': ['cellular+compartments'],
    'cellular_organizational_structure': ['cellular+organizational+structure'],
    'cellulose': ['cellulose'],
    'cercozoa': ['cercozoa'],
    'chain': ['chain'],
    'chalcogen': ['chalcogen'],
    'chaperome': ['chaperome'],
    'chaperone': ['chaperone'],
    'chaperones': ['chaperones'],
    'charophyta': ['charophyta'],
    'chemical': ['chemical'],
    'chemical_bond': ['chemical+bond'],
    'chemical_compound': ['chemical+compound'],
    'chemical_compound_the_chemical_formula_ch4': [   'chemical+compound+the+chemical+formula+ch4'],
    'chemical_conformation': ['chemical+conformation'],
    'chemical_element': ['chemical+element'],
    'chemical_element_symbol_fe': ['chemical+element+symbol+fe'],
    'chemical_element_the_symbol_au': ['chemical+element+the+symbol+au'],
    'chemical_element_the_symbol_n_atomic_number_it_was_first_discovered': [   'chemical+element+the+symbol+n+atomic+number+it+was+first+discovered'],
    'chemical_element_the_symbol_o_atomic_number_it_is_a_member': [   'chemical+element+the+symbol+o+atomic+number+it+is_a+member'],
    'chemical_elements': ['chemical+elements'],
    'chemical_energy': ['chemical+energy'],
    'chemical_formula': ['chemical+formula'],
    'chemical_ion_or_radical:_p+o32−_containing_phosphorus': [   'chemical+ion+or+radical:+p+o32−+containing+phosphorus'],
    'chemical_messenger_system_comprising_feedback_loops': [   'chemical+messenger+system+comprising+feedback+loops'],
    'chemical_processes_within': ['chemical+processes+within'],
    'chemical_reaction': ['chemical+reaction'],
    'chemical_reaction_in': ['chemical+reaction+in'],
    'chemical_structure': ['chemical+structure'],
    'chemical_structures': ['chemical+structures'],
    'chemical_substance': ['chemical+substance'],
    'chemical_the_formula_ch3oh': ['chemical+the+formula+ch3oh'],
    'chemistry': ['chemistry'],
    'chemokine': ['chemokine'],
    'chemosynthesis': ['chemosynthesis'],
    'chemotherapeutic_agent': ['chemotherapeutic+agent'],
    'chemotherapy': ['chemotherapy'],
    'chevrotain': ['chevrotain'],
    'chimera': ['chimera'],
    'chimeric_antigen_receptor_t_cell': ['chimeric+antigen+receptor+t+cell'],
    'chirality': ['chirality'],
    'chloroplast_dna': ['chloroplast+dna'],
    'cholera': ['cholera'],
    'chromatography': ['chromatography'],
    'chromosome': ['chromosome'],
    'chromosomes': ['chromosomes'],
    'ciliate': ['ciliate'],
    'ciliates': ['ciliates'],
    'cis-regulatory_element': ['cis-regulatory+element'],
    'cisterna': ['cisterna'],
    'cisternae': ['cisternae'],
    'cis–trans_isomerism': ['cis–trans+isomerism'],
    'clade': ['clade'],
    'clinical_sample': ['clinical+sample'],
    'clinical_study': ['clinical+study'],
    'clinical_study_design': ['clinical+study+design'],
    'cloned': ['cloned'],
    'cloned_cdna_fragments_inserted_into_a_host_cells': [   'cloned+cdna+fragments+inserted+into+a+host+cells'],
    'cloning': ['cloning'],
    'clustal': ['clustal'],
    'clustalw': ['clustalw'],
    'codec': ['codec'],
    'coding': ['coding'],
    'collagen': ['collagen'],
    'colon_cancer': ['colon+cancer'],
    'colon_carcinoma': ['colon+carcinoma'],
    'colonial_green_algae': ['colonial+green+algae'],
    'colorectal_cancer': ['colorectal+cancer'],
    'commodities': ['commodities'],
    'commodity': ['commodity'],
    'commonly_prescribed': ['commonly+prescribed'],
    'compact_identifier': ['compact+identifier'],
    'company': ['company'],
    'complex_formed_between_rna': ['complex+formed+between+rna'],
    'compound': ['compound'],
    'comprehensive_dynamic_tracing_framework_created_by_sun_microsystems_troubleshooting_kernel': [   'comprehensive+dynamic+tracing+framework+created+by+sun+microsystems+troubleshooting+kernel'],
    'compression_genomic_sequencing_data': [   'compression+genomic+sequencing+data'],
    'computation': ['computation'],
    'computational_method_calculating_the': [   'computational+method+calculating+the'],
    'computer': ['computer'],
    'computer_programming': ['computer+programming'],
    'computer_science': ['computer+science'],
    'computing': ['computing'],
    'concentration': ['concentration'],
    'concept': ['concept'],
    'condition': ['condition'],
    'conformational_change': ['conformational+change'],
    'conformational_isomerism': ['conformational+isomerism'],
    'connecticut_agricultural_experiment_station': [   'connecticut+agricultural+experiment+station'],
    "connecticut_state_government's_agricultural_experiment_station": [   "connecticut+state+government's+agricultural+experiment+station"],
    'connective_tissue': ['connective+tissue'],
    'conoid': ['conoid'],
    'conosa': ['conosa'],
    'consciousness': ['consciousness'],
    'conserved': ['conserved'],
    'conserved_sequence': ['conserved+sequence'],
    'considered': ['considered'],
    'constructing_a_building_or_infrastructure': [   'constructing+a+building+or+infrastructure'],
    'construction': ['construction'],
    'contiguous_united_states': ['contiguous+united+states'],
    'coordinate_system': ['coordinate+system'],
    'coordination_complex': ['coordination+complex'],
    'coplanar': ['coplanar'],
    'coplanar_if_there_exists_a_geometric_plane': [   'coplanar+if+there+exists+a+geometric+plane'],
    'coplanarity': ['coplanarity'],
    'covalent_bond_between_two_atoms': ['covalent+bond+between+two+atoms'],
    'crab-eating_macaque': ['crab-eating+macaque'],
    'cribriform_morphology': ['cribriform+morphology'],
    'cross-coupling_reaction': ['cross-coupling+reaction'],
    'crude_lysate': ['crude+lysate'],
    'cryo-electron_microscopy': ['cryo-electron+microscopy'],
    'cryoelectron_microscopy': ['cryoelectron+microscopy'],
    'cryogenic_electron_microscopy': ['cryogenic+electron+microscopy'],
    'crystal': ['crystal'],
    'crystalline': ['crystalline'],
    'crystalline_silicon': ['crystalline+silicon'],
    'crystallite': ['crystallite'],
    'crystallization': ['crystallization'],
    'crystallize': ['crystallize'],
    'cud': ['cud'],
    'culling': ['culling'],
    'cultural_movement_practising': ['cultural+movement+practising'],
    'culture': ['culture'],
    'cyanobacteria': ['cyanobacteria'],
    'cyclol': ['cyclol'],
    'cytokine': ['cytokine'],
    'cytolysis': ['cytolysis'],
    'cytoplasm': ['cytoplasm'],
    'cytoskeletal_disruptor': ['cytoskeletal+disruptor'],
    'cytoskeletal_motor_proteins': ['cytoskeletal+motor+proteins'],
    'cytoskeleton': ['cytoskeleton'],
    'cytosol': ['cytosol'],
    'cytotoxic_activity': ['cytotoxic+activity'],
    'cytotoxic_t_cell': ['cytotoxic+t+cell'],
    'cytotoxicity': [   'cytotoxicity',
                        'cytotoxic+agent',
                        'cytotoxic+effect',
                        'cytotoxicity+immunologic',
                        'cytotoxicity+test+immunologic'],
    'd_nits': ['d+nits'],
    'd_proteome_balance': ['d+proteome+balance'],
    'd_silurian_period': ['d+silurian+period'],
    'data': ['data'],
    'daunorubicin': ['daunorubicin'],
    'daytona_prototype': ['daytona+prototype'],
    'defined_as_abstract_ideas_or_general_notions': [   'defined+as+abstract+ideas+or+general+notions'],
    'defined_as_those_land_plants': ['defined+as+those+land+plants'],
    'dehydration': ['dehydration'],
    'demo1': ['demo1'],
    'denaturation': ['denaturation'],
    'deoxyribonucleic_acid_molecule_part_or_all': [   'deoxyribonucleic+acid+molecule+part+or+all'],
    'deoxyribonucleoside': ['deoxyribonucleoside'],
    'deoxyribonucleotide': ['deoxyribonucleotide'],
    'deoxyribonucleotides': ['deoxyribonucleotides'],
    'design': ['design'],
    'designer': ['designer'],
    'designing': ['designing'],
    'designing_women': ['designing+women'],
    'detection': ['detection'],
    'detoxification': ['detoxification'],
    'detoxifies': ['detoxifies'],
    'developed_by_silverbridge_holdings': [   'developed+by+silverbridge+holdings'],
    'developing_useful_or_valuable_proteins': [   'developing+useful+or+valuable+proteins'],
    'device': ['device'],
    'diabetes': ['diabetes'],
    'diagram': ['diagram'],
    'diagram_commonly': ['diagram+commonly'],
    'dichroic': ['dichroic'],
    'dichroic_glass': ['dichroic+glass'],
    'diet': ['diet'],
    'dietary_fiber': ['dietary+fiber'],
    'dieting': ['dieting'],
    'diffusion': ['diffusion'],
    'digestion': ['digestion'],
    'digital_object_identifier': ['digital+object+identifier'],
    'dihedral_angle': ['dihedral+angle'],
    'dirigent_protein': ['dirigent+protein'],
    'disaccharide': ['disaccharide'],
    'disease': ['disease'],
    'dispersed_particles_relative_to_a_fluid_under_the': [   'dispersed+particles+relative+to+a+fluid+under+the'],
    'disposition_or': ['disposition+or'],
    'dissociation_constant': ['dissociation+constant'],
    'distance': ['distance'],
    'distances': ['distances'],
    'distinct_juvenile_form_many_animals_undergo_before_metamorphosis_into_adults': [   'distinct+juvenile+form+many+animals+undergo+before+metamorphosis+into+adults'],
    'distributed_computing': ['distributed+computing'],
    'disulfide_bond': ['disulfide+bond'],
    'disulfide_bond_formation_protein_b': [   'disulfide+bond+formation+protein+b'],
    'dna': ['dna'],
    'dna-binding_protein': ['dna-binding+protein'],
    'dna_polymerase': ['dna+polymerase'],
    'dna_repair': ['dna+repair'],
    'dna_replication': ['dna+replication'],
    'dna_sequence': ['dna+sequence'],
    'dna_sequencer': ['dna+sequencer'],
    'dna_sequencing': ['dna+sequencing'],
    'dnaa': ['dnaa'],
    'dnac': ['dnac'],
    'dnae': ['dnae'],
    'dnag': ['dnag'],
    'dnah': ['dnah'],
    'dnai': ['dnai'],
    'dnan': ['dnan'],
    'dnaq': ['dnaq'],
    'dnax': ['dnax'],
    'docking': ['docking'],
    'domesticated': ['domesticated'],
    'domestication': ['domestication'],
    'double-bond': ['double-bond'],
    'double_bond': ['double+bond'],
    'downregulation_upregulation': ['downregulation+upregulation'],
    'doxorubicin': ['doxorubicin'],
    'drug': ['drug'],
    'drug_development': ['drug+development'],
    'dtrace': ['dtrace'],
    'dual-polarization_interferometry': ['dual-polarization+interferometry'],
    'dual_polarisation_interferometry': ['dual+polarisation+interferometry'],
    'ductal_morphology': ['ductal+morphology'],
    'dynein': ['dynein'],
    'earth': ['earth'],
    'earth_science_concerned_the_solid_earth': [   'earth+science+concerned+the+solid+earth'],
    'eating': ['eating'],
    'echinamoebidae': ['echinamoebidae'],
    'edestin': ['edestin'],
    'edible_legume': ['edible+legume'],
    'eicosanoid': ['eicosanoid'],
    'eicosanoid_metabolism': ['eicosanoid+metabolism'],
    'elastin': ['elastin'],
    'electric_charge': ['electric+charge'],
    'electric_power_conversion': ['electric+power+conversion'],
    'electric_power_converter': ['electric+power+converter'],
    'electrically_neutral': ['electrically+neutral'],
    'electrofocusing': ['electrofocusing'],
    'electromagnet': ['electromagnet'],
    'electromagnetic': ['electromagnetic'],
    'electromagnetic_radiation': ['electromagnetic+radiation'],
    'electromagnetism': ['electromagnetism'],
    'electron': ['electron'],
    'electron_crystallography': ['electron+crystallography'],
    'electron_microscopy_technique_applied_on_samples_cooled_to_cryogenic_temperatures': [   'electron+microscopy+technique+applied+on+samples+cooled+to+cryogenic+temperatures'],
    'electron_transport_chain': ['electron+transport+chain'],
    'electrons': ['electrons'],
    'electrophoresis': ['electrophoresis'],
    'elemental_analysis': ['elemental+analysis'],
    'embryo': ['embryo'],
    'embryonic_plant_enclosed': ['embryonic+plant+enclosed'],
    'emulsion_polymerization': ['emulsion+polymerization'],
    'enclosing_or_separating_membrane': ['enclosing+or+separating+membrane'],
    'encodes': ['encodes'],
    'endocrine': ['endocrine'],
    'endocrine_system': ['endocrine+system'],
    'endogenous': ['endogenous'],
    'endogeny': ['endogeny'],
    'endonuclease': ['endonuclease'],
    'endoplasmic_reticulum': ['endoplasmic+reticulum'],
    'energy': ['energy'],
    'engine': ['engine'],
    'engineering': ['engineering'],
    'enol': ['enol'],
    'entity': ['entity'],
    'entity_comprising_multiple_people': ['entity+comprising+multiple+people'],
    'enzyme': ['enzyme'],
    "enzyme's_ability_to_catalyze_consecutive_reactions_without_releasing_its_substratefor_example": [   "enzyme's+ability+to+catalyze+consecutive+reactions+without+releasing+its+substratefor+example"],
    'enzyme_assay': ['enzyme+assay'],
    'enzyme_catalysis': ['enzyme+catalysis'],
    'enzyme_found': ['enzyme+found'],
    'enzyme_kinetics': ['enzyme+kinetics'],
    'enzymology': ['enzymology'],
    'eosin': ['eosin'],
    'epigenetics': ['epigenetics'],
    'epirubicin': ['epirubicin'],
    'epistemology': ['epistemology'],
    'epothilone': ['epothilone'],
    'equine_coat_color_genetics': ['equine+coat+color+genetics'],
    'essential_amino': ['essential+amino'],
    'essential_amino_acid': ['essential+amino+acid'],
    'essential_amino_acids': ['essential+amino+acids'],
    'essential_fatty_acid': ['essential+fatty+acid'],
    'essential_nutrients_the_human_body': [   'essential+nutrients+the+human+body'],
    'ester': ['ester'],
    'ethanol': ['ethanol'],
    'ethanol_fermentation': ['ethanol+fermentation'],
    'ethanol_metabolism': ['ethanol+metabolism'],
    'ethenol': ['ethenol'],
    'ethynol': ['ethynol'],
    'eukaryote': ['eukaryote'],
    'eukaryotes': ['eukaryotes'],
    'eukaryotic': ['eukaryotic'],
    'eukaryotic_organelle': ['eukaryotic+organelle'],
    'eukaryotic_transcription': ['eukaryotic+transcription'],
    'eusocial_insects': ['eusocial+insects'],
    'eusociality': ['eusociality'],
    'evaluation': ['evaluation'],
    'evolutionarily_conserved_protein_domain': [   'evolutionarily+conserved+protein+domain'],
    'evolutionary_psychology': ['evolutionary+psychology'],
    'excitatory_ability': ['excitatory+ability'],
    'exergy': ['exergy'],
    'exocrine_gland': ['exocrine+gland'],
    'experiment': ['experiment'],
    'experimental_system': ['experimental+system'],
    'experimentation': ['experimentation'],
    'experiments': ['experiments'],
    'expiration': ['expiration'],
    'explanation': ['explanation'],
    'explanations': ['explanations'],
    'extinct_plants': ['extinct+plants'],
    'extinct_plants_only': ['extinct+plants+only'],
    'extremophile': ['extremophile'],
    'extremophilic': ['extremophilic'],
    'fact': ['fact'],
    'facts': ['facts'],
    'fatty_acid': ['fatty+acid'],
    'fatty_acids': ['fatty+acids'],
    'fermentation': ['fermentation'],
    'filtration': ['filtration'],
    'first-person_shooter_video_game_developed_by_polish_game_studio_people_can_fly': [   'first-person+shooter+video+game+developed+by+polish+game+studio+people+can+fly'],
    'flabellinia': ['flabellinia'],
    'flowering_plant': ['flowering+plant'],
    'fluid': ['fluid'],
    'fluids': ['fluids'],
    'fluorescent_acidic_compound': ['fluorescent+acidic+compound'],
    'flying_insects_closely_related_to_wasps': [   'flying+insects+closely+related+to+wasps'],
    'foam': ['foam'],
    'food': ['food'],
    'forbes': ['forbes'],
    'force': ['force'],
    'form': ['form'],
    'forming': ['forming'],
    'forms': ['forms'],
    'fossil': ['fossil'],
    'four_basic': ['four+basic'],
    'fourier-transform_infrared_spectroscopy': [   'fourier-transform+infrared+spectroscopy'],
    'free-swimming': ['free-swimming'],
    'free_java_implementations': ['free+java+implementations'],
    'frequency': ['frequency'],
    'fructose': ['fructose'],
    'fruit': ['fruit'],
    'functional_group_or_chemical_compound_containing_a_carbon–nitrogen_double_bond': [   'functional+group+or+chemical+compound+containing+a+carbon–nitrogen+double+bond'],
    'fungus': ['fungus'],
    'fur': ['fur'],
    'fusion_power': ['fusion+power'],
    'fusion_protein': ['fusion+protein'],
    'galaxies': ['galaxies'],
    'galaxy': ['galaxy'],
    'gamete': ['gamete'],
    'gas': ['gas'],
    'gencode': ['gencode'],
    'gene': ['gene'],
    'gene_encoding_the_ε': ['gene+encoding+the+ε'],
    'gene_structure': ['gene+structure'],
    'generally_any_chemical_compounds': ['generally+any+chemical+compounds'],
    'generic_drug': ['generic+drug'],
    'generic_name_sweet-tasting': ['generic+name+sweet-tasting'],
    'genes': ['genes'],
    'genetic_disorder': ['genetic+disorder'],
    'genetics': ['genetics'],
    'genome': ['genome'],
    'genome_sequencing': ['genome+sequencing'],
    'genus': ['genus'],
    'geologic': ['geologic'],
    'geologic_period': ['geologic+period'],
    'geological_period': ['geological+period'],
    'geology': ['geology'],
    'geometric_variation_found_at_certain': [   'geometric+variation+found+at+certain'],
    'geometry': ['geometry'],
    'gland': ['gland'],
    'gland_structure': ['gland+structure'],
    'glass': ['glass'],
    'gleason_grading_system': ['gleason+grading+system', 'gleason+pattern'],
    'globular_protein': ['globular+protein'],
    'globular_proteins': ['globular+proteins'],
    'glucose': ['glucose'],
    'glycine': ['glycine'],
    'glycines': ['glycines'],
    'glycosidic_bond': ['glycosidic+bond'],
    'glycosylamine': ['glycosylamine'],
    'glycosylamines': ['glycosylamines'],
    'gold': ['gold'],
    'grading_system': ['grading+system'],
    'gram-negative_bacteria': ['gram-negative+bacteria'],
    'gram-negative_proteobacteria': ['gram-negative+proteobacteria'],
    'green_algae': ['green+algae'],
    'growth': ['growth'],
    'gs_alpha_subunit': ['gs+alpha+subunit'],
    'guild': ['guild'],
    'gαs': ['gαs'],
    'haematopoiesis': ['haematopoiesis'],
    'hair_removal': ['hair+removal'],
    'haploid_cell': ['haploid+cell'],
    'head_lice_infestation': ['head+lice+infestation'],
    'health': ['health'],
    'health_science': ['health+science'],
    'healthy_cell': ['healthy+cell'],
    'heat': ['heat'],
    'helix': ['helix'],
    'hematological': ['hematological'],
    'hematopoiesis': ['hematopoiesis'],
    'hematoxylin': ['hematoxylin'],
    'heredity': ['heredity'],
    'heritable_phenotype_changes': ['heritable+phenotype+changes'],
    'heterokont': ['heterokont'],
    'heterokontae': ['heterokontae'],
    'heterokonts': ['heterokonts'],
    'heterolobosea': ['heterolobosea'],
    'hexapod_invertebrates': ['hexapod+invertebrates'],
    'highly-digestible': ['highly-digestible'],
    'histocompatibility': ['histocompatibility'],
    'histologic_stain': ['histologic+stain'],
    'histology': ['histology'],
    'histopathological_image': [   'histopathological+image',
                                   'histopathology+image'],
    'histopathology': ['histopathology'],
    'hormone': ['hormone'],
    'horse': ['horse'],
    'human': ['human'],
    'humanism': ['humanism'],
    'humanities': ['humanities'],
    'humans': ['humans'],
    'hushing': ['hushing'],
    'hydrogen': ['hydrogen'],
    'hydrolysis': ['hydrolysis'],
    'hydroxyl': ['hydroxyl'],
    'hydroxyl_radical': ['hydroxyl+radical'],
    'hypotheses': ['hypotheses'],
    'hypothesis': ['hypothesis'],
    'idarubicin': ['idarubicin'],
    'idea': ['idea'],
    'il-15_receptor': ['il-15+receptor'],
    'il-15rα': ['il-15rα'],
    'illness': ['illness'],
    'image': ['image'],
    'image_analysis': ['image+analysis'],
    'images': ['images'],
    'imidate': ['imidate'],
    'imide': ['imide'],
    'imine': ['imine'],
    'imines': ['imines'],
    'immediate_constituent_analysis': ['immediate+constituent+analysis'],
    'immune_response': ['immune+response'],
    'immune_system': ['immune+system'],
    'immunology': ['immunology'],
    'immunotherapy': ['immunotherapy'],
    'in_turn_known_as_ligands_or_complexing_agents': [   'in+turn+known+as+ligands+or+complexing+agents'],
    'in_vivo': ['in+vivo'],
    'individual': ['individual'],
    'individual_entity': ['individual+entity'],
    'inductor': ['inductor'],
    'inductors': ['inductors'],
    'infection': ['infection'],
    'infectious_disease': ['infectious+disease'],
    'infectious_disease_caused_or_transmitted_by_a_parasite': [   'infectious+disease+caused+or+transmitted+by+a+parasite'],
    'inflammation': ['inflammation'],
    'inflammation_or_painful_reaction_to_allergy_or_cell-lining_damage': [   'inflammation+or+painful+reaction+to+allergy+or+cell-lining+damage'],
    'inflammatory_chemokines': ['inflammatory+chemokines'],
    'informal': ['informal'],
    'informal_term_single-celled_eukaryotes': [   'informal+term+single-celled+eukaryotes'],
    'information': ['information'],
    'infrared': ['infrared'],
    'infrastructure': ['infrastructure'],
    'ingestion': ['ingestion'],
    'injuries': ['injuries'],
    'injury': ['injury'],
    'innate_immune_system': ['innate+immune+system'],
    'inorganic': ['inorganic'],
    'inorganic_compound': ['inorganic+compound'],
    'insect': ['insect'],
    'insects': ['insects'],
    'instrument': ['instrument'],
    'instrumentalism': ['instrumentalism'],
    'instrumentation': ['instrumentation'],
    'interact': ['interact'],
    'interacting': ['interacting'],
    'interacting_or_interrelated_entities': [   'interacting+or+interrelated+entities'],
    'interaction': ['interaction'],
    'interdisciplinarity': ['interdisciplinarity'],
    'interdisciplinary_field': ['interdisciplinary+field'],
    'interleukin': ['interleukin', 'interleukin+1β', 'receptors+interleukin'],
    'interleukin-15_receptor': ['interleukin-15+receptor'],
    'interleukin-2': ['interleukin-2'],
    'interleukin_15': ['interleukin+15'],
    'interleukin_2': ['interleukin+2'],
    'intermediate_end': ['intermediate+end'],
    'international_standard_covering_the': [   'international+standard+covering+the'],
    'international_standard_covering_the_materials_sizes': [   'international+standard+covering+the+materials+sizes'],
    'investigative': ['investigative'],
    'investigative_journalism': ['investigative+journalism'],
    'investment': ['investment'],
    'involuntary_flexion_or_extension': ['involuntary+flexion+or+extension'],
    'ion': ['ion'],
    'ions': ['ions'],
    'ions_or_molecules_identical_formulas_but_distinct_structures': [   'ions+or+molecules+identical+formulas+but+distinct+structures'],
    'iron': ['iron'],
    'irregular_bone_a_complex_structure': [   'irregular+bone+a+complex+structure'],
    'irritability': ['irritability'],
    'irritants': ['irritants'],
    'irritation': ['irritation'],
    'iso': ['iso'],
    'iso_6344': ['iso+6344'],
    'iso_8601': ['iso+8601'],
    'isobutanol': ['isobutanol'],
    'isobutyl': ['isobutyl'],
    'isobutyl_nitrite': ['isobutyl+nitrite'],
    'isoelectric_focusing': ['isoelectric+focusing'],
    'isomer': ['isomer'],
    'isomerism': ['isomerism'],
    'isomers': ['isomers'],
    'jaligner': ['jaligner'],
    'kinase': ['kinase'],
    'knowledge': ['knowledge'],
    'laboratory_methods_measuring_enzymatic_activity': [   'laboratory+methods+measuring+enzymatic+activity'],
    'laboratory_technique_combining_reverse': [   'laboratory+technique+combining+reverse'],
    'lame': ['lame'],
    'lanthanide': ['lanthanide'],
    'lanthanides': ['lanthanides'],
    'large-scale': ['large-scale'],
    'large-scale_brain_networks': ['large-scale+brain+networks'],
    'large_biomolecules': ['large+biomolecules'],
    'large_insoluble_food_molecules_into_small_water-soluble_food_molecules_so': [   'large+insoluble+food+molecules+into+small+water-soluble+food+molecules+so'],
    'larva': ['larva'],
    'larval': ['larval'],
    'laser': ['laser'],
    'lead': ['lead'],
    'leads': ['leads'],
    'leather': ['leather'],
    'legume': ['legume'],
    'legumin': ['legumin'],
    'lentil': ['lentil'],
    'lentils': ['lentils'],
    'levacetylmethadol': ['levacetylmethadol'],
    'lewis_lung_carcinoma': ['lewis+lung+carcinoma'],
    'lice': ['lice'],
    'life': ['life'],
    'life-sustaining_chemical': ['life-sustaining+chemical'],
    'ligand': ['ligand'],
    'ligase': ['ligase'],
    'light': ['light'],
    'linguistics': ['linguistics'],
    'lipid': ['lipid'],
    'lipid_bilayer': ['lipid+bilayer'],
    'lipid_layer': ['lipid+layer'],
    'lipids': ['lipids'],
    'liquid': ['liquid'],
    'list_extinct_plants': ['list+extinct+plants'],
    'list_internet_phenomena': ['list+internet+phenomena'],
    'list_mail_server_software': ['list+mail+server+software'],
    'list_protein_structure_prediction_software': [   'list+protein+structure+prediction+software'],
    'liver': ['liver'],
    'lives': ['lives'],
    'livestock': ['livestock'],
    'living': ['living'],
    'lobosa': ['lobosa'],
    'lobose': ['lobose'],
    'louse': ['louse'],
    'love': ['love'],
    'lung_cancer': ['lung+cancer'],
    'lustre': ['lustre'],
    'lymph_node': ['lymph+node'],
    'lymphocyte': ['lymphocyte'],
    'lymphocytes': ['lymphocytes'],
    'lysis': ['lysis'],
    'machine': ['machine'],
    'machine_designed_to_convert_one': ['machine+designed+to+convert+one'],
    'macromolecule': ['macromolecule'],
    'macromolecules': ['macromolecules'],
    'mai_basic_four': ['mai+basic+four'],
    'mail': ['mail'],
    'mail_server': ['mail+server'],
    'main_core_membrane': ['main+core+membrane'],
    'mainly_multicellular': ['mainly+multicellular'],
    'major_taxonomic_group_containing_about_400_described': [   'major+taxonomic+group+containing+about+400+described'],
    'male_gamete': ['male+gamete'],
    'male_reproductive_system': ['male+reproductive+system'],
    'malignancy': ['malignancy'],
    'malignant_cancer': ['malignant+cancer'],
    'malignant_cell': ['malignant+cell'],
    'malignant_cells': ['malignant+cells'],
    'malignant_prostate_cell': ['malignant+prostate+cell'],
    'mammal': ['mammal'],
    'mammals': ['mammals'],
    'maser': ['maser'],
    'mass': ['mass'],
    'material': ['material'],
    'materialism': ['materialism'],
    'mathematics': ['mathematics'],
    'matter': ['matter'],
    'measure': ['measure'],
    'measurement': ['measurement'],
    'meat': ['meat'],
    'meat_glue': ['meat+glue'],
    'mechanics': ['mechanics'],
    'mechanisms': ['mechanisms'],
    'medal': ['medal'],
    'medical_device': ['medical+device'],
    'medical_devices': ['medical+devices'],
    'medical_image': ['medical+image'],
    'medical_image_analysis': ['medical+image+analysis'],
    'medical_study': ['medical+study'],
    'medication': ['medication'],
    'medicine': ['medicine'],
    'melanoma': ['melanoma'],
    'membrane': ['membrane'],
    'membrane-bound_organelle': ['membrane-bound+organelle'],
    'memory_cd8_t_cell': ['memory+cd8+t+cell'],
    'memory_t_cell': ['memory+t+cell'],
    'mental_disorder': ['mental+disorder'],
    'mental_illness': ['mental+illness'],
    'metabolic': ['metabolic'],
    'metabolic_disorder': ['metabolic+disorder'],
    'metabolic_pathway': ['metabolic+pathway'],
    'metabolic_pathways': ['metabolic+pathways'],
    'metabolism': ['metabolism'],
    'metabolite': ['metabolite'],
    'metabolites': ['metabolites'],
    'metal': ['metal'],
    'metal_ammine_complex': ['metal+ammine+complex'],
    'metal_complexes_containing_at_least_one_ammonia_ligand': [   'metal+complexes+containing+at+least+one+ammonia+ligand'],
    'metallicity': ['metallicity'],
    'metastatic_breast_cancer': ['metastatic+breast+cancer'],
    'methabol': ['methabol'],
    'methadol': ['methadol'],
    'methane': ['methane'],
    'methanol': ['methanol'],
    'methionine': ['methionine'],
    'methodology': ['methodology'],
    'methods_in_enzymology': ['methods+in+enzymology'],
    'microfiltration': ['microfiltration'],
    'microorganism': ['microorganism'],
    'microorganisms': ['microorganisms'],
    'microscope': ['microscope'],
    'microscopic': ['microscopic'],
    'microscopic_organism': ['microscopic+organism'],
    'microscopic_scale': ['microscopic+scale'],
    'microscopy': ['microscopy'],
    'microsoft_exchange_server': ['microsoft+exchange+server'],
    'microtubule': ['microtubule'],
    'microtubules': ['microtubules'],
    'milk': ['milk'],
    'mineral': ['mineral'],
    'mining': ['mining'],
    'mitochondria': ['mitochondria'],
    'mitochondrial': ['mitochondrial'],
    'mitochondrial_dna': ['mitochondrial+dna'],
    'mitosis': ['mitosis'],
    'mitoxantrone': ['mitoxantrone'],
    'mohism': ['mohism'],
    'moiety_derived_by_the': ['moiety+derived+by+the'],
    'mold': ['mold'],
    'molds': ['molds'],
    'molecular_cloning': ['molecular+cloning'],
    'molecular_motor': ['molecular+motor'],
    'molecule': ['molecule'],
    'molecules': ['molecules'],
    'monism': ['monism'],
    'monitoring': ['monitoring'],
    'monomer': ['monomer'],
    'monomers': ['monomers'],
    'monosaccharide': ['monosaccharide'],
    'monosaccharides': ['monosaccharides'],
    'mood_disorder_subset_in': ['mood+disorder+subset+in'],
    'morphology': ['morphology'],
    'motility': ['motility'],
    'motor_protein': ['motor+protein'],
    'mouse_model': ['mouse+model'],
    'mouse_model_colorectal_intestinal_cancer': [   'mouse+model+colorectal+intestinal+cancer'],
    'mouse_tumor_models': ['mouse+tumor+models'],
    'multi-subunit': ['multi-subunit'],
    'multicelluar_organism': ['multicelluar+organism'],
    'multicellular_eukaryotic_organisms': [   'multicellular+eukaryotic+organisms'],
    'multicellular_organism': ['multicellular+organism'],
    'muon-catalyzed_fusion': ['muon-catalyzed+fusion'],
    'murine_tumor_cell_line': ['murine+tumor+cell+line'],
    'muscle': ['muscle'],
    'mushroom': ['mushroom'],
    'mushrooms': ['mushrooms'],
    'name': ['name'],
    'national_institutes_technology': ['national+institutes+technology'],
    'native_metal': ['native+metal'],
    'natural': ['natural'],
    'natural_killer_cell': ['natural+killer+cell', 'nk+cell'],
    'natural_or_artificial_molecular_machines': [   'natural+or+artificial+molecular+machines'],
    'natural_or_synthetic_steroid_hormone': [   'natural+or+synthetic+steroid+hormone'],
    'natural_philosophy': ['natural+philosophy'],
    'natural_philosophy_proposing': ['natural+philosophy+proposing'],
    'natural_science': ['natural+science'],
    'nature': ['nature'],
    'naturism': ['naturism'],
    'nazi_human_experimentation': ['nazi+human+experimentation'],
    'nbpf15': ['nbpf15'],
    'nearly_incompressible_fluid': ['nearly+incompressible+fluid'],
    'neoplasm': ['neoplasm'],
    'neoplasms': ['neoplasms'],
    'neuroendocrine_tumor': ['neuroendocrine+tumor'],
    'neutron': ['neutron'],
    'new_living_organisms_or_organelles': [   'new+living+organisms+or+organelles'],
    'newtons_method_in_optimization': ['newtons+method+in+optimization'],
    'nitrate': ['nitrate'],
    'nitrite': ['nitrite'],
    'nitrogen': ['nitrogen'],
    'nitrogen-containing_biological_compounds': [   'nitrogen-containing+biological+compounds'],
    'non_coding_dna': ['non+coding+dna'],
    'noncoding_dna': ['noncoding+dna'],
    'nuclease': ['nuclease'],
    'nucleic_acid_sequence': ['nucleic+acid+sequence'],
    'nucleobase': ['nucleobase'],
    'nucleobases': ['nucleobases'],
    'nucleoside': ['nucleoside'],
    'nucleoside_including_deoxyribose_as_a_component': [   'nucleoside+including+deoxyribose+as+a+component'],
    'nucleosides': ['nucleosides'],
    'nucleotide': ['nucleotide'],
    'nucleotides': ['nucleotides'],
    'nudism': ['nudism'],
    'nudist': ['nudist'],
    'nudist_paradise': ['nudist+paradise'],
    'nudity': ['nudity'],
    'numb': ['numb'],
    'number': ['number'],
    'nutrient': ['nutrient'],
    'nutrients': ['nutrients'],
    'obesity': ['obesity'],
    'object': ['object'],
    'object-oriented_programming': ['object-oriented+programming'],
    'objects': ['objects'],
    'observation': ['observation'],
    'occupation_founded_upon_specialized_educational_training': [   'occupation+founded+upon+specialized+educational+training'],
    'odor': ['odor'],
    'odorless': ['odorless'],
    'officer': ['officer'],
    'offspring': ['offspring'],
    'olfaction': ['olfaction'],
    'open-source_framework_developed': ['open-source+framework+developed'],
    'open_source_java_implementation': ['open+source+java+implementation'],
    'opiod': ['opiod'],
    'optical_microscopy': ['optical+microscopy'],
    'opticks': ['opticks'],
    'optics': ['optics'],
    'ordinal_data': ['ordinal+data'],
    'ore': ['ore'],
    'organ': ['organ'],
    'organ_only': ['organ+only'],
    'organelle': ['organelle'],
    'organelles': ['organelles'],
    'organic_compound': ['organic+compound'],
    'organisation': ['organisation'],
    'organisation_todt': ['organisation+todt'],
    'organised': ['organised'],
    'organised_crime_groups_originating': [   'organised+crime+groups+originating'],
    'organism': ['organism'],
    'organism_optimal': ['organism+optimal'],
    'organisms': ['organisms'],
    'organization': ['organization'],
    'organizing': ['organizing'],
    'organometallic_chemistry': ['organometallic+chemistry'],
    'organometallic_compounds': ['organometallic+compounds'],
    'oxidant': ['oxidant'],
    'oxidation': ['oxidation'],
    'oxidation_state': ['oxidation+state'],
    'oxide': ['oxide'],
    'oxides': ['oxides'],
    'oxidized': ['oxidized'],
    'oxidized_cellulose': ['oxidized+cellulose'],
    'oxidizer': ['oxidizer'],
    'oxidoreductase': ['oxidoreductase'],
    'oxoacid': ['oxoacid'],
    'oxygen': ['oxygen'],
    'oxymetholone': ['oxymetholone'],
    'pain': ['pain'],
    'painkiller': ['painkiller'],
    'pancreas': ['pancreas'],
    'pancreatitis': ['pancreatitis'],
    'parasitic': ['parasitic'],
    'parasitic_alveolates': ['parasitic+alveolates'],
    'parasitic_disease': ['parasitic+disease'],
    'parasitic_diseases': ['parasitic+diseases'],
    'parasitic_twin': ['parasitic+twin'],
    'parasitism': ['parasitism'],
    'parotitis': ['parotitis'],
    'part': ['part'],
    'particle': ['particle'],
    'particular_abnormal_condition': ['particular+abnormal+condition'],
    'patent': ['patent'],
    'patent_expiration': ['patent+expiration', 'patent+expire'],
    'pathogen': ['pathogen'],
    "pathogen's_or_microbe's_ability_to_infect_or_damage_a_host": [   "pathogen's+or+microbe's+ability+to+infect+or+damage+a+host"],
    'pathogenic_bacteria': ['pathogenic+bacteria'],
    'pathogens': ['pathogens'],
    'pathology': ['pathology'],
    'patient_adherence': ['patient+adherence'],
    'patient_derived_xenograft': ['patient+derived+xenograft'],
    'patient_monitoring': ['patient+monitoring'],
    'pd-1': ['pd-1'],
    'pd-l1': ['pd-l1'],
    'pea': ['pea'],
    'peas': ['peas'],
    'pediculosis': ['pediculosis'],
    'pelvis': ['pelvis'],
    'peptide': ['peptide'],
    'peptides': ['peptides'],
    'peptidomimetic': ['peptidomimetic'],
    'peptidomimetics': ['peptidomimetics'],
    'peptoid': ['peptoid'],
    'percolozoa': ['percolozoa'],
    'period': ['period'],
    'period_6_element': ['period+6+element'],
    'periodic_table': ['periodic+table'],
    'periodization': ['periodization'],
    'peripheral_blood_lymphocyte': ['peripheral+blood+lymphocyte'],
    'peripheral_blood_lymphocytes': ['peripheral+blood+lymphocytes'],
    'persistent_identifier_or_handle': ['persistent+identifier+or+handle'],
    'person_who_is_accorded_special_privileges_due_to_their_status_or_importance': [   'person+who+is_accorded+special+privileges+due+to+their+status+or+importance'],
    'person_who_makes_designs_objects': ['person+who+makes+designs+objects'],
    'personal_protective_equipment': ['personal+protective+equipment'],
    'pfu_dna_polymerase': ['pfu+dna+polymerase'],
    'ph': ['ph'],
    'pharmaceutical_drug': ['pharmaceutical+drug'],
    'pharmaceutical_formulation': ['pharmaceutical+formulation'],
    'pharmaceutical_science': ['pharmaceutical+science'],
    'pharmaceutical_sciences': ['pharmaceutical+sciences'],
    'pharmacodynamic': ['pharmacodynamic'],
    'pharmacodynamics': ['pharmacodynamics'],
    'pharmacology': ['pharmacology'],
    'pharmacy': ['pharmacy'],
    'phenomena': ['phenomena'],
    'phenomenalism': ['phenomenalism'],
    'phenomenon': ['phenomenon'],
    'phenotype': ['phenotype'],
    'phenotypes': ['phenotypes'],
    'phosphate': ['phosphate'],
    'phosphoprotein': ['phosphoprotein'],
    'phosphoproteins': ['phosphoproteins'],
    'phosphorus': ['phosphorus'],
    'phosphorus_monoxide': ['phosphorus+monoxide'],
    'phosphoryl_group': ['phosphoryl+group'],
    'phosphorylation': ['phosphorylation'],
    'phosphotransferase': ['phosphotransferase'],
    'photon': ['photon'],
    'photosynthesis': ['photosynthesis'],
    'phototransduction': ['phototransduction'],
    'phylogenetic_tree': ['phylogenetic+tree'],
    'phylum': ['phylum'],
    'physical_object': ['physical+object'],
    'physical_organization': ['physical+organization'],
    'physics': ['physics'],
    'physiological_or_medicinal': ['physiological+or+medicinal'],
    'physiology': ['physiology'],
    'plan_or_specification_the': ['plan+or+specification+the'],
    'planet': ['planet'],
    'planet_earth': ['planet+earth'],
    'planets': ['planets'],
    'plant': ['plant'],
    'plants': ['plants'],
    'planula': ['planula'],
    'plastid': ['plastid'],
    'plastids': ['plastids'],
    'pleasure': ['pleasure'],
    'ploidy': ['ploidy'],
    'poison': ['poison'],
    'poisonous_substance_produced': ['poisonous+substance+produced'],
    'polymer': ['polymer'],
    'polymerase': ['polymerase'],
    'polymeric_molecule': ['polymeric+molecule'],
    'polymerization': ['polymerization'],
    'polymers_produced_by_living_organisms': [   'polymers+produced+by+living+organisms'],
    'polynucleotide': ['polynucleotide'],
    'polyphyly': ['polyphyly'],
    'positive-sense_single-stranded_rna_virus': [   'positive-sense+single-stranded+rna+virus'],
    'post-transcriptional_modification': ['post-transcriptional+modification'],
    'prediction': ['prediction'],
    'predictions': ['predictions'],
    'preparing_beef_consumption': ['preparing+beef+consumption'],
    'presenting_information_about_the_chemical': [   'presenting+information+about+the+chemical'],
    'preserved_remains': ['preserved+remains'],
    'price': ['price'],
    'price_decrease': ['price+decrease'],
    'price_increase': ['price+increase'],
    'primary_male_sex_hormone': ['primary+male+sex+hormone'],
    'primate': ['primate'],
    'problem_solving': ['problem+solving'],
    'procedure_carried_out_to_support': ['procedure+carried+out+to+support'],
    'process': ['process'],
    'process_allowing_nuclear_fusion_to_take_place_at_temperatures_significantly_lower_than_the_temperatures_required_thermonuclear_fusion': [   'process+allowing+nuclear+fusion+to+take+place+at+temperatures+significantly+lower+than+the+temperatures+required+thermonuclear+fusion'],
    'process_flow_diagram': ['process+flow+diagram'],
    'process_unit_air_pollution': ['process+unit+air+pollution'],
    'processes': ['processes'],
    'processivity': ['processivity'],
    'product_promotion': [   'product+promotion',
                             'promotion+new_product',
                             'promotion+product'],
    'profession': ['profession'],
    'program': ['program'],
    'programmed_cell_death': ['programmed+cell+death'],
    'programmer': ['programmer'],
    'programming': ['programming'],
    'prokaryote': ['prokaryote'],
    'prokaryotes': ['prokaryotes'],
    'prokaryotic': ['prokaryotic'],
    'prokaryotic_microorganism': ['prokaryotic+microorganism'],
    'prokaryotic_translation': ['prokaryotic+translation'],
    'promotion': ['promotion'],
    'proposed_basal_podiate_taxon': ['proposed+basal+podiate+taxon'],
    'proposed_explanation_a_phenomenon': ['proposed+explanation+a+phenomenon'],
    'prostate': ['prostate'],
    'prostate_cancer': ['prostate+cancer'],
    'prostate_cell': ['prostate+cell'],
    'prostate_histopathology': ['prostate+histopathology'],
    'prostate_histopathology_image': ['prostate+histopathology+image'],
    'prostate_pathology': ['prostate+pathology'],
    'prostatectomy_specimen': ['prostatectomy+specimen'],
    'protective_response': ['protective+response'],
    'protein': ['protein'],
    'protein_domain': ['protein+domain'],
    'protein_engineering': ['protein+engineering'],
    'protein_engineering_technique': ['protein+engineering+technique'],
    'protein_quaternary_structure': ['protein+quaternary+structure'],
    'protein_substance_analogous_to_the': [   'protein+substance+analogous+to+the'],
    'proteinogenic_amino_acid': ['proteinogenic+amino+acid'],
    'proteins': ['proteins'],
    'proteobacteria': ['proteobacteria'],
    'proteome': ['proteome'],
    'proteomics': ['proteomics'],
    'proteopathy': ['proteopathy'],
    'proteostasis': ['proteostasis'],
    'proteotoxicity': ['proteotoxicity'],
    'proteus': ['proteus'],
    'protist': ['protist'],
    'proton': ['proton'],
    'protonated': ['protonated'],
    'protonation': ['protonation'],
    'protons': ['protons'],
    'protozoa': ['protozoa'],
    'protozoan': ['protozoan'],
    'protozoan_infection': ['protozoan+infection'],
    'protozoans': ['protozoans'],
    'pseudopod': ['pseudopod'],
    'pseudopodia': ['pseudopodia'],
    'pseudopods': ['pseudopods'],
    'psychology': ['psychology'],
    'pyridoxal_phosphate_-dependent_transaminase_enzyme': [   'pyridoxal+phosphate+-dependent+transaminase+enzyme'],
    'pyrococcus_furiosus': ['pyrococcus+furiosus'],
    'qmail': ['qmail'],
    'quantitative_property': ['quantitative+property'],
    'quantitative_research': ['quantitative+research'],
    'quantity': ['quantity'],
    'quantum_mechanics': ['quantum+mechanics'],
    'quaternary_structure': ['quaternary+structure'],
    'radiation': ['radiation'],
    'reacting_monomer_molecules_together': [   'reacting+monomer+molecules+together'],
    'reaction': ['reaction'],
    'receptor': ['receptor'],
    'redox': ['redox'],
    'region_on_a_macromolecule_such_as_a_protein': [   'region+on+a+macromolecule+such+as+a+protein'],
    'regulated_market': ['regulated+market'],
    'regulated_process_during_gene_expression': [   'regulated+process+during+gene+expression'],
    'regulation_gene_expression': ['regulation+gene+expression'],
    'regulatory_t_cell': ['regulatory+t+cell'],
    'remote_patient_monitoring': ['remote+patient+monitoring'],
    'renca_renal_cell': ['renca+renal+cell'],
    'repeated': ['repeated'],
    'report': ['report'],
    'reporter_gene': ['reporter+gene'],
    'reproduction': ['reproduction'],
    'reproductive_system': ['reproductive+system'],
    'reptation': ['reptation'],
    'research_investment': ['research+investment'],
    'residue': ['residue'],
    'resonance': ['resonance'],
    'resonant': ['resonant'],
    'resonant_converter': ['resonant+converter'],
    'response': ['response'],
    'restriction_enzyme': ['restriction+enzyme'],
    'result': ['result'],
    'retinoid': ['retinoid'],
    'reverse_transcription': ['reverse+transcription'],
    'reverse_transcription_polymerase_chain_reaction': [   'reverse+transcription+polymerase+chain+reaction'],
    'rhodopsin': ['rhodopsin'],
    'ribbon_diagram': ['ribbon+diagram'],
    'ribonuclease': ['ribonuclease'],
    'ribonuclease_a': ['ribonuclease+a'],
    'ribonuclease_inhibitor': ['ribonuclease+inhibitor'],
    'ribonucleases': ['ribonucleases'],
    'ribonucleoprotein': ['ribonucleoprotein'],
    'ribonucleoprotein_particle': ['ribonucleoprotein+particle'],
    'rli-15': ['rli-15'],
    'rna': ['rna'],
    'rna-dependent_rna_polymerase': ['rna-dependent+rna+polymerase'],
    'rna_molecule': ['rna+molecule'],
    'rna_processing_in': ['rna+processing+in'],
    'rna_splicing': ['rna+splicing'],
    'robot_deployed_agricultural_purposes': [   'robot+deployed+agricultural+purposes'],
    'roton': ['roton'],
    'ruled_surface': ['ruled+surface'],
    'rumen': ['rumen'],
    'ruminant': ['ruminant'],
    'ruminants': ['ruminants'],
    'rush': ['rush'],
    'sample': ['sample'],
    'sandpaper': ['sandpaper'],
    'scale': ['scale'],
    'scalp': ['scalp'],
    'scanning_machine': ['scanning+machine'],
    'schizophrenia': ['schizophrenia'],
    'science': ['science'],
    'science_concerned_the_description': ['science+concerned+the+description'],
    'science_technology': ['science+technology'],
    'scientific': ['scientific'],
    'scientific_discipline_involved_elements': [   'scientific+discipline+involved+elements'],
    'scientific_instrument': ['scientific+instrument'],
    'scientific_method': ['scientific+method'],
    'scientific_principles_to_design': ['scientific+principles+to+design'],
    'scientific_publications_focused_primarily_on_research': [   'scientific+publications+focused+primarily+on+research'],
    'seasonal_affective_disorder': ['seasonal+affective+disorder'],
    'sediment': ['sediment'],
    'seed': ['seed'],
    'segregating_organisms': ['segregating+organisms'],
    'selective_barrier': ['selective+barrier'],
    'sensory_transduction': ['sensory+transduction'],
    'sentence_analysis': ['sentence+analysis'],
    'sequence': ['sequence'],
    'sequencing': ['sequencing'],
    'series': ['series'],
    'serine': ['serine'],
    'sex': ['sex'],
    'sex_organ': ['sex+organ'],
    'shape_like_a_corkscrew_or_spiral_staircase': [   'shape+like+a+corkscrew+or+spiral+staircase'],
    'signaling_molecules_made_by_the_enzymatic_or_non-enzymatic': [   'signaling+molecules+made+by+the+enzymatic+or+non-enzymatic'],
    'silurian': ['silurian'],
    'simple_ketonic_monosaccharide': ['simple+ketonic+monosaccharide'],
    'simple_sugar_the_molecular_formula_c6h12o_glucose_is_a_most_abundant_monosaccharide': [   'simple+sugar+the+molecular+formula+c6h12o+glucose+is_a+most+abundant+monosaccharide'],
    'simplest_enol': ['simplest+enol'],
    'situation': ['situation'],
    'skeleton': ['skeleton'],
    'skid_row,_los_angeles': ['skid+row,+los+angeles'],
    'skin_cancer': ['skin+cancer'],
    'slide': ['slide'],
    'small_123_amino_acid_protein': ['small+123+amino+acid+protein'],
    'small_infectious_agent': ['small+infectious+agent'],
    'small_localized_object_to': ['small+localized+object+to'],
    'small_or_even_microscopic_crystal': ['small+or+even+microscopic+crystal'],
    'small_portable_artistic_object': ['small+portable+artistic+object'],
    'small_protein': ['small+protein'],
    'small_protein-like_chain_designed_to_mimic_a_peptide': [   'small+protein-like+chain+designed+to+mimic+a+peptide'],
    'smallest_constituent': ['smallest+constituent'],
    'societies': ['societies'],
    'society': ['society'],
    'sociology': ['sociology'],
    'soft_tissue': ['soft+tissue'],
    'software': ['software'],
    'solid_material': ['solid+material'],
    'solute': ['solute'],
    'solution': ['solution'],
    'solvent': ['solvent'],
    'song_by_american_rock_band_i_prevail': [   'song+by+american+rock+band+i+prevail'],
    'song_by_american_rock_band_linkin_park': [   'song+by+american+rock+band+linkin+park'],
    'song_by_american_violinist_lindsey_stirling': [   'song+by+american+violinist+lindsey+stirling'],
    'song_by_the_american_rock_band_linkin_park': [   'song+by+the+american+rock+band+linkin+park'],
    'space': ['space'],
    'specialised_sequence_elements': ['specialised+sequence+elements'],
    'specialized_into_male': ['specialized+into+male'],
    'specialized_subunit': ['specialized+subunit'],
    'species': ['species'],
    'specimen': ['specimen'],
    'spectroscopy': ['spectroscopy'],
    'sperm': ['sperm'],
    'spermatozoa': ['spermatozoa'],
    'spermatozoon': ['spermatozoon'],
    'spherical_proteins': ['spherical+proteins'],
    "sports_prototype_racing_car_developed_specifically_the_grand_american_road_racing_association's_rolex_sports_car_series_as_their_top": [   "sports+prototype+racing+car+developed+specifically+the+grand+american+road+racing+association's+rolex+sports+car+series+as+their+top"],
    'stain': ['stain'],
    'standard': ['standard'],
    'standard_linear_solid_model': ['standard+linear+solid+model'],
    'standardization': ['standardization'],
    'star': ['star'],
    'starch': ['starch'],
    'stars': ['stars'],
    'state': ['state'],
    'statements_usually_constructed_to_describe_a_facts': [   'statements+usually+constructed+to+describe+a+facts'],
    'stereochemistry': ['stereochemistry'],
    'stereoisomerism': ['stereoisomerism'],
    'steroid': ['steroid'],
    'steroid_hormone': ['steroid+hormone'],
    'stomach': ['stomach'],
    'structural_formula': ['structural+formula'],
    'structuralism': ['structuralism'],
    'structure': ['structure'],
    'study': ['study'],
    'subatomic_particle': ['subatomic+particle'],
    'subphylum': ['subphylum'],
    'substance': ['substance'],
    'substance_consumed_to_provide_nutritional_support_an_organism': [   'substance+consumed+to+provide+nutritional+support+an+organism'],
    'subtribe': ['subtribe'],
    'succession_base-pairs': ['succession+base-pairs'],
    'sucrase': ['sucrase'],
    'sucrose': ['sucrose'],
    'sugar': ['sugar'],
    'sugar_formed_when_two_monosaccharides_is_a_joined_by_glycosidic_linkage': [   'sugar+formed+when+two+monosaccharides+is_a+joined+by+glycosidic+linkage'],
    'sugaring': ['sugaring'],
    'sulfur_oxoacid': ['sulfur+oxoacid'],
    'summarizes_commonly': ['summarizes+commonly'],
    'superagonist': ['superagonist'],
    'sushi+_domain': ['sushi++domain'],
    'sushi_domain': ['sushi+domain'],
    'sustained_multi-generational_relationship_in': [   'sustained+multi-generational+relationship+in'],
    'symbiosis': ['symbiosis'],
    'symbiotic_relationship_between_species': [   'symbiotic+relationship+between+species'],
    'symbol': ['symbol'],
    'symbols': ['symbols'],
    'system': ['system'],
    'system_sex_organs': ['system+sex+organs'],
    'systematic_empirical': ['systematic+empirical'],
    'systematic_enterprise': ['systematic+enterprise'],
    'systems': ['systems'],
    't_cell': ['t+cell'],
    'tabular_display': ['tabular+display'],
    'taxonomic_rank': ['taxonomic+rank'],
    'taxonomy': ['taxonomy'],
    'technique_separating_different_molecules_by': [   'technique+separating+different+molecules+by'],
    'technology': ['technology'],
    'technology_to_enable': ['technology+to+enable'],
    'temperature': ['temperature'],
    'temperatures': ['temperatures'],
    'temporary_arm-like': ['temporary+arm-like'],
    'testate_amoebae': ['testate+amoebae'],
    'testosterone': ['testosterone'],
    'the_catalyst': ['the+catalyst'],
    'the_cells': ['the+cells'],
    'the_chemical': ['the+chemical'],
    'the_chemical_brothers': ['the+chemical+brothers'],
    'the_military_forces': ['the+military+forces'],
    'the_natural': ['the+natural'],
    'the_offspring': ['the+offspring'],
    'the_only_extant_members': ['the+only+extant+members'],
    'thermal': ['thermal'],
    'thermal_oxidizer': ['thermal+oxidizer'],
    'thermodynamics': ['thermodynamics'],
    'thing': ['thing'],
    'tide': ['tide'],
    'time': ['time'],
    'tissue': ['tissue'],
    'tissues_similar_functions': ['tissues+similar+functions'],
    'tobymac': ['tobymac'],
    'topic': ['topic'],
    'toxic': ['toxic'],
    'toxicant': ['toxicant'],
    'toxicants': ['toxicants'],
    'toxicity': ['toxicity'],
    'toxin': ['toxin'],
    'toxins': ['toxins'],
    'trace': ['trace'],
    'transaminase': ['transaminase'],
    'transaminases': ['transaminases'],
    'transamination': ['transamination'],
    'transcriptome': ['transcriptome'],
    'transduction': ['transduction'],
    'transgender_hormone_therapy': ['transgender+hormone+therapy'],
    'transmembrane_receptors_expressed_on_the': [   'transmembrane+receptors+expressed+on+the'],
    'transmission_electron_cryomicroscopy': [   'transmission+electron+cryomicroscopy'],
    'treatment': ['treatment'],
    'trial_phase': ['trial+phase', 'phase+trial'],
    'trna': ['trna'],
    'troubleshoot': ['troubleshoot'],
    'troubleshooting': ['troubleshooting'],
    'true_smut_fungi': ['true+smut+fungi'],
    'tubulin': ['tubulin'],
    'tumor': ['tumor'],
    'tumor_cell': ['tumor+cell'],
    'two_main_immunity_strategies': ['two+main+immunity+strategies'],
    'type_agonist': ['type+agonist'],
    'type_i_cytokine_receptor': ['type+i+cytokine+receptor'],
    'ultrasound': ['ultrasound'],
    'ungulate': ['ungulate'],
    'unicellular_organism': ['unicellular+organism'],
    'unit': ['unit'],
    'united_states_armed_forces': ['united+states+armed+forces'],
    'universe': ['universe'],
    'universities': ['universities'],
    'university': ['university'],
    'urosporidae': ['urosporidae'],
    'ustilaginomycetes': ['ustilaginomycetes'],
    'ustilaginomycotina': ['ustilaginomycotina'],
    'usually_taken_as_mental_representational': [   'usually+taken+as+mental+representational'],
    'vaccination': ['vaccination'],
    'vaccine': ['vaccine'],
    'vacuolaria': ['vacuolaria'],
    'vacuole': ['vacuole'],
    'vahlkampfiidae': ['vahlkampfiidae'],
    'valrubicin': ['valrubicin'],
    'vampyrellidea': ['vampyrellidea'],
    'vannellidae': ['vannellidae'],
    'vannellina': ['vannellina'],
    'variosea': ['variosea'],
    'varipodida': ['varipodida'],
    'varisulca': ['varisulca'],
    'vascular_plant': ['vascular+plant'],
    'vaucheriales': ['vaucheriales'],
    'vault': ['vault'],
    'velocity': ['velocity'],
    'vermamoebidae': ['vermamoebidae'],
    'verrucomicrobia': ['verrucomicrobia'],
    'vertebra': ['vertebra'],
    'vertebrate': ['vertebrate'],
    'vertebrate_animals_constituting_the_class_mammalia': [   'vertebrate+animals+constituting+the+class+mammalia'],
    'vertebrates': ['vertebrates'],
    'very_important_person': ['very+important+person'],
    'very_large_molecule': ['very+large+molecule'],
    'very_simple_bilaterians_up_to_a_few_centimeters_long': [   'very+simple+bilaterians+up+to+a+few+centimeters+long'],
    'vetches': ['vetches'],
    'vexilliferidae': ['vexilliferidae'],
    'vicia': ['vicia'],
    'vinyl_alcohol': ['vinyl+alcohol'],
    'viral_eukaryogenesis': ['viral+eukaryogenesis'],
    'virtue': ['virtue'],
    'virulence': ['virulence'],
    'virus': ['virus'],
    'viruses': ['viruses'],
    'visual_phototransduction': ['visual+phototransduction'],
    'vitrella_brassicaformis': ['vitrella+brassicaformis'],
    'volvox_carteri': ['volvox+carteri'],
    'voromonadidae': ['voromonadidae'],
    'voromonas': ['voromonas'],
    'vorticella': ['vorticella'],
    'was': ['was'],
    'wasp': ['wasp'],
    'wasps': ['wasps'],
    'water': ['water'],
    'water-insoluble': ['water-insoluble'],
    'wavelength': ['wavelength'],
    'wavelengths': ['wavelengths'],
    'wax': ['wax'],
    'way': ['way'],
    'way_light_interacts_the': ['way+light+interacts+the'],
    'weak_entity': ['weak+entity'],
    'white_blood_cell': [   'white+blood+cell',
                            'colorless+corpuscle',
                            'immune+cell',
                            'inflammatory+cell',
                            'leucocyte+cell',
                            'leukocyte+count',
                            'leukocyte+disorder',
                            'types+of+immune+cell',
                            'white+blood+corpuscle',
                            'white+cell',
                            'white+corpuscle'],
    'whole_genome_sequencing': ['whole+genome+sequencing'],
    'widespread_brain_regions_showing_functional_connectivity_by_statistical_analysis': [   'widespread+brain+regions+showing+functional+connectivity+by+statistical+analysis'],
    'wool': ['wool'],
    'world': ['world'],
    'xenacoelomorpha': ['xenacoelomorpha'],
    'xenoturbella': ['xenoturbella'],
    'xenoturbellid': ['xenoturbellid'],
    'xenoturbellida': ['xenoturbellida'],
    'xenoturbellids': ['xenoturbellids'],
    'xylonomycetes': ['xylonomycetes'],
    'yeast': ['yeast'],
    'yeasts': ['yeasts'],
    'yellow-green_algae': ['yellow-green+algae'],
    'zosterophyll': ['zosterophyll'],
    'zosterophyllopsida': ['zosterophyllopsida'],
    'zygnematophyceae': ['zygnematophyceae'],
    'zygocystinae': ['zygocystinae'],
    'zygomycota': ['zygomycota'],
    'ɑ-amino_acid': ['ɑ-amino+acid'],
    'α-methylfentanyl': ['α-methylfentanyl'],
    'γ-oryzanol': ['γ-oryzanol']}
