
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_rel_defines_dict = {
    '-definition of Limit': [   'https://en.wikipedia.org/wiki/(%CE%B5,_%CE%B4)-definition_of_limit'],
    '4-aminobutyrate Transaminase': [   'https://en.wikipedia.org/wiki/4-aminobutyrate_transaminase'],
    'Abbreviated Dialing': [   'https://en.wikipedia.org/wiki/Abbreviated_dialing'],
    'Abnormal Posturing': ['https://en.wikipedia.org/wiki/Abnormal_posturing'],
    'Absorbance': ['https://en.wikipedia.org/wiki/Absorbance'],
    'Acceleration': ['https://en.wikipedia.org/wiki/Acceleration'],
    'Acetoin': ['https://en.wikipedia.org/wiki/Acetoin'],
    'Acetone': ['https://en.wikipedia.org/wiki/Acetone'],
    'Acetone–butanol–ethanol Fermentation': [   'https://en.wikipedia.org/wiki/Acetone%E2%80%93butanol%E2%80%93ethanol_fermentation'],
    'Acetyl Group': ['https://en.wikipedia.org/wiki/Acetyl_group'],
    'Acetylation': ['https://en.wikipedia.org/wiki/Acetylation'],
    'Acid': ['https://en.wikipedia.org/wiki/Acid'],
    'Acidic Oxide': ['https://en.wikipedia.org/wiki/Acidic_oxide'],
    'Acidity Regulator': ['https://en.wikipedia.org/wiki/Acidity_regulator'],
    'Acoelomorpha': ['https://en.wikipedia.org/wiki/Acoelomorpha'],
    'Acpd': ['https://en.wikipedia.org/wiki/ACPD'],
    'Active Site': ['https://en.wikipedia.org/wiki/Active_site'],
    'Acute Proliferative Glomerulonephritis': [   'https://en.wikipedia.org/wiki/Acute_proliferative_glomerulonephritis'],
    'Acyl Group': ['https://en.wikipedia.org/wiki/Acyl_group'],
    'Acylation': ['https://en.wikipedia.org/wiki/Acylation'],
    'Adaptation': ['https://en.wikipedia.org/wiki/Adaptation'],
    'Adaptive Immune System': [   'https://en.wikipedia.org/wiki/Adaptive_immune_system'],
    'Adenine': ['https://en.wikipedia.org/wiki/Adenine'],
    'Adenosine': ['https://en.wikipedia.org/wiki/Adenosine'],
    'Adenylate Kinase': ['https://en.wikipedia.org/wiki/Adenylate_kinase'],
    'Adherence': ['https://en.wikipedia.org/wiki/Adherence_(medicine)'],
    'Adoption': ['https://en.wikipedia.org/wiki/Adoption'],
    'Affection': ['https://en.wikipedia.org/wiki/Affection'],
    'Agonist': ['https://en.wikipedia.org/wiki/Agonist'],
    'Agricultural Robot': ['https://en.wikipedia.org/wiki/Agricultural_robot'],
    'Agriculture': ['https://en.wikipedia.org/wiki/Agriculture'],
    'Alanine': ['https://en.wikipedia.org/wiki/Alanine'],
    'Albumin': ['https://en.wikipedia.org/wiki/Albumin'],
    'Alcohol': ['https://en.wikipedia.org/wiki/Alcohol'],
    'Algae': ['https://en.wikipedia.org/wiki/Algae'],
    'Algorithm': ['https://en.wikipedia.org/wiki/Algorithm'],
    'Algorithms For Calculating Variance': [   'https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance'],
    'Alkyl Nitrites': ['https://en.wikipedia.org/wiki/Alkyl_nitrites'],
    'Alternative Splicing': [   'https://en.wikipedia.org/wiki/Alternative_splicing'],
    'Alveolate': ['https://en.wikipedia.org/wiki/Alveolate'],
    'Amide': ['https://en.wikipedia.org/wiki/Amide'],
    'Amidicity': ['https://en.wikipedia.org/wiki/Amidicity'],
    'Aminal': ['https://en.wikipedia.org/wiki/Aminal'],
    'Amination': ['https://en.wikipedia.org/wiki/Amination'],
    'Amine': ['https://en.wikipedia.org/wiki/Amine'],
    'Amino Acid': ['https://en.wikipedia.org/wiki/Amino_acid'],
    'Aminoacyl Trna Synthetase': [   'https://en.wikipedia.org/wiki/Aminoacyl_tRNA_synthetase'],
    'Aminoacylation': ['https://en.wikipedia.org/wiki/Aminoacylation'],
    'Ammonia': ['https://en.wikipedia.org/wiki/Ammonia'],
    'Amoeba': ['https://en.wikipedia.org/wiki/Amoeba'],
    'Amoeboid Movement': ['https://en.wikipedia.org/wiki/Amoeboid_movement'],
    'Amoebozoa': ['https://en.wikipedia.org/wiki/Amoebozoa'],
    'Amplifier': ['https://en.wikipedia.org/wiki/Amplifier'],
    'Anabolic Steroid': ['https://en.wikipedia.org/wiki/Anabolic_steroid'],
    'Anabolism': ['https://en.wikipedia.org/wiki/Anabolism'],
    'Anaerobic Respiration': [   'https://en.wikipedia.org/wiki/Anaerobic_respiration'],
    'Analgesic': ['https://en.wikipedia.org/wiki/Analgesic'],
    'Analysis': ['https://en.wikipedia.org/wiki/Analysis'],
    'Analytical Technique': [   'https://en.wikipedia.org/wiki/Analytical_technique'],
    'Anatomy': ['https://en.wikipedia.org/wiki/Anatomy'],
    'Ancestor': ['https://en.wikipedia.org/wiki/Ancestor'],
    'Ancient History': ['https://en.wikipedia.org/wiki/Ancient_history'],
    'Androgen': ['https://en.wikipedia.org/wiki/Androgen'],
    'Angiogenin': ['https://en.wikipedia.org/wiki/Angiogenin'],
    'Animal': ['https://en.wikipedia.org/wiki/Animal'],
    'Animation': ['https://en.wikipedia.org/wiki/Animation'],
    'Animator': ['https://en.wikipedia.org/wiki/Animator'],
    'Anime': ['https://en.wikipedia.org/wiki/Anime'],
    'Anise': ['https://en.wikipedia.org/wiki/Anise'],
    'Anoikis': ['https://en.wikipedia.org/wiki/Anoikis'],
    'Anomer': ['https://en.wikipedia.org/wiki/Anomer'],
    'Anoxygenic Photosynthesis': [   'https://en.wikipedia.org/wiki/Anoxygenic_photosynthesis'],
    'Ant': ['https://en.wikipedia.org/wiki/Ant'],
    'Anthracycline': ['https://en.wikipedia.org/wiki/Anthracycline'],
    'Anthropology': ['https://en.wikipedia.org/wiki/Anthropology'],
    'Antibiotic': ['https://en.wikipedia.org/wiki/Antibiotic'],
    'Antibody': ['https://en.wikipedia.org/wiki/Antibody'],
    'Antibody-drug conjugate': [   'https://en.wikipedia.org/wiki/Antibody-drug_conjugate'],
    'Antigen-presenting Cell': [   'https://en.wikipedia.org/wiki/Antigen-presenting_cell'],
    'Antioxidant': ['https://en.wikipedia.org/wiki/Antioxidant'],
    'Antz': ['https://en.wikipedia.org/wiki/Antz'],
    'Ape': ['https://en.wikipedia.org/wiki/Ape'],
    'Apicomplexa': ['https://en.wikipedia.org/wiki/Apicomplexa'],
    'Archaea': ['https://en.wikipedia.org/wiki/Archaea'],
    'Archaeol': ['https://en.wikipedia.org/wiki/Archaeol'],
    'Arrangement': ['https://en.wikipedia.org/wiki/Arrangement'],
    'Art': ['https://en.wikipedia.org/wiki/Art'],
    'Ascomycota': ['https://en.wikipedia.org/wiki/Ascomycota'],
    'Aspartate Kinase': ['https://en.wikipedia.org/wiki/Aspartate_kinase'],
    'Aspartate Transaminase': [   'https://en.wikipedia.org/wiki/Aspartate_transaminase'],
    'Assay': ['https://en.wikipedia.org/wiki/Assay'],
    'Atom': ['https://en.wikipedia.org/wiki/Atom'],
    'Atomism': ['https://en.wikipedia.org/wiki/Atomism'],
    'Atoms in Molecules': ['https://en.wikipedia.org/wiki/Atoms_in_molecules'],
    'Atp Synthase': ['https://en.wikipedia.org/wiki/ATP_synthase'],
    'Authority': ['https://en.wikipedia.org/wiki/Authority'],
    'Auto Racing': ['https://en.wikipedia.org/wiki/Auto_racing'],
    'Axe': ['https://en.wikipedia.org/wiki/Axe'],
    'Axillary Lymph Nodes': [   'https://en.wikipedia.org/wiki/Axillary_lymph_nodes'],
    'Azide': ['https://en.wikipedia.org/wiki/Azide'],
    'B Cell': ['https://en.wikipedia.org/wiki/B_cell'],
    'B16 Melanoma': ['https://en.wikipedia.org/wiki/B16_Melanoma'],
    'Bacteria': [   'https://en.wikipedia.org/wiki/Bacteria',
                    'https://en.wikipedia.org/wiki/Pathogenic_bacteria'],
    'Bacterial Display': ['https://en.wikipedia.org/wiki/Bacterial_display'],
    'Bacterial Transcription': [   'https://en.wikipedia.org/wiki/Bacterial_transcription'],
    'Balantidiasis': ['https://en.wikipedia.org/wiki/Balantidiasis'],
    'Balantidium Coli': ['https://en.wikipedia.org/wiki/Balantidium_coli'],
    'Base Pair': ['https://en.wikipedia.org/wiki/Base_pair'],
    'Basidiomycota': ['https://en.wikipedia.org/wiki/Basidiomycota'],
    'Battle of Cisterna': ['https://en.wikipedia.org/wiki/Battle_of_Cisterna'],
    'Bean': ['https://en.wikipedia.org/wiki/Bean'],
    'Bechdel Test': ['https://en.wikipedia.org/wiki/Bechdel_test'],
    'Bee': ['https://en.wikipedia.org/wiki/Bee'],
    'Beef Aging': ['https://en.wikipedia.org/wiki/Beef_aging'],
    'Bernard Malamud': ['https://en.wikipedia.org/wiki/Bernard_Malamud'],
    'Beta Sheet': ['https://en.wikipedia.org/wiki/Beta_sheet'],
    'Bibcode': ['https://en.wikipedia.org/wiki/Bibcode'],
    'Big Five Personality Traits': [   'https://en.wikipedia.org/wiki/Big_Five_personality_traits'],
    'Bilateria': ['https://en.wikipedia.org/wiki/Bilateria'],
    'Binding Site': ['https://en.wikipedia.org/wiki/Binding_site'],
    'Biochemistry': ['https://en.wikipedia.org/wiki/Biochemistry'],
    'Biogenesis': ['https://en.wikipedia.org/wiki/Biogenesis'],
    'Bioinformatics': ['https://en.wikipedia.org/wiki/Bioinformatics'],
    'Biological Membrane': [   'https://en.wikipedia.org/wiki/Biological_membrane'],
    'Biological Process': ['https://en.wikipedia.org/wiki/Biological_process'],
    'Biological System': ['https://en.wikipedia.org/wiki/Biological_system'],
    'Biological Warfare': ['https://en.wikipedia.org/wiki/Biological_warfare'],
    'Biology': ['https://en.wikipedia.org/wiki/Biology'],
    'Biomolecule': ['https://en.wikipedia.org/wiki/Biomolecule'],
    'Biopharmaceutical Drug': [   'https://en.wikipedia.org/wiki/Biopharmaceutical'],
    'Biopolymer': ['https://en.wikipedia.org/wiki/Biopolymer'],
    'Biosynthesis': ['https://en.wikipedia.org/wiki/Biosynthesis'],
    'Blood': ['https://en.wikipedia.org/wiki/Blood'],
    'Bovina': ['https://en.wikipedia.org/wiki/Bovina_(subtribe)'],
    'Bow Down': ['https://en.wikipedia.org/wiki/Bow_Down_(I_Prevail_song)'],
    'Bradford Protein Assay': [   'https://en.wikipedia.org/wiki/Bradford_protein_assay'],
    'Branched-chain Alpha-keto Acid Dehydrogenase Complex': [   'https://en.wikipedia.org/wiki/Branched-chain_alpha-keto_acid_dehydrogenase_complex'],
    'Breaking Down': ['https://en.wikipedia.org/wiki/Breaking_Down'],
    'Bright Field Microscopy': [   'https://en.wikipedia.org/wiki/Bright-field_microscopy'],
    'British Firms': [   'https://en.wikipedia.org/wiki/British_firms_(organised_crime)'],
    'Building': ['https://en.wikipedia.org/wiki/Building'],
    'Business': ['https://en.wikipedia.org/wiki/Business'],
    'Butanol': ['https://en.wikipedia.org/wiki/Butanol'],
    'Calculation': ['https://en.wikipedia.org/wiki/Calculation'],
    'California Gold Rush': [   'https://en.wikipedia.org/wiki/California_Gold_Rush'],
    'Cancer Immunotherapy': [   'https://en.wikipedia.org/wiki/Cancer_immunotherapy'],
    'Cancer Treatment': ['https://en.wikipedia.org/wiki/Treatment_of_cancer'],
    'Capacitor': ['https://en.wikipedia.org/wiki/Capacitor'],
    'Carbene': ['https://en.wikipedia.org/wiki/Carbene'],
    'Carbohydrate': ['https://en.wikipedia.org/wiki/Carbohydrate'],
    'Carbohydrate Metabolism': [   'https://en.wikipedia.org/wiki/Carbohydrate_metabolism'],
    'Carbon': ['https://en.wikipedia.org/wiki/Carbon'],
    'Carboximidate': ['https://en.wikipedia.org/wiki/Carboximidate'],
    'Cartesian Coordinate System': [   'https://en.wikipedia.org/wiki/Cartesian_coordinate_system'],
    'Casein': ['https://en.wikipedia.org/wiki/Casein'],
    'Catabolism': ['https://en.wikipedia.org/wiki/Catabolism'],
    'Catalase': ['https://en.wikipedia.org/wiki/Catalase'],
    'Causes of Cancer': ['https://en.wikipedia.org/wiki/Causes_of_cancer'],
    'Cdna Library': ['https://en.wikipedia.org/wiki/CDNA_library'],
    'Cefalexin': ['https://en.wikipedia.org/wiki/Cefalexin'],
    'Cell': ['https://en.wikipedia.org/wiki/Cell_(biology)'],
    'Cell Adhesion': ['https://en.wikipedia.org/wiki/Cell_adhesion'],
    'Cell Biology': ['https://en.wikipedia.org/wiki/Cell_biology'],
    'Cell Culture': ['https://en.wikipedia.org/wiki/Cell_culture'],
    'Cell Membrane': ['https://en.wikipedia.org/wiki/Cell_membrane'],
    'Cell Nucleus': ['https://en.wikipedia.org/wiki/Cell_nucleus'],
    'Cellular Compartment': [   'https://en.wikipedia.org/wiki/Cellular_compartment'],
    'Cellular Organizational Structure': [   'https://en.wikipedia.org/wiki/Cellular_organizational_structure'],
    'Cellulose': ['https://en.wikipedia.org/wiki/Cellulose'],
    'Cercozoa': ['https://en.wikipedia.org/wiki/Cercozoa'],
    'Chain': ['https://en.wikipedia.org/wiki/Chain'],
    'Chalcogen': ['https://en.wikipedia.org/wiki/Chalcogen'],
    'Chaperome': ['https://en.wikipedia.org/wiki/Chaperome'],
    'Chaperone': ['https://en.wikipedia.org/wiki/Chaperone_(protein)'],
    'Charophyta': ['https://en.wikipedia.org/wiki/Charophyta'],
    'Chemical Bond': ['https://en.wikipedia.org/wiki/Chemical_bond'],
    'Chemical Compound': ['https://en.wikipedia.org/wiki/Chemical_compound'],
    'Chemical Element': ['https://en.wikipedia.org/wiki/Chemical_element'],
    'Chemical Energy': ['https://en.wikipedia.org/wiki/Chemical_energy'],
    'Chemical Formula': ['https://en.wikipedia.org/wiki/Chemical_formula'],
    'Chemical Reaction': ['https://en.wikipedia.org/wiki/Chemical_reaction'],
    'Chemical Structure': ['https://en.wikipedia.org/wiki/Chemical_structure'],
    'Chemical Substance': ['https://en.wikipedia.org/wiki/Chemical_substance'],
    'Chemistry': ['https://en.wikipedia.org/wiki/Chemistry'],
    'Chemokine': ['https://en.wikipedia.org/wiki/Chemokine'],
    'Chemosynthesis': ['https://en.wikipedia.org/wiki/Chemosynthesis'],
    'Chemotherapeutic Agent': [   'https://en.wikipedia.org/wiki/List_of_chemotherapeutic_agents'],
    'Chemotherapy': ['https://en.wikipedia.org/wiki/Chemotherapy'],
    'Chevrotain': ['https://en.wikipedia.org/wiki/Chevrotain'],
    'Chimeric Antigen Receptor T Cell': [   'https://en.wikipedia.org/wiki/Chimeric_antigen_receptor_T_cell'],
    'Chirality': ['https://en.wikipedia.org/wiki/Chirality_(chemistry)'],
    'Chloroplast DNA': ['https://en.wikipedia.org/wiki/Chloroplast_DNA'],
    'Cholera': ['https://en.wikipedia.org/wiki/Cholera'],
    'Chromatography': ['https://en.wikipedia.org/wiki/Chromatography'],
    'Chromosome': ['https://en.wikipedia.org/wiki/Chromosome'],
    'Ciliate': ['https://en.wikipedia.org/wiki/Ciliate'],
    'Cis-regulatory Element': [   'https://en.wikipedia.org/wiki/Cis-regulatory_element'],
    'Cis–trans Isomerism': [   'https://en.wikipedia.org/wiki/Cis%E2%80%93trans_isomerism'],
    'Clade': ['https://en.wikipedia.org/wiki/Clade'],
    'Clinical Study Design': [   'https://en.wikipedia.org/wiki/Clinical_study_design'],
    'Cloning': ['https://en.wikipedia.org/wiki/Cloning'],
    'Clustal': ['https://en.wikipedia.org/wiki/Clustal'],
    'Codec': ['https://en.wikipedia.org/wiki/Codec'],
    'Collagen': ['https://en.wikipedia.org/wiki/Collagen'],
    'Colorectal Cancer': ['https://en.wikipedia.org/wiki/Colorectal_cancer'],
    'Commodity': ['https://en.wikipedia.org/wiki/Commodity'],
    'Compression of Genomic Sequencing Data': [   'https://en.wikipedia.org/wiki/Compression_of_Genomic_Sequencing_Data'],
    'Computation': ['https://en.wikipedia.org/wiki/Computation'],
    'Computer Programming': [   'https://en.wikipedia.org/wiki/Computer_programming'],
    'Computer Science': ['https://en.wikipedia.org/wiki/Computer_science'],
    'Computing': ['https://en.wikipedia.org/wiki/Computing'],
    'Concentration': ['https://en.wikipedia.org/wiki/Concentration'],
    'Concept': ['https://en.wikipedia.org/wiki/Concept'],
    'Conformational Change': [   'https://en.wikipedia.org/wiki/Conformational_change'],
    'Conformational Isomerism': [   'https://en.wikipedia.org/wiki/Conformational_isomerism'],
    'Connecticut Agricultural Experiment Station': [   'https://en.wikipedia.org/wiki/Connecticut_Agricultural_Experiment_Station'],
    'Connective Tissue': ['https://en.wikipedia.org/wiki/Connective_tissue'],
    'Conoid': ['https://en.wikipedia.org/wiki/Conoid'],
    'Conosa': ['https://en.wikipedia.org/wiki/Conosa'],
    'Consciousness': ['https://en.wikipedia.org/wiki/Consciousness'],
    'Conserved Sequence': ['https://en.wikipedia.org/wiki/Conserved_sequence'],
    'Construction': ['https://en.wikipedia.org/wiki/Construction'],
    'Contiguous United States': [   'https://en.wikipedia.org/wiki/Contiguous_United_States'],
    'Coordinate System': ['https://en.wikipedia.org/wiki/Coordinate_system'],
    'Coordination Complex': [   'https://en.wikipedia.org/wiki/Coordination_complex'],
    'Coplanarity': ['https://en.wikipedia.org/wiki/Coplanarity'],
    'Crab-eating Macaque': [   'https://en.wikipedia.org/wiki/Crab-eating_macaque'],
    'Cross-coupling Reaction': [   'https://en.wikipedia.org/wiki/Cross-coupling_reaction'],
    'Cryogenic Electron Microscopy': [   'https://en.wikipedia.org/wiki/Cryogenic_electron_microscopy'],
    'Crystal': ['https://en.wikipedia.org/wiki/Crystal'],
    'Crystalline Silicon': [   'https://en.wikipedia.org/wiki/Crystalline_silicon'],
    'Crystallite': ['https://en.wikipedia.org/wiki/Crystallite'],
    'Crystallization': ['https://en.wikipedia.org/wiki/Crystallization'],
    'Crystallize': [   'https://en.wikipedia.org/wiki/Crystallize_(Lindsey_Stirling_song)'],
    'Cud': ['https://en.wikipedia.org/wiki/Cud'],
    'Culling': ['https://en.wikipedia.org/wiki/Culling'],
    'Culture': ['https://en.wikipedia.org/wiki/Culture'],
    'Cyanobacteria': ['https://en.wikipedia.org/wiki/Cyanobacteria'],
    'Cyclol': ['https://en.wikipedia.org/wiki/Cyclol'],
    'Cytokine': ['https://en.wikipedia.org/wiki/Cytokine'],
    'Cytolysis': ['https://en.wikipedia.org/wiki/Cytolysis'],
    'Cytoplasm': ['https://en.wikipedia.org/wiki/Cytoplasm'],
    'Cytoskeleton': ['https://en.wikipedia.org/wiki/Cytoskeleton'],
    'Cytotoxic T Cell': ['https://en.wikipedia.org/wiki/Cytotoxic_T_cell'],
    'Cytotoxicity': ['https://en.wikipedia.org/wiki/Cytotoxicity'],
    'Data': ['https://en.wikipedia.org/wiki/Data'],
    'Daytona Prototype': ['https://en.wikipedia.org/wiki/Daytona_Prototype'],
    'Dehydration': ['https://en.wikipedia.org/wiki/Dehydration'],
    'Denaturation': [   'https://en.wikipedia.org/wiki/Denaturation_(biochemistry)'],
    'Deoxyribonucleoside': [   'https://en.wikipedia.org/wiki/Deoxyribonucleoside'],
    'Deoxyribonucleotide': [   'https://en.wikipedia.org/wiki/Deoxyribonucleotide'],
    'Design': ['https://en.wikipedia.org/wiki/Design'],
    'Designer': ['https://en.wikipedia.org/wiki/Designer'],
    'Designing Women': ['https://en.wikipedia.org/wiki/Designing_Women'],
    'Detoxification': ['https://en.wikipedia.org/wiki/Detoxification'],
    'Diabetes': ['https://en.wikipedia.org/wiki/Diabetes'],
    'Diagram': ['https://en.wikipedia.org/wiki/Diagram'],
    'Dichroic Glass': ['https://en.wikipedia.org/wiki/Dichroic_glass'],
    'Dietary Fiber': ['https://en.wikipedia.org/wiki/Dietary_fiber'],
    'Dieting': ['https://en.wikipedia.org/wiki/Dieting'],
    'Diffusion': ['https://en.wikipedia.org/wiki/Diffusion'],
    'Digestion': ['https://en.wikipedia.org/wiki/Digestion'],
    'Digital Object Identifier': [   'https://en.wikipedia.org/wiki/Digital_object_identifier'],
    'Dihedral Angle': ['https://en.wikipedia.org/wiki/Dihedral_angle'],
    'Dirigent Protein': ['https://en.wikipedia.org/wiki/Dirigent_protein'],
    'Disaccharide': ['https://en.wikipedia.org/wiki/Disaccharide'],
    'Disease': ['https://en.wikipedia.org/wiki/Disease'],
    'Dissociation Constant': [   'https://en.wikipedia.org/wiki/Dissociation_constant'],
    'Distance': ['https://en.wikipedia.org/wiki/Distance'],
    'Distributed Computing': [   'https://en.wikipedia.org/wiki/Distributed_computing'],
    'Disulfide Bond Formation Protein B': [   'https://en.wikipedia.org/wiki/Disulfide_bond_formation_protein_B'],
    'Dna': ['https://en.wikipedia.org/wiki/DNA'],
    'Dna Polymerase': ['https://en.wikipedia.org/wiki/DNA_polymerase'],
    'Dna Repair': ['https://en.wikipedia.org/wiki/DNA_repair'],
    'Dna Replication': ['https://en.wikipedia.org/wiki/DNA_replication'],
    'Dna Sequencer': ['https://en.wikipedia.org/wiki/DNA_sequencer'],
    'Dna Sequencing': ['https://en.wikipedia.org/wiki/DNA_sequencing'],
    'Dna-binding Protein': [   'https://en.wikipedia.org/wiki/DNA-binding_protein'],
    'Dnaa': ['https://en.wikipedia.org/wiki/DnaA'],
    'Dnac': ['https://en.wikipedia.org/wiki/DnaC'],
    'Dnae': ['https://en.wikipedia.org/wiki/DnaE'],
    'Dnag': ['https://en.wikipedia.org/wiki/DnaG'],
    'Dnah': ['https://en.wikipedia.org/wiki/DnaH'],
    'Dnai': ['https://en.wikipedia.org/wiki/DnaI'],
    'Dnan': ['https://en.wikipedia.org/wiki/DnaN'],
    'Dnaq': ['https://en.wikipedia.org/wiki/DnaQ'],
    'Dnax': ['https://en.wikipedia.org/wiki/DnaX'],
    'Docking': ['https://en.wikipedia.org/wiki/Docking_(molecular)'],
    'Domestication': ['https://en.wikipedia.org/wiki/Domestication'],
    'Double Bond': ['https://en.wikipedia.org/wiki/Double_bond'],
    'Downregulation And Upregulation': [   'https://en.wikipedia.org/wiki/Downregulation_and_upregulation'],
    'Drug': ['https://en.wikipedia.org/wiki/Drug'],
    'Drug Development': ['https://en.wikipedia.org/wiki/Drug_development'],
    'Dtrace': ['https://en.wikipedia.org/wiki/DTrace'],
    'Dual-polarization Interferometry': [   'https://en.wikipedia.org/wiki/Dual-polarization_interferometry'],
    'Dynein': ['https://en.wikipedia.org/wiki/Dynein'],
    'Earth': ['https://en.wikipedia.org/wiki/Earth'],
    'Eating': ['https://en.wikipedia.org/wiki/Eating'],
    'Echinamoebidae': ['https://en.wikipedia.org/wiki/Echinamoebidae'],
    'Edestin': ['https://en.wikipedia.org/wiki/Edestin'],
    'Eicosanoid': ['https://en.wikipedia.org/wiki/Eicosanoid'],
    'Elastin': ['https://en.wikipedia.org/wiki/Elastin'],
    'Electric Charge': ['https://en.wikipedia.org/wiki/Electric_charge'],
    'Electric Power Conversion': [   'https://en.wikipedia.org/wiki/Electric_power_conversion'],
    'Electromagnet': ['https://en.wikipedia.org/wiki/Electromagnet'],
    'Electromagnetic Radiation': [   'https://en.wikipedia.org/wiki/Electromagnetic_radiation'],
    'Electromagnetism': ['https://en.wikipedia.org/wiki/Electromagnetism'],
    'Electron': ['https://en.wikipedia.org/wiki/Electron_(software_framework)'],
    'Electron Crystallography': [   'https://en.wikipedia.org/wiki/Electron_crystallography'],
    'Electron Transport Chain': [   'https://en.wikipedia.org/wiki/Electron_transport_chain'],
    'Electrophoresis': ['https://en.wikipedia.org/wiki/Electrophoresis'],
    'Elemental Analysis': ['https://en.wikipedia.org/wiki/Elemental_analysis'],
    'Embryo': ['https://en.wikipedia.org/wiki/Embryo'],
    'Emulsion Polymerization': [   'https://en.wikipedia.org/wiki/Emulsion_polymerization'],
    'Endocrine System': ['https://en.wikipedia.org/wiki/Endocrine_system'],
    'Endogeny': ['https://en.wikipedia.org/wiki/Endogeny_(biology)'],
    'Endonuclease': ['https://en.wikipedia.org/wiki/Endonuclease'],
    'Endoplasmic Reticulum': [   'https://en.wikipedia.org/wiki/Endoplasmic_reticulum'],
    'Energy': ['https://en.wikipedia.org/wiki/Energy'],
    'Engine': ['https://en.wikipedia.org/wiki/Engine'],
    'Engineering': ['https://en.wikipedia.org/wiki/Engineering'],
    'Enol': ['https://en.wikipedia.org/wiki/Enol'],
    'Enzyme': ['https://en.wikipedia.org/wiki/Enzyme'],
    'Enzyme Assay': ['https://en.wikipedia.org/wiki/Enzyme_assay'],
    'Enzyme Catalysis': ['https://en.wikipedia.org/wiki/Enzyme_catalysis'],
    'Enzyme Kinetics': ['https://en.wikipedia.org/wiki/Enzyme_kinetics'],
    'Eosin': ['https://en.wikipedia.org/wiki/Eosin'],
    'Epigenetics': ['https://en.wikipedia.org/wiki/Epigenetics'],
    'Epistemology': ['https://en.wikipedia.org/wiki/Epistemology'],
    'Equine Coat Color Genetics': [   'https://en.wikipedia.org/wiki/Equine_coat_color_genetics'],
    'Essential Amino Acid': [   'https://en.wikipedia.org/wiki/Essential_amino_acid'],
    'Essential Fatty Acid': [   'https://en.wikipedia.org/wiki/Essential_fatty_acid'],
    'Ester': ['https://en.wikipedia.org/wiki/Ester'],
    'Ethanol': ['https://en.wikipedia.org/wiki/Ethanol'],
    'Ethanol Fermentation': [   'https://en.wikipedia.org/wiki/Ethanol_fermentation'],
    'Ethanol Metabolism': ['https://en.wikipedia.org/wiki/Ethanol_metabolism'],
    'Ethynol': ['https://en.wikipedia.org/wiki/Ethynol'],
    'Eukaryote': ['https://en.wikipedia.org/wiki/Eukaryote'],
    'Eukaryotic Transcription': [   'https://en.wikipedia.org/wiki/Eukaryotic_transcription'],
    'Eusociality': ['https://en.wikipedia.org/wiki/Eusociality'],
    'Evolutionary Psychology': [   'https://en.wikipedia.org/wiki/Evolutionary_psychology'],
    'Exergy': ['https://en.wikipedia.org/wiki/Exergy_(software)'],
    'Experiment': ['https://en.wikipedia.org/wiki/Experiment'],
    'Explanation': ['https://en.wikipedia.org/wiki/Explanation'],
    'Extremophile': ['https://en.wikipedia.org/wiki/Extremophile'],
    'Fact': ['https://en.wikipedia.org/wiki/Fact'],
    'Fatty Acid': ['https://en.wikipedia.org/wiki/Fatty_acid'],
    'Fermentation': ['https://en.wikipedia.org/wiki/Fermentation'],
    'Flabellinia': ['https://en.wikipedia.org/wiki/Flabellinia'],
    'Flowering Plant': ['https://en.wikipedia.org/wiki/Flowering_plant'],
    'Fluid': ['https://en.wikipedia.org/wiki/Fluid'],
    'Foam': ['https://en.wikipedia.org/wiki/Foam'],
    'Food': ['https://en.wikipedia.org/wiki/Food'],
    'Forbes': ['https://en.wikipedia.org/wiki/Forbes'],
    'Force': ['https://en.wikipedia.org/wiki/Force'],
    'Fossil': ['https://en.wikipedia.org/wiki/Fossil'],
    'Fourier-transform Infrared Spectroscopy': [   'https://en.wikipedia.org/wiki/Fourier-transform_infrared_spectroscopy'],
    'Free Java Implementations': [   'https://en.wikipedia.org/wiki/Free_Java_implementations'],
    'Frequency': ['https://en.wikipedia.org/wiki/Frequency'],
    'Fructose': ['https://en.wikipedia.org/wiki/Fructose'],
    'Fruit': ['https://en.wikipedia.org/wiki/Fruit'],
    'Fungus': ['https://en.wikipedia.org/wiki/Fungus'],
    'Fur': ['https://en.wikipedia.org/wiki/Fur'],
    'Fusion Power': ['https://en.wikipedia.org/wiki/Fusion_power'],
    'Fusion Protein': ['https://en.wikipedia.org/wiki/Fusion_protein'],
    'Galaxy': ['https://en.wikipedia.org/wiki/Galaxy'],
    'Gamete': ['https://en.wikipedia.org/wiki/Gamete'],
    'Gas': ['https://en.wikipedia.org/wiki/Gas'],
    'Gencode': ['https://en.wikipedia.org/wiki/GENCODE'],
    'Gene': ['https://en.wikipedia.org/wiki/Gene'],
    'Gene Structure': ['https://en.wikipedia.org/wiki/Gene_structure'],
    'Genetic Disorder': ['https://en.wikipedia.org/wiki/Genetic_disorder'],
    'Genetics': ['https://en.wikipedia.org/wiki/Genetics'],
    'Genome': ['https://en.wikipedia.org/wiki/Genome'],
    'Genus': ['https://en.wikipedia.org/wiki/Genus'],
    'Geological Period': ['https://en.wikipedia.org/wiki/Geological_period'],
    'Geology': ['https://en.wikipedia.org/wiki/Geology'],
    'Geometry': ['https://en.wikipedia.org/wiki/Geometry'],
    'Glass': ['https://en.wikipedia.org/wiki/Glass'],
    'Gleason Grading System': [   'https://en.wikipedia.org/wiki/Gleason_grading_system'],
    'Globular Protein': ['https://en.wikipedia.org/wiki/Globular_protein'],
    'Glucose': ['https://en.wikipedia.org/wiki/Glucose'],
    'Glycine': ['https://en.wikipedia.org/wiki/Glycine'],
    'Glycosidic Bond': ['https://en.wikipedia.org/wiki/Glycosidic_bond'],
    'Glycosylamine': ['https://en.wikipedia.org/wiki/Glycosylamine'],
    'Gold': ['https://en.wikipedia.org/wiki/Gold'],
    'Gram-negative Bacteria': [   'https://en.wikipedia.org/wiki/Gram-negative_bacteria'],
    'Green Algae': ['https://en.wikipedia.org/wiki/Green_algae'],
    'Gs Alpha Subunit': ['https://en.wikipedia.org/wiki/Gs_alpha_subunit'],
    'Guild': ['https://en.wikipedia.org/wiki/Guild'],
    'Haematopoiesis': ['https://en.wikipedia.org/wiki/Haematopoiesis'],
    'Head Lice Infestation': [   'https://en.wikipedia.org/wiki/Head_lice_infestation'],
    'Health': ['https://en.wikipedia.org/wiki/Health'],
    'Heat': ['https://en.wikipedia.org/wiki/Heat'],
    'Helix': ['https://en.wikipedia.org/wiki/Helix'],
    'Hematoxylin': ['https://en.wikipedia.org/wiki/Haematoxylin'],
    'Heredity': ['https://en.wikipedia.org/wiki/Heredity'],
    'Heterokont': ['https://en.wikipedia.org/wiki/Heterokont'],
    'Histocompatibility': ['https://en.wikipedia.org/wiki/Histocompatibility'],
    'Histology': ['https://en.wikipedia.org/wiki/Histology'],
    'Histopathology': ['https://en.wikipedia.org/wiki/Histopathology'],
    'Hormone': ['https://en.wikipedia.org/wiki/Hormone'],
    'Horse': ['https://en.wikipedia.org/wiki/Horse'],
    'Human': ['https://en.wikipedia.org/wiki/Human'],
    'Humanism': ['https://en.wikipedia.org/wiki/Humanism'],
    'Humanities': ['https://en.wikipedia.org/wiki/Humanities'],
    'Hushing': ['https://en.wikipedia.org/wiki/Hushing'],
    'Hydrogen': ['https://en.wikipedia.org/wiki/Hydrogen'],
    'Hydrolysis': ['https://en.wikipedia.org/wiki/Hydrolysis'],
    'Hydroxyl Radical': ['https://en.wikipedia.org/wiki/Hydroxyl_radical'],
    'Hypothesis': ['https://en.wikipedia.org/wiki/Hypothesis'],
    'Idea': ['https://en.wikipedia.org/wiki/Idea'],
    'Image': ['https://en.wikipedia.org/wiki/Image'],
    'Imide': ['https://en.wikipedia.org/wiki/Imide'],
    'Imine': ['https://en.wikipedia.org/wiki/Imine'],
    'Immediate Constituent Analysis': [   'https://en.wikipedia.org/wiki/Immediate_constituent_analysis'],
    'Immune Response': ['https://en.wikipedia.org/wiki/Immune_response'],
    'Immunology': ['https://en.wikipedia.org/wiki/Immunology'],
    'In Vivo': ['https://en.wikipedia.org/wiki/In_vivo'],
    'Individual': ['https://en.wikipedia.org/wiki/Individual'],
    'Inductor': ['https://en.wikipedia.org/wiki/Inductor'],
    'Infection': ['https://en.wikipedia.org/wiki/Infection'],
    'Infectious Disease': [   'https://en.wikipedia.org/wiki/Infectious_disease_(medical_specialty)'],
    'Inflammation': ['https://en.wikipedia.org/wiki/Inflammation'],
    'Information': ['https://en.wikipedia.org/wiki/Information'],
    'Infrared': ['https://en.wikipedia.org/wiki/Infrared'],
    'Infrastructure': ['https://en.wikipedia.org/wiki/Infrastructure'],
    'Ingestion': ['https://en.wikipedia.org/wiki/Ingestion'],
    'Injury': ['https://en.wikipedia.org/wiki/Injury'],
    'Innate Immune System': [   'https://en.wikipedia.org/wiki/Innate_immune_system'],
    'Inorganic Compound': ['https://en.wikipedia.org/wiki/Inorganic_compound'],
    'Insect': ['https://en.wikipedia.org/wiki/Insect'],
    'Instrumentalism': ['https://en.wikipedia.org/wiki/Instrumentalism'],
    'Instrumentation': [   'https://en.wikipedia.org/wiki/Instrumentation_(computer_programming)'],
    'Interaction': ['https://en.wikipedia.org/wiki/Interaction'],
    'Interdisciplinarity': [   'https://en.wikipedia.org/wiki/Interdisciplinarity'],
    'Interleukin': ['https://en.wikipedia.org/wiki/Interleukin'],
    'Interleukin 15': ['https://en.wikipedia.org/wiki/Interleukin_15'],
    'Interleukin 2': ['https://en.wikipedia.org/wiki/Interleukin_2'],
    'Interleukin-15 Receptor': [   'https://en.wikipedia.org/wiki/Interleukin-15_receptor'],
    'Investigative Journalism': [   'https://en.wikipedia.org/wiki/Investigative_journalism'],
    'Ion': ['https://en.wikipedia.org/wiki/Ion'],
    'Iron': ['https://en.wikipedia.org/wiki/Iron'],
    'Irritability': ['https://en.wikipedia.org/wiki/Irritability'],
    'Irritation': ['https://en.wikipedia.org/wiki/Irritation'],
    'Iso 6344': ['https://en.wikipedia.org/wiki/ISO_6344'],
    'Iso 8601': ['https://en.wikipedia.org/wiki/ISO_8601'],
    'Isobutanol': ['https://en.wikipedia.org/wiki/Isobutanol'],
    'Isobutyl Nitrite': ['https://en.wikipedia.org/wiki/Isobutyl_nitrite'],
    'Isoelectric Focusing': [   'https://en.wikipedia.org/wiki/Isoelectric_focusing'],
    'Isomer': ['https://en.wikipedia.org/wiki/Isomer'],
    'Jaligner': ['https://en.wikipedia.org/wiki/JAligner'],
    'Kinase': ['https://en.wikipedia.org/wiki/Kinase'],
    'Knowledge': ['https://en.wikipedia.org/wiki/Knowledge'],
    'Lame': ['https://en.wikipedia.org/wiki/LAME'],
    'Lanthanide': ['https://en.wikipedia.org/wiki/Lanthanide'],
    'Large-scale Brain Networks': [   'https://en.wikipedia.org/wiki/Large-scale_brain_networks'],
    'Larva': ['https://en.wikipedia.org/wiki/Larva'],
    'Lead': ['https://en.wikipedia.org/wiki/Lead'],
    'Leather': ['https://en.wikipedia.org/wiki/Leather'],
    'Legume': ['https://en.wikipedia.org/wiki/Legume'],
    'Legumin': ['https://en.wikipedia.org/wiki/Legumin'],
    'Lentil': ['https://en.wikipedia.org/wiki/Lentil'],
    'Levacetylmethadol': ['https://en.wikipedia.org/wiki/Levacetylmethadol'],
    'Lewis Lung Carcinoma': [   'https://en.wikipedia.org/wiki/Lewis_lung_carcinoma'],
    'Life': ['https://en.wikipedia.org/wiki/Life'],
    'Ligand': ['https://en.wikipedia.org/wiki/Ligand'],
    'Ligase': ['https://en.wikipedia.org/wiki/Ligase'],
    'Light': ['https://en.wikipedia.org/wiki/Light'],
    'Linguistics': ['https://en.wikipedia.org/wiki/Linguistics'],
    'Lipid': ['https://en.wikipedia.org/wiki/Lipid'],
    'Lipid Bilayer': ['https://en.wikipedia.org/wiki/Lipid_bilayer'],
    'Liquid': ['https://en.wikipedia.org/wiki/Liquid'],
    'List of Extinct Plants': [   'https://en.wikipedia.org/wiki/List_of_extinct_plants'],
    'List of Internet Phenomena': [   'https://en.wikipedia.org/wiki/List_of_Internet_phenomena'],
    'List of Mail Server Software': [   'https://en.wikipedia.org/wiki/List_of_mail_server_software'],
    'List of Protein Structure Prediction Software': [   'https://en.wikipedia.org/wiki/List_of_protein_structure_prediction_software'],
    'Liver': ['https://en.wikipedia.org/wiki/Liver'],
    'Livestock': ['https://en.wikipedia.org/wiki/Livestock'],
    'Lobosa': ['https://en.wikipedia.org/wiki/Lobosa'],
    'Louse': ['https://en.wikipedia.org/wiki/Louse'],
    'Love': ['https://en.wikipedia.org/wiki/Love'],
    'Lustre': ['https://en.wikipedia.org/wiki/Lustre_(mineralogy)'],
    'Lymph Node': ['https://en.wikipedia.org/wiki/Lymph_node'],
    'Lymphocyte': ['https://en.wikipedia.org/wiki/Lymphocyte'],
    'Lysis': ['https://en.wikipedia.org/wiki/Lysis'],
    'Macromolecule': ['https://en.wikipedia.org/wiki/Macromolecule'],
    'Mai Basic Four': ['https://en.wikipedia.org/wiki/MAI_Basic_Four'],
    'Male Reproductive System': [   'https://en.wikipedia.org/wiki/Male_reproductive_system'],
    'Malignancy': ['https://en.wikipedia.org/wiki/Malignancy'],
    'Mammal': ['https://en.wikipedia.org/wiki/Mammal'],
    'Maser': ['https://en.wikipedia.org/wiki/Maser'],
    'Mass': ['https://en.wikipedia.org/wiki/Mass'],
    'Materialism': ['https://en.wikipedia.org/wiki/Materialism'],
    'Mathematics': ['https://en.wikipedia.org/wiki/Mathematics'],
    'Matter': ['https://en.wikipedia.org/wiki/Matter'],
    'Measurement': ['https://en.wikipedia.org/wiki/Measurement'],
    'Meat': ['https://en.wikipedia.org/wiki/Meat'],
    'Meat Glue': ['https://en.wikipedia.org/wiki/Meat_glue'],
    'Mechanics': ['https://en.wikipedia.org/wiki/Mechanics'],
    'Medal': ['https://en.wikipedia.org/wiki/Medal'],
    'Medical Device': ['https://en.wikipedia.org/wiki/Medical_device'],
    'Medication': ['https://en.wikipedia.org/wiki/Medication'],
    'Medicine': ['https://en.wikipedia.org/wiki/Medicine'],
    'Membrane': ['https://en.wikipedia.org/wiki/Membrane'],
    'Memory T Cell': ['https://en.wikipedia.org/wiki/Memory_T_cell'],
    'Mental Disorder': ['https://en.wikipedia.org/wiki/Mental_disorder'],
    'Metabolic Disorder': ['https://en.wikipedia.org/wiki/Metabolic_disorder'],
    'Metabolic Pathway': ['https://en.wikipedia.org/wiki/Metabolic_pathway'],
    'Metabolism': ['https://en.wikipedia.org/wiki/Metabolism'],
    'Metabolite': ['https://en.wikipedia.org/wiki/Metabolite'],
    'Metal': ['https://en.wikipedia.org/wiki/Metal'],
    'Metal Ammine Complex': [   'https://en.wikipedia.org/wiki/Metal_ammine_complex'],
    'Metallicity': ['https://en.wikipedia.org/wiki/Metallicity'],
    'Metastatic Breast Cancer': [   'https://en.wikipedia.org/wiki/Metastatic_breast_cancer'],
    'Methane': ['https://en.wikipedia.org/wiki/Methane'],
    'Methanol': ['https://en.wikipedia.org/wiki/Methanol'],
    'Methionine': ['https://en.wikipedia.org/wiki/Methionine'],
    'Methodology': ['https://en.wikipedia.org/wiki/Methodology'],
    'Methods in Enzymology': [   'https://en.wikipedia.org/wiki/Methods_in_Enzymology'],
    'Microorganism': ['https://en.wikipedia.org/wiki/Microorganism'],
    'Microscope': ['https://en.wikipedia.org/wiki/Microscope'],
    'Microscopic Scale': ['https://en.wikipedia.org/wiki/Microscopic_scale'],
    'Microscopy': ['https://en.wikipedia.org/wiki/Microscopy'],
    'Microsoft Exchange Server': [   'https://en.wikipedia.org/wiki/Microsoft_Exchange_Server'],
    'Microtubule': ['https://en.wikipedia.org/wiki/Microtubule'],
    'Milk': ['https://en.wikipedia.org/wiki/Milk'],
    'Mineral': ['https://en.wikipedia.org/wiki/Mineral'],
    'Mining': ['https://en.wikipedia.org/wiki/Mining'],
    'Mitochondrial Dna': ['https://en.wikipedia.org/wiki/Mitochondrial_DNA'],
    'Mitosis': ['https://en.wikipedia.org/wiki/Mitosis'],
    'Mohism': ['https://en.wikipedia.org/wiki/Mohism'],
    'Mold': ['https://en.wikipedia.org/wiki/Mold'],
    'Molecular Cloning': ['https://en.wikipedia.org/wiki/Molecular_cloning'],
    'Molecular Motor': ['https://en.wikipedia.org/wiki/Molecular_motor'],
    'Molecule': ['https://en.wikipedia.org/wiki/Molecule'],
    'Monism': ['https://en.wikipedia.org/wiki/Monism'],
    'Monomer': ['https://en.wikipedia.org/wiki/Monomer'],
    'Monosaccharide': ['https://en.wikipedia.org/wiki/Monosaccharide'],
    'Motility': ['https://en.wikipedia.org/wiki/Motility'],
    'Motor Protein': ['https://en.wikipedia.org/wiki/Motor_protein'],
    'Mouse Model of Colorectal And Intestinal Cancer': [   'https://en.wikipedia.org/wiki/Mouse_model_of_colorectal_and_intestinal_cancer'],
    'Multicelluar Organism': [   'https://en.wikipedia.org/wiki/Multicellular_organism'],
    'Multicellular Organism': [   'https://en.wikipedia.org/wiki/Multicellular_organism'],
    'Muon-catalyzed Fusion': [   'https://en.wikipedia.org/wiki/Muon-catalyzed_fusion'],
    'Muscle': ['https://en.wikipedia.org/wiki/Muscle'],
    'Mushroom': ['https://en.wikipedia.org/wiki/Mushroom'],
    'National Institutes of Technology': [   'https://en.wikipedia.org/wiki/National_Institutes_of_Technology'],
    'Native Metal': ['https://en.wikipedia.org/wiki/Native_metal'],
    'Natural Killer Cell': [   'https://en.wikipedia.org/wiki/Natural_killer_cell'],
    'Natural Philosophy': ['https://en.wikipedia.org/wiki/Natural_philosophy'],
    'Natural Science': ['https://en.wikipedia.org/wiki/Natural_science'],
    'Nature': ['https://en.wikipedia.org/wiki/Nature'],
    'Naturism': ['https://en.wikipedia.org/wiki/Naturism'],
    'Nazi Human Experimentation': [   'https://en.wikipedia.org/wiki/Nazi_human_experimentation'],
    'Nbpf15': ['https://en.wikipedia.org/wiki/NBPF15'],
    'Neoplasm': ['https://en.wikipedia.org/wiki/Neoplasm'],
    'Neuroendocrine Tumor': [   'https://en.wikipedia.org/wiki/Neuroendocrine_tumor'],
    'Neutron': ['https://en.wikipedia.org/wiki/Neutron'],
    "Newton's Method in Optimization": [   'https://en.wikipedia.org/wiki/Newton%27s_method_in_optimization'],
    'Nitrate': ['https://en.wikipedia.org/wiki/Nitrate'],
    'Nitrite': ['https://en.wikipedia.org/wiki/Nitrite'],
    'Nitrogen': ['https://en.wikipedia.org/wiki/Nitrogen'],
    'Non Coding DNA': ['https://en.wikipedia.org/wiki/Non-coding_DNA'],
    'Nuclease': ['https://en.wikipedia.org/wiki/Nuclease'],
    'Nucleic Acid Sequence': [   'https://en.wikipedia.org/wiki/Nucleic_acid_sequence'],
    'Nucleobase': ['https://en.wikipedia.org/wiki/Nucleobase'],
    'Nucleoside': ['https://en.wikipedia.org/wiki/Nucleoside'],
    'Nucleotide': ['https://en.wikipedia.org/wiki/Nucleotide'],
    'Nudist Paradise': ['https://en.wikipedia.org/wiki/Nudist_Paradise'],
    'Nudity': ['https://en.wikipedia.org/wiki/Nudity'],
    'Numb': ['https://en.wikipedia.org/wiki/Numb_(Linkin_Park_song)'],
    'Number': ['https://en.wikipedia.org/wiki/Number'],
    'Nutrient': ['https://en.wikipedia.org/wiki/Nutrient'],
    'Obesity': ['https://en.wikipedia.org/wiki/Obesity'],
    'Object-oriented Programming': [   'https://en.wikipedia.org/wiki/Object-oriented_programming'],
    'Observation': ['https://en.wikipedia.org/wiki/Observation'],
    'Odor': ['https://en.wikipedia.org/wiki/Odor'],
    'Officer': ['https://en.wikipedia.org/wiki/Officer_(armed_forces)'],
    'Olfaction': ['https://en.wikipedia.org/wiki/Olfaction'],
    'Optical Microscopy': ['https://en.wikipedia.org/wiki/Optical_microscope'],
    'Opticks': ['https://en.wikipedia.org/wiki/Opticks'],
    'Optics': ['https://en.wikipedia.org/wiki/Optics'],
    'Ordinal Data': ['https://en.wikipedia.org/wiki/Ordinal_data'],
    'Ore': ['https://en.wikipedia.org/wiki/Ore'],
    'Organ': ['https://en.wikipedia.org/wiki/Organ_(anatomy)'],
    'Organelle': ['https://en.wikipedia.org/wiki/Organelle'],
    'Organic Compound': ['https://en.wikipedia.org/wiki/Organic_compound'],
    'Organisation Todt': ['https://en.wikipedia.org/wiki/Organisation_Todt'],
    'Organism': ['https://en.wikipedia.org/wiki/Organism'],
    'Organization': ['https://en.wikipedia.org/wiki/Organization'],
    'Organometallic Chemistry': [   'https://en.wikipedia.org/wiki/Organometallic_chemistry'],
    'Oxidation State': ['https://en.wikipedia.org/wiki/Oxidation_state'],
    'Oxide': ['https://en.wikipedia.org/wiki/Oxide'],
    'Oxidized Cellulose': ['https://en.wikipedia.org/wiki/Oxidized_cellulose'],
    'Oxidoreductase': ['https://en.wikipedia.org/wiki/Oxidoreductase'],
    'Oxygen': ['https://en.wikipedia.org/wiki/Oxygen'],
    'Oxymetholone': ['https://en.wikipedia.org/wiki/Oxymetholone'],
    'PD-1': ['https://en.wikipedia.org/wiki/PD-1_and_PD-L1_inhibitors'],
    'PD-L1': ['https://en.wikipedia.org/wiki/PD-1_and_PD-L1_inhibitors'],
    'PH': ['https://en.wikipedia.org/wiki/PH'],
    'Pain': ['https://en.wikipedia.org/wiki/Pain'],
    'Painkiller': ['https://en.wikipedia.org/wiki/Painkiller_(video_game)'],
    'Pancreas': ['https://en.wikipedia.org/wiki/Pancreas'],
    'Pancreatitis': ['https://en.wikipedia.org/wiki/Pancreatitis'],
    'Parasitic Disease': ['https://en.wikipedia.org/wiki/Parasitic_disease'],
    'Parasitic Twin': ['https://en.wikipedia.org/wiki/Parasitic_twin'],
    'Parasitism': ['https://en.wikipedia.org/wiki/Parasitism'],
    'Parotitis': ['https://en.wikipedia.org/wiki/Parotitis'],
    'Particle': ['https://en.wikipedia.org/wiki/Particle'],
    'Pathogen': ['https://en.wikipedia.org/wiki/Pathogen'],
    'Pathogenic Bacteria': [   'https://en.wikipedia.org/wiki/Pathogenic_bacteria'],
    'Pathology': ['https://en.wikipedia.org/wiki/Pathology'],
    'Patient Derived Xenograft': [   'https://en.wikipedia.org/wiki/Patient_derived_xenograft'],
    'Pea': ['https://en.wikipedia.org/wiki/Pea'],
    'Pediculosis': ['https://en.wikipedia.org/wiki/Pediculosis'],
    'Peptide': ['https://en.wikipedia.org/wiki/Peptide'],
    'Peptidomimetic': ['https://en.wikipedia.org/wiki/Peptidomimetic'],
    'Peptoid': ['https://en.wikipedia.org/wiki/Peptoid'],
    'Percolozoa': ['https://en.wikipedia.org/wiki/Percolozoa'],
    'Period 6 Element': ['https://en.wikipedia.org/wiki/Period_6_element'],
    'Periodic Table': ['https://en.wikipedia.org/wiki/Periodic_table'],
    'Periodization': ['https://en.wikipedia.org/wiki/Periodization'],
    'Peripheral Blood Lymphocyte': [   'https://en.wikipedia.org/wiki/Peripheral_blood_lymphocyte'],
    'Personal Protective Equipment': [   'https://en.wikipedia.org/wiki/Personal_protective_equipment'],
    'Pfu Dna Polymerase': ['https://en.wikipedia.org/wiki/Pfu_DNA_polymerase'],
    'Pharmaceutical Drug': ['https://en.wikipedia.org/wiki/Medication'],
    'Pharmaceutical Formulation': [   'https://en.wikipedia.org/wiki/Pharmaceutical_formulation'],
    'Pharmacodynamics': ['https://en.wikipedia.org/wiki/Pharmacodynamics'],
    'Pharmacology': ['https://en.wikipedia.org/wiki/Pharmacology'],
    'Pharmacy': ['https://en.wikipedia.org/wiki/Pharmacy'],
    'Phenomenalism': ['https://en.wikipedia.org/wiki/Phenomenalism'],
    'Phenomenon': ['https://en.wikipedia.org/wiki/Phenomenon'],
    'Phenotype': ['https://en.wikipedia.org/wiki/Phenotype'],
    'Phosphate': ['https://en.wikipedia.org/wiki/Phosphate'],
    'Phosphoprotein': ['https://en.wikipedia.org/wiki/Phosphoprotein'],
    'Phosphorus': ['https://en.wikipedia.org/wiki/Phosphorus'],
    'Phosphorus Monoxide': [   'https://en.wikipedia.org/wiki/Phosphorus_monoxide'],
    'Phosphoryl Group': ['https://en.wikipedia.org/wiki/Phosphoryl_group'],
    'Phosphorylation': ['https://en.wikipedia.org/wiki/Phosphorylation'],
    'Phosphotransferase': ['https://en.wikipedia.org/wiki/Phosphotransferase'],
    'Photon': ['https://en.wikipedia.org/wiki/Photon'],
    'Photosynthesis': ['https://en.wikipedia.org/wiki/Photosynthesis'],
    'Phylogenetic Tree': ['https://en.wikipedia.org/wiki/Phylogenetic_tree'],
    'Phylum': ['https://en.wikipedia.org/wiki/Phylum'],
    'Physical Object': ['https://en.wikipedia.org/wiki/Physical_object'],
    'Physics': ['https://en.wikipedia.org/wiki/Physics'],
    'Physiology': ['https://en.wikipedia.org/wiki/Physiology'],
    'Planet': ['https://en.wikipedia.org/wiki/Planet'],
    'Planet Earth': [   'https://en.wikipedia.org/wiki/Planet_Earth_(2006_TV_series)'],
    'Plant': ['https://en.wikipedia.org/wiki/Plant'],
    'Planula': ['https://en.wikipedia.org/wiki/Planula'],
    'Plastid': ['https://en.wikipedia.org/wiki/Plastid'],
    'Pleasure': ['https://en.wikipedia.org/wiki/Pleasure'],
    'Ploidy': ['https://en.wikipedia.org/wiki/Ploidy'],
    'Poison': ['https://en.wikipedia.org/wiki/Poison'],
    'Polymer': ['https://en.wikipedia.org/wiki/Polymer'],
    'Polymerization': ['https://en.wikipedia.org/wiki/Polymerization'],
    'Polynucleotide': ['https://en.wikipedia.org/wiki/Polynucleotide'],
    'Positive-sense Single-stranded Rna Virus': [   'https://en.wikipedia.org/wiki/Positive-sense_single-stranded_RNA_virus'],
    'Post-transcriptional Modification': [   'https://en.wikipedia.org/wiki/Post-transcriptional_modification'],
    'Problem Solving': ['https://en.wikipedia.org/wiki/Problem_solving'],
    'Process Flow Diagram': [   'https://en.wikipedia.org/wiki/Process_flow_diagram'],
    'Processivity': ['https://en.wikipedia.org/wiki/Processivity'],
    'Profession': ['https://en.wikipedia.org/wiki/Profession'],
    'Programmed Cell Death': [   'https://en.wikipedia.org/wiki/Programmed_cell_death'],
    'Programmer': ['https://en.wikipedia.org/wiki/Programmer'],
    'Prokaryote': ['https://en.wikipedia.org/wiki/Prokaryote'],
    'Prokaryotic Translation': [   'https://en.wikipedia.org/wiki/Prokaryotic_translation'],
    'Protein': [   'https://en.wikipedia.org/wiki/Protein',
                   'https://en.wikipedia.org/wiki/Protein_(nutrient)'],
    'Protein Domain': ['https://en.wikipedia.org/wiki/Protein_domain'],
    'Protein Engineering': [   'https://en.wikipedia.org/wiki/Protein_engineering'],
    'Protein Quaternary Structure': [   'https://en.wikipedia.org/wiki/Protein_quaternary_structure'],
    'Proteinogenic Amino Acid': [   'https://en.wikipedia.org/wiki/Proteinogenic_amino_acid'],
    'Proteobacteria': ['https://en.wikipedia.org/wiki/Proteobacteria'],
    'Proteome': ['https://en.wikipedia.org/wiki/Proteome'],
    'Proteomics': ['https://en.wikipedia.org/wiki/Proteomics'],
    'Proteopathy': ['https://en.wikipedia.org/wiki/Proteopathy'],
    'Proteostasis': ['https://en.wikipedia.org/wiki/Proteostasis'],
    'Proteus': ['https://en.wikipedia.org/wiki/Proteus_(bacterium)'],
    'Proton': ['https://en.wikipedia.org/wiki/Proton'],
    'Protonation': ['https://en.wikipedia.org/wiki/Protonation'],
    'Protozoa': ['https://en.wikipedia.org/wiki/Protozoa'],
    'Protozoan Infection': [   'https://en.wikipedia.org/wiki/Protozoan_infection'],
    'Pseudopodia': ['https://en.wikipedia.org/wiki/Pseudopodia'],
    'Psychology': ['https://en.wikipedia.org/wiki/Psychology'],
    'Pyrococcus Furiosus': [   'https://en.wikipedia.org/wiki/Pyrococcus_furiosus'],
    'Qmail': ['https://en.wikipedia.org/wiki/Qmail'],
    'Quantitative Research': [   'https://en.wikipedia.org/wiki/Quantitative_research'],
    'Quantity': ['https://en.wikipedia.org/wiki/Quantity'],
    'Quantum Mechanics': ['https://en.wikipedia.org/wiki/Quantum_mechanics'],
    'Radiation': ['https://en.wikipedia.org/wiki/Radiation'],
    'Receptor': ['https://en.wikipedia.org/wiki/Receptor_(biochemistry)'],
    'Redox': ['https://en.wikipedia.org/wiki/Redox'],
    'Regulated Market': ['https://en.wikipedia.org/wiki/Regulated_market'],
    'Regulation of Gene Expression': [   'https://en.wikipedia.org/wiki/Regulation_of_gene_expression'],
    'Regulatory T Cell': ['https://en.wikipedia.org/wiki/Regulatory_T_cell'],
    'Remote Patient Monitoring': [   'https://en.wikipedia.org/wiki/Remote_patient_monitoring'],
    'Reporter Gene': ['https://en.wikipedia.org/wiki/Reporter_gene'],
    'Reproduction': ['https://en.wikipedia.org/wiki/Reproduction'],
    'Reproductive System': [   'https://en.wikipedia.org/wiki/Reproductive_system'],
    'Reptation': ['https://en.wikipedia.org/wiki/Reptation'],
    'Residue': ['https://en.wikipedia.org/wiki/Residue_(chemistry)'],
    'Resonant Converter': ['https://en.wikipedia.org/wiki/Resonant_converter'],
    'Restriction Enzyme': ['https://en.wikipedia.org/wiki/Restriction_enzyme'],
    'Result': ['https://en.wikipedia.org/wiki/Result'],
    'Reverse Transcription Polymerase Chain Reaction': [   'https://en.wikipedia.org/wiki/Reverse_transcription_polymerase_chain_reaction'],
    'Rhodopsin': ['https://en.wikipedia.org/wiki/Rhodopsin'],
    'Ribbon Diagram': ['https://en.wikipedia.org/wiki/Ribbon_diagram'],
    'Ribonuclease': ['https://en.wikipedia.org/wiki/Ribonuclease'],
    'Ribonuclease Inhibitor': [   'https://en.wikipedia.org/wiki/Ribonuclease_inhibitor'],
    'Ribonucleoprotein Particle': [   'https://en.wikipedia.org/wiki/Ribonucleoprotein_particle'],
    'Rna': ['https://en.wikipedia.org/wiki/RNA'],
    'Rna Splicing': ['https://en.wikipedia.org/wiki/RNA_splicing'],
    'Rna-dependent Rna Polymerase': [   'https://en.wikipedia.org/wiki/RNA-dependent_RNA_polymerase'],
    'Roton': ['https://en.wikipedia.org/wiki/Roton'],
    'Rumen': ['https://en.wikipedia.org/wiki/Rumen'],
    'Ruminant': ['https://en.wikipedia.org/wiki/Ruminant'],
    'Sandpaper': ['https://en.wikipedia.org/wiki/Sandpaper'],
    'Scalp': ['https://en.wikipedia.org/wiki/Scalp'],
    'Schizophrenia': ['https://en.wikipedia.org/wiki/Schizophrenia'],
    'Science': ['https://en.wikipedia.org/wiki/Science'],
    'Science And Technology': [   'https://en.wikipedia.org/wiki/Science_and_technology'],
    'Scientific Instrument': [   'https://en.wikipedia.org/wiki/Scientific_instrument'],
    'Scientific Method': ['https://en.wikipedia.org/wiki/Scientific_method'],
    'Seasonal Affective Disorder': [   'https://en.wikipedia.org/wiki/Seasonal_affective_disorder'],
    'Sediment': ['https://en.wikipedia.org/wiki/Sediment'],
    'Seed': ['https://en.wikipedia.org/wiki/Seed'],
    'Serine': ['https://en.wikipedia.org/wiki/Serine'],
    'Sex': ['https://en.wikipedia.org/wiki/Sex'],
    'Sex Organ': ['https://en.wikipedia.org/wiki/Sex_organ'],
    'Silurian': ['https://en.wikipedia.org/wiki/Silurian'],
    'Skeleton': ['https://en.wikipedia.org/wiki/Skeleton'],
    'Skid Row, Los Angeles': [   'https://en.wikipedia.org/wiki/Skid_Row,_Los_Angeles'],
    'Society': ['https://en.wikipedia.org/wiki/Society'],
    'Sociology': ['https://en.wikipedia.org/wiki/Sociology'],
    'Soft Tissue': ['https://en.wikipedia.org/wiki/Soft_tissue'],
    'Software': ['https://en.wikipedia.org/wiki/Software'],
    'Solution': ['https://en.wikipedia.org/wiki/Solution'],
    'Solvent': ['https://en.wikipedia.org/wiki/Solvent'],
    'Space': ['https://en.wikipedia.org/wiki/Space'],
    'Species': ['https://en.wikipedia.org/wiki/Species'],
    'Spectroscopy': ['https://en.wikipedia.org/wiki/Spectroscopy'],
    'Sperm': ['https://en.wikipedia.org/wiki/Sperm'],
    'Spermatozoon': ['https://en.wikipedia.org/wiki/Spermatozoon'],
    'Standard Linear Solid Model': [   'https://en.wikipedia.org/wiki/Standard_linear_solid_model'],
    'Standardization': ['https://en.wikipedia.org/wiki/Standardization'],
    'Star': ['https://en.wikipedia.org/wiki/Star'],
    'Starch': ['https://en.wikipedia.org/wiki/Starch'],
    'Stereochemistry': ['https://en.wikipedia.org/wiki/Stereochemistry'],
    'Stereoisomerism': ['https://en.wikipedia.org/wiki/Stereoisomerism'],
    'Steroid': ['https://en.wikipedia.org/wiki/Steroid'],
    'Steroid Hormone': ['https://en.wikipedia.org/wiki/Steroid_hormone'],
    'Stomach': ['https://en.wikipedia.org/wiki/Stomach'],
    'Structuralism': ['https://en.wikipedia.org/wiki/Structuralism'],
    'Structure': ['https://en.wikipedia.org/wiki/Structure'],
    'Subatomic Particle': ['https://en.wikipedia.org/wiki/Subatomic_particle'],
    'Subphylum': ['https://en.wikipedia.org/wiki/Subphylum'],
    'Sucrase': ['https://en.wikipedia.org/wiki/Sucrase'],
    'Sucrose': ['https://en.wikipedia.org/wiki/Sucrose'],
    'Sugar': ['https://en.wikipedia.org/wiki/Sugar'],
    'Sugaring': ['https://en.wikipedia.org/wiki/Sugaring_(epilation)'],
    'Sulfur Oxoacid': ['https://en.wikipedia.org/wiki/Sulfur_oxoacid'],
    'Superagonist': ['https://en.wikipedia.org/wiki/Superagonist'],
    'Sushi Domain': ['https://en.wikipedia.org/wiki/Sushi_domain'],
    'Symbiosis': ['https://en.wikipedia.org/wiki/Symbiosis'],
    'Symbol': [   'https://en.wikipedia.org/wiki/Symbol',
                  'https://en.wikipedia.org/wiki/Symbol_(chemistry)'],
    'System': ['https://en.wikipedia.org/wiki/System'],
    'T Cell': ['https://en.wikipedia.org/wiki/T_cell'],
    'Taxonomy': ['https://en.wikipedia.org/wiki/Taxonomy_(biology)'],
    'Technology': ['https://en.wikipedia.org/wiki/Technology'],
    'Temperature': ['https://en.wikipedia.org/wiki/Temperature'],
    'Testate Amoebae': ['https://en.wikipedia.org/wiki/Testate_amoebae'],
    'Testosterone': ['https://en.wikipedia.org/wiki/Testosterone'],
    'The Catalyst': ['https://en.wikipedia.org/wiki/The_Catalyst'],
    'The Chemical Brothers': [   'https://en.wikipedia.org/wiki/The_Chemical_Brothers'],
    'The Natural': ['https://en.wikipedia.org/wiki/The_Natural'],
    'The Offspring': ['https://en.wikipedia.org/wiki/The_Offspring'],
    'Thermal': ['https://en.wikipedia.org/wiki/Thermal'],
    'Thermal Oxidizer': ['https://en.wikipedia.org/wiki/Thermal_oxidizer'],
    'Thermodynamics': ['https://en.wikipedia.org/wiki/Thermodynamics'],
    'Tide': ['https://en.wikipedia.org/wiki/Tide'],
    'Time': ['https://en.wikipedia.org/wiki/Time'],
    'Tissue': ['https://en.wikipedia.org/wiki/Tissue_(biology)'],
    'Tobymac': ['https://en.wikipedia.org/wiki/TobyMac'],
    'Toxicant': ['https://en.wikipedia.org/wiki/Toxicant'],
    'Toxicity': ['https://en.wikipedia.org/wiki/Toxicity'],
    'Toxin': ['https://en.wikipedia.org/wiki/Toxin'],
    'Transaminase': ['https://en.wikipedia.org/wiki/Transaminase'],
    'Transamination': ['https://en.wikipedia.org/wiki/Transamination'],
    'Transcriptome': ['https://en.wikipedia.org/wiki/Transcriptome'],
    'Transduction': ['https://en.wikipedia.org/wiki/Transduction_(physiology)'],
    'Transgender Hormone Therapy': [   'https://en.wikipedia.org/wiki/Transgender_hormone_therapy_(male-to-female)'],
    'Transmission Electron Cryomicroscopy': [   'https://en.wikipedia.org/wiki/Transmission_electron_cryomicroscopy'],
    'Troubleshooting': ['https://en.wikipedia.org/wiki/Troubleshooting'],
    'Tubulin': ['https://en.wikipedia.org/wiki/Tubulin'],
    'Type I Cytokine Receptor': [   'https://en.wikipedia.org/wiki/Type_I_cytokine_receptor'],
    'Unicellular Organism': [   'https://en.wikipedia.org/wiki/Unicellular_organism'],
    'United States Armed Forces': [   'https://en.wikipedia.org/wiki/United_States_Armed_Forces'],
    'Universe': ['https://en.wikipedia.org/wiki/Universe'],
    'University': ['https://en.wikipedia.org/wiki/University'],
    'Urosporidae': ['https://en.wikipedia.org/wiki/Urosporidae'],
    'Ustilaginomycetes': ['https://en.wikipedia.org/wiki/Ustilaginomycetes'],
    'Ustilaginomycotina': ['https://en.wikipedia.org/wiki/Ustilaginomycotina'],
    'Vaccination': ['https://en.wikipedia.org/wiki/Vaccination'],
    'Vaccine': ['https://en.wikipedia.org/wiki/Vaccine'],
    'Vacuole': ['https://en.wikipedia.org/wiki/Vacuole'],
    'Vahlkampfiidae': ['https://en.wikipedia.org/wiki/Vahlkampfiidae'],
    'Vannellidae': ['https://en.wikipedia.org/wiki/Vannellidae'],
    'Varisulca': ['https://en.wikipedia.org/wiki/Varisulca'],
    'Vascular Plant': ['https://en.wikipedia.org/wiki/Vascular_plant'],
    'Vault': ['https://en.wikipedia.org/wiki/Vault_(organelle)'],
    'Velocity': ['https://en.wikipedia.org/wiki/Velocity'],
    'Verrucomicrobia': ['https://en.wikipedia.org/wiki/Verrucomicrobia'],
    'Vertebra': ['https://en.wikipedia.org/wiki/Vertebra'],
    'Vertebrate': ['https://en.wikipedia.org/wiki/Vertebrate'],
    'Very Important Person': [   'https://en.wikipedia.org/wiki/Very_important_person'],
    'Vexilliferidae': ['https://en.wikipedia.org/wiki/Vexilliferidae'],
    'Vicia': ['https://en.wikipedia.org/wiki/Vicia'],
    'Vinyl Alcohol': ['https://en.wikipedia.org/wiki/Vinyl_alcohol'],
    'Viral Eukaryogenesis': [   'https://en.wikipedia.org/wiki/Viral_eukaryogenesis'],
    'Virtue': ['https://en.wikipedia.org/wiki/Virtue'],
    'Virulence': ['https://en.wikipedia.org/wiki/Virulence'],
    'Virus': ['https://en.wikipedia.org/wiki/Virus'],
    'Visual Phototransduction': [   'https://en.wikipedia.org/wiki/Visual_phototransduction'],
    'Vitrella Brassicaformis': [   'https://en.wikipedia.org/wiki/Vitrella_brassicaformis'],
    'Volvox Carteri': ['https://en.wikipedia.org/wiki/Volvox_carteri'],
    'Voromonas': ['https://en.wikipedia.org/wiki/Voromonas'],
    'Vorticella': ['https://en.wikipedia.org/wiki/Vorticella'],
    'Wasp': ['https://en.wikipedia.org/wiki/Wasp'],
    'Water': ['https://en.wikipedia.org/wiki/Water'],
    'Wavelength': ['https://en.wikipedia.org/wiki/Wavelength'],
    'Wax': ['https://en.wikipedia.org/wiki/Wax'],
    'Weak Entity': ['https://en.wikipedia.org/wiki/Weak_entity'],
    'White Blood Cell': ['https://en.wikipedia.org/wiki/White_blood_cell'],
    'Whole Genome Sequencing': [   'https://en.wikipedia.org/wiki/Whole_genome_sequencing'],
    'Wool': ['https://en.wikipedia.org/wiki/Wool'],
    'World': ['https://en.wikipedia.org/wiki/World'],
    'Xenacoelomorpha': ['https://en.wikipedia.org/wiki/Xenacoelomorpha'],
    'Xenoturbella': ['https://en.wikipedia.org/wiki/Xenoturbella'],
    'Yeast': ['https://en.wikipedia.org/wiki/Yeast'],
    'Yellow-green Algae': ['https://en.wikipedia.org/wiki/Yellow-green_algae'],
    'Zosterophyll': ['https://en.wikipedia.org/wiki/Zosterophyll'],
    'Zygnematophyceae': ['https://en.wikipedia.org/wiki/Zygnematophyceae'],
    'Zygocystinae': ['https://en.wikipedia.org/wiki/Zygocystinae'],
    'Zygomycota': ['https://en.wikipedia.org/wiki/Zygomycota'],
    'cytosol': ['https://en.wikipedia.org/wiki/Cytosol'],
    'xenoturbellids': ['https://en.wikipedia.org/wiki/Informal_economy'],
    'Α-methylfentanyl': ['https://en.wikipedia.org/wiki/%CE%91-Methylfentanyl'],
    'Γ-oryzanol': ['https://en.wikipedia.org/wiki/%CE%93-Oryzanol']}
