
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_rel_implies_dict = {
    '4-aminobutyrate Transaminase': [   'Enzyme',
                                        'Methods in Enzymology',
                                        'Transaminase'],
    'Acceleration': ['Mechanics', 'Time', 'Velocity'],
    'Acetoin': ['Liquid', 'Odor'],
    'Acetone': ['Acetoin'],
    'Acetone–butanol–ethanol Fermentation': [   'Acetone',
                                                'Butanol',
                                                'Ethanol',
                                                'Glucose',
                                                'Starch'],
    'Acetyl Group': ['Acetylation', 'Acyl Group'],
    'Acetylation': ['Acetyl Group'],
    'Acid': [   'Acidic Oxide',
                'Acidity Regulator',
                'Ion',
                'Molecule',
                'Proton',
                'Protonation'],
    'Acidic Oxide': ['Acid', 'Oxide', 'Water'],
    'Acidity Regulator': ['Acid', 'Acidity Regulator', 'PH'],
    'Acoelomorpha': ['Animal', 'Life', 'Planula', 'Subphylum'],
    'Acpd': ['Agonist'],
    'Active Site': ['Biology', 'Enzyme'],
    'Acyl Group': ['Acylation', 'Amide', 'Hydroxyl Radical', 'Sulfur Oxoacid'],
    'Acylation': ['Acyl Group', 'Chemistry'],
    'Adaptation': ['Adoption', 'Biology'],
    'Adaptive Immune System': ['Pathogen'],
    'Adenine': ['Nucleobase'],
    'Adenosine': ['Medication'],
    'Adenylate Kinase': ['Enzyme', 'Kinase', 'Phosphotransferase'],
    'Affection': ['Love'],
    'Agriculture': ['Ant', 'Livestock', 'Plant'],
    'Alanine': ['Acpd', 'Protein'],
    'Albumin': ['Protein'],
    'Alcohol': ['Carbene', 'Carbon', 'Chemistry', 'Hydroxyl Radical'],
    'Algae': ['Organism'],
    'Algorithm': ['Algorithm', 'Computation', 'Mathematics'],
    'Alkyl Nitrites': ['Nitrate', 'Nitrite'],
    'Alternative Splicing': ['Gene', 'Protein'],
    'Alveolate': ['Clade', 'Conoid', 'Protist'],
    'Amide': [   'Acid',
                 'Amidicity',
                 'Amine',
                 'Azide',
                 'Carboximidate',
                 'Hydrogen',
                 'Imide'],
    'Aminal': ['Amine', 'Carbon'],
    'Amination': ['Amine', 'Molecule'],
    'Amine': [   'Amide',
                 'Amino Acid',
                 'Atom',
                 'Imine',
                 'Metal Ammine Complex',
                 'Nitrogen'],
    'Amino Acid': ['Amide', 'Amine', 'Imine'],
    'Aminoacyl Trna Synthetase': [   'Aminoacyl Trna Synthetase',
                                     'Aminoacylation',
                                     'Enzyme',
                                     'Ligase'],
    'Aminoacylation': ['Aminoacyl Trna Synthetase'],
    'Ammonia': ['Ammonia', 'Gas', 'Hydrogen', 'Nitrogen'],
    'Amoeba': ['Amoeboid Movement', 'Pseudopodia', 'Testate Amoebae'],
    'Amoeboid Movement': ['Amoeba'],
    'Anabolic Steroid': [   'Anabolic Steroid',
                            'Anabolism',
                            'Androgen',
                            'Steroid',
                            'Testosterone'],
    'Anabolism': ['Molecule'],
    'Anaerobic Respiration': ['Oxygen'],
    'Analgesic': ['Drug', 'Pain', 'Painkiller'],
    'Analytical Technique': ['Concentration'],
    'Androgen': ['Hormone', 'Steroid', 'Vertebrate'],
    'Angiogenin': ['Gene', 'Protein', 'Ribonuclease'],
    'Animal': ['Animal', 'Organism'],
    'Animation': ['Animator', 'Anime', 'Image'],
    'Animator': ['Animation', 'Anime'],
    'Anime': ['Animation', 'Animator'],
    'Anise': ['Plant'],
    'Anomer': ['Carbohydrate'],
    'Anoxygenic Photosynthesis': ['Photosynthesis'],
    'Ant': ['Antz', 'Bee', 'Insect', 'Wasp'],
    'Anthropology': ['Anthropology', 'Human', 'Humanities', 'Society'],
    'Antioxidant': ['Oxidation State'],
    'Apicomplexa': ['Alveolate', 'Phylum'],
    'Archaea': ['Archaea', 'Archaeol'],
    'Archaeol': ['Archaea'],
    'Art': ['Idea'],
    'Ascomycota': ['Phylum'],
    'Aspartate Kinase': [   'Aspartate Transaminase',
                            'Enzyme',
                            'Kinase',
                            'Phosphorylation'],
    'Aspartate Transaminase': [   'Aspartate Transaminase',
                                  'Enzyme',
                                  'Metabolism',
                                  'Transaminase'],
    'Assay': ['Pharmacology'],
    'Atom': ['Atomism', 'Matter'],
    'Atomism': ['Atom'],
    'Atoms in Molecules': ['Atom'],
    'Atp Synthase': ['Enzyme'],
    'Axe': ['Symbol'],
    'Azide': ['Amide'],
    'B Cell': ['Lymphocyte'],
    'Bacteria': ['Proteus'],
    'Bacterial Display': ['Protein'],
    'Balantidium Coli': ['Alveolate', 'Balantidiasis', 'Ciliate', 'Species'],
    'Base Pair': ['Nucleobase'],
    'Bean': ['Anise'],
    'Bee': ['Ant', 'Insect', 'Wasp'],
    'Beta Sheet': ['Protein'],
    'Bilateria': ['Animal', 'Embryo'],
    'Binding Site': ['Macromolecule', 'Protein'],
    'Biochemistry': ['Chemistry', 'Life', 'Liver', 'Organism'],
    'Biogenesis': ['Life', 'Organelle', 'Organism'],
    'Bioinformatics': ['Bioinformatics'],
    'Biological Membrane': ['Membrane'],
    'Biological Process': ['Life', 'Organism'],
    'Biological System': ['System'],
    'Biological Warfare': ['Bacteria', 'Fungus', 'Toxin', 'Virulence', 'Virus'],
    'Biology': ['Life', 'Methane', 'Organism'],
    'Biomolecule': ['Ion', 'Molecule', 'Organism'],
    'Biopolymer': ['Biomolecule', 'Biopolymer', 'Organism', 'Polymer'],
    'Biosynthesis': ['Enzyme'],
    'Blood': ['Anime', 'Nutrient', 'Oxygen'],
    'Bradford Protein Assay': ['Protein'],
    'Branched-chain Alpha-keto Acid Dehydrogenase Complex': ['Enzyme'],
    'Butanol': ['Alcohol', 'Carbon', 'Hydroxyl Radical', 'Isobutyl Nitrite'],
    'California Gold Rush': ['Gold', 'Hushing'],
    'Cancer Cell': ['Cancer'],
    'Capacitor': ['Capacitor'],
    'Carbene': ['Carbon', 'Chemistry', 'Molecule'],
    'Carbohydrate': [   'Anomer',
                        'Atom',
                        'Biomolecule',
                        'Carbon',
                        'Hydrogen',
                        'Oxygen',
                        'Α-methylfentanyl'],
    'Carbohydrate Metabolism': [   'Carbohydrate',
                                   'Life',
                                   'Liver',
                                   'Metabolism',
                                   'Organism'],
    'Carbon': ['Electron'],
    'Carboximidate': ['Alcohol', 'Amide', 'Ester'],
    'Casein': ['Phosphoprotein'],
    'Catabolism': [   'Anabolic Steroid',
                      'Anabolism',
                      'Energy',
                      'Molecule',
                      'Oxidation State'],
    'Catalase': ['Enzyme', 'Liver', 'Oxygen'],
    'Cdna Library': ['Cloning', 'Transcriptome'],
    'Cell': ['Organism'],
    'Cell Biology': ['Biology', 'Life'],
    'Cellular Organizational Structure': ['Biology', 'Troubleshooting'],
    'Cellulose': ['Glucose'],
    'Chalcogen': ['Ore'],
    'Chaperome': ['Proteopathy', 'Proteostasis'],
    'Chaperone': ['Chaperome', 'Protein'],
    'Charophyta': ['Clade'],
    'Chemical Bond': ['Atom', 'Ion', 'Molecule'],
    'Chemical Compound': ['Atom', 'Molecule'],
    'Chemical Element': ['Atom', 'Proton'],
    'Chemical Formula': ['Atom', 'Molecule'],
    'Chemical Reaction': ['Lead'],
    'Chemical Structure': ['Molecule'],
    'Chemical Substance': ['Chemical Substance', 'Matter'],
    'Chemistry': ['Atom', 'Atomism', 'Ion', 'Iron', 'Molecule', 'Structure'],
    'Chemosynthesis': ['Methane', 'Oxidation State', 'Photosynthesis'],
    'Chevrotain': ['Ungulate'],
    'Chirality': ['Chemistry'],
    'Cholera': ['Cholera', 'Infection'],
    'Ciliate': ['Ciliate', 'Protozoa', 'Protozoan Infection'],
    'Cis-regulatory Element': ['Dna', 'Gene', 'Rna'],
    'Clade': ['Ancestor', 'Organism'],
    'Cloning': ['Organism'],
    'Clustal': ['Dna Sequencing', 'Jaligner'],
    'Collagen': ['Protein'],
    'Commodity': ['Gold'],
    'Computation': ['Algorithm', 'Computer Programming'],
    'Computer Programming': ['Computer Programming', 'Computing', 'Programmer'],
    'Computer Science': ['Computation', 'Computing', 'Data', 'Science'],
    'Computing': [   'Computation',
                     'Computer Programming',
                     'Information',
                     'Profession'],
    'Concentration': ['Chemistry', 'Concentration'],
    'Concept': ['Idea'],
    'Conformational Change': ['Biochemistry', 'Macromolecule'],
    'Conformational Isomerism': ['Chemistry', 'Isomer', 'Stereoisomerism'],
    'Connecticut Agricultural Experiment Station': ['Agriculture'],
    'Connective Tissue': ['Animal', 'Muscle'],
    'Conoid': ['Geometry'],
    'Construction': ['Building', 'Guild', 'Infrastructure', 'Profession'],
    'Coordinate System': ['Coordinate System', 'Geometry'],
    'Coordination Complex': ['Atom', 'Ion', 'Ligand', 'Molecule'],
    'Coplanarity': ['Geometry'],
    'Cross-coupling Reaction': ['The Catalyst'],
    'Crystal': [   'Crystalline Silicon',
                   'Crystallite',
                   'Crystallization',
                   'Foam'],
    'Crystalline Silicon': ['Crystal'],
    'Crystallite': ['Crystal'],
    'Crystallization': [   'Crystal',
                           'Crystallite',
                           'Crystallization',
                           'Molecule'],
    'Cud': ['Ruminant'],
    'Culling': ['Biology', 'Culling'],
    'Culture': ['Art', 'Society'],
    'Cyanobacteria': ['Bacteria', 'Eukaryote', 'Life', 'Plastid'],
    'Cyclol': ['Hypothesis', 'Protein'],
    'Cytolysis': ['Lysis'],
    'Cytoskeleton': ['Archaea', 'Bacteria', 'Cytoplasm', 'Protein'],
    'Data': ['Information'],
    'Dehydration': ['Metabolism'],
    'Denaturation': ['Acid', 'Heat', 'Protein', 'Radiation', 'Solvent'],
    'Deoxyribonucleoside': ['Deoxyribonucleotide', 'Nucleoside', 'Nucleotide'],
    'Deoxyribonucleotide': ['Deoxyribonucleoside', 'Dna', 'Monomer'],
    'Design': ['Construction', 'Designer', 'Process'],
    'Designer': ['Design'],
    'Detoxification': ['Detoxification', 'Liver', 'Organism'],
    'Diabetes': ['Sugar'],
    'Diagram': ['Information'],
    'Dichroic Glass': ['Glass'],
    'Dietary Fiber': ['Plant'],
    'Dieting': ['Diabetes', 'Eating', 'Obesity'],
    'Diffusion': ['Diffusion'],
    'Digestion': ['Food'],
    'Digital Object Identifier': ['Iso 8601'],
    'Dirigent Protein': ['Protein', 'Stereochemistry'],
    'Disaccharide': ['Monosaccharide', 'Sugar', 'Sugaring'],
    'Disease': [   'Disease',
                   'Injury',
                   'Seasonal Affective Disorder',
                   'Structure'],
    'Dissociation Constant': ['Chemistry'],
    'Distance': ['Measurement'],
    'Dna': ['Helix', 'Organism', 'Reproduction', 'Virus'],
    'Dna Polymerase': [   'Deoxyribonucleotide',
                          'Dna',
                          'Dna Polymerase',
                          'Dnaa',
                          'Dnac',
                          'Dnae',
                          'Dnag',
                          'Dnah',
                          'Dnai',
                          'Dnan',
                          'Dnaq',
                          'Dnax',
                          'Enzyme',
                          'Molecule',
                          'Rna'],
    'Dna Repair': ['Dna', 'Genome', 'Processivity', 'Rna'],
    'Dna Replication': [   'Dna',
                           'Dnaa',
                           'Dnac',
                           'Dnae',
                           'Dnag',
                           'Dnah',
                           'Dnai',
                           'Dnan',
                           'Dnaq',
                           'Dnax',
                           'Processivity',
                           'Rna'],
    'Dna Sequencer': ['Dna'],
    'Dna Sequencing': ['Cdna Library', 'Dna', 'Nucleotide', 'Rna'],
    'Dna-binding Protein': ['Dna', 'Protein'],
    'Dnaa': [   'Bacteria',
                'Dna',
                'Dnac',
                'Dnae',
                'Dnag',
                'Dnah',
                'Dnai',
                'Dnan',
                'Dnaq',
                'Dnax',
                'Protein',
                'Rna'],
    'Dnac': ['Dnaa', 'Dnae', 'Dnag', 'Dnah', 'Dnai', 'Dnan', 'Dnaq', 'Dnax'],
    'Dnae': ['Dnaa', 'Dnac', 'Dnag', 'Dnah', 'Dnai', 'Dnan', 'Dnaq', 'Dnax'],
    'Dnag': [   'Dna',
                'Dnaa',
                'Dnac',
                'Dnae',
                'Dnah',
                'Dnai',
                'Dnan',
                'Dnaq',
                'Dnax',
                'Rna'],
    'Dnah': [   'Dnaa',
                'Dnac',
                'Dnae',
                'Dnag',
                'Dnai',
                'Dnan',
                'Dnaq',
                'Dnax',
                'Gene'],
    'Dnai': [   'Dnaa',
                'Dnac',
                'Dnae',
                'Dnag',
                'Dnah',
                'Dnan',
                'Dnaq',
                'Dnax',
                'Protein'],
    'Dnan': [   'Dnaa',
                'Dnac',
                'Dnae',
                'Dnag',
                'Dnah',
                'Dnai',
                'Dnaq',
                'Dnax',
                'Gene'],
    'Dnaq': ['Dnaa', 'Dnac', 'Dnae', 'Dnag', 'Dnah', 'Dnai', 'Dnan', 'Dnax'],
    'Dnax': [   'Dnaa',
                'Dnac',
                'Dnae',
                'Dnag',
                'Dnah',
                'Dnai',
                'Dnan',
                'Dnaq',
                'Gene'],
    'Docking': ['Molecule'],
    'Domestication': ['Organism', 'Reproduction'],
    'Double Bond': ['Atom', 'Chemistry'],
    'Downregulation And Upregulation': ['Genetics', 'Organism', 'Protein'],
    'Drug': ['Physiology', 'Psychology'],
    'Dtrace': ['Troubleshooting'],
    'Dual-polarization Interferometry': ['Absorbance'],
    'Dynein': ['Microtubule', 'Protein'],
    'Earth': ['Earth', 'Life', 'Planet', 'Plant'],
    'Eating': ['Eating', 'Food', 'Ingestion', 'Organism'],
    'Edestin': ['Legumin', 'Protein'],
    'Eicosanoid': ['Oxidation State'],
    'Elastin': ['Protein'],
    'Electric Charge': ['Force', 'Matter'],
    'Electric Power Conversion': ['Frequency'],
    'Electromagnet': ['Electromagnetism'],
    'Electromagnetic Radiation': ['Energy', 'Physics', 'Radiation'],
    'Electromagnetism': [   'Electromagnet',
                            'Electromagnetic Radiation',
                            'Force',
                            'Physics'],
    'Electron Transport Chain': ['Electron', 'Proton', 'Redox'],
    'Embryo': ['Embryo', 'Organism'],
    'Emulsion Polymerization': ['Monomer', 'Polymerization'],
    'Endocrine System': ['Gland', 'Hormone', 'Organism'],
    'Endonuclease': ['Endonuclease', 'Enzyme', 'Polynucleotide'],
    'Endoplasmic Reticulum': ['Battle of Cisterna', 'Organelle'],
    'Energy': ['Energy', 'Exergy', 'Heat', 'Physics'],
    'Engine': ['Energy', 'Force', 'Machine'],
    'Engineering': ['Design', 'Engine'],
    'Enzyme': ['Protein', 'The Catalyst'],
    'Enzyme Assay': ['Assay', 'Enzyme'],
    'Enzyme Catalysis': ['Enzyme', 'Process'],
    'Enzyme Kinetics': ['Catalase', 'Enzyme', 'The Catalyst'],
    'Epistemology': ['Knowledge'],
    'Equine Coat Color Genetics': ['Gene', 'Horse'],
    'Essential Amino Acid': ['Acid'],
    'Ester': ['Acid', 'Amide', 'Chemistry'],
    'Ethanol': [   'Abbreviated Dialing',
                   'Alcohol',
                   'Ethanol',
                   'Ethynol',
                   'Methanol',
                   'Vinyl Alcohol'],
    'Ethanol Fermentation': [   'Ethanol',
                                'Fermentation',
                                'Fructose',
                                'Glucose',
                                'Sucrose',
                                'Sugar'],
    'Ethanol Metabolism': ['Alcohol', 'Ethanol', 'Metabolism', 'Nature'],
    'Ethynol': ['Alcohol', 'Ethanol', 'Vinyl Alcohol'],
    'Eukaryote': [   'Eukaryote',
                     'Eukaryotic Transcription',
                     'Organelle',
                     'Organism',
                     'Prokaryote',
                     'Prokaryotic Translation'],
    'Evolutionary Psychology': ['Psychology'],
    'Exergy': ['Software'],
    'Experiment': ['Hypothesis'],
    'Explanation': ['Fact'],
    'Fatty Acid': ['Biochemistry', 'Chemistry'],
    'Fermentation': ['Enzyme', 'Fermentation'],
    'Flowering Plant': ['Flowering Plant', 'Plant', 'Species'],
    'Fluid': ['Physics'],
    'Foam': ['Gas'],
    'Food': ['Organism'],
    'Forbes': ['Business'],
    'Force': ['Interaction', 'Physics'],
    'Fossil': ['Fossil'],
    'Fourier-transform Infrared Spectroscopy': ['Spectroscopy'],
    'Free Java Implementations': ['Software'],
    'Fructose': [   'Disaccharide',
                    'Glucose',
                    'Monosaccharide',
                    'Sucrose',
                    'Sugar',
                    'Sugaring'],
    'Fruit': ['Bean', 'Fruit', 'Plant', 'Seed'],
    'Fungus': ['Fungus', 'Mold', 'Mushroom', 'Organism', 'Yeast'],
    'Fur': ['Animal'],
    'Fusion Protein': ['Gene', 'Protein'],
    'Galaxy': ['Star'],
    'Gencode': ['Genome'],
    'Gene': ['Biology', 'Gencode', 'Genetics', 'Nucleotide', 'Protein'],
    'Gene Structure': ['Gene'],
    'Genetics': ['Biology', 'Gene', 'Heredity', 'Organism'],
    'Genome': ['Gene', 'Genetics'],
    'Genus': ['Biology', 'Fossil', 'Genus', 'Life', 'Organism', 'Virus'],
    'Geological Period': ['Geology', 'Periodization', 'Time'],
    'Geology': ['Earth', 'Tide', 'Time'],
    'Geometry': ['Mathematics'],
    'Glass': ['Glass', 'Optics'],
    'Globular Protein': ['Protein'],
    'Glucose': ['Carbohydrate', 'Monosaccharide', 'Sugar', 'Sugaring'],
    'Glycine': ['Acpd', 'Amine', 'Gas', 'Hydrogen'],
    'Glycosidic Bond': ['Carbohydrate'],
    'Glycosylamine': ['Amine'],
    'Gram-negative Bacteria': ['Bacteria'],
    'Green Algae': ['Algae'],
    'Head Lice Infestation': ['Insect', 'Louse', 'Pediculosis', 'Scalp'],
    'Health': ['Disease'],
    'Heat': ['Energy', 'Thermodynamics'],
    'Heredity': ['Organism'],
    'Heterokont': ['Eukaryote', 'Life', 'Yellow-green Algae'],
    'Histopathology': ['Tissue'],
    'Hormone': ['Gland', 'Physiology'],
    'Human': ['Humanism'],
    'Humanities': ['Art', 'Culture', 'Human', 'Humanism', 'Society'],
    'Hushing': ['Mining', 'Water'],
    'Hydroxyl Radical': ['Hydroxyl Radical'],
    'Hypothesis': ['Explanation', 'Phenomenon'],
    'Idea': ['Idea', 'Image'],
    'Imide': ['Amide', 'Imine', 'Nitrogen'],
    'Imine': ['Aminal', 'Amine', 'Carbene', 'Carbon', 'Imide', 'Nitrogen'],
    'Immunology': ['Biology', 'Organism'],
    'Inductor': ['Energy'],
    'Infection': ['Disease', 'Organism', 'Toxin'],
    'Inflammation': ['Inflammation', 'Irritation', 'Parotitis', 'Pathogen'],
    'Information': ['Nature'],
    'Infrared': ['Light', 'Wavelength'],
    'Infrastructure': ['Infrastructure'],
    'Ingestion': ['Organism'],
    'Innate Immune System': ['Vertebrate'],
    'Insect': ['Phylum'],
    'Instrumentalism': [   'Epistemology',
                           'List of Internet Phenomena',
                           'Phenomenalism'],
    'Instrumentation': ['Dtrace'],
    'Ion': ['Atom', 'Iron', 'Molecule'],
    'Iron': ['Metal', 'Metallicity'],
    'Irritability': ['Love'],
    'Irritation': ['Biology', 'Inflammation', 'Irritability', 'Physiology'],
    'Iso 6344': ['Sandpaper', 'Standardization'],
    'Iso 8601': ['Time'],
    'Isobutyl Nitrite': ['Ester', 'Isobutanol', 'Nitrate', 'Nitrite'],
    'Isoelectric Focusing': ['Molecule'],
    'Isomer': ['Chemistry', 'Molecule'],
    'Kinase': ['Biochemistry', 'Enzyme', 'Phosphate'],
    'Lame': ['Codec'],
    'Larva': ['Animal'],
    'Legume': ['Fruit', 'Legume', 'Plant', 'Seed'],
    'Legumin': ['Bean', 'Casein', 'Lentil', 'Milk', 'Pea', 'Protein', 'Vicia'],
    'Lentil': ['Legume'],
    'Levacetylmethadol': ['Opiod'],
    'Life': ['Ape', 'Life'],
    'Ligand': ['Ion', 'Iron', 'Metal', 'Molecule'],
    'Ligase': ['Biochemistry', 'Enzyme', 'Hydrolysis', 'Muon-catalyzed Fusion'],
    'Light': ['Radiation'],
    'Linguistics': ['Linguistics'],
    'Lipid': ['Biochemistry', 'Biology', 'Biomolecule'],
    'Liquid': ['Fluid'],
    'List of Mail Server Software': ['Qmail'],
    'Liver': [   'Biochemistry',
                 'Detoxification',
                 'Digestion',
                 'Metabolite',
                 'Protein',
                 'Vertebrate'],
    'Livestock': [   'Animal',
                     'Commodity',
                     'Domestication',
                     'Fur',
                     'Leather',
                     'Meat',
                     'Milk',
                     'Wool'],
    'Lobosa': ['Amoeba'],
    'Louse': ['Insect'],
    'Love': ['Affection', 'Pleasure', 'Virtue'],
    'Lustre': ['Crystal', 'Mineral', 'Wax'],
    'Lymphocyte': ['Blood', 'Vertebrate'],
    'Macromolecule': [   'Macromolecule',
                         'Molecule',
                         'Monomer',
                         'Polymerization',
                         'Protein'],
    'Mammal': [   'Animal',
                  'Ape',
                  'Art',
                  'Fur',
                  'Mammal',
                  'Milk',
                  'Seed',
                  'Vertebrate'],
    'Maser': ['Amplifier'],
    'Mass': ['Acceleration', 'Force'],
    'Materialism': [   'Consciousness',
                       'Force',
                       'Matter',
                       'Mohism',
                       'Monism',
                       'Nature'],
    'Mathematics': ['Quantity', 'Space'],
    'Matter': ['Chemistry', 'Gas', 'Mass', 'Physics', 'Space'],
    'Meat': ['Animal', 'Food', 'Meat'],
    'Meat Glue': ['Meat', 'Protein'],
    'Mechanics': ['Physics'],
    'Medal': ['Metal'],
    'Medication': ['Disease', 'Drug'],
    'Medicine': ['Disease', 'Science'],
    'Metabolic Pathway': ['Biochemistry', 'Serine'],
    'Metabolism': ['Life', 'Organism'],
    'Metabolite': ['Metabolism'],
    'Metal': ['Medal', 'Metallicity'],
    'Metal Ammine Complex': ['Ammonia', 'Ligand'],
    'Metallicity': ['Hydrogen', 'Metal'],
    'Methanol': ['Alcohol', 'Ethanol', 'Levacetylmethadol', 'Oxymetholone'],
    'Methodology': ['Analysis'],
    'Methods in Enzymology': ['Biochemistry'],
    'Microorganism': ['Organism'],
    'Microscope': ['Microscopic Scale', 'Microscopy'],
    'Microscopic Scale': ['Microscope', 'Microscopic Scale', 'Microscopy'],
    'Microscopy': ['Microscope', 'Microscopic Scale', 'Microscopy'],
    'Microsoft Exchange Server': ['Qmail'],
    'Microtubule': ['Cytoskeleton', 'Microtubule', 'Polymer', 'Tubulin'],
    'Milk': ['Food', 'Mammal', 'Milk'],
    'Mineral': ['Mining'],
    'Mining': ['Mineral', 'Ore'],
    'Mitochondrial Dna': ['Dna', 'Organelle', 'Rna'],
    'Mohism': ['Science'],
    'Mold': ['Fungus'],
    'Molecular Cloning': ['Cloning', 'Dna'],
    'Molecule': ['Atom', 'Molecule'],
    'Monism': ['Concept', 'Mohism'],
    'Monomer': ['Molecule', 'Polymer', 'Polymerization'],
    'Monosaccharide': ['Carbohydrate', 'Sugar', 'Sugaring'],
    'Motility': ['Organism'],
    'Motor Protein': ['Animal', 'Cytoplasm', 'Protein'],
    'Multicelluar Organism': ['Organism'],
    'Multicellular Organism': ['Organism'],
    'Muon-catalyzed Fusion': ['Temperature'],
    'Native Metal': ['Metal'],
    'Natural Philosophy': ['Nature', 'Science', 'Universe', 'University'],
    'Natural Science': ['Nazi Human Experimentation', 'Observation', 'Science'],
    'Nature': [   'Materialism',
                  'Nature',
                  'Naturism',
                  'The Natural',
                  'Universe',
                  'World'],
    'Naturism': ['Nudist Paradise', 'Nudity'],
    'Nbpf15': ['Gene', 'Human', 'Protein'],
    'Neutron': ['Mass', 'Particle', 'Photon', 'Proton', 'Roton'],
    'Nitrate': ['Nitrite'],
    'Nitrite': ['Ion'],
    'Nitrogen': ['Gas', 'Wax'],
    'Nuclease': ['Enzyme', 'Nucleotide'],
    'Nucleobase': ['Monomer', 'Nucleoside', 'Nucleotide'],
    'Nucleoside': ['Glycosylamine', 'Nucleotide'],
    'Nucleotide': ['Molecule', 'Nucleoside'],
    'Nudity': ['Human', 'Sex Organ'],
    'Number': ['Measurement', 'Number'],
    'Nutrient': ['Nutrient'],
    'Object-oriented Programming': ['Data'],
    'Observation': ['Information'],
    'Officer': ['Authority'],
    'Olfaction': ['Olfaction'],
    'Opticks': ['Optics'],
    'Optics': ['Light', 'Matter', 'Opticks', 'Optics', 'Physics'],
    'Ore': ['Metal', 'Mineral', 'Mining', 'Sediment'],
    'Organ': ['Organ', 'Organism'],
    'Organic Compound': ['Carbon', 'Chemistry'],
    'Organism': ['Biology', 'Life'],
    'Organization': ['British Firms', 'Organisation Todt'],
    'Organometallic Chemistry': [   'Atom',
                                    'Carbon',
                                    'Chemistry',
                                    'Metal',
                                    'Molecule'],
    'Oxidation State': ['Atom', 'Oxidation State', 'Oxide'],
    'Oxide': ['Oxygen'],
    'Oxidized Cellulose': ['Cellulose'],
    'Oxidoreductase': ['Antioxidant', 'Biochemistry', 'Electron', 'Enzyme'],
    'Oxygen': ['Chalcogen', 'Oxidation State', 'Oxide', 'Thermal Oxidizer'],
    'Oxymetholone': ['Anabolic Steroid', 'Androgen', 'Steroid'],
    'PH': ['Chemistry'],
    'Pancreas': ['Endocrine System', 'Pancreatitis', 'Vertebrate'],
    'Parasitic Disease': ['Parasitism'],
    'Parasitism': ['Adaptation', 'Head Lice Infestation', 'Species'],
    'Parotitis': ['Inflammation'],
    'Particle': ['Chemical Substance', 'Mass'],
    'Pathogen': ['Biology', 'Disease'],
    'Pea': ['Fruit', 'Pea', 'Seed'],
    'Pediculosis': ['Head Lice Infestation'],
    'Peptide': ['Amide', 'Peptide', 'Peptoid'],
    'Peptidomimetic': ['Peptide', 'Peptoid'],
    'Peptoid': ['Glycine', 'Peptide', 'Peptidomimetic'],
    'Period 6 Element': ['Lanthanide'],
    'Periodic Table': ['Electron'],
    'Periodization': ['Time'],
    'Personal Protective Equipment': ['Infection', 'Injury'],
    'Pharmacology': ['Drug', 'Medication'],
    'Pharmacy': ['Drug'],
    'Phenomenalism': ['List of Internet Phenomena'],
    'Phenotype': ['Gene', 'Genetics', 'Organism'],
    'Phosphate': ['Acidic Oxide'],
    'Phosphoprotein': ['Molecule', 'Phosphate', 'Protein'],
    'Phosphorus Monoxide': ['Phosphorus'],
    'Phosphoryl Group': ['Oxygen', 'Phosphorus', 'Phosphorylation'],
    'Phosphorylation': ['Chemistry'],
    'Phosphotransferase': ['Enzyme', 'Phosphorylation'],
    'Photon': ['Particle', 'Photon', 'Proton'],
    'Photosynthesis': ['Plant'],
    'Phylogenetic Tree': ['Species'],
    'Phylum': ['Phylum'],
    'Physical Object': ['Matter', 'Space'],
    'Physiology': ['Life'],
    'Planet': ['Planet', 'Star'],
    'Plant': ['Eukaryote', 'Eukaryotic Transcription', 'Plant'],
    'Planula': ['Larva'],
    'Plastid': ['Algae', 'Organelle', 'Plant', 'Plastid'],
    'Pleasure': ['Animal', 'Human'],
    'Poison': ['Biology', 'Organ'],
    'Polymer': ['Macromolecule', 'Molecule', 'Reptation'],
    'Polymerization': ['Monomer', 'Polymer'],
    'Polynucleotide': ['Biopolymer', 'Monomer'],
    'Positive-sense Single-stranded Rna Virus': ['Virus'],
    'Post-transcriptional Modification': ['Dna', 'Gene', 'Rna'],
    'Problem Solving': ['Problem Solving'],
    'Processivity': [   'Biochemistry',
                        'Dna',
                        'Dna Polymerase',
                        'Dnaa',
                        'Dnac',
                        'Dnae',
                        'Dnag',
                        'Dnah',
                        'Dnai',
                        'Dnan',
                        'Dnaq',
                        'Dnax',
                        'Enzyme',
                        'Muon-catalyzed Fusion',
                        'Nucleotide'],
    'Prokaryote': ['Mitochondrial Dna', 'Organelle'],
    'Prokaryotic Translation': ['Prokaryote', 'Protein'],
    'Prostate Pathology': ['Prostate'],
    'Protein': [   'Acid',
                   'Amino Acid',
                   'Biomolecule',
                   'Macromolecule',
                   'Protein'],
    'Protein Engineering': ['Engineering', 'Protein'],
    'Protein Quaternary Structure': ['Protein'],
    'Proteinogenic Amino Acid': ['Amide', 'Protein'],
    'Proteobacteria': ['Bacteria', 'Phylum'],
    'Proteome': ['Genome', 'Protein', 'Proteomics'],
    'Proteomics': ['Protein', 'Proteome'],
    'Proteopathy': ['Medicine'],
    'Proteostasis': ['Beef Aging', 'Biogenesis'],
    'Proton': ['Neutron', 'Particle', 'Photon', 'Protonation', 'Roton'],
    'Protonation': ['Acidity Regulator', 'Atom', 'Ion', 'Molecule', 'Proton'],
    'Protozoa': ['Culling', 'Eukaryote', 'Microorganism'],
    'Protozoan Infection': ['Organism'],
    'Quantum Mechanics': [   'Mechanics',
                             'Nature',
                             'Physics',
                             'Quantum Mechanics'],
    'Radiation': ['Energy', 'Particle', 'Physics', 'Space'],
    'Receptor': ['Biochemistry', 'Pharmacology', 'Protein'],
    'Redox': ['Atom', 'Ore', 'Oxidized Cellulose'],
    'Regulation of Gene Expression': ['Genetics'],
    'Reporter Gene': ['Bacteria', 'Gene'],
    'Reproduction': ['Organism', 'The Offspring'],
    'Reptation': ['Macromolecule', 'Polymer'],
    'Residue': ['Chemistry'],
    'Resonant Converter': ['Capacitor', 'Inductor'],
    'Restriction Enzyme': ['Dna', 'Endonuclease', 'Enzyme'],
    'Reverse Transcription Polymerase Chain Reaction': ['Rna'],
    'Rhodopsin': ['Protein', 'Visual Phototransduction'],
    'Ribonuclease': ['Nuclease'],
    'Ribonuclease Inhibitor': ['Protein', 'Ribonuclease'],
    'Ribonucleoprotein Particle': ['Rna'],
    'Rna': ['Gene', 'Genetics'],
    'Rna Splicing': ['Aminoacyl Trna Synthetase', 'Dna'],
    'Rna-dependent Rna Polymerase': ['Dna', 'Dna Polymerase', 'Enzyme', 'Rna'],
    'Roton': ['Energy', 'Proton'],
    'Rumen': ['Ruminant'],
    'Ruminant': ['Mammal', 'Rumen', 'Stomach'],
    'Sandpaper': ['Axe'],
    'Science': [   'Explanation',
                   'Knowledge',
                   'Organism',
                   'Science',
                   'Universe',
                   'University'],
    'Science And Technology': ['Science', 'Technology'],
    'Scientific Instrument': ['Instrumentalism', 'Instrumentation'],
    'Scientific Method': ['Knowledge', 'Science'],
    'Seed': ['Plant'],
    'Serine': ['Acpd', 'Biosynthesis', 'Protein'],
    'Sex': ['Organism'],
    'Skeleton': ['Organism'],
    'Society': ['Society'],
    'Sociology': ['Culture', 'Society'],
    'Software': ['Computation', 'Computer Programming', 'Data'],
    'Solution': ['Chemistry', 'Solution'],
    'Solvent': ['Solution'],
    'Spectroscopy': ['Matter', 'Radiation'],
    'Standardization': ['Iso 8601', 'Standardization'],
    'Star': ['Star'],
    'Starch': ['Carbohydrate', 'Glucose'],
    'Stereochemistry': ['Atom', 'Chemistry', 'Molecule'],
    'Stereoisomerism': ['Anomer', 'Cis–trans Isomerism', 'Stereochemistry'],
    'Steroid': ['Steroid'],
    'Steroid Hormone': ['Hormone', 'Steroid'],
    'Stomach': ['Stomach'],
    'Structuralism': ['Anthropology', 'Linguistics', 'Sociology', 'System'],
    'Structure': ['Organism', 'Organization', 'System'],
    'Subatomic Particle': ['Atom', 'Particle'],
    'Subphylum': ['Phylum'],
    'Sucrase': ['Enzyme', 'Fructose', 'Glucose', 'Hydrolysis', 'Sucrose'],
    'Sucrose': ['Sucrase', 'Sugar', 'Sugaring'],
    'Sugar': ['Carbohydrate', 'Food', 'Sugaring'],
    'Sugaring': ['Sugar'],
    'Sulfur Oxoacid': ['Hydrogen', 'Oxygen', 'Sulfur Oxoacid'],
    'Symbiosis': ['Interaction', 'Organism'],
    'Symbol': ['Idea'],
    'System': ['Interaction'],
    'Taxonomy': ['Biology', 'Organism', 'Science'],
    'Testate Amoebae': ['Amoeboid Movement', 'Protist', 'Pseudopodia'],
    'Testosterone': ['Anabolism', 'Hormone', 'Sex', 'Steroid'],
    'Thermodynamics': [   'Energy',
                          'Exergy',
                          'Heat',
                          'Matter',
                          'Physics',
                          'Radiation',
                          'Temperature'],
    'Tide': ['Force', 'Tide', 'Time'],
    'Toxicant': ['Toxicity', 'Toxin'],
    'Toxicity': ['Organism', 'Toxicant', 'Toxicity', 'Toxin'],
    'Toxin': ['Toxicant', 'Toxicity'],
    'Transaminase': [   'Amine',
                        'Enzyme',
                        'Muon-catalyzed Fusion',
                        'Transamination'],
    'Transduction': ['Physiology'],
    'Transgender Hormone Therapy': ['Sex'],
    'Troubleshooting': ['System'],
    'Tubulin': ['Protein', 'Tubulin'],
    'Unicellular Organism': ['Organism'],
    'Universe': [   'Energy',
                    'Foam',
                    'Forbes',
                    'Force',
                    'Galaxy',
                    'Matter',
                    'Planet',
                    'Plant',
                    'Space',
                    'Star',
                    'Tide',
                    'Time'],
    'Vault': ['Organelle', 'Ribonucleoprotein Particle'],
    'Velocity': ['Time'],
    'Verrucomicrobia': ['Bacteria'],
    'Vertebra': ['Vertebrate'],
    'Vertebrate': ['Animal', 'Species', 'Subphylum', 'Vertebra', 'Vertebrate'],
    'Vicia': ['Genus', 'Legume', 'Plant', 'Species'],
    'Vinyl Alcohol': ['Enol', 'Ethanol', 'Ethynol'],
    'Viral Eukaryogenesis': ['Dna', 'Hypothesis', 'Life', 'Rna'],
    'Virulence': ['Virus'],
    'Virus': ['Life', 'Organism', 'Virulence'],
    'Vitrella Brassicaformis': ['Alveolate'],
    'Volvox Carteri': ['Species'],
    'Vorticella': ['Ciliate'],
    'Wasp': ['Ant', 'Bee', 'Insect', 'Wasp'],
    'Water': ['Fluid', 'Life', 'Olfaction', 'Organism'],
    'Wavelength': ['Physics'],
    'White Blood Cell': ['Blood', 'Disease'],
    'World': ['Earth', 'Life', 'Planet'],
    'Xenacoelomorpha': ['Acoelomorpha', 'Animal', 'Phylum', 'Xenoturbella'],
    'Xenoturbella': ['Bilateria', 'Genus'],
    'Yeast': ['Fungus', 'Microorganism'],
    'Zosterophyll': ['Plant'],
    'Zygnematophyceae': ['Algae'],
    'Zygomycota': ['Fungus', 'Phylum'],
    'Α-methylfentanyl': ['Analgesic'],
    'Γ-oryzanol': ['Lipid']}
