
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_seealso_dict = {
    '4-Aminobutyrate Transaminase': [   'Pyridoxal Phosphate -Dependent '
                                        'Transaminase Enzyme'],
    'Abbreviated Dialing': [   'A Very Short Digit Sequence To Reach Specific '
                               'Telephone Numbers',
                               'Abbreviated'],
    'Abnormal Posturing': ['Abnormal', 'Involuntary Flexion Or Extension'],
    'Absorbance': ['Adsorbed'],
    'Acetoin': ['Acetone'],
    'Acetyl Group': ['Acetyl'],
    'Acetylation': ['Acetyl'],
    'Acid': ['Amide'],
    'Acidic Oxide': ['Acidic', 'Acids'],
    'Acidity Regulator': ['Acid', 'Acidity', 'Acids'],
    'Acoelomorpha': ['Acoelomorph', 'Acoelomorphs'],
    'Acpd': ['Acid'],
    'Acyl Group': ['Acyl', 'Moiety Derived By The'],
    'Acylation': ['Acyl', 'Adding An Acyl Group To A Compound'],
    'Adaptation': ['Adapted'],
    'Adaptive Immune System': [   'A Vaccine To Help The Immune System Develop '
                                  'Protection',
                                  'Two Main Immunity Strategies'],
    'Adherence': ['Adherence Medicine', 'Patient Adherence'],
    'Adoption': ['Adaptation'],
    'Affection': ['Disposition Or'],
    'Agonist': ['Type Of Agonist'],
    'Agricultural Robot': ['Robot Deployed For Agricultural Purposes'],
    'Alcohol': ['Alcohols'],
    'Algorithms For Calculating Variance': [   'Computational Method For '
                                               'Calculating The'],
    'Alkyl Nitrites': [   'A Chemical Compounds Based Upon The Molecular '
                          'Structure R-Ono',
                          'Alkyl Nitrite'],
    'Alveolate': ['Alveolates'],
    'Amide': ['Acids', 'Amides', 'Amines'],
    'Amidicity': ['Amide'],
    'Aminal': ['Imine'],
    'Amination': ['Amino'],
    'Amine': ['Amide', 'Amines', 'Amino'],
    'Amino Acid': ['Amines', 'Amino'],
    'Aminoacyl Trna Synthetase': ['Rna', 'Trna'],
    'Aminoacylation': ['Adding An Aminoacyl Group To A Compound', 'Aminoacyl'],
    'Amoeba': ['Amoebae'],
    'Amoeboid Movement': ['Amoeboid'],
    'Amoebozoa': ['A Amoebozoa'],
    'Amplifier': ['Amplification'],
    'Anabolic Steroid': ['Anabolic'],
    'Anabolism': ['Anabolic'],
    'Anaerobic Respiration': ['Aerobic Respiration'],
    'Analysis': ['Breaking A Complex Topic Or Substance Into Smaller'],
    'Ancient History': ['Ancient'],
    'Androgen': ['Androgens'],
    'Animal': ['Animals'],
    'Animation': ['Anime'],
    'Animator': ['Animation', 'Artist Who Creates Multiple Images'],
    'Anime': ['Animals'],
    'Anise': ['Animal'],
    'Anoikis': ['Anti-Metastatic Activity'],
    'Anomer': ['Atom', 'Atoms', 'Geometric Variation Found At Certain'],
    'Ant': ['Art'],
    'Antibiotic': ['Antimicrobial Substance Active Against Bacteria'],
    'Antibody-Drug Conjugate': ['Adc'],
    'Antioxidant': ['Oxidant'],
    'Antz': [   '1998 American Computer Animated Adventure Comedy Film '
                'Directed By Eric Darnell',
                'Ants'],
    'Ape': ['A Old World Tailless Simians', 'Apes', 'Are'],
    'Archaeol': ['Archaeon'],
    'Art': ['Are'],
    'Ascomycota': ['Xylonomycetes'],
    'Aspartate Kinase': ['Aspartokinase'],
    'Aspartate Transaminase': ['Aspartate'],
    'Assay': ['Assays'],
    'Atom': ['Atoms'],
    'Atomism': ['Atom', 'Atoms'],
    'Atoms In Molecules': ['Atom Or Molecule'],
    'Auto Racing': [   'Sports Prototype Racing Car Developed Specifically For '
                       "The Grand American Road Racing Association'S Rolex "
                       'Sports Car Series As Their Top'],
    'Axe': ['Are'],
    'Azide': ['Amide'],
    'B16 Melanoma': ['B16F10', 'Murine Tumor Cell Line'],
    'Balantidium Coli': ['A Parasitic Alveolates', 'Parasitic Alveolates'],
    'Battle Of Cisterna': ['Cisterna', 'Cisternae'],
    'Bean': ['Beans'],
    'Bee': ['Bees', 'Flying Insects Closely Related To Wasps'],
    'Beef Aging': ['Aging', 'Are', 'Preparing Beef For Consumption'],
    'Bernard Malamud': ['1952 Novel About Baseball By Bernard Malamud'],
    'Bibcode': ['Compact Identifier'],
    'Bilateria': [   'Animals With Bilateral Symmetry As An Embryo',
                     'Bilaterians'],
    'Binding Site': ['Region On A Macromolecule Such As A Protein'],
    'Biochemistry': ['Biochemicals'],
    'Biogenesis': ['New Living Organisms Or Organelles'],
    'Biological Membrane': ['Enclosing Or Separating Membrane'],
    'Biological Process': ['Biological Process By'],
    'Biomolecule': ['Biomolecules', 'Large Biomolecules'],
    'Biopolymer': ['Polymers Produced By Living Organisms'],
    'Blood': ['Hematological'],
    'Bovina': ['Subtribe'],
    'Bow Down': ['Song By American Rock Band I Prevail'],
    'British Firms': [   'Organisation',
                         'Organised',
                         'Organised Crime Groups Originating'],
    'Cancer Immunotherapy': ['Anti-Pd1 Therapy'],
    'Capacitor': ['Capacitors'],
    'Carbene': ['Carbon'],
    'Carbohydrate': ['Carbohydrates'],
    'Carboximidate': ['Amide', 'Imidate'],
    'Cartesian Coordinate System': ['Cartesian Coordinates'],
    'Catalase': ['Catalysed'],
    'Cdna Library': ['Cdna', 'Dna'],
    'Cefalexin': ['Commonly Prescribed'],
    'Cell': ['Biological Cell', 'The Cells'],
    'Cell Culture': ['Renca Renal Cell'],
    'Cellular Compartment': ['Cellular Compartments'],
    'Cellular Organizational Structure': ['Cell'],
    'Cercozoa': ['Vampyrellidea'],
    'Chaperome': ['Chaperones'],
    'Chemical Element': ['Chemical Elements'],
    'Chemical Formula': [   'Chemical Compound With The Chemical Formula Ch4',
                            'Chemical With The Formula Ch3Oh',
                            'Presenting Information About The Chemical'],
    'Chemical Reaction': ['Chemical Reaction In'],
    'Chemical Structure': ['Chemical Structures'],
    'Chemical Substance': ['Chemical', 'Substance'],
    'Chemistry': ['Scientific Discipline Involved With Elements'],
    'Chemokine': ['Inflammatory Chemokines'],
    'Chemotherapy': ['Anti-Tumor'],
    'Chevrotain': ['The Only Extant Members'],
    'Chimeric Antigen Receptor T Cell': [   'Transmembrane Receptors Expressed '
                                            'On The'],
    'Chromosome': ['Chromosomes'],
    'Ciliate': ['Ciliates'],
    'Cis–Trans Isomerism': ['Isomerism'],
    'Clinical Study Design': ['Clinical Study'],
    'Cloning': ['Cloned'],
    'Clustal': ['Clustalw'],
    'Codec': ['Coding'],
    'Colorectal Cancer': ['Colon Carcinoma'],
    'Commodity': ['Commodities'],
    'Computation': ['Computer'],
    'Computer Programming': ['Computer', 'Computing', 'Program'],
    'Computing': ['Computer'],
    'Concentration': ['A Constituent Divided By The Total'],
    'Concept': ['Defined As Abstract Ideas Or General Notions'],
    'Conformational Isomerism': ['Chemical Conformation'],
    'Connecticut Agricultural Experiment Station': [   'Connecticut State '
                                                       "Government'S "
                                                       'Agricultural '
                                                       'Experiment Station'],
    'Conoid': ['Considered'],
    'Conosa': ['Variosea', 'Varipodida'],
    'Conserved Sequence': ['Conserved'],
    'Construction': ['Constructing A Building Or Infrastructure'],
    'Coordination Complex': [   'In Turn Known As Ligands Or Complexing Agents',
                                'Metal Complexes Containing At Least One '
                                'Ammonia Ligand '],
    'Coplanarity': ['Coplanar', 'Coplanar If There Exists A Geometric Plane'],
    'Cryogenic Electron Microscopy': [   'Cryo-Electron Microscopy',
                                         'Electron Microscopy Technique '
                                         'Applied On Samples Cooled To '
                                         'Cryogenic Temperatures'],
    'Crystalline Silicon': ['Crystalline'],
    'Crystallite': ['Crystalline', 'Small Or Even Microscopic Crystal'],
    'Crystallization': ['Crystal'],
    'Crystallize': [   'Crystallize',
                       'Song By American Violinist Lindsey Stirling'],
    'Cud': ['Highly-Digestible'],
    'Culling': ['Celled', 'Segregating Organisms'],
    'Cytokine': ['A Small Cytokines'],
    'Cytosol': ['Cytosol'],
    'Deoxyribonucleoside': [   'Deoxyribonucleotide',
                               'Nucleoside Including Deoxyribose As A '
                               'Component'],
    'Deoxyribonucleotide': ['Deoxyribonucleotides'],
    'Design': ['Plan Or Specification For The'],
    'Designer': ['Design', 'Person Who Makes Designs For Objects'],
    'Designing Women': ['Designing'],
    'Detoxification': ['Detoxifies', 'Physiological Or Medicinal'],
    'Dichroic Glass': ['Dichroic'],
    'Dietary Fiber': ['Water-Insoluble'],
    'Dieting': ['Diet'],
    'Digestion': [   'Large Insoluble Food Molecules Into Small Water-Soluble '
                     'Food Molecules So'],
    'Digital Object Identifier': ['Persistent Identifier Or Handle'],
    'Dihedral Angle': ['Angle Between Two Intersecting Planes'],
    'Disease': ['Illness', 'Particular Abnormal Condition'],
    'Distance': ['Distances'],
    'Disulfide Bond Formation Protein B': ['Disulfide Bond'],
    'Dna': ['Rna'],
    'Dna Polymerase': ['Polymerase'],
    'Dna Sequencer': ['Dna Sequence'],
    'Dna Sequencing': ['Sequence', 'Sequencing'],
    'Dnaa': ['Dna'],
    'Dnac': ['Dna'],
    'Dnae': ['Catalytic Α', 'Dna'],
    'Dnag': ['Dna'],
    'Dnah': ['Dna'],
    'Dnai': ['Dna'],
    'Dnan': ['Dna'],
    'Dnaq': ['Dna', 'Gene Encoding The Ε'],
    'Dnax': ['Dna'],
    'Domestication': [   'Domesticated',
                         'Sustained Multi-Generational Relationship In'],
    'Double Bond': ['Covalent Bond Between Two Atoms', 'Double-Bond'],
    'Drug Development': [   'Bringing A New Pharmaceutical Drug To The Market '
                            'Once A Lead Compound Has Been Identified Through '
                            'The'],
    'Dtrace': [   'Comprehensive Dynamic Tracing Framework Created By Sun '
                  'Microsystems For Troubleshooting Kernel',
                  'Trace'],
    'Dual-Polarization Interferometry': ['Dual Polarisation Interferometry'],
    'Echinamoebidae': ['Vermamoebidae'],
    'Eicosanoid': [   'Eicosanoid Metabolism',
                      'Signaling Molecules Made By The Enzymatic Or '
                      'Non-Enzymatic'],
    'Electric Charge': ['Electrically Neutral'],
    'Electric Power Conversion': ['Electric Power Converter'],
    'Electromagnet': ['Electromagnetism'],
    'Electromagnetic Radiation': ['Electromagnetic', 'Electromagnetism'],
    'Electron': ['Electron', 'Electrons', 'Open-Source Framework Developed'],
    'Electrophoresis': ['Dispersed Particles Relative To A Fluid Under The'],
    'Endocrine System': [   'Chemical Messenger System Comprising Feedback '
                            'Loops',
                            'Endocrine'],
    'Endogeny': ['Endogenous'],
    'Engine': ['Engineering', 'Machine Designed To Convert One'],
    'Engineering': ['Scientific Principles To Design'],
    'Enzyme': ['Enzyme Found'],
    'Enzyme Assay': ['Laboratory Methods For Measuring Enzymatic Activity'],
    'Epigenetics': ['Heritable Phenotype Changes'],
    'Essential Amino Acid': ['Essential Amino', 'Essential Amino Acids'],
    'Ethynol': ['Ethenol'],
    'Eukaryote': ['A Single-Celled Eukaryotes', 'Eukaryotes', 'Voromonadidae'],
    'Eukaryotic Transcription': ['Eukaryotic'],
    'Eusociality': ['Eusocial Insects'],
    'Exergy': ['Developed By Silverbridge Holdings', 'Energy', 'Exergy'],
    'Experiment': ['Experiments', 'Procedure Carried Out To Support'],
    'Explanation': [   'Explanations',
                       'Statements Usually Constructed To Describe A Facts'],
    'Extremophile': ['Extremophilic', 'Organism With Optimal'],
    'Fact': ['Facts'],
    'Fatty Acid': [   'Carboxylic Acid With A Long Aliphatic Chain',
                      'Fatty Acids'],
    'Flabellinia': ['Vannellina'],
    'Flowering Plant': ['About 14 Flowering Plants'],
    'Fluid': ['Fluids'],
    'Foam': ['Forming', 'Forms'],
    'Food': [   'Substance Consumed To Provide Nutritional Support For An '
                'Organism'],
    'Forbes': ['Forms'],
    'Force': ['Form'],
    'Fossil': ['Preserved Remains'],
    'Free Java Implementations': ['Open Source Java Implementation'],
    'Fructose': ['Simple Ketonic Monosaccharide'],
    'Fusion Power': [   'Process Allowing Nuclear Fusion To Take Place At '
                        'Temperatures Significantly Lower Than The '
                        'Temperatures Required For Thermonuclear Fusion'],
    'Fusion Protein': ['Chimera '],
    'Galaxy': ['Galaxies'],
    'Gamete': ['Male Gamete'],
    'Gas': ['Was'],
    'Gencode': ['Encodes'],
    'Gene': ['Genes', 'Genetics'],
    'Gene Structure': ['Specialised Sequence Elements'],
    'Genetics': ['Gene', 'Genes'],
    'Geological Period': ['Geologic Period'],
    'Geology': ['Earth Science Concerned With The Solid Earth', 'Geologic'],
    'Globular Protein': ['Globular Proteins', 'Spherical Proteins'],
    'Glucose': [   'Simple Sugar With The Molecular Formula C6H12O Glucose '
                   'Is_A Most Abundant Monosaccharide'],
    'Glycine': ['Glycines'],
    'Glycosidic Bond': [   'Sugar Formed When Two Monosaccharides Is_A Joined '
                           'By Glycosidic Linkage'],
    'Glycosylamine': ['Glycosylamines'],
    'Green Algae': ['Colonial Green Algae'],
    'Gs Alpha Subunit': ['Gαs'],
    'Guild': ['Artisans Or Merchants Who Oversee The', 'Building'],
    'Haematopoiesis': ['Blood Cellular Components', 'Hematopoiesis'],
    'Head Lice Infestation': ['Lice', 'Life', 'Lives'],
    'Helix': ['Shape Like A Corkscrew Or Spiral Staircase'],
    'Human': ['Humans'],
    'Humanism': ['Humans'],
    'Humanities': ['Humans'],
    'Hushing': ['Rush'],
    'Hydroxyl Radical': ['Hydroxyl'],
    'Hypothesis': ['Hypotheses', 'Proposed Explanation For A Phenomenon'],
    'Idea': ['Usually Taken As Mental Representational'],
    'Image': ['Images'],
    'Imide': ['Amide'],
    'Imine': [   'Amines',
                 'Functional Group Or Chemical Compound Containing A '
                 'Carbon–Nitrogen Double Bond',
                 'Imines'],
    'Immediate Constituent Analysis': [   'Sentence Analysis',
                                          'Smallest Constituent'],
    'Inductor': ['Inductors'],
    'Infection': ["An Organism'S Body Tissues By Disease-Causing Agents"],
    'Ingestion': ['A Substance By An Organism'],
    'Injury': ['Injuries'],
    'Inorganic Compound': ['Inorganic'],
    'Insect': ['Hexapod Invertebrates', 'Infection', 'Insects'],
    'Instrumentalism': ['Instrument'],
    'Instrumentation': ['Instrument', 'Instrumentation'],
    'Interaction': ['Interact', 'Interacting'],
    'Interdisciplinarity': ['Interdisciplinary Field'],
    'Interleukin 15': ['Il-15Rα', 'Rli-15'],
    'Interleukin 2': ['Interleukin-2'],
    'Interleukin-15 Receptor': ['Il-15 Receptor'],
    'Investigative Journalism': ['Investigative'],
    'Ion': ['Ions'],
    'Iron': ['Chemical Element With Symbol Fe', 'Ion', 'Ions'],
    'Irritability': ['Excitatory Ability', 'Irritation'],
    'Irritation': [   'Inflammation Or Painful Reaction To Allergy Or '
                      'Cell-Lining Damage',
                      'Irritants'],
    'Iso 6344': [   'International Standard Covering The',
                    'International Standard Covering The Materials Sizes'],
    'Iso 8601': ['Iso'],
    'Isobutyl Nitrite': ['Isobutyl'],
    'Isoelectric Focusing': [   'Electrofocusing',
                                'Technique For Separating Different Molecules '
                                'By'],
    'Isomer': [   'Ions Or Molecules With Identical Formulas But Distinct '
                  'Structures',
                  'Isomers'],
    'Jaligner': ['Alignment'],
    'Lame': ['Name'],
    'Lanthanide': ['Lanthanides'],
    'Large-Scale Brain Networks': [   'Large-Scale',
                                      'Widespread Brain Regions Showing '
                                      'Functional Connectivity By Statistical '
                                      'Analysis'],
    'Larva': [   'Distinct Juvenile Form Many Animals Undergo Before '
                 'Metamorphosis Into Adults',
                 'Larval'],
    'Lead': ['Leads'],
    'Lentil': ['Edible Legume', 'Lentils'],
    'Levacetylmethadol': ['Methadol', 'Methanol'],
    'Lewis Lung Carcinoma': ['Carcinoma Mouse Models'],
    'Life': ['Living'],
    'Lipid': ['Lipids'],
    'Lipid Bilayer': ['Lipid Layer'],
    'Liquid': ['Nearly Incompressible Fluid'],
    'List Of Extinct Plants': ['Extinct Plants', 'Extinct Plants Only'],
    'List Of Internet Phenomena': ['Phenomena'],
    'List Of Mail Server Software': ['Mail Server'],
    'List Of Protein Structure Prediction Software': [   'Prediction',
                                                         'Predictions',
                                                         'Summarizes Commonly'],
    'Liver': ['Living'],
    'Lobosa': ['Lobose'],
    'Love': ['Living'],
    'Lustre': ['Way Light Interacts With The'],
    'Lymphocyte': ['Lymphocyte', 'Lymphocytes'],
    'Lysis': ['Crude Lysate'],
    'Macromolecule': ['Macromolecules', 'Very Large Molecule'],
    'Mai Basic Four': ['Four Basic'],
    'Malignancy': [   'A Medical Condition To Become Progressively Worse',
                      'Malignant Cells'],
    'Mammal': ['Mammals', 'Vertebrate Animals Constituting The Class Mammalia'],
    'Maser': ['Laser'],
    'Materialism': ['Material'],
    'Measurement': ['Measure'],
    'Meat Glue': ['Protein Substance Analogous To The'],
    'Medal': ['Metal', 'Small Portable Artistic Object'],
    'Medical Device': ['Medical Devices'],
    'Membrane': ['Main Core Membrane', 'Selective Barrier'],
    'Memory T Cell': ['Memory Cd8 T Cell'],
    'Mental Disorder': ['Behavioral Or Mental Pattern', 'Mental Illness'],
    'Metabolic Pathway': ['Metabolic Pathways'],
    'Metabolism': ['Life-Sustaining Chemical', 'Metabolic'],
    'Metabolite': ['Intermediate End', 'Metabolites'],
    'Metal Ammine Complex': ['Amines', 'Ammine'],
    'Metallicity': ['Metal'],
    'Metastatic Breast Cancer': ['Anti-Metastatic'],
    'Methane': ['Mechanisms'],
    'Methanol': ['Ethanol'],
    'Methods In Enzymology': [   'Enzymology',
                                 'Scientific Publications Focused Primarily On '
                                 'Research'],
    'Microorganism': ['Microorganisms', 'Microscopic Organism'],
    'Microscopic Scale': ['Microscope', 'Microscopic'],
    'Microscopy': ['Microscope'],
    'Microtubule': ['Microtubules'],
    'Mining': ['Mineral'],
    'Mitochondrial Dna': ['Mitochondria', 'Mitochondrial'],
    'Mitosis': ['Vacuolaria'],
    'Mohism': ['Monism'],
    'Mold': ['Molds'],
    'Molecular Cloning': ['Cloned Cdna Fragments Inserted Into A Host Cells'],
    'Molecular Motor': [   'A Molecular Motors',
                           'Natural Or Artificial Molecular Machines'],
    'Molecule': ['For Molecules', 'Molecules'],
    'Monomer': ['Monomers'],
    'Monosaccharide': ['Monosaccharides'],
    'Motility': ['An Organism To Move Independently', 'Free-Swimming'],
    'Motor Protein': ['Cytoskeletal Motor Proteins'],
    'Mouse Model Of Colorectal And Intestinal Cancer': ['Mouse Model'],
    'Multicelluar Organism': ['Multicellular Eukaryotic Organisms'],
    'Multicellular Organism': ['Multicellular Eukaryotic Organisms'],
    'Muon-Catalyzed Fusion': ['Catalyze', 'Catalyzing'],
    'Mushroom': ['Mushrooms'],
    'National Institutes Of Technology': ['D Nits'],
    'Natural Philosophy': ['Natural Philosophy Proposing'],
    'Natural Science': ['Science Concerned With The Description'],
    'Naturism': ['Cultural Movement Practising', 'Nature'],
    'Nazi Human Experimentation': ['Experimentation'],
    'Neoplasm': ['Neoplasms'],
    'Neuroendocrine Tumor': ['Tumor'],
    "Newton'S Method In Optimization": ['Method In'],
    'Nitrate': ['Nitrite'],
    'Nitrogen': ['Nitrogen-Containing Biological Compounds'],
    'Non Coding Dna': ['Noncoding Dna'],
    'Nucleic Acid Sequence': [   'Deoxyribonucleic Acid Molecule With Part Or '
                                 'All',
                                 'Succession Of Base-Pairs'],
    'Nucleobase': ['Nucleobases'],
    'Nucleoside': ['Nucleosides', 'Nucleotides'],
    'Nucleotide': ['Nucleosides', 'Nucleotides'],
    'Nudist Paradise': ['Nudism', 'Nudist'],
    'Numb': [   'Song By American Rock Band Linkin Park',
                'Song By The American Rock Band Linkin Park'],
    'Nutrient': ['Essential Nutrients For The Human Body', 'Nutrients'],
    'Object-Oriented Programming': ['Object', 'Objects'],
    'Olfaction': ['Odorless'],
    'Opticks': ['Book By English Natural Philosopher Isaac Newton', 'Optics'],
    'Ore': ['Are'],
    'Organ': ['Organ Only', 'Tissues With Similar Functions'],
    'Organelle': [   'Eukaryotic Organelle',
                     'Membrane-Bound Organelle',
                     'Organelles',
                     'Specialized Subunit'],
    'Organic Compound': ['Generally Any Chemical Compounds'],
    'Organisation Todt': ['Organisation'],
    'Organism': ['Individual Entity', 'Organisms', 'Organization'],
    'Organization': ['Entity Comprising Multiple People', 'Organizing'],
    'Organometallic Chemistry': ['Organometallic Compounds'],
    'Oxidation State': ['Oxidation', 'Oxides'],
    'Oxide': ['Oxidation', 'Oxides'],
    'Oxidized Cellulose': ['Oxidation', 'Oxidized'],
    'Oxymetholone': ['Methabol', 'Methanol'],
    'Painkiller': [   'First-Person Shooter Video Game Developed By Polish '
                      'Game Studio People Can Fly',
                      'Painkiller'],
    'Parasitic Disease': [   'Infectious Disease Caused Or Transmitted By A '
                             'Parasite',
                             'Parasitic Diseases'],
    'Parasitic Twin': ['Parasitic'],
    'Parasitism': ['A Parasites'],
    'Parotitis': ['Part'],
    'Particle': ['Small Localized Object To'],
    'Pathogen': ['Pathogens', 'Small Infectious Agent'],
    'Patient Derived Xenograft': ['Mouse Tumor Models'],
    'Pea': ['Peas'],
    'Peptide': ['Peptides'],
    'Peptidomimetic': [   'Peptidomimetics',
                          'Small Protein-Like Chain Designed To Mimic A '
                          'Peptide'],
    'Peptoid': ['Peptide', 'Peptides'],
    'Percolozoa': ['Heterolobosea'],
    'Period 6 Element': [   'Chemical Element With The Symbol O Atomic Number '
                            'It Is_A Member'],
    'Periodic Table': ['Tabular Display'],
    'Periodization': ['Period'],
    'Peripheral Blood Lymphocyte': ['Peripheral Blood Lymphocytes'],
    'Personal Protective Equipment': ['Protective Response'],
    'Pfu Dna Polymerase': ["An Organism'S Dna"],
    'Pharmacodynamics': ['Pharmacodynamic'],
    'Pharmacy': ['Pharmaceutical Sciences'],
    'Phenomenalism': ['Phenomena'],
    'Phenotype': ['Phenotypes'],
    'Phosphoprotein': ['Phosphoproteins'],
    'Phosphorus Monoxide': [   'Chemical Ion Or Radical: P+O32− Containing '
                               'Phosphorus'],
    'Phosphoryl Group': ['A Phosphoryl Group'],
    'Photon': ['Proton'],
    'Phylogenetic Tree': [   'Branching Diagram Or Tree Showing The '
                             'Evolutionary Relationships Among Various '
                             'Biological Species Or Other Entities—Their '
                             'Phylogeny —Based Upon Similarities'],
    'Planet': [   'Astronomical Body Orbiting A Star Or Stellar Remnant',
                  'Planets'],
    'Planet Earth': ['Planet Earth'],
    'Plant': ['Mainly Multicellular', 'Planets', 'Plants'],
    'Plastid': ['Plastids'],
    'Ploidy': ['Haploid Cell'],
    'Poison': ['Poisonous Substance Produced'],
    'Polymer': ['Macromolecule', 'Polymeric Molecule'],
    'Polymerization': ['Reacting Monomer Molecules Together'],
    'Post-Transcriptional Modification': [   'Biological Processes Common To '
                                             'Most Eukaryotic Cells By',
                                             'Rna Processing In'],
    'Process Flow Diagram': ['Chemical Processes Within', 'Diagram Commonly'],
    'Processivity': [   "Enzyme'S Ability To Catalyze Consecutive Reactions "
                        'Without Releasing Its Substratefor Example',
                        'Processes'],
    'Profession': [   'Occupation Founded Upon Specialized Educational '
                      'Training',
                      'Process'],
    'Programmer': ['Program', 'Programming'],
    'Prokaryote': ['Prokaryotes'],
    'Prokaryotic Translation': ['Prokaryotes', 'Prokaryotic'],
    'Protein': ['Both Proteins', 'Proteins', 'Small 123 Amino Acid Protein'],
    'Protein Domain': ['Evolutionarily Conserved Protein Domain'],
    'Protein Engineering': [   'Developing Useful Or Valuable Proteins',
                               'Protein Engineering Technique'],
    'Protein Quaternary Structure': ['Multi-Subunit', 'Quaternary Structure'],
    'Proteinogenic Amino Acid': ['Ɑ-Amino Acid'],
    'Proteobacteria': ['Gram-Negative Proteobacteria'],
    'Proteome': ['Proteomics'],
    'Proteomics': ['D Proteome Balance'],
    'Proteopathy': ['Proteotoxicity'],
    'Proteus': ['Bacterium'],
    'Proton': ['Protons'],
    'Protonation': ['Proton', 'Protonated'],
    'Protozoa': ['Informal Term For Single-Celled Eukaryotes'],
    'Protozoan Infection': ['Protozoan', 'Protozoans'],
    'Pseudopodia': ['Pseudopod', 'Pseudopods', 'Temporary Arm-Like'],
    'Qmail': ['Mail'],
    'Quantitative Research': ['Quantitative Property', 'Systematic Empirical'],
    'Regulation Of Gene Expression': [   'Regulated Process During Gene '
                                         'Expression'],
    'Remote Patient Monitoring': ['Patient Monitoring'],
    'Reptation': ['Repeated'],
    'Residue': ['Residue '],
    'Resonant Converter': ['Resonance', 'Resonant'],
    'Reverse Transcription Polymerase Chain Reaction': [   'Laboratory '
                                                           'Technique '
                                                           'Combining Reverse',
                                                           'Reverse '
                                                           'Transcription'],
    'Ribonuclease': ['Ribonuclease A', 'Ribonucleases'],
    'Ribonucleoprotein Particle': [   'Complex Formed Between Rna',
                                      'Ribonucleoprotein'],
    'Rna': ['Dna', 'Rna Molecule'],
    'Roton': ['Proton'],
    'Rumen': ['Ruminants'],
    'Science And Technology': ['Systematic Enterprise'],
    'Scientific Method': ['Scientific'],
    'Seasonal Affective Disorder': [   'Affective',
                                       'Affects',
                                       'Mood Disorder Subset In'],
    'Seed': ['Embryonic Plant Enclosed'],
    'Serine': ['Series'],
    'Sex': ['Specialized Into Male'],
    'Sex Organ': ['System Of Sex Organs'],
    'Silurian': ['D Silurian Period'],
    'Society': ['Societies'],
    'Solution': ['Solute'],
    'Species': ['Major Taxonomic Group Containing About 400 Described'],
    'Spermatozoon': ['Spermatozoa'],
    'Standard Linear Solid Model': ['Solid Material'],
    'Standardization': ['Standard'],
    'Star': ['Stars'],
    'Steroid': [   'Biologically Active Organic Compound With Four Rings '
                   'Arranged'],
    'Steroid Hormone': ['Natural Or Synthetic Steroid Hormone'],
    'Structuralism': ['Basic Structural'],
    'Study': ['Evaluation'],
    'Sucrase': ['Sucrose'],
    'Sugar': ['Generic Name For Sweet-Tasting'],
    'Sugaring': ['Sugar', 'Sugaring'],
    'Sulfur Oxoacid': ['Oxoacid'],
    'Sushi Domain': ['Sushi+ Domain'],
    'Symbiosis': ['Symbiotic Relationship Between Species'],
    'Symbol': [   'Abbreviation For A Chemical Element',
                  'Chemical Element With The Symbol Au',
                  'Chemical Element With The Symbol N Atomic Number It Was '
                  'First Discovered',
                  'Symbols'],
    'System': ['Interacting Or Interrelated Entities', 'Systems'],
    'Technology': ['Technology To Enable'],
    'Temperature': ['Temperatures'],
    'Testate Amoebae': ['Amebae', 'Amoebae'],
    'The Catalyst': ['Catalyst', 'Catalysts'],
    'The Chemical Brothers': ['The Chemical'],
    'The Natural': ['Natural', 'Nature'],
    'The Offspring': ['Offspring'],
    'Thermal Oxidizer': [   'Oxides',
                            'Oxidizer',
                            'Process Unit For Air Pollution'],
    'Tide': ['Time'],
    'Tobymac': ['A Diverse'],
    'Toxicant': ['Toxicants', 'Toxin'],
    'Toxicity': ['Toxic', 'Toxicants', 'Toxin'],
    'Toxin': ['Toxins'],
    'Transaminase': ['Transaminases'],
    'Transduction': ['A Sensory Stimulus', 'Sensory Transduction'],
    'Transgender Hormone Therapy': ['Primary Male Sex Hormone'],
    'Transmission Electron Cryomicroscopy': ['Cryoelectron Microscopy'],
    'Troubleshooting': ['Troubleshoot'],
    'Unicellular Organism': ['Cell Or Unicellular Organism'],
    'United States Armed Forces': [   'An Armed Forces Or Uniformed Service '
                                      'Who Holds A Authority',
                                      'The Military Forces'],
    'University': ['Universe', 'Universities'],
    'Ustilaginomycetes': ['True Smut Fungi'],
    'Varisulca': ['Proposed Basal Podiate Taxon'],
    'Vascular Plant': ['Defined As Those Land Plants'],
    'Vertebra': ['Irregular Bone With A Complex Structure', 'Vertebrates'],
    'Vertebrate': ['Vertebrates'],
    'Very Important Person': [   'An Important',
                                 'Person Who Is_Accorded Special Privileges '
                                 'Due To Their Status Or Importance'],
    'Vicia': ['Vetches'],
    'Vinyl Alcohol': ['Ethanol', 'Ethenol', 'Simplest Enol'],
    'Virulence': [   "Pathogen'S Or Microbe'S Ability To Infect Or Damage A "
                     'Host',
                     'Virus'],
    'Virus': ['Viruses'],
    'Visual Phototransduction': ['Phototransduction'],
    'Vitrella Brassicaformis': ['Alveolates Isolated'],
    'Vorticella': ['Bell-Shaped Ciliates'],
    'Wasp': ['Wasps'],
    'Wavelength': ['Wavelengths'],
    'Wax': ['Way'],
    'Weak Entity': ['Individual Entity'],
    'White Blood Cell': ['By Cells To Increase Or Decrease The'],
    'Whole Genome Sequencing': ['Genome Sequencing'],
    'Xenoturbella': [   'Very Simple Bilaterians Up To A Few Centimeters Long',
                        'Xenoturbellid',
                        'Xenoturbellida',
                        'Xenoturbellids'],
    'Xenoturbellids': ['Any Economy', 'Informal'],
    'Yeast': ['Yeasts'],
    'Yellow-Green Algae': ['Heterokontae', 'Heterokonts', 'Vaucheriales'],
    'Zosterophyll': ['Zosterophyllopsida']}
