#!/usr/bin/env python
# -*- coding: UTF-8 -*-


import codecs


def main():
    from cendalytics.wikipedia.etl.svc import CreateCendantEntity

    terms = [
        # 'ATP synthase',
        # 'Acetone–butanol–ethanol fermentation',
        # 'Acid',
        # 'Actin',
        # 'Active site',
        # 'Adaptive immune system',
        # 'Adenine',
        # 'Adenosine triphosphate',
        # 'Adenylate kinase',
        # 'Aerobic respiration',
        # 'Alanine',
        # 'Albumin',
        # 'Alpha carbon',
        # 'Alpha helix',
        # 'Alternative splicing',
        # 'Amino',
        # 'Amino acid',
        # 'Amino acid synthesis',
        # 'Amino acids',
        # 'Aminoacyl tRNA synthetase',
        # 'Anabolism',
        # 'Anaerobic respiration',
        # 'Angiogenin',
        # 'Animal shell',
        # 'Anoxygenic photosynthesis',
        # 'Antibodies',
        # 'Antibody',
        # 'Anticodon',
        # 'Antigen',
        # 'Archaea',
        # 'Aspartate',
        # 'Aspartokinase',
        # 'Assay',
        # 'Atom',
        # 'Atomic mass unit',
        # 'B cell',
        # 'Bacteria',
        # 'Bacterial display',
        # 'Bacterial transcription',
        # 'Base pair',
        # 'Beta oxidation',
        # 'Beta sheet',
        # 'Bibcode',
        # 'Binding site',
        # 'Biochemistry',
        # 'Bioenergetics',
        # 'Bioinformatics',
        # 'Bioinorganic chemistry',
        # 'Biological tissue',
        # 'Biomolecule',
        # 'Blood',
        # 'Bradford protein assay',
        # 'C-terminus',
        # 'CHON',
        # 'Carbohydrate',
        # 'Carbohydrate catabolism',
        # 'Carbohydrate metabolism',
        # 'Carbon fixation',
        # 'Carboxyl',
        # 'Carl von Voit',
        # 'Cartesian coordinates',
        # 'Cartilage',
        # 'Catabolism',
        # 'Catalysis',
        # 'Cell (biology)',
        # 'Cell adhesion',
        # 'Cell biology',
        # 'Cell cycle',
        # 'Cell membrane',
        # 'Cell nucleus',
        # 'Cell signaling',
        # 'Cellular compartment',
        # 'Central dogma of molecular biology',
        # 'Chaperone (protein)',
        # 'Chemical bond',
        # 'Chemical conformation',
        # 'Chemical ligation',
        # 'Chemical polarity',
        # 'Chemosynthesis',
        # 'Chimera (protein)',
        # 'Chirality (chemistry)',
        # 'Cholera',
        # 'Chromatin immunoprecipitation',
        # 'Chromatography',
        # 'Circular dichroism',
        # 'Cis-regulatory element',
        # 'Citric acid cycle',
        # 'ClustalW',
        # 'Coagulate',
        # 'Codon',
        # 'Cofactor (biochemistry)',
        # 'Collagen',
        # 'Colloid',
        # 'Conformational change',
        # 'Connecticut Agricultural Experiment Station',
        # 'Connective tissue',
        # 'Coplanar',
        # 'Crude lysate',
        # 'Cryo-electron microscopy',
        # 'Cryoelectron microscopy',
        # 'Crystallize',
        # 'Cyclol',
        # 'Cytolysis',
        # 'Cytoplasm',
        # 'Cytoskeleton',
        # 'DNA',
        # 'DNA-binding protein',
        # 'DNA repair',
        # 'DNA replication',
        # 'DNA sequence',
        # 'Dehydration',
        # 'Dehydron',
        # 'Denaturation (biochemistry)',
        # 'Deproteination',
        # 'Diet (nutrition)',
        # 'Diffraction-limited system',
        # 'Diffusion',
        # 'Digestion',
        # 'Digital object identifier',
        # 'Dihedral angle',
        # 'Dirigent protein',
        # 'Dissociation constant',
        # 'Distance geometry',
        # 'Distributed computing',
        # 'Disulfide bond',
        # 'Docking (molecular)',
        # 'Double-bond',
        # 'Downregulation and upregulation',
        # 'Drug design',
        # 'Dual-polarization interferometry',
        # 'Dual polarisation interferometry',
        # 'Dynein',
        # 'Edestin',
        # 'Eicosanoid metabolism',
        # 'Elastin',
        # 'Electrofocusing',
        # 'Electron crystallography',
        # 'Electron microscope',
        # 'Electron transport chain',
        # 'Electrophoresis',
        # 'Elemental analysis',
        # 'Empirical formula',
        # 'Endoplasmic reticulum',
        # 'Enzyme',
        # 'Enzyme assay',
        # 'Enzyme catalysis',
        # 'Enzyme kinetics',
        # 'Epigenetics',
        # 'Escherichia coli',
        # 'Essential amino acid',
        # 'Essential amino acids',
        # 'Essential fatty acid',
        # 'Ethanol fermentation',
        # 'Ethanol metabolism',
        # 'Eukaryote',
        # 'Eukaryotic Linear Motif resource',
        # 'Eukaryotic transcription',
        # 'Eukaryotic translation',
        # 'Evolution',
        # 'Experiment',
        # 'Fatty acid degradation',
        # 'Fatty acid metabolism',
        # 'Fatty acid synthesis',
        # 'Feather',
        # 'Fermentation',
        # 'Fibrin',
        # 'Fibrous protein',
        # 'Five-prime cap',
        # 'Flavor',
        # 'Flocculation',
        # 'Fluorescent',
        # 'Folding@home',
        # 'Food additive',
        # 'Food chemistry',
        # 'Food coloring',
        # 'Food fortification',
        # 'Fructolysis',
        # 'Fusion protein',
        # 'Galactolysis',
        # 'Gel electrophoresis',
        # 'Gel electrophoresis of proteins',
        # 'Gene',
        # 'Gene expression',
        # 'Gene ontology',
        # 'Gene regulatory network',
        # 'Genes',
        # 'Genetic code',
        # 'Genetic engineering',
        # 'Genome',
        # 'Genomic imprinting',
        # 'Genomics',
        # 'Gerardus Johannes Mulder',
        # 'Globular protein',
        # 'Globular proteins',
        # 'Globulin',
        # 'Gluconeogenesis',
        # 'Glucose',
        # 'Glutamic acid',
        # 'Glutamine synthetase',
        # 'Gluten',
        # 'Glycogenesis',
        # 'Glycogenolysis',
        # 'Glycolysis',
        # 'Glycosylation',
        # 'Graphics processing unit',
        # 'Greek language',
        # 'Green fluorescent protein',
        # 'Guanine',
        # 'HIV',
        # 'HOPES',
        # 'Haemoglobin',
        # 'Hair',
        # 'Half-life',
        # 'Heme',
        # 'Heme group',
        # 'Hemoglobin',
        # 'Hermann Emil Fischer',
        # 'Hexokinase',
        # 'His-tag',
        # 'Histidine',
        # 'Histone acetylation and deacetylation',
        # 'History of molecular biology',
        # 'Homology modeling',
        # 'Hoof',
        # 'Hormone',
        # 'Human',
        # 'Human genome',
        # 'Human iron metabolism',
        # 'Hydrogen bond',
        # 'Hydrogen bonding',
        # 'Hydrolysis',
        # 'Hydrophobic',
        # 'Hydrophobic core',
        # 'Immunoelectron microscopy',
        # 'Immunoglobulin G',
        # 'Immunohistochemistry',
        # 'Immunoprecipitation',
        # 'Immunostaining',
        # 'In-gel digestion',
        # 'In silico',
        # 'In vitro',
        # 'In vivo',
        # 'Indirect immunofluorescence',
        # 'Insulin',
        # 'Integrated Authority File',
        # 'Intein',
        # 'Interactome',
        # 'Intracellular transport',
        # 'Intrinsically disordered proteins',
        # 'Introduction to genetics',
        # 'Ion channel',
        # 'Isoelectric point',
        # 'Isoleucine',
        # 'Isopycnic centrifugation',
        # 'Isothermal titration calorimetry',
        # 'Keratin',
        # 'Ketosis',
        # 'Kinase',
        # 'Kinesin',
        # 'Kingdom (biology)',
        # 'Laboratory rat',
        # 'Lac operon',
        # 'Lactic acid fermentation',
        # 'Lafayette Mendel',
        # 'Lectins',
        # 'Leucine',
        # 'Ligand',
        # 'Linus Pauling',
        # 'Lipid',
        # 'Lipid metabolism',
        # 'Lipogenesis',
        # 'Lipolysis',
        # 'Lung',
        # 'Lymphoblastoid',
        # 'Lysine',
        # 'MRNA display',
        # 'Macromolecular Assembly',
        # 'Macromolecular docking',
        # 'Macromolecule',
        # 'Mass spectrometry',
        # 'Mathematical model',
        # 'Max Perutz',
        # 'Membrane protein',
        # 'Messenger RNA',
        # 'Metabolic network',
        # 'Metabolic pathway',
        # 'Metabolism',
        # 'Methionine',
        # 'MicroRNA',
        # 'Microorganism',
        # 'Microscale thermophoresis',
        # 'Microscopy',
        # 'Mineral (nutrient)',
        # 'Molecular dynamics',
        # 'Molecular mass',
        # 'Molecular mechanics',
        # 'Molecular modeling on GPU',
        # 'Molecular recognition',
        # 'Monte Carlo method',
        # 'Motility',
        # 'Motor protein',
        # 'Muscle',
        # 'Mycoplasma',
        # 'Myoglobin',
        # 'Myosin',
        # 'N-linked glycosylation',
        # 'N-terminus',
        # 'Nail (anatomy)',
        # 'National Diet Library',
        # 'Native conformation',
        # 'Nickel',
        # 'Nuclear magnetic resonance',
        # 'Nuclear magnetic resonance spectroscopy of proteins',
        # 'Nuclear membrane',
        # 'Nucleic acid',
        # 'Nucleic acid metabolism',
        # 'Nucleoid',
        # 'Nucleotide',
        # 'Nucleotide salvage',
        # 'Nucleotide sequence',
        # 'O-linked glycosylation',
        # 'Oligomer',
        # 'Oligopeptide',
        # 'Onconase',
        # 'Open reading frame',
        # 'Optical microscope',
        # 'Organelle',
        # 'Organic synthesis',
        # 'Organism',
        # 'Orotate decarboxylase',
        # 'Oxidative phosphorylation',
        # 'Oxygen',
        # 'P-bodies',
        # 'Pentose phosphate pathway',
        # 'Peptide',
        # 'Peptide bond',
        # 'Peptide mass fingerprinting',
        # 'Peptide sequence',
        # 'Peptide synthesis',
        # 'Phage display',
        # 'Phosphorylation',
        # 'Photoactivated localization microscopy',
        # 'Photosynthesis',
        # 'Phylogenetic tree',
        # 'Plasma cell',
        # 'Polyadenylation',
        # 'Polyamide',
        # 'Polymer',
        # 'Polypeptide',
        # 'Polysaccharide',
        # 'Post-transcriptional modification',
        # 'Post-transcriptional regulation',
        # 'Post-translational modification',
        # 'Post-translational regulation',
        # 'Posttranslational modification',
        # 'Potassium',
        # 'Precipitation (chemistry)',
        # 'Precursor mRNA',
        # 'Primary nutritional groups',
        # 'Primary structure',
        # 'Prion',
        # 'Prokaryote',
        # 'Prokaryotic translation',
        # 'Proline',
        # 'Promoter (genetics)',
        # 'Prosthetic group',
        # 'Protease',
        # 'Proteasome',
        # 'Protein (disambiguation)',
        # 'Protein (nutrient)',
        # 'Protein Data Bank',
        # 'Protein NMR',
        # 'Protein biosynthesis',
        # 'Protein catabolism',
        # 'Protein complex',
        # 'Protein conformation',
        # 'Protein design',
        # 'Protein domain',
        # 'Protein engineering',
        # 'Protein folding',
        # 'Protein mass spectrometry',
        # 'Protein metabolism',
        # 'Protein methods',
        # 'Protein microarray',
        # 'Protein purification',
        # 'Protein quality',
        # 'Protein quinary structure',
        # 'Protein sequencing',
        # 'Protein structure',
        # 'Protein structure prediction',
        # 'Protein subunit',
        # 'Protein superfamily',
        # 'Protein targeting',
        # 'Protein translocation',
        # 'Protein turnover',
        # 'Proteinogenic amino acid',
        # 'Proteins',
        # 'Protein–DNA interaction',
        # 'Protein–carbohydrate interaction',
        # 'Protein–lipid interaction',
        # 'Protein–protein interaction',
        # 'Protein–protein interaction prediction',
        # 'Proteolysis',
        # 'Proteome',
        # 'Proteomics',
        # 'Proteopathy',
        # 'Proteopedia',
        # 'PubMed Central',
        # 'PubMed Identifier',
        # 'Purine metabolism',
        # 'Pyrimidine metabolism',
        # 'Pyrrolysine',
        # 'Pyruvate dehydrogenase',
        # 'Quantum mechanics',
        # 'Quaternary structure',
        # 'RNA',
        # 'RNA-dependent RNA polymerase',
        # 'RNA polymerase',
        # 'RNA splicing',
        # 'Radiotrophic fungus',
        # 'Reaction mechanism',
        # 'Receptor (biochemistry)',
        # 'Regulation of gene expression',
        # 'Reporter gene',
        # 'Residue (biochemistry)',
        # 'Resonance (chemistry)',
        # 'Restriction enzyme',
        # 'Reverse cholesterol transport',
        # 'Reverse transcription',
        # 'Rhodopsin',
        # 'Ribbon diagram',
        # 'Ribonuclease A',
        # 'Ribonuclease inhibitor',
        # 'Ribosome',
        # 'Ribosome-nascent chain complex',
        # 'Ribosome display',
        # 'SH3 domain',
        # 'Saccharomyces cerevisiae',
        # 'Salt bridge (protein)',
        # 'Salting out',
        # 'Sarcomere',
        # 'Scaffolding',
        # 'Scleroprotein',
        # 'Secondary structure',
        # 'Secrete',
        # 'Secretion assay',
        # 'Selenocysteine',
        # 'Semipermeable membrane',
        # 'Sequence alignment',
        # 'Sequence homology',
        # 'Sequence profiling tool',
        # 'Sequence space (evolution)',
        # 'Serum albumin',
        # 'Sexual reproduction',
        # 'Side chain',
        # 'Signal transduction',
        # 'Site-directed mutagenesis',
        # 'Slaughterhouse',
        # 'Small molecule',
        # 'Sodium',
        # 'Soluble',
        # 'Spectroscopy',
        # 'Spermatozoon',
        # 'Sphingolipid metabolism',
        # 'Spirochaete',
        # 'Staphylococcus aureus',
        # 'Starvation',
        # 'Stereochemistry',
        # 'Steroid',
        # 'Structural alignment',
        # 'Structural domain',
        # 'Structural genomics',
        # 'Substrate-level phosphorylation',
        # 'Substrate (biochemistry)',
        # 'Super-resolution microscopy',
        # 'Surface plasmon resonance',
        # 'Tertiary structure',
        # 'Threonine',
        # 'Titin',
        # 'Toxin',
        # 'Transcription (biology)',
        # 'Transcription (genetics)',
        # 'Transcription factor',
        # 'Transcriptional regulation',
        # 'Transfer RNA',
        # 'Translation (biology)',
        # 'Translation (genetics)',
        # 'Translational regulation',
        # 'Transmembrane protein',
        # 'Triose phosphate isomerase',
        # 'Tubulin',
        # 'Turn (biochemistry)',
        # 'Two-dimensional gel electrophoresis',
        # 'Two-hybrid screening',
        # 'Ultracentrifugation',
        # 'Uracil',
        # 'Urea cycle',
        # 'Urease',
        # 'Valine',
        # 'Vertebrate',
        # 'Vertico spatially modulated illumination',
        # 'Villin',
        # 'Virus',
        # 'Viruses',
        # 'Vitamin',
        # 'X-ray crystallography',
        # 'Xylose metabolism',
        # 'Yeast',
        # 'Yeast display'
        "Pancreatitis",
    ]

    d_master = {}
    for term in terms:
        try:
            d_results = CreateCendantEntity(is_debug=True,
                                            invalidate_cache=False).process(term)

            for k in d_results:
                if k not in d_master:
                    d_master[k] = []
                d_master[k].append(d_results[k])


        except KeyError as e:
            print(e)
            continue
        except TypeError as e:
            print(e)
            continue
        except Exception as e:
            print(e)
            print(f"Failed on Term: {term}")
            raise ValueError

    target = codecs.open("/Users/craig.trimibm.com/Desktop/cendant-results.txt",
                         encoding="utf-8", mode="a")
    for k in d_master:
        for item in d_master[k]:
            target.write(item)
            target.write('\n\n')
        target.write('\n\n')
        target.write('\n\n')

    target.close()


if __name__ == "__main__":
    main()
