
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_certifications_dict = {
    'AIX Certification': 'IBM',
    'AIX Certified Associate': 'IBM',
    'AIX Certified System Administrator': 'IBM',
    'ASV Certification': 'PCI',
    'AWS Certification': 'Amazon',
    'AWS Certified Advanced Networking': 'Amazon',
    'AWS Certified Alexa Skill Builder': 'Amazon',
    'AWS Certified Big Data': 'Amazon',
    'AWS Certified Cloud Practitioner': 'Amazon',
    'AWS Certified DevOps Engineer': 'Amazon',
    'AWS Certified Developer': 'Amazon',
    'AWS Certified Machine Learning': 'Amazon',
    'AWS Certified Security': 'Amazon',
    'AWS Certified Solutions Architect': 'Amazon',
    'AWS Certified SysOps Administrator': 'Amazon',
    'Aliababa Certification': 'Alibaba',
    'Alibaba Big Data Associate': 'Alibaba',
    'Alibaba Big Data Certification': 'Alibaba',
    'Alibaba Big Data Expert': 'Alibaba',
    'Alibaba Big Data Professional': 'Alibaba',
    'Alibaba Cloud Certification Associate': 'Alibaba',
    'Alibaba Cloud Certification Expert': 'Alibaba',
    'Alibaba Cloud Certification Professional': 'Alibaba',
    'Alibaba Cloud Computing Associate': 'Alibaba',
    'Alibaba Cloud Computing Certification': 'Alibaba',
    'Alibaba Cloud Computing Expert': 'Alibaba',
    'Alibaba Cloud Computing Professional': 'Alibaba',
    'Alibaba Cloud Security Associate': 'Alibaba',
    'Alibaba Cloud Security Expert': 'Alibaba',
    'Alibaba Cloud Security Professional': 'Alibaba',
    'Alibaba Security Certification': 'Alibaba',
    'Azure AI Engineer Associate': 'Microsoft',
    'Azure Administrator Associate': 'Microsoft',
    'Azure Certification': 'Microsoft',
    'Azure Data Engineer Associate': 'Microsoft',
    'Azure Data Scientist Associate': 'Microsoft',
    'Azure DevOps Engineer Expert': 'Microsoft',
    'Azure Developer Associate': 'Microsoft',
    'Azure Security Engineer Associate': 'Microsoft',
    'Azure Solutions Architect Expert': 'Microsoft',
    'Base Programming Credentials': 'SAS',
    'CAP Certification': 'ISC',
    'CCDA': 'Cisco',
    'CCDE': 'Cisco',
    'CCDP': 'Cisco',
    'CCENT': 'Cisco',
    'CCIE Collaboration Certification': 'Cisco',
    'CCIE Data Center': 'Cisco',
    'CCIE Routing and Switching': 'Cisco',
    'CCIE Security': 'Cisco',
    'CCIE Service Provider': 'Cisco',
    'CCIE Wireless': 'Cisco',
    'CCNA Cloud Certification': 'Cisco',
    'CCNA Collaboration Certification': 'Cisco',
    'CCNA Cyber Ops': 'Cisco',
    'CCNA Data Center Certification': 'Cisco',
    'CCNA Industrial': 'Cisco',
    'CCNA Routing and Switching': 'Cisco',
    'CCNA Security': 'Cisco',
    'CCNA Service Provider': 'Cisco',
    'CCNA Wireless': 'Cisco',
    'CCNP Cloud Certification': 'Cisco',
    'CCNP Collaboration Certification': 'Cisco',
    'CCNP Data Center': 'Cisco',
    'CCNP Routing and Switching': 'Cisco',
    'CCNP Security': 'Cisco',
    'CCNP Service Provider': 'Cisco',
    'CCNP Wireless': 'Cisco',
    'CCSK Certification': 'Cloud Security Alliance',
    'CCSP Certification': 'ISC',
    'CCT Data Center': 'Cisco',
    'CCT Routing & Switching': 'Cisco',
    'CGEIT Certification': 'ISACA',
    'CISA Certification': 'ISACA',
    'CISM Certification': 'ISACA',
    'CISSP Certification': 'ISC',
    'CRISC Certification': 'ISACA',
    'CSA Certification': 'Cloud Security Alliance',
    'CSSA Certification': 'infosec',
    'CSSLP Certification': 'ISC',
    'Certified Desktop Administrator': 'Microsoft',
    'Certified Enterprise Administrator': 'Microsoft',
    'Certified Messaging Administrator': 'Microsoft',
    'Certified Microsoft Access': 'Microsoft',
    'Certified Microsoft Excel': 'Microsoft',
    'Certified Microsoft Office': 'Microsoft',
    'Certified Microsoft Outlook': 'Microsoft',
    'Certified Microsoft PowerPoint': 'Microsoft',
    'Certified Microsoft Word': 'Microsoft',
    'Certified Security Administrator': 'Microsoft',
    'Certified Teamwork Administrator': 'Microsoft',
    'Certified Windows Server 2012': 'Microsoft',
    'Certified Windows Server 2016': 'Microsoft',
    'Cisco Business Architecture Analyst': 'Cisco',
    'Cisco Business Architecture Practitioner': 'Cisco',
    'Cisco Business Architecture Specialist': 'Cisco',
    'Cisco Business Certification': 'Cisco',
    'Cisco Certification': 'Cisco',
    'Cisco Certified Design': 'Cisco',
    'Cisco Certified Design Associate': 'Cisco',
    'Cisco Certified Design Expert': 'Cisco',
    'Cisco Certified Design Professional': 'Cisco',
    'Cisco Certified Internetwork Expert Routing and Switching': 'Cisco',
    'Cisco Certified Network Professional': 'Cisco',
    'Cisco Certified Technican Routing and Switching': 'Cisco',
    'Cisco Cloud Certification': 'Cisco',
    'Cisco Collaboration Certification': 'Cisco',
    'Cisco Cyber Security Specialist': 'Cisco',
    'Cisco Data Center Certification': 'Cisco',
    'Cisco Design Track': 'Cisco',
    'Cisco Industrial Certification': 'Cisco',
    'Cisco Industrial Networking Specialist': 'Cisco',
    'Cisco Network Programmability Design and Implementation Specialist': 'Cisco',
    'Cisco Network Programmability Developer Specialist': 'Cisco',
    'Cisco Routing Certification': 'Cisco',
    'Cisco Routing and Switching Certification': 'Cisco',
    'Cisco Security Certification': 'Cisco',
    'Cisco Service Provider Certification': 'Cisco',
    'Cisco Service Provider Mobility CDMA to LTE Specialist': 'Cisco',
    'Cisco Service Provider Mobility UMTS to LTE Specialist': 'Cisco',
    'Cisco TelePresence Solutions Specialist': 'Cisco',
    'Cisco Unified Contact Center Enterprise Specialist': 'Cisco',
    'Cisco Video Network Specialist': 'Cisco',
    'Cisco Wireless Certification': 'Cisco',
    'Cisco and NetApp FlexPod Design Specialist': 'Cisco',
    'Cisco and NetApp FlexPod Implementation and Administration Specialist': 'Cisco',
    'Citrix Certification': 'Citrix',
    'Citrix Certified Administrator': 'Citrix',
    'Citrix Certified Mobility Professional': 'Citrix',
    'Citrix Certified Networking Associate': 'Citrix',
    'Citrix Certified Networking Expert': 'Citrix',
    'Citrix Certified Networking Professional': 'Citrix',
    'Citrix Certified Virtualization Associate': 'Citrix',
    'Citrix Certified Virtualization Expert': 'Citrix',
    'Citrix Certified Virtualization Professional': 'Citrix',
    'Citrix Cloud Certification': 'Citrix',
    'Citrix Endpoint Management Certified': 'Citrix',
    'Citrix Microsoft Azure Certified': 'Citrix',
    'Citrix Netscaler Certification': 'Citrix',
    'Citrix Networking Certification': 'Citrix',
    'Citrix Sharefile Certified': 'Citrix',
    'Citrix Virtualization Certification': 'Citrix',
    'Citrix XenServer Certified': 'Citrix',
    'Cloudera Administrator Certification': 'Cloudera',
    'Cloudera Certification': 'Cloudera',
    'Cloudera Certified Associate': 'Cloudera',
    'Cloudera Certified Data Engineer': 'Cloudera',
    'Cloudera Certified Professional': 'Cloudera',
    'Cloudera Data Analyst Certification': 'Cloudera',
    'Cloudera Spark and Hadoop Certification': 'Cloudera',
    'DB2 Certified Database Administrator': 'IBM',
    'DB2 Certified Database Associate': 'IBM',
    'Data Engineering with Azure': 'Microsoft',
    'Dell Certification': 'Dell',
    'Dell Cloud Certification': 'Dell',
    'Dell Converged Infrastructure Certification': 'Dell',
    'Dell Data Protection Certification': 'Dell',
    'Dell Data Science Certifictation': 'Dell',
    'Dell Enterprise Architect Certification': 'Dell',
    'Dell Networking Certification': 'Dell',
    'Dell Security Certification': 'Dell',
    'Dell Server Certification': 'Dell',
    'Dell Storage Certification': 'Dell',
    'Dynamics 365': 'Microsoft',
    'Dynamics 365 Fundamentals': 'Microsoft',
    'Dynamics 365 for Customer Service': 'Microsoft',
    'Dynamics 365 for Field Service': 'Microsoft',
    'Dynamics 365 for Finance and Operations': 'Microsoft',
    'Dynamics 365 for Marketing': 'Microsoft',
    'Dynamics 365 for Operations': 'Microsoft',
    'Dynamics 365 for Sales': 'Microsoft',
    'GASF Certification': 'GIAC',
    'GAWN Certification': 'GIAC',
    'GCCC Certification': 'GIAC',
    'GCDA Certification': 'GIAC',
    'GCED Certification': 'GIAC',
    'GCFA Certification': 'GIAC',
    'GCFE Certification': 'GIAC',
    'GCIA Certification': 'GIAC',
    'GCIH Certification': 'GIAC',
    'GCIP Certification': 'GIAC',
    'GCPM Certification': 'GIAC',
    'GCTI Certification': 'GIAC',
    'GCUX Certification': 'GIAC',
    'GCWN Certification': 'GIAC',
    'GDAT Certification': 'GIAC',
    'GDSA Certification': 'GIAC',
    'GEVA Certification': 'GIAC',
    'GIAC Certification': 'GIAC',
    'GISCP Certification': 'GIAC',
    'GISF Certification': 'GIAC',
    'GISP Certification': 'GIAC',
    'GLEG Certification': 'GIAC',
    'GMOB Certification': 'GIAC',
    'GMON Certification': 'GIAC',
    'GNFA Certification': 'GIAC',
    'GPEN Certification': 'GIAC',
    'GPPA Certification': 'GIAC',
    'GPYC Certification': 'GIAC',
    'GREM Certification': 'GIAC',
    'GRID Certification': 'GIAC',
    'GSE Certification': 'GIAC',
    'GSEC Certification': 'GIAC',
    'GSLC Certification': 'GIAC',
    'GSNA Certification': 'GIAC',
    'GSSP Certification': 'GIAC',
    'GSTRT Certification': 'GIAC',
    'GWAPT Certification': 'GIAC',
    'GWEB Certification': 'GIAC',
    'GXPN Certification': 'GIAC',
    'Google Ads Certification': 'Google',
    'Google Ads Display Certification': 'Google',
    'Google Ads Search Certification': 'Google',
    'Google Ads Video Certification': 'Google',
    'Google Certification': 'Google',
    'Google Certified Android Developer': 'Google',
    'Google Certified Associate Cloud Engineer': 'Google',
    'Google Certified Mobile Web Specialist': 'Google',
    'Google Certified Professional Cloud Architect': 'Google',
    'Google Certified Professional Data Engineer': 'Google',
    'Google Cloud Certification': 'Google',
    'Google Developers Certification': 'Google',
    'HCISPP Certification': 'ISC',
    'Hortonworks Certification': 'Hortonworks',
    'Hortonworks Certified Administrator': 'Cloudera',
    'Hortonworks Certified Developer': 'Cloudera',
    'Hortonworks Certified Professional': 'Hortonworks',
    'Hortonworks Spark Certification': 'Cloudera',
    'IBM Certification': 'IBM',
    'IBM Q Associate Ambassador': 'IBM',
    'IBM Q Certification': 'IBM',
    'IBM Q Intermediate Ambassador': 'IBM',
    'IBM Q Senior Ambassador': 'IBM',
    'IOS XR Specialist': 'Cisco',
    'ISA Certification': 'PCI',
    'ISACA Certification': 'ISACA',
    'ISC Certification': 'ISC',
    'ISMS Certification': 'ISMS',
    'ISMS Internal Auditor Certification': 'ISMS',
    'ISMS Lead Auditor Certification': 'ISMS',
    'ISMS Lead Implementer Certification': 'ISMS',
    'ITIL Certification': 'Axelos',
    'ITIL Foundation Certification': 'Axelos',
    'ITIL Service Design Certification': 'Axelos',
    'ITIL Service Management Certification': 'Axelos',
    'Infosec Certification': 'infosec',
    'JD Edwards Certification': 'Oracle',
    'JD Edwards EnterpriseOne Configurable Network Computing 9.2 Implementation Essentials': 'Oracle',
    'JD Edwards EnterpriseOne Distribution 9.2 Implementation Essentials': 'Oracle',
    'JD Edwards EnterpriseOne Financial Management 9.2 Implementation Essentials': 'Oracle',
    'JMP Certification': 'SAS',
    'JMP Design and Analysis of Experiments Using JMP 14': 'SAS',
    'JMP Scripting Using JMP 14': 'SAS',
    'JMP Statistical Thinking for Industrial Problem Solving': 'SAS',
    'Java Certification': 'Oracle',
    'Java EE 6 Enterprise Architect Certified Master': 'Oracle',
    'Java EE 7 Application Developer': 'Oracle',
    'Java Foundations': 'Oracle',
    'Java SE 11 Programmer I': 'Oracle',
    'Java SE 11 Programmer II': 'Oracle',
    'Java SE 7/8 Bronze - Japan Only Exam': 'Oracle',
    'Java SE 8 Programmer I': 'Oracle',
    'Java SE 8 Programmer II': 'Oracle',
    'Juniper Certification': 'Juniper Networks',
    'Juniper Networks Certified Design Specialist': 'Juniper Networks',
    'Juniper Networks Certified Internet Associate': 'Juniper Networks',
    'Juniper Networks Certified Professional': 'Juniper Networks',
    'Juniper Networks Technical Certification': 'Juniper Networks',
    'Level 1 Certification': 'IBM',
    'Level 2 Certification': 'IBM',
    'Level 3 Certification': 'IBM',
    'MCDBA Certification': 'Microsoft',
    'MCSA Certification': 'Microsoft',
    'MCSD Certification': 'Microsoft',
    'MCSE Certification': 'Microsoft',
    'MCTS Certification': 'Microsoft',
    'MOS Certification': 'Microsoft',
    'MTA Certification': 'Microsoft',
    'Microsoft 365 Certification': 'Microsoft',
    'Microsoft App Builder': 'Microsoft',
    'Microsoft Business Applications': 'Microsoft',
    'Microsoft Certification': 'Microsoft',
    'Microsoft Certified BI Development': 'Microsoft',
    'Microsoft Certified BI Reporting': 'Microsoft',
    'Microsoft Certified BlockBased Languages': 'Microsoft',
    'Microsoft Certified Cloud Fundamentals': 'Microsoft',
    'Microsoft Certified Database Administration': 'Microsoft',
    'Microsoft Certified Database Development': 'Microsoft',
    'Microsoft Certified Database Fundamentals': 'Microsoft',
    'Microsoft Certified Development Fundamentals': 'Microsoft',
    'Microsoft Certified HTML and CSS': 'Microsoft',
    'Microsoft Certified HTML5': 'Microsoft',
    'Microsoft Certified Java Programmer': 'Microsoft',
    'Microsoft Certified Javascript Programmer': 'Microsoft',
    'Microsoft Certified Mobility Fundamentals': 'Microsoft',
    'Microsoft Certified Networking Fundamentals': 'Microsoft',
    'Microsoft Certified Productivity': 'Microsoft',
    'Microsoft Certified Professional': 'Microsoft',
    'Microsoft Certified Python Programmer': 'Microsoft',
    'Microsoft Certified SQL Server': 'Microsoft',
    'Microsoft Certified Security Fundamentals': 'Microsoft',
    'Microsoft Certified Web Applications': 'Microsoft',
    'Microsoft Certified Windows Fundamentals': 'Microsoft',
    'Microsoft Certified Windows Server Fundamentals': 'Microsoft',
    'Microsoft Core Infrastructure': 'Microsoft',
    'Microsoft Data Management and Analytics': 'Microsoft',
    'Oracle Access Management Suite Plus 11g Essentials': 'Oracle',
    'Oracle Advanced Controls Applications 2014 Essentials': 'Oracle',
    'Oracle Application Certification': 'Oracle',
    'Oracle Application Development Framework 12c Essentials': 'Oracle',
    'Oracle Application Grid 11g Essentials': 'Oracle',
    'Oracle Application Integration Architecture 11g Essentials': 'Oracle',
    'Oracle Architect Certification': 'Oracle',
    'Oracle Business Intelligence': 'Oracle',
    'Oracle Business Intelligence (Obi) Foundation Suite 11G Essentials': 'Oracle',
    'Oracle Business Process Management Suite 12c Essentials': 'Oracle',
    'Oracle CRM On Demand Essentials': 'Oracle',
    'Oracle Certification': 'Oracle',
    'Oracle Cloud Application Foundation Essentials': 'Oracle',
    'Oracle Cloud Certification': 'Oracle',
    'Oracle Commerce 11 Guided Search Implementation Essentials': 'Oracle',
    'Oracle Commerce 11 Platform Development Implementation Essentials': 'Oracle',
    'Oracle Commerce Certification': 'Oracle',
    'Oracle Customer Hub and Oracle Data Quality Essentials': 'Oracle',
    'Oracle Data Integrator 12c Essentials': 'Oracle',
    'Oracle E-Business Suite (Ebs) R12 Human Capital Management Essentials': 'Oracle',
    'Oracle E-Business Suite (Ebs) R12 Project Essentials': 'Oracle',
    'Oracle E-Business Suite R12.1 General Ledger Essentials': 'Oracle',
    'Oracle E-Business Suite R12.1 Inventory Essentials': 'Oracle',
    'Oracle E-Business Suite R12.1 Order Management Essentials': 'Oracle',
    'Oracle E-Business Suite R12.1 Payables Essentials': 'Oracle',
    'Oracle E-Business Suite R12.1 Purchasing Essentials': 'Oracle',
    'Oracle E-Business Suite R12.1 Receivables Essentials': 'Oracle',
    'Oracle EBS Certification': 'Oracle',
    'Oracle EBS R12: Advanced Supply Chain Planning': 'Oracle',
    'Oracle EBS R12: Install, Patch and Maintain Applications': 'Oracle',
    'Oracle Ebusiness Certification': 'Oracle',
    'Oracle Endeca Information Discovery 3.1 Essentials': 'Oracle',
    'Oracle Essbase 11 Essentials': 'Oracle',
    'Oracle Fusion Middleware 11g: Build Applications with Oracle Forms': 'Oracle',
    'Oracle GoldenGate 12c Implementation Essentials': 'Oracle',
    'Oracle Hyperion Certification': 'Oracle',
    'Oracle Hyperion Data Relationship Management Essentials': 'Oracle',
    'Oracle Hyperion Financial Management 11 Essentials': 'Oracle',
    'Oracle Hyperion Planning 11 Essentials': 'Oracle',
    'Oracle IT Architecture BPM 2013 Essentials': 'Oracle',
    'Oracle IT Architecture Release 3 Essentials': 'Oracle',
    'Oracle IT Architecture SOA 2013 Essentials': 'Oracle',
    'Oracle Identity Governance Suite 11g PS3 Implementation Essentials': 'Oracle',
    'Oracle Mobile Certification': 'Oracle',
    'Oracle Mobile Development 2015 Essentials': 'Oracle',
    'Oracle SOA Suite 12c Essentials': 'Oracle',
    'Oracle Value Chain Planning: Demantra Demand Management 7 Essentials': 'Oracle',
    'Oracle WebCenter Content 11g Essentials': 'Oracle',
    'Oracle WebCenter Portal 11.1.1.8 Essentials': 'Oracle',
    'Oracle WebCenter Sites 11g Essentials': 'Oracle',
    'Oracle WebLogic Server 11g: System Administration I': 'Oracle',
    'Oracle WebLogic Server 12c Essentials': 'Oracle',
    'Oracle WebLogic Server 12c: Administration I': 'Oracle',
    'Oracle WebLogic Server 12c: Advanced Administrator II': 'Oracle',
    'P2PE Assessor Certification': 'PCI',
    'PAQSA Certification': 'PCI',
    'PCI Certification': 'PCI',
    'PRINCE2 Agile Certification': 'Axelos',
    'PRINCE2 Agile Foundation Certification': 'Axelos',
    'PRINCE2 Agile Practitioner Certification': 'Axelos',
    'PRINCE2 Certification': 'Axelos',
    'PRINCE2 Foundation Certification': 'Axelos',
    'PRINCE2 Practitioner Certification': 'Axelos',
    'Palo Alto Network Certification': 'Palo Alto Networks',
    'Palo Alto Networks Certified Cybersecurity Associate': 'Palo Alto '
                                                            'Networks',
    'Palo Alto Networks Certified Network Security Administrator': 'Palo Alto '
                                                                   'Networks',
    'Palo Alto Networks Certified Network Security Engineer': 'Palo Alto '
                                                              'Networks',
    'PeopleSoft 9.2 Financials Implementation Essentials': 'Oracle',
    'PeopleSoft 9.2 Human Resources Essentials': 'Oracle',
    'PeopleSoft PeopleTools 8.5x Implementation Essentials': 'Oracle',
    'Peoplesoft Certification': 'Oracle',
    'Professions Certification': 'IBM',
    'Project Lifecycle Management (Plm) Essentials': 'Oracle',
    'Project Management Professional': 'PMI',
    'QIR Certification': 'PCI',
    'QSA Certification': 'PCI',
    'Redhat Ansible Automation Certification': 'IBM',
    'Redhat Business Process Design Certification': 'IBM',
    'Redhat Business Rules Certification': 'IBM',
    'Redhat Camel Development Certification': 'IBM',
    'Redhat Ceph Storage Administration Certification': 'IBM',
    'Redhat Certification': 'IBM',
    'Redhat Certified Engineer': 'IBM',
    'Redhat Certified Specialist': 'IBM',
    'Redhat Certified System Administrator': 'IBM',
    'Redhat Configuration Management Certification': 'IBM',
    'Redhat Data Virtualization Certification': 'IBM',
    'Redhat Deployment and Systems Management Certification': 'IBM',
    'Redhat Enterprise Application Server Administration Certification': 'IBM',
    'Redhat Gluster Storage Administration Certification': 'IBM',
    'Redhat High Availability Clustering Certification': 'IBM',
    'Redhat Hybrid Cloud Management Certification': 'IBM',
    'Redhat Identity Management Certification': 'IBM',
    'Redhat Linux Diagnostics and Troubleshooting Certification': 'IBM',
    'Redhat Linux Performance Tuning Certification': 'IBM',
    'Redhat Messaging Administration Certification': 'IBM',
    'Redhat OpenShift Administration Certification': 'IBM',
    'Redhat OpenShift Application Development Certification': 'IBM',
    'Redhat OpenShift Certification': 'IBM',
    'Redhat OpenStack Certification': 'IBM',
    'Redhat Security Certification': 'IBM',
    'Redhat Security Containers and OpenShift Container Platform Certification': 'IBM',
    'Redhat Security Linux Certification': 'IBM',
    'Redhat Virtualization Certification': 'IBM',
    'SAS AI and Machine Learning Professional': 'SAS',
    'SAS Administration Certification': 'SAS',
    'SAS Advanced Analytics Certification': 'SAS',
    'SAS Analytics Certification': 'SAS',
    'SAS Certification': 'SAS',
    'SAS Certified Advanced Analytics Professional Using SAS 9': 'SAS',
    'SAS Certified Advanced Programmer for SAS 9': 'SAS',
    'SAS Certified Architecture and Design Specialist for SAS Grid Manager 9.4': 'SAS',
    'SAS Certified BI Content Developer for SAS 9': 'SAS',
    'SAS Certified Big Data Professional Using SAS 9': 'SAS',
    'SAS Certified Clinical Trials Programmer Using SAS 9': 'SAS',
    'SAS Certified Data Integration Developer for SAS 9': 'SAS',
    'SAS Certified Data Quality Steward for SAS 9': 'SAS',
    'SAS Certified Data Scientist Using SAS 9': 'SAS',
    'SAS Certified Deployment Specialist for Visual Analytics 7.3': 'SAS',
    'SAS Certified Deployment and Implementation Specialist for SAS Grid Manager 9.4': 'SAS',
    'SAS Certified Intelligence Platform Deployment Professional for SAS 9': 'SAS',
    'SAS Certified Platform Administrator for SAS 9': 'SAS',
    'SAS Certified Platform Upgrade Specialist for SAS 9.4': 'SAS',
    'SAS Certified Predictive Modeler Using SAS Enterprise Miner 14': 'SAS',
    'SAS Certified Specialist: Forecasting and Optimization Using SAS Viya 3.4': 'SAS',
    'SAS Certified Specialist: Machine Learning Using SAS Viya 3.4': 'SAS',
    'SAS Certified Statistical Business Analyst Using SAS 9: Regression and Modeling': 'SAS',
    'SAS Certified Technical Specialist for Visual Analytics 7.4': 'SAS',
    'SAS Certified Visual Business Analyst: Exploration and Design Using SAS Visual Analytics': 'SAS',
    'SAS Certified Visual Modeler Using SAS Visual Statistics 7.4': 'SAS',
    'SAS Data Management Certification': 'SAS',
    'SAS Foundation Certification': 'SAS',
    'SAS Natural Language and Computer Vision Specialist': 'SAS',
    'SAS Other Certification': 'SAS',
    'SNIA Certification': 'Storage Networking Industry Association',
    'SNIA Certified Information Architect': 'Storage Networking Industry '
                                            'Association',
    'SNIA Certified Storage Architect': 'Storage Networking Industry '
                                        'Association',
    'SNIA Certified Storage Engineer': 'Storage Networking Industry '
                                       'Association',
    'SNIA Certified Storage Networking Expert': 'Storage Networking Industry '
                                                'Association',
    'SNIA Certified Storage Professional': 'Storage Networking Industry '
                                           'Association',
    'SSCP Certification': 'ISC',
    'Shopping Ads Certification': 'Google',
    'Siebel 8 Consultant Exam': 'Oracle',
    'Universal Windows Platform': 'Microsoft',
    'Upgrade Java SE 7 to Java SE 8 OCP Programmer': 'Oracle',
    'Upgrade OCP Java 6, 7 & 8 to Java SE 11 Developer': 'Oracle',
    'Upgrade To Java Se 8 Ocp (Java Se 6 And All Prior Versions)': 'Oracle',
    'VMWare Certification': 'VMWare Company',
    'VMware Certified Advanced Professional': 'VMWare Company',
    'VMware Certified Associate': 'VMWare Company',
    'VMware Certified Design Expert': 'VMWare Company',
    'VMware Certified Professional': 'VMWare Company',
    'Webcenter Certification': 'Oracle',
    'Weblogic Certification': 'Oracle'}
