
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_city_to_region_dict = {
    'aachen': 'eu',
    'aarau': 'eu',
    'aarhus': 'eu',
    'aarhus n': 'eu',
    'aarslev': 'eu',
    'aberdeen': 'eu',
    'abu dhabi': 'mea',
    'abuja': 'mea',
    'accra': 'mea',
    'adelaide': 'ap',
    'agana': 'na',
    'agoura hills': 'na',
    'ahmedabad': 'ap',
    'aichi': 'jp',
    'aiken': 'na',
    'alameda': 'na',
    'albandy': 'eu',
    'albany': 'na',
    'aldeatejada': 'eu',
    'alexandria': 'mea, na',
    'alfragide': 'eu',
    'algiers': 'mea',
    'aliso viejo': 'na',
    'all': 'eu',
    'allen park': 'na',
    'allentown': 'na',
    'allerod': 'eu',
    'almhult': 'eu',
    'almieda': 'eu',
    'aloha': 'na',
    'alpharetta': 'na',
    'alphaville': 'la',
    'amersfoort': 'eu',
    'ames': 'na',
    'amstelveen': 'eu',
    'amsterdam': 'eu',
    'andover': 'na',
    'angola': 'mea',
    'anhui': 'gcg',
    'anjar': 'mea',
    'ankara': 'mea',
    'ann arbor': 'na',
    'annapolis': 'na',
    'annapolis junction': 'na',
    'anniston': 'na',
    'antananarivo': 'mea',
    'antwerp': 'eu',
    'apeldoorn': 'eu',
    'appleton': 'na',
    'aprilia': 'eu',
    'argentina': 'la',
    'arhus': 'eu',
    'arlington': 'na',
    'armonk': 'na',
    'arnold': 'eu',
    'arras': 'eu',
    'as appropriate': 'ap',
    'asan': 'ap',
    'ashburn': 'na',
    'assen': 'eu',
    'astana': 'mea',
    'athens': 'eu',
    'atlanta': 'na',
    'atsugi': 'jp',
    'aubiere': 'eu',
    'auckland': 'ap',
    'augusta': 'na',
    'aurangabad': 'ap',
    'austin': 'na',
    'austria': 'eu',
    'avignon': 'eu',
    'azerbaijan': 'mea',
    'badalona': 'eu',
    'baden': 'eu',
    'baku': 'mea',
    'ballarat': 'ap',
    'ballerup': 'eu',
    'baltimore': 'na',
    'banagalore': 'ap',
    'banaglore': 'ap',
    'bandung': 'ap',
    'bangalor': 'ap',
    'bangalore': 'ap',
    'bangalore india': 'ap',
    'bangaluru': 'ap',
    'bangkok': 'ap',
    'banglore': 'ap',
    'banska bystrica': 'eu',
    'barcelona': 'eu',
    'bari': 'eu',
    'barracas': 'eu',
    'barrie': 'na',
    'barrow in furness': 'eu',
    'basel': 'eu',
    'basingstoke': 'eu',
    'bath': 'eu',
    'baton rouge': 'na',
    'baulkham hills': 'ap',
    'bedford': 'na, eu',
    'bei jing': 'gcg',
    'beijing': 'gcg',
    'belapur': 'ap',
    'belem': 'la',
    'belfast': 'eu',
    'belgium': 'eu',
    'belgrade': 'eu',
    'bella vista': 'na',
    'belo horizonte': 'la',
    'bengalore': 'ap',
    'bengaluru': 'ap',
    'bentonville': 'na',
    'bergamo': 'eu',
    'bergen': 'eu',
    'berlin': 'eu',
    'bern': 'eu',
    'bertrange': 'eu',
    'bethesda': 'na',
    'bgc': 'eu',
    'bharuch': 'ap',
    'bhopal': 'ap',
    'bhubaneswar': 'ap',
    'bielefeld': 'eu',
    'bielsko-biala': 'eu',
    'bilbao': 'eu',
    'birmingham': 'eu, na',
    'bkk': 'ap',
    'blagnac cedex': 'eu',
    'bloomington': 'na',
    'blore': 'ap',
    'blue bell': 'na',
    'boblingen': 'eu',
    'boca raton': 'na',
    'boeblingen': 'eu',
    'bogota': 'la',
    'boigny sur bionne': 'eu',
    'bois colombes': 'eu',
    'bois colombes cedex': 'eu',
    'boise': 'na',
    'bologna': 'eu',
    'bonn': 'eu',
    'bordeaux': 'eu',
    'boston': 'na',
    'boulder': 'na',
    'bracknell': 'eu',
    'bradford': 'eu',
    'brasilia': 'la',
    'braskin': 'eu',
    'brasov': 'eu',
    'bratislava': 'eu',
    'brazzaville': 'mea',
    'bregenz': 'eu',
    'brest': 'eu',
    'bridgetown': 'la',
    'bridgewater': 'eu',
    'brighton': 'eu',
    'brisbane': 'ap',
    'bristol': 'eu',
    'brno': 'eu',
    'bromont': 'na',
    'brondby': 'eu',
    'brono': 'eu',
    'brussel': 'eu',
    'brussels': 'eu',
    'bruxelles': 'eu',
    'brøndby': 'eu',
    'bs as': 'la',
    'bucarest': 'eu',
    'bucharest': 'eu',
    'bucuresti': 'eu',
    'budapest': 'eu',
    'buenos aires': 'la',
    'bufalo': 'na',
    'buffalo': 'na',
    'bulgaria': 'eu',
    'burgess hill': 'eu',
    'burlington': 'na',
    'burnaby': 'ap, na',
    'bussigny': 'eu',
    'caba': 'la',
    'cairo': 'mea',
    'calcutta': 'ap',
    'calgar': 'eu',
    'calgary': 'na',
    'cambridge': 'eu, na',
    'camlica-kisikli': 'mea',
    'camp hill': 'na',
    'campinas': 'la',
    'canberra': 'ap',
    'cape town': 'mea',
    'capellen': 'eu',
    'capellen bertrange': 'eu',
    'capital federal': 'la',
    'caracas': 'la',
    'cario': 'la',
    'cary': 'na',
    'casa': 'eu',
    'casablanca': 'mea',
    'cascais': 'eu',
    'cdmx': 'na',
    'cebu': 'ap',
    'chandigarh': 'ap',
    'changan': 'gcg',
    'changchun': 'gcg',
    'chantilly': 'na',
    'charlotte': 'na',
    'chelmsford': 'eu',
    'cheltenham': 'ap, eu',
    'chemnitz': 'eu',
    'chendu': 'gcg',
    'cheng du': 'gcg',
    'chengdu': 'gcg',
    'chennai': 'ap',
    'chester': 'eu',
    'cheyenne': 'na',
    'chiba': 'jp',
    'chicago': 'na',
    'chile': 'la',
    'chongqing': 'gcg',
    'christchurch': 'ap',
    'chuo ku': 'jp',
    'cincinnati': 'na',
    'clermont ferrand': 'eu',
    'clermont-ferrand': 'eu',
    'cleveland': 'na',
    'clichy': 'eu',
    'cluj': 'eu',
    'cochin': 'ap',
    'coghlan': 'la',
    'coimbatore': 'ap',
    'collegeville': 'na',
    'collegien': 'eu',
    'cologne': 'eu',
    'colombo': 'ap',
    'colombus': 'eu',
    'columbia': 'la, na',
    'columbus': 'na',
    'como': 'eu',
    'copenhagen': 'eu',
    'coppell': 'na',
    'coral gables': 'na',
    'cordoba': 'eu',
    'cork': 'eu',
    'cornaredo': 'eu',
    'costa mesa': 'na',
    'coventry': 'eu',
    'cracow': 'eu',
    'croydon': 'eu',
    'crystal city': 'na',
    'culver city': 'na',
    'curitiba': 'la',
    'cyberjaya': 'ap',
    'cypress': 'na',
    'cz': 'eu',
    'czech republic': 'eu',
    'córdoba': 'la',
    'da lian': 'gcg',
    'da qing': 'gcg',
    'daegu': 'ap',
    'daejeon': 'ap',
    'dahlgren': 'na',
    'dakar': 'mea',
    'dalian': 'gcg',
    'dallas': 'na',
    'dalton': 'na',
    'damansara': 'ap',
    'daqing': 'gcg',
    'darmstadt': 'eu',
    'darwen': 'eu',
    'darwin': 'ap',
    'daytona beach': 'na',
    'dc': 'na',
    'de': 'na',
    'dearborn': 'na',
    'deerfield': 'na',
    'delaware': 'na',
    'delft': 'eu',
    'delhi': 'ap',
    'delhi ncr': 'ap',
    'demark': 'eu',
    'den haag': 'eu',
    'denmark': 'eu',
    'denmark remote': 'eu',
    'denton': 'na',
    'denver': 'na',
    'derby': 'eu',
    'derio': 'eu',
    'des moines': 'na',
    'detriot': 'mea',
    'detroit': 'na',
    'df': 'na',
    'dhaka': 'ap',
    'distrito federal': 'na',
    'dk': 'na',
    'dl': 'ap',
    'doha': 'mea',
    'don mills': 'na',
    'dongguan': 'gcg',
    'dorchester': 'eu',
    'dortmund': 'eu',
    'dorval': 'na',
    'dover': 'eu',
    'draper': 'na',
    'dresden': 'eu',
    'dubai': 'mea',
    'dublin': 'eu, na',
    'dubuque': 'na',
    'duesseldorf': 'eu',
    'duisburg': 'eu',
    'duluth': 'na',
    'dunton warley': 'eu',
    'dunwoody': 'na',
    'durban': 'mea',
    'durham': 'na',
    'durrington': 'eu',
    'dusseldorf': 'eu',
    'e5a': 'jp',
    'eagan': 'na',
    'eagen': 'na',
    'east aurora': 'na',
    'east botany': 'ap',
    'east fishkill': 'na',
    'east hawthorn': 'na',
    'east kilbride': 'eu',
    'east lansing': 'na',
    'east rutherford': 'na',
    'eastwood': 'eu',
    'eatontown': 'na',
    'ecully': 'eu',
    'edinburgh': 'eu',
    'edmonton': 'na',
    'eerduosi': 'gcg',
    'egypt': 'mea',
    'ehnigen': 'eu',
    'ehningen': 'eu',
    'eindhoven': 'eu',
    'ejt': 'eu',
    'el dorado hills': 'na',
    'el paso': 'na',
    'el salto': 'na',
    'emeryville': 'na',
    'endicott': 'na',
    'england': 'eu',
    'englewood': 'na',
    'englewood cliffs': 'na',
    'erfurt': 'eu',
    'ermont': 'eu',
    'eschborn': 'eu',
    'espoo': 'eu',
    'esquimalt': 'na',
    'essen': 'eu',
    'essex': 'eu',
    'essex junction': 'na',
    'esslingen': 'eu',
    'estereo': 'la',
    'estero': 'na',
    'estero florida': 'na',
    'eure': 'eu',
    'eure val de reuil': 'eu',
    'europe': 'eu',
    'exton': 'na',
    'fagersta': 'eu',
    'fairfax': 'na',
    'fairfield': 'na',
    'fargo': 'na',
    'farmers branch': 'na',
    'farmington': 'na',
    'farnborough': 'eu',
    'feltham': 'eu',
    'finland': 'eu',
    'firenze': 'eu',
    'fleet': 'eu',
    'flensburg': 'eu',
    'florence': 'eu',
    'florenceville': 'na',
    'florham park': 'na',
    'florianopolis': 'la',
    'florida': 'na',
    'forrest': 'ap, na',
    'fort de france': 'eu',
    'fort lauderdale': 'na',
    'fort lee': 'na',
    'fort mill': 'na',
    'fort myers': 'na',
    'fort worth': 'na',
    'fortaleza': 'la',
    'forth worth': 'eu',
    'fortworth': 'na',
    'foster city': 'na',
    'framingham': 'na',
    'france': 'eu',
    'frankfurt': 'eu',
    'frankfurt am': 'eu',
    'frankfurt am main': 'eu',
    'frankfurt main': 'eu',
    'franklin': 'na',
    'fredericton': 'na',
    'freemont': 'na',
    'freeport': 'na',
    'fremont': 'na',
    'fresno': 'na',
    'fresnos': 'la',
    'frisco': 'na',
    'ft lauderdale': 'na',
    'ft meade': 'na',
    'ft myers': 'na',
    'fuchu': 'jp',
    'fuji': 'jp',
    'fujian': 'gcg',
    'fujisawa': 'jp',
    'fukuoka': 'jp',
    'fukuyama': 'jp',
    'futakotamagawa': 'jp',
    'fuzhou': 'gcg',
    'gaithersburg': 'na',
    'gatineau': 'na',
    'gauteng': 'mea',
    'gdansk': 'eu',
    'geelong': 'ap',
    'geneva': 'eu',
    'geneve': 'eu',
    'genoa': 'eu',
    'genova': 'eu',
    'gentilly': 'eu',
    'georgetown': 'na',
    'georgia': 'na',
    'germantown': 'na',
    'germany': 'eu',
    'getxo-vizcaya': 'eu',
    'ggn': 'mea',
    'ghent': 'eu',
    'gic hungary': 'eu',
    'giza': 'mea',
    'glasgow': 'eu',
    'glen mills': 'na',
    'glendale': 'na',
    'glenview': 'na',
    'glenview il': 'na',
    'glostrup': 'eu',
    'gloucester': 'eu',
    'goiania': 'la',
    'goleta': 'na',
    'gotenburg': 'eu',
    'gothenburg': 'na',
    'grafton': 'na',
    'grand rapida': 'la',
    'grand rapids': 'na',
    'grand rapis mi': 'eu',
    'graz': 'eu',
    'greater noida': 'ap',
    'greece': 'eu',
    'greenfield': 'na',
    'greenford': 'eu',
    'greenock': 'eu',
    'greenville': 'na',
    'greenwood': 'na',
    'greenwood village': 'na',
    'groningen': 'eu',
    'gta': 'na',
    'guadalajara': 'na',
    'guadalajara jalisco': 'na',
    'guang an': 'gcg',
    'guang dong': 'gcg',
    'guang zhou': 'gcg',
    'guangan': 'gcg',
    'guangdong': 'gcg',
    'guangzhou': 'gcg',
    'guayaquil': 'la',
    'guemligen': 'eu',
    'gugaon': 'ap',
    'gui yang': 'gcg',
    'guinea': 'mea',
    'guiyang': 'gcg',
    'guizhou': 'gcg',
    'gujarat': 'ap',
    'gulfport': 'na',
    'gur': 'eu',
    'gurgaon': 'ap',
    'gurgaon haryana': 'ap',
    'gurgn': 'mea',
    'gurgoan': 'ap',
    'gurugaon': 'ap',
    'gurugram': 'ap',
    'gwangju': 'ap',
    'gz': 'mea',
    'göteborg': 'eu',
    'haag': 'eu',
    'hachiouji': 'jp',
    'hagagun': 'jp',
    'hague': 'eu',
    'hakata': 'jp',
    'hakozaki': 'jp',
    'halifax': 'na',
    'hallifax': 'eu',
    'halsskov': 'eu',
    'hamamatsu': 'jp',
    'hamar': 'eu',
    'hamburg': 'eu',
    'hami': 'gcg',
    'hamilton': 'na',
    'hampton': 'na',
    'hampton roads': 'na',
    'haneda': 'jp',
    'hang zhou': 'gcg',
    'hangzhou': 'gcg',
    'hannover': 'eu',
    'hanoi': 'ap',
    'hanover': 'eu',
    'harrisburg': 'na',
    'hartford': 'na',
    'hartland': 'eu, na',
    'hartsville': 'na',
    'harumi': 'jp',
    'hataka': 'jp',
    'hato rey': 'na',
    'havant': 'eu',
    'hawaii': 'na',
    'hazelwood': 'na',
    'hazlet': 'na',
    'heathrow': 'eu',
    'hefei': 'gcg',
    'hefi': 'eu',
    'heidenheim': 'eu',
    'helsingborg': 'eu',
    'helsingfors': 'eu',
    'helsinki': 'eu',
    'hemel hempstead': 'eu',
    'henderson': 'na',
    'heredia': 'la',
    'herndon': 'na',
    'hf': 'eu',
    'hikari': 'jp',
    'hillsboro': 'na',
    'hillswood': 'na',
    'hingham': 'na',
    'hino': 'jp',
    'hiroshima': 'jp',
    'hk': 'gcg',
    'ho chi minh city': 'ap',
    'hoboken': 'eu',
    'hoffman estates': 'na',
    'hohhot': 'gcg',
    'hollywood': 'na',
    'holmdel': 'na',
    'holte': 'eu',
    'holzminden': 'eu',
    'home': 'eu',
    'homewood': 'na',
    'hong kong': 'gcg',
    'hongkong': 'gcg',
    'honmachi': 'jp',
    'honolulu': 'na',
    'hoofddorp': 'eu',
    'hoover': 'na',
    'hopewell': 'na',
    'hopewell junction': 'na',
    'horolandia': 'la',
    'horsham': 'na',
    'hortolandia': 'la',
    'hortolandia sao paulo': 'la',
    'hortolandia sp': 'la',
    'hosur': 'ap',
    'houston': 'na',
    'houton': 'eu',
    'hove': 'eu',
    'hsinchu': 'gcg',
    'hu he hao te': 'gcg',
    'hu zhou': 'gcg',
    'huaian': 'gcg',
    'huangdao': 'gcg',
    'huhehaote': 'gcg',
    'hui zhou': 'gcg',
    'huizhou': 'gcg',
    'hull': 'eu',
    'hungary': 'eu',
    'hungery': 'eu',
    'hungry': 'eu',
    'huntsville': 'na',
    'hursely': 'eu',
    'hursley': 'eu',
    'huzhou': 'gcg',
    'hvidovre': 'eu',
    'hyd': 'ap',
    'hyderabad': 'ap',
    'hyderbad': 'ap',
    'hyvinkaa': 'eu',
    'hz': 'la',
    'ibm plaza': 'ap',
    'ibm plaza eastwood': 'ap',
    'idf': 'eu',
    'iga': 'jp',
    'ijmuiden': 'eu',
    'ile de france': 'eu',
    'illinois': 'na',
    'incheon': 'ap',
    'india': 'ap',
    'india south asia': 'ap',
    'indianapolis': 'na',
    'indonesia': 'ap',
    'indore': 'ap',
    'ingolstadt': 'eu',
    'inner mongolia': 'gcg',
    'inzai': 'jp',
    'ireland': 'eu',
    'irvin': 'na',
    'irvine': 'eu',
    'irving': 'na',
    'iselin': 'na',
    'islamabad': 'mea',
    'israel': 'mea',
    'issy les moulineaux': 'eu',
    'istanbul': 'mea',
    'ita': 'la',
    'italy': 'eu',
    'izmir': 'mea',
    'jacksonville': 'na',
    'jaipur': 'ap',
    'jakarata': 'ap',
    'jakarta': 'ap',
    'jammu': 'ap',
    'jamshedpur': 'ap',
    'japan': 'jp',
    'jeddah': 'mea',
    'jefferson city': 'na',
    'jersey': 'eu',
    'jersey city': 'na',
    'jerusalem': 'mea',
    'jharkhand': 'ap',
    'jian liu': 'gcg',
    'jiang su': 'ap',
    'jiang xi': 'gcg',
    'jiang yin': 'gcg',
    'jiangmen': 'gcg',
    'jiangsu': 'gcg',
    'jiangxi': 'gcg',
    'jiangyin': 'gcg',
    'jiaxing': 'gcg',
    'jilin': 'gcg',
    'jin hua': 'gcg',
    'jinan': 'gcg',
    'jinhua': 'gcg',
    'jinjiang': 'gcg',
    'jk': 'mea',
    'jodhpur': 'ap',
    'jodpur': 'na',
    'johannesburg': 'mea',
    'johnston': 'na',
    'jorberg': 'mea',
    'jr大阪駅': 'jp',
    'jubail': 'mea',
    'kabul': 'mea',
    'kachidoki': 'jp',
    'kadoma': 'jp, mea',
    'kakogawa': 'jp',
    'kalamazoo': 'na',
    'kanagawa': 'jp',
    'kanazawa': 'jp',
    'kanda': 'jp',
    'kani': 'jp',
    'kansas city': 'na',
    'kaohsiung': 'gcg',
    'karachi': 'mea',
    'kariya': 'jp',
    'karlsruhe': 'eu',
    'karnataka': 'ap',
    'karur': 'ap',
    'kashiwa': 'jp',
    'kassel': 'eu',
    'katowice': 'eu',
    'katy': 'na',
    'kawasaki': 'eu, jp',
    'kazan': 'eu',
    'keene': 'na',
    'keiv': 'na',
    'kelsterbach': 'eu',
    'kenilworth': 'eu',
    'kent': 'eu',
    'kerala': 'ap',
    'kerry': 'eu',
    'keyport': 'na',
    'kidman park': 'ap',
    'kiev': 'eu',
    'kifissia': 'eu',
    'kiheung': 'ap',
    'kilkenny': 'eu',
    'kincardine': 'na',
    'kinderdijk': 'eu',
    'kingston': 'na, la',
    'kingswood': 'eu',
    'kirkland': 'na',
    'kisarazu': 'jp',
    'kista': 'eu',
    'kitakyushu': 'jp',
    'kiyv': 'eu',
    'kl': 'ap',
    'klagenfurt': 'eu',
    'knoxville': 'na',
    'knutsford': 'eu',
    'ko': 'mea',
    'kobe': 'jp',
    'koblenz': 'eu',
    'kochi': 'ap',
    'koeln': 'eu',
    'kofu': 'jp',
    'kogarah': 'ap',
    'kokata': 'la',
    'kol': 'eu',
    'kolkata': 'ap',
    'kolkatta': 'jp',
    'koln': 'eu',
    'kosice': 'eu',
    'koto ku': 'jp',
    'kotoーku': 'mea',
    'kouto ku': 'jp',
    'krakow': 'eu',
    'kuala lumpur': 'ap',
    'kualalampur': 'mea',
    'kula lumpur': 'ap',
    'kumagaya': 'jp',
    'kumamoto': 'jp',
    'kun ming': 'gcg',
    'kunming': 'gcg',
    'kurashiki': 'jp',
    'kuwait': 'mea',
    'kuwait city': 'mea',
    'ky': 'na',
    'kyiv': 'eu',
    'kyjev': 'eu',
    'kyoto': 'jp',
    'la coruña': 'eu',
    'la defence': 'mea',
    'la defense': 'eu',
    'la gaude': 'eu',
    'la pineville': 'na',
    'la valleta': 'eu',
    'lafayette': 'na',
    'lagos': 'mea',
    'lahore': 'ap, mea',
    'lake forest': 'na',
    'lake mary': 'na',
    'lakehurst': 'na',
    'lakeland': 'na',
    'lakewood': 'na',
    'langfang': 'gcg',
    'lanham': 'na',
    'lansing': 'na',
    'laos': 'ap',
    'laredo': 'na',
    'largo': 'na',
    'las vegas': 'na',
    'lausanne': 'eu',
    'laverton': 'ap',
    'leamington spa': 'eu',
    'leawood': 'na',
    'leeds': 'eu',
    'legaria': 'eu',
    'lehi': 'na',
    'leicester': 'eu',
    'leiden': 'eu',
    'leinster': 'eu',
    'leipzig': 'eu',
    'lenexa': 'na',
    'leon': 'eu',
    'leon gto': 'na',
    'lestrem': 'eu',
    'leverkusen': 'eu',
    'lewisville': 'na',
    'lexington': 'na',
    'libreville': 'mea',
    'liege': 'eu',
    'lile': 'na',
    'lille': 'eu',
    'lillie': 'eu',
    'lima': 'la',
    'lincoln': 'na',
    'linhai': 'gcg',
    'linthicum': 'na',
    'linz': 'eu',
    'lippstadt': 'eu',
    'lisboa': 'eu',
    'lisbon': 'eu',
    'lisle': 'eu',
    'lisle il': 'eu',
    'listowel': 'eu',
    'lithuania': 'eu',
    'littleton': 'na',
    'liu zhou': 'gcg',
    'liuzhou': 'gcg',
    'liverpool': 'eu',
    'livingston': 'na',
    'livingston nj': 'na',
    'livonia': 'na',
    'ljubljana': 'eu',
    'loja': 'eu',
    'lomme': 'eu',
    'london': 'na, eu',
    'longmont': 'na',
    'longueuil': 'na',
    'los angeles': 'na',
    'los angelos': 'eu',
    'los angles': 'eu',
    'louisville': 'na',
    'louisville ky': 'na',
    'lu zhou': 'gcg',
    'luanda': 'mea',
    'lucknow': 'ap',
    'lugano': 'eu',
    'lund': 'eu',
    'luoyang': 'gcg',
    'luqa': 'eu',
    'luxembourg': 'eu',
    'luxembourg city': 'eu',
    'luxemburg': 'eu',
    'luzhou': 'gcg',
    'lyon': 'eu',
    'maastricht': 'eu',
    'macau': 'gcg',
    'madison': 'na',
    'madrid': 'eu',
    'magdeburg': 'eu',
    'mahwah': 'na',
    'mahwah nj': 'na',
    'maidenhead': 'eu',
    'maindenhead': 'eu',
    'mainz': 'eu',
    'maison alfort': 'eu',
    'maisons alfort': 'eu',
    'makati': 'ap',
    'makati city': 'ap',
    'makuhari': 'jp',
    'malaga': 'eu',
    'malakoff': 'eu',
    'malaysia': 'ap',
    'malmo': 'eu',
    'malmö': 'eu',
    'malta': 'eu',
    'malvern': 'eu',
    'manassas': 'na',
    'manaus': 'la',
    'manchester': 'eu',
    'mandaluyong': 'ap',
    'mandaluyong city': 'ap',
    'mangalore': 'ap',
    'manhattan': 'na',
    'manhattan beach': 'na',
    'manila': 'ap',
    'manilla': 'ap',
    'manira': 'ap',
    'mannheim': 'eu',
    'markahm': 'na',
    'markham': 'na',
    'marnes': 'eu',
    'marseille': 'eu',
    'martinez': 'na',
    'marunouchi': 'jp',
    'marva': 'eu',
    'marwah': 'ap',
    'maryland': 'na',
    'maryland nj': 'na',
    'marysville': 'na',
    'marysville ohio united states': 'na',
    'mason': 'na',
    'matsue': 'jp',
    'matsumoto': 'jp',
    'matsuyama': 'jp',
    'maurepas': 'eu',
    'mayfield': 'na',
    'mayfield village': 'eu',
    'mazaryk': 'na',
    'mclean': 'na',
    'mechanicsburg': 'na',
    'medan': 'ap',
    'medellin': 'la',
    'meguro': 'jp',
    'meguro ku': 'jp',
    'melbourne': 'ap',
    'melville': 'na',
    'memphis': 'na',
    'meng dong': 'gcg',
    'menlo park': 'na',
    'meridian': 'na',
    'merrifield': 'na',
    'metro': 'ap',
    'meudon': 'eu',
    'mexi': 'la',
    'mexico': 'na',
    'mexico city': 'na',
    'mexico d f': 'na',
    'mexico df': 'na',
    'meyrin': 'eu',
    'miami': 'na',
    'microcentro': 'la',
    'middletown': 'na',
    'midland': 'na',
    'milan': 'eu',
    'milano': 'eu',
    'milton keynes': 'eu',
    'milwaukee': 'na',
    'minato': 'jp',
    'minessota': 'na',
    'minneapolis': 'na',
    'minnesota': 'na',
    'minnetonka': 'na',
    'mississauga': 'na',
    'missouri': 'na',
    'mito': 'jp',
    'miyazaki': 'jp',
    'mo': 'na',
    'mogliano veneto': 'eu',
    'mogliano veneto tv': 'eu',
    'mohali': 'ap',
    'mohringen': 'eu',
    'monore': 'la',
    'monroe': 'na',
    'mons': 'eu',
    'mont saint aignan': 'eu',
    'monterey park': 'na',
    'monterrey': 'na',
    'montevideo': 'la',
    'montgomery': 'na',
    'montogmery': 'na',
    'montpelier': 'na',
    'montpellier': 'eu',
    'montpellier cedex 01': 'eu',
    'montrea': 'na',
    'montreal': 'na',
    'montreuil': 'eu',
    'mooka': 'jp',
    'moorestown': 'na',
    'mooresville': 'na',
    'morocco': 'mea',
    'morristown': 'na',
    'morrisville': 'na',
    'moscow': 'eu',
    'mounds view': 'na',
    'moundsview': 'na',
    'mountain view': 'na',
    'mt laurel': 'na',
    'mty': 'na',
    'mtz': 'eu',
    'muenchen': 'eu',
    'muenster': 'eu',
    'mulhuddart': 'eu',
    'multiple': 'eu',
    'mumbai': 'ap',
    'munch': 'eu',
    'munchen': 'eu',
    'munich': 'eu',
    'munster': 'eu',
    'musashino': 'jp',
    'muscat': 'mea',
    'mysore': 'ap',
    'n a diverse': 'eu',
    'n a remote': 'na',
    'na': 'eu',
    'naga city': 'ap',
    'nagano': 'jp',
    'nagasaki': 'jp',
    'nagoya': 'jp',
    'nagpur': 'ap',
    'naha': 'jp',
    'nairobi': 'mea',
    'nanchang': 'gcg',
    'nancy': 'eu',
    'nanjing': 'gcg',
    'nantes': 'eu',
    'napoli': 'eu',
    'nashville': 'na',
    'navi mumbai': 'ap',
    'ncr': 'mea',
    'netherland': 'ap',
    'netherlands': 'eu',
    'new': 'eu',
    'new castle': 'na',
    'new delhi': 'ap',
    'new jersey': 'na',
    'new orleans': 'na',
    'new plymouth': 'ap',
    'new york': 'na',
    'new york city': 'na',
    'new zealand': 'ap',
    'newark': 'na',
    'newbury': 'na',
    'newcastle': 'eu',
    'newcastle upon tyne': 'eu',
    'newport': 'eu',
    'newyork': 'jp',
    'nice': 'eu',
    'nice meridia': 'eu',
    'nicosia': 'eu',
    'niigata': 'jp',
    'ningbo': 'gcg',
    'niort': 'eu',
    'niteroi': 'la',
    'nj': 'na',
    'nl central': 'ap',
    'nodia': 'la',
    'noia': 'eu',
    'noida': 'ap',
    'noisy le grand': 'eu',
    'noisy-le-grand': 'eu',
    'norderstedt': 'eu',
    'nordrhein westfalen': 'eu',
    'nordrhein westphalen': 'eu',
    'norfolk': 'eu',
    'norfolk island': 'na',
    'norman': 'na',
    'north bay': 'na',
    'north hampton': 'na',
    'north harbour': 'na',
    'north ryde': 'ap',
    'north wales pa': 'na',
    'north york': 'na',
    'northampton': 'eu, na',
    'northamton': 'eu',
    'northapton': 'na',
    'northern': 'na',
    'northern ca': 'na',
    'northridge': 'na',
    'norwalk': 'na',
    'norway': 'eu',
    'norwich': 'eu',
    'nossegem': 'eu',
    'not relevant': 'eu',
    'nottingham': 'eu',
    'novara': 'eu',
    'novato': 'na',
    'novi': 'na',
    'nsw': 'ap',
    'nuernberg': 'eu',
    'nuremberg': 'eu',
    'nurnberg': 'eu',
    'nuvali': 'ap',
    'ny': 'na',
    'ny nj': 'na',
    'nyc': 'na',
    'nürnberg': 'eu',
    'oakville': 'na',
    'odense': 'eu',
    'offenbach a m': 'eu',
    'oftringen': 'eu',
    'ohama': 'mea',
    'ohio': 'na',
    'ohmiya': 'jp',
    'ohta': 'jp',
    'ohtawara': 'jp',
    'okayama': 'jp',
    'okazaki': 'jp',
    'oklahoma city': 'na',
    'olivos': 'la',
    'omaha': 'na',
    'on site': 'eu',
    'ontario': 'na',
    'open': 'eu',
    'ora': 'jp',
    'orange': 'na',
    'oranjestad': 'eu',
    'ordos': 'gcg',
    'orlando': 'na',
    'orleans': 'na',
    'osaka': 'jp',
    'osaka city': 'jp',
    'osaki': 'jp',
    'osasco': 'la',
    'oslo': 'eu',
    'ostrava': 'eu',
    'otawa': 'na',
    'otemachi': 'jp',
    'other': 'na',
    'ottawa': 'na',
    'oume city': 'jp',
    'oune': 'mea',
    'overland park': 'na',
    'oviedo': 'eu',
    'oxford': 'na',
    'padova': 'eu',
    'padua': 'eu',
    'pahang': 'ap',
    'painted post': 'na',
    'palermo': 'eu',
    'palisades': 'na',
    'palma de mallorca': 'eu',
    'palo alto': 'na',
    'papeete': 'eu',
    'paramus': 'na',
    'paris': 'eu',
    'paris la defense': 'eu',
    'park ridge': 'na',
    'parkridge': 'na',
    'parkside': 'ap',
    'parma': 'eu',
    'parramatta': 'ap',
    'parsippany': 'na',
    'pasig': 'ap',
    'pasig city': 'ap',
    'pasteur': 'eu',
    'pau': 'eu',
    'penang': 'ap',
    'pennsylvania': 'na',
    'peoria': 'na',
    'pero': 'eu',
    'perth': 'ap',
    'peschiera borromeo': 'eu',
    'petach tikva': 'mea',
    'petah tikva': 'mea',
    'petaling jaya': 'ap',
    'petaluma': 'na',
    'pheonix': 'ap',
    'philadelphia': 'na',
    'phildelphia': 'na',
    'philippines': 'ap',
    'philly': 'na',
    'phoenix': 'na',
    'phoneix': 'na',
    'pindamonhangaba': 'la',
    'pineville': 'na',
    'pineville la': 'na',
    'pioltello': 'eu',
    'piscataway': 'na',
    'pitsburgh': 'la',
    'pittsburgh': 'na',
    'plano': 'na',
    'plaza carso': 'na',
    'pleasanton': 'na',
    'pleasonton': 'na',
    'pointe a pitre': 'eu',
    'pointe a pitre guadeloupe': 'eu',
    'poissy': 'eu',
    'pok': 'la',
    'polanco': 'eu',
    'poland': 'eu',
    'poltava': 'eu',
    'poone': 'mea',
    'portland': 'na',
    'porto': 'eu',
    'porto alegre': 'la',
    'porto salvo': 'eu',
    'portsmouth': 'eu',
    'portugal': 'eu',
    'poughkeepsie': 'na',
    'poznan': 'eu',
    'pragua': 'eu',
    'prague': 'eu',
    'praha': 'eu',
    'praque': 'la',
    'preston': 'eu',
    'pretoria': 'mea',
    'prilly': 'eu',
    'princeton': 'na',
    'provensvej': 'eu',
    'prøvensvej': 'eu',
    'pt': 'na',
    'pu': 'na',
    'puerto madero': 'la',
    'pune': 'ap',
    'punr': 'na',
    'pusan': 'ap',
    'qatar': 'mea',
    'qd': 'eu',
    'qing dao': 'gcg',
    'qingdao': 'gcg',
    'qinggao': 'gcg',
    'qinghai': 'gcg',
    'quebec': 'na',
    'quebec city': 'na',
    'queretaro': 'na',
    'querã?taro': 'na',
    'querétaro': 'na',
    'quezon': 'ap',
    'quezon city': 'ap',
    'quezon cty': 'ap',
    'quincy': 'na',
    'quita': 'la',
    'quito': 'la',
    'raamsdonksveer': 'eu',
    'radbroke': 'eu',
    'raleigh': 'na',
    'randburg': 'mea',
    'randstad': 'eu',
    'ras al khair': 'mea',
    'rat burana': 'ap',
    'raynham': 'na',
    'reading': 'eu',
    'recife': 'la',
    'reggio emilia': 'eu',
    'regina': 'na',
    'reims france': 'eu',
    'releigh': 'na',
    'remote': 'na',
    'remote work': 'na',
    'remoto': 'eu',
    'reno': 'eu',
    'renton': 'na',
    'research triangle park': 'na',
    'reston': 'na',
    'retiro': 'la',
    'reunion': 'eu',
    'reutlingen': 'eu',
    'rheinland pfalz worth am rhein': 'eu',
    'rhode island': 'na',
    'riadh': 'eu',
    'rialto': 'eu',
    'richmond': 'na',
    'riga': 'eu',
    'riihimaki': 'eu',
    'rijswijk': 'eu',
    'ringsted': 'eu',
    'rio de janeiro': 'la',
    'riyad': 'mea',
    'riyadh': 'mea',
    'roanoke': 'na',
    'roanoke va': 'na',
    'rochester': 'na',
    'rocket center': 'na',
    'rockville': 'na',
    'roissy': 'eu',
    'roma': 'eu',
    'rome': 'eu',
    'rosario': 'la',
    'rotkreuz': 'eu',
    'rotterdam': 'eu',
    'rouen': 'eu',
    'royersford': 'na',
    'rtp': 'na',
    'rueil malmaison': 'eu',
    'rui an': 'gcg',
    'ruian': 'gcg',
    'rungis': 'eu',
    'russia': 'eu',
    'russian fed.': 'eu',
    'rye': 'na',
    'sa': 'eu',
    'sacramento': 'na',
    'saint herblain': 'eu',
    'saint john': 'na',
    'saint laurent': 'eu',
    'saint louis': 'na',
    'saint ouen': 'eu',
    'saint petersburg': 'eu, na',
    'saint-denis de la reunion': 'eu',
    'saitama': 'jp',
    'salisbury': 'eu',
    'salisbury us': 'eu',
    'salt lake city': 'na',
    'salvador': 'la',
    'salzburg': 'eu',
    'san antonio': 'na',
    'san diego': 'na',
    'san fernando de henares': 'eu',
    'san francisco': 'na',
    'san jose': 'na',
    'san ramon': 'na',
    'sandton': 'mea',
    'sandy springs': 'na',
    'santa barbara': 'na',
    'santa clara': 'na',
    'santa monica': 'na',
    'santa rosa city': 'ap',
    'santaclara': 'na',
    'santiago': 'la',
    'santiago de chile': 'la',
    'santo amaro': 'la',
    'santo andre': 'la',
    'sao paulo': 'la',
    'sao paulo sp': 'la',
    'sapporo': 'jp',
    'sasebo': 'jp',
    'saskatoon': 'na',
    'saudi arabia': 'mea',
    'schaumburg': 'na',
    'se': 'la',
    'seattle': 'na',
    'secaucus': 'na',
    'segrate': 'eu',
    'selangor': 'ap',
    'sen jose': 'eu',
    'sendai': 'jp',
    'seongnam': 'ap',
    'seoul': 'ap',
    'sesto fiorentino': 'eu',
    'settimo milanese': 'eu',
    'several': 'eu',
    'sevilla': 'eu',
    'sfv': 'la',
    'sg': 'eu',
    'sh': 'eu',
    'shang hai': 'gcg',
    'shanghai': 'gcg',
    'shen zhen': 'gcg',
    'shenyang': 'gcg',
    'shenzen': 'gcg',
    'shenzhen': 'gcg',
    'shibuya ku': 'jp',
    'shinagawa ku': 'jp',
    'shinjuku': 'jp',
    'shiodome': 'jp',
    'shizuoka': 'jp',
    'shunan': 'jp',
    'siena': 'eu',
    'sigonella': 'eu',
    'simpsonville': 'na',
    'singapore': 'gcg',
    'sioux falls': 'na',
    'sjælland': 'eu',
    'sk': 'na',
    'sligo': 'eu',
    'slough': 'eu',
    'slovakia': 'eu',
    'slovenia': 'eu',
    'smyrna': 'na',
    'sofia': 'eu',
    'somers': 'na',
    'somerset': 'eu',
    'songdo': 'ap',
    'sophia antipolis': 'eu',
    'south': 'ap',
    'south bank': 'eu',
    'south east': 'eu',
    'southampton': 'eu',
    'southbank': 'ap',
    'southbury': 'eu, na',
    'southend': 'eu',
    'southfield': 'na',
    'sp': 'la',
    'spain': 'eu',
    'speke': 'eu',
    'springfield': 'na',
    'sri lanka': 'ap',
    'srilanka': 'ap',
    'st james park': 'eu',
    'st john': 'na',
    'st laurent': 'eu',
    'st leo': 'na',
    'st leonards': 'ap',
    'st louis': 'na',
    "st. john's": 'na',
    'staines': 'eu',
    'stamford': 'na',
    'stanford': 'na',
    'staten island': 'na',
    'stavanger': 'eu',
    'sterling forest': 'na',
    'stevenage': 'eu',
    'stevens point': 'na',
    'stgo': 'la',
    'stockholm': 'eu',
    'stokholm': 'eu',
    'strasbourg': 'eu',
    'strathroy': 'na',
    'sturtevant': 'na',
    'stuttgart': 'eu',
    'su zhou': 'gcg',
    'suihua': 'gcg',
    'suitengumae': 'jp',
    'suitland': 'na',
    'sumida kameido': 'jp',
    'summit': 'na',
    'sunbury': 'na',
    'sundsvall': 'eu',
    'sunnyvale': 'na',
    'surabaya': 'ap',
    'surat': 'ap',
    'suwanee': 'na',
    'suwon': 'ap',
    'suzhou': 'gcg',
    'swansea': 'eu',
    'sweden': 'eu',
    'swindon': 'eu',
    'switzerland': 'eu',
    'sydney': 'ap',
    'sz': 'eu',
    'szekesfehervar': 'eu',
    'szf': 'mea',
    'taguig': 'ap',
    'taguig city': 'ap',
    'taichung': 'gcg',
    'tainan': 'gcg',
    'taipei': 'gcg',
    'taipie': 'ap',
    'taiwan': 'ap',
    'taizhou': 'gcg',
    'takahama': 'jp',
    'takamatsu': 'jp',
    'takasaki': 'jp',
    'tallinn': 'eu',
    'tama': 'jp',
    'tampa': 'na',
    'taranto': 'eu',
    'taunton': 'eu',
    'tba': 'eu',
    'tbc': 'eu',
    'tbd': 'eu',
    'tel aviv': 'mea',
    'telanagana': 'ap',
    'telangana': 'ap',
    'telengana': 'ap',
    'telford': 'eu',
    'telford tbc': 'eu',
    'tempe': 'na',
    'tenjin': 'jp',
    'terneuzen': 'eu',
    'test': 'na',
    'test2': 'na',
    'test3': 'na',
    'texas': 'na',
    'th': 'eu',
    'thailand': 'ap',
    'thane': 'ap',
    'the hague': 'eu',
    'tian jin': 'gcg',
    'tianjin': 'gcg',
    'tigery': 'eu',
    'timisoara': 'eu',
    'timoteo mg': 'la',
    'tirno': 'eu',
    'tiverton': 'eu',
    'tj': 'mea',
    'tlv': 'mea',
    'tokushima': 'jp',
    'tokyo': 'jp',
    'tokyo osaka': 'jp',
    'toledo': 'na',
    'tomar': 'eu',
    'tongxiang': 'gcg',
    'topeka': 'na',
    'toranto': 'jp',
    'torino': 'eu',
    'toron': 'eu',
    'toronto': 'na',
    'torrance': 'na',
    'torre madero': 'la',
    'toulouse': 'eu',
    'tours': 'eu',
    'toyama': 'jp',
    'toyo cho': 'jp',
    'toyoake': 'jp',
    'toyoda': 'jp',
    'toyonaka': 'jp',
    'toyosu': 'jp',
    'toyota': 'jp',
    'travel': 'la',
    'trenton': 'na',
    'tres cantos': 'eu',
    'treviso': 'eu',
    'trieste': 'eu',
    'trivandrum': 'ap',
    'trollasen': 'eu',
    'trondheim': 'eu',
    'troy': 'mea',
    'tsukuba': 'jp',
    'tucson': 'na',
    'tukwila': 'na',
    'tulsa': 'na',
    'tunis': 'mea',
    'turin': 'eu',
    'turkey': 'mea',
    'tutoia': 'la',
    'twickenham': 'eu',
    'tychy': 'eu',
    'uae': 'mea',
    'uberlandia': 'la',
    'uithoorn': 'eu',
    'uk': 'eu',
    'uk sunbury': 'eu',
    'umea': 'eu',
    'umeda': 'jp',
    'unassigned': 'ap',
    'undefined': 'mea',
    'uneda': 'la',
    'union station': 'na',
    'united kingdom': 'eu',
    'united states': 'na',
    'unspecified': 'mea',
    'up technohub': 'ap',
    'upa': 'eu',
    'upa j': 'la',
    'upaj': 'ap',
    'upaj 3f': 'ap',
    'upj': 'ap',
    'upm': 'ap',
    'upper gwynedd': 'na',
    'uruguay': 'la',
    'us': 'eu',
    'utah': 'na',
    'utd.arab.emir.': 'mea',
    'utrecht': 'eu',
    'utsunomiya': 'jp',
    'uxbridge': 'eu',
    'v': 'na',
    'vac': 'eu',
    'vaduz': 'eu',
    'val de reuil': 'eu',
    'valapad thrissur kerala': 'ap',
    'valencia': 'eu',
    'valladolid': 'eu',
    'vancouver': 'na',
    'varie': 'eu',
    'vasteras': 'eu',
    'vaughan': 'na',
    'veghel': 'eu',
    'veldhoven': 'eu',
    'velizy': 'eu',
    'velsen': 'eu',
    'velson': 'na',
    'velzen': 'eu',
    'velzen noord': 'eu',
    'venezuela': 'la',
    'venice': 'eu',
    'ventura': 'na',
    'verona': 'eu',
    'vevey': 'eu',
    'vicenza': 'eu',
    'victoria': 'na',
    'victoria mahe': 'mea',
    'vienna': 'eu',
    'villeneuve sur lot': 'eu',
    'vilnius': 'eu',
    'virginia': 'na',
    'virtual': 'eu',
    'visakhapatnam': 'ap',
    'viseu': 'eu',
    'vitoria': 'la, eu',
    'wakefield': 'eu',
    'wako': 'jp',
    'waldorf': 'eu',
    'walldorf': 'eu',
    'wallingford': 'eu',
    'waltham': 'na',
    'warren': 'na',
    'warrington': 'eu',
    'warsaw': 'eu',
    'warszawa': 'eu',
    'warwick': 'eu',
    'washington': 'na',
    'washington d c': 'na',
    'washington dc': 'na',
    'waterloo': 'na',
    'watson': 'na',
    'wattens': 'eu',
    'waukegan': 'na',
    'wawa pa': 'na',
    'wayne': 'na',
    'wayzata': 'na',
    'weehawken': 'na',
    'wei fang': 'gcg',
    'weifang': 'gcg',
    'weihai': 'gcg',
    'wellington': 'ap',
    'wen zhou': 'gcg',
    'wenzhou': 'gcg',
    'west bengal': 'ap',
    'west melbourne': 'ap',
    'west of england': 'eu',
    'west pennant hills': 'ap',
    'west perth': 'ap',
    'west virginia': 'na',
    'westfield': 'na',
    'westlake': 'na',
    'westlake village': 'na',
    'weston': 'eu',
    'westport': 'na',
    'wethersfield': 'na',
    'wgn': 'ap',
    'wh': 'na',
    'white oak': 'na',
    'white plains': 'na',
    'wien': 'eu',
    'wiesbaden': 'eu',
    'wilimington': 'na',
    'willenhall': 'eu',
    'williston': 'na',
    'wilmington': 'na',
    'wimbledon': 'eu',
    'winchester': 'eu',
    'windsor': 'na',
    'winnipeg': 'na',
    'winter haven': 'na',
    'winter park': 'na',
    'winterthur': 'eu',
    'witney oxon': 'eu',
    'wma': 'eu',
    'wny': 'mea',
    'woking': 'eu',
    'wolfsburg': 'eu',
    'wolverhampton': 'eu',
    'woodbridge': 'eu',
    'wooster': 'na',
    'work at home': 'eu',
    'workingham': 'na',
    'workington': 'eu',
    'worthing': 'eu',
    'wp': 'eu',
    'wph': 'ap',
    'wro': 'eu',
    'wroclaw': 'eu',
    'wrocław': 'eu',
    'wu han': 'gcg',
    'wu lu mu qi': 'gcg',
    'wuerzburg': 'eu',
    'wuhai': 'gcg',
    'wuhan': 'gcg',
    'wulumuqi': 'gcg',
    'wuppertal': 'eu',
    'wuxi': 'gcg',
    'xi an': 'gcg',
    'xia men': 'gcg',
    'xiamen': 'gcg',
    'xian': 'gcg',
    'xinjiang': 'gcg',
    'xuzhou': 'gcg',
    'xx': 'eu',
    'yamagata': 'jp',
    'yamato': 'eu',
    'yantai': 'gcg',
    'yanzhou': 'gcg',
    'yellowknife': 'na',
    'yeoido': 'ap',
    'yixing': 'gcg',
    'yokohama': 'jp',
    'yongin': 'ap',
    'yonkers': 'na',
    'york': 'eu',
    'yorktown heights': 'na',
    'youngin': 'na',
    'yuede': 'gcg',
    'zagreb': 'eu',
    'zama': 'jp',
    'zaragoza': 'eu',
    'zaventem': 'eu',
    'zeist': 'eu',
    'zelienople': 'na',
    'zhang qiu': 'gcg',
    'zhangqiu': 'gcg',
    'zhejiang': 'gcg',
    'zhen jiang': 'gcg',
    'zhengzhou': 'gcg',
    'zhenjiang': 'gcg',
    'zhu hai': 'gcg',
    'zhuhai': 'gcg',
    'zoetermeer': 'eu',
    'zoeterwoude': 'eu',
    'zuerich': 'eu',
    'zurich': 'eu',
    'zürich': 'eu',
    'さいたま市': 'jp',
    'さいたま市与野': 'jp',
    '三島市': 'jp',
    '三鷹': 'jp',
    '上北郡野辺地町': 'jp',
    '下関市': 'jp',
    '世田谷区太子堂': 'jp',
    '両国': 'jp',
    '中央区': 'jp',
    '中津駅': 'jp',
    '中野': 'jp',
    '中野区': 'jp',
    '丸の内': 'jp',
    '丸の内 晴海': 'jp',
    '丸の内 東京駅': 'jp',
    '二子玉川': 'jp',
    '云南昆明': 'gcg',
    '五反田': 'jp',
    '京都': 'jp',
    '京都市': 'jp',
    '京都市 清水五条駅': 'jp',
    '京都市伏見区': 'jp',
    '京都市左京区': 'jp',
    '仙台市': 'jp',
    '伊万里市': 'jp',
    '佐倉市 佐倉駅': 'jp',
    '八丁堀駅': 'jp',
    '八王子': 'jp',
    '八王子市': 'jp',
    '八王子市 北八王子駅': 'jp',
    '八王子市南大沢': 'jp',
    '六ヶ所': 'jp',
    '函館市松陰町': 'jp',
    '刈谷市': 'jp',
    '初台駅': 'jp',
    '加古川': 'jp',
    '北九州市小倉': 'jp',
    '北八王子': 'jp',
    '北八王子駅': 'jp',
    '北新横浜': 'jp',
    '北海道札幌市': 'jp',
    '千代田区': 'jp',
    '千代田区丸の内 東京駅': 'jp',
    '千代田区内幸町': 'jp',
    '千代田区大手町': 'jp',
    '千代田区平河町 永田町': 'jp',
    '千曲市 篠ノ井駅': 'jp',
    '千葉': 'jp',
    '千葉 東京': 'jp',
    '千葉市': 'jp',
    '千葉県千葉市': 'jp',
    '可児市': 'jp',
    '台場 仙台': 'jp',
    '台東区': 'jp',
    '吉野川市鴨島町': 'jp',
    '名古屋': 'jp',
    '名古屋市': 'jp',
    '名古屋市守山区': 'jp',
    '和光': 'jp',
    '和光市': 'jp',
    '品川': 'jp',
    '品川区': 'jp',
    '品川区 天王洲アイル': 'jp',
    '四日市': 'jp',
    '四日市市': 'jp',
    '土佐市': 'jp',
    '土浦市': 'jp',
    '堺市': 'jp',
    '墨田区': 'jp',
    '多摩センター': 'jp',
    '多摩センター駅': 'jp',
    '多摩市': 'jp',
    '多摩市 多摩センター駅': 'jp',
    '多摩市唐木田': 'jp',
    '大井町駅': 'jp',
    '大和市': 'jp',
    '大和市中央林間': 'jp',
    '大垣市': 'jp',
    '大崎': 'jp',
    '大手町': 'jp',
    '大手町 or 押上': 'jp',
    '大村市': 'jp',
    '大森': 'jp',
    '大田区': 'jp',
    '大田区 蒲田': 'jp',
    '大連': 'gcg',
    '大阪市': 'jp',
    '大阪市 大阪駅': 'jp',
    '大阪市 新大阪': 'jp',
    '大阪市住之江区': 'jp',
    '大阪市内': 'jp',
    '大阪市此花区桜島': 'jp',
    '大阪府': 'jp',
    '大阪府千里': 'gcg',
    '天王洲': 'gcg',
    '天王洲アイル': 'jp',
    '太田市': 'jp',
    '姫路市 jr姫路駅': 'jp',
    '姫路市 姫路駅': 'jp',
    '宇都宮': 'jp',
    '守口市': 'jp',
    '守谷市': 'jp',
    '宮原': 'jp',
    '宮崎市': 'jp',
    '宮崎県': 'jp',
    '富山県 高岡市': 'jp',
    '尼崎市': 'jp',
    '山形市': 'jp',
    '岐阜市': 'jp',
    '岐阜県 可児市': 'jp',
    '岡山市': 'jp',
    '岡山市北区': 'jp',
    '岡崎市 東岡崎駅': 'jp',
    '川内市': 'ap',
    '川崎市': 'jp',
    '常総市': 'jp',
    '幕張': 'jp',
    '広島': 'jp',
    '広島市': 'jp',
    '広島市中区小町': 'jp',
    '府中': 'jp',
    '府中市': 'jp',
    '弁天橋 鶴見区': 'jp',
    '愛甲郡愛川町中津': 'jp',
    '戸田市': 'jp',
    '文京区': 'jp',
    '文京区 護国寺駅': 'jp',
    '新宿': 'jp',
    '新宿区': 'jp',
    '新宿区 新宿駅': 'jp',
    '新宿区新宿三丁目': 'jp',
    '新川': 'jp',
    '新座市': 'jp',
    '新木場駅': 'jp',
    '新松戸': 'jp',
    '新横浜': 'jp',
    '新横浜 仲町台': 'jp',
    '新橋': 'jp',
    '新橋駅': 'jp',
    '新潟市': 'jp',
    '新町': 'jp',
    '日暮里': 'jp',
    '日本橋': 'jp',
    '日野市': 'jp',
    '旭市': 'jp',
    '明石市 西明石': 'jp',
    '昭島市': 'jp',
    '晴海': 'gcg',
    '有楽町': 'jp',
    '朝霞台': 'jp',
    '朝霞市': 'jp',
    '朝霞市 朝霞駅': 'jp',
    '本厚木': 'jp',
    '本町': 'jp',
    '札幌': 'jp',
    '朽網': 'jp',
    '杉並区永福': 'jp',
    '東久留米市': 'jp',
    '東京': 'jp',
    '東京 or 水天宮': 'jp',
    '東京 名古屋': 'jp',
    '東京都 水天宮前': 'jp',
    '東京都内': 'jp',
    '東京都台東区': 'jp',
    '東京都深川': 'jp',
    '東京都港区': 'jp',
    '東銀座': 'jp',
    '東陽町': 'jp',
    '松山市天山': 'jp',
    '板橋区': 'jp',
    '板橋区志村': 'jp',
    '柏市': 'jp',
    '桜木町': 'jp',
    '梅田': 'jp',
    '横浜': 'jp',
    '横浜市': 'jp',
    '横浜市中区': 'jp',
    '横浜市仲町台': 'jp',
    '武生駅': 'gcg',
    '武蔵野市': 'jp',
    '武蔵野市吉祥寺本町': 'jp',
    '水天宮前': 'jp',
    '水天宮駅': 'jp',
    '汐留': 'jp',
    '汐留駅': 'jp',
    '江戸川橋': 'jp',
    '江東区': 'jp',
    '江東区有明': 'jp',
    '沖縄': 'jp',
    '沖縄県那覇市': 'jp',
    '浅草': 'jp',
    '浜松市': 'jp',
    '浜松市 浜松駅': 'jp',
    '浜松市浜中区': 'jp',
    '浜松市浜東区': 'jp',
    '浜松町他': 'jp',
    '淀屋橋駅': 'jp',
    '深川': 'jp',
    '渋谷区': 'jp',
    '渋谷区 代々木公園駅': 'jp',
    '渋谷区 渋谷': 'jp',
    '港区': 'jp',
    '熊本市': 'jp',
    '燕市': 'gcg',
    '田町': 'jp',
    '田町駅': 'jp',
    '目黒': 'jp',
    '目黒区': 'jp',
    '相模原市': 'jp',
    '知多郡東浦町': 'jp',
    '石狩市': 'jp',
    '磐田': 'jp',
    '磐田市': 'jp',
    '磐田駅': 'jp',
    '神埼市': 'jp',
    '神奈川県鎌倉市': 'jp',
    '神戸': 'jp',
    '神戸市': 'jp',
    '福井市': 'jp',
    '福山市': 'ap',
    '福岡市': 'jp',
    '福岡市南区大楠': 'jp',
    '福岡県': 'jp',
    '秋葉原': 'jp',
    '立川': 'jp',
    '立川市': 'jp',
    '立川市 jr立川駅': 'jp',
    '箱崎': 'jp',
    '築地': 'jp',
    '米子市': 'jp',
    '綾部市味方町': 'jp',
    '羽村市': 'jp',
    '習志野市': 'jp',
    '能美': 'jp',
    '船橋市': 'jp',
    '芝浦ふ頭 田町': 'jp',
    '芳賀郡芳賀町芳賀台': 'jp',
    '茅ヶ崎市 茅ヶ崎': 'jp',
    '茅ヶ崎市茅ヶ崎': 'jp',
    '茅場町駅': 'jp',
    '茨木市': 'jp',
    '草津市': 'jp',
    '薩摩川内市': 'jp',
    '虎ノ門': 'jp',
    '裾野市': 'jp',
    '調布市': 'jp',
    '豊中市': 'jp',
    '豊島区 高田馬場駅': 'jp',
    '豊橋市明海町': 'jp',
    '豊洲': 'jp',
    '豊田市': 'jp',
    '近江八幡': 'jp',
    '那覇': 'jp',
    '那覇市': 'jp',
    '金山駅': 'jp',
    '金沢市': 'jp',
    '錦糸町': 'jp',
    '長岡京': 'jp',
    '長岡京市': 'jp',
    '長野': 'jp',
    '長野市': 'jp',
    '門真 守口 京橋': 'jp',
    '門真市': 'jp',
    '青山一丁目': 'jp',
    '青梅市末広町': 'jp',
    '高松市': 'jp',
    '高松市春日町': 'jp',
    '高浜市': 'jp',
    '高田馬場': 'jp',
    '鴨島駅': 'gcg',
    '鴨川市': 'jp',
    '麹町': 'jp'}
