
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_country_to_region_dict = {
    'afghanistan': 'mea',
    'albania': 'eu',
    'algeria': 'mea',
    'angola': 'mea',
    'argentina': 'la',
    'australia': 'ap',
    'austria': 'eu',
    'azerbaijan': 'mea',
    'bahamas': 'na',
    'bahrain': 'mea',
    'bangladesh': 'ap',
    'barbados': 'la',
    'bei jing': 'gcg',
    'belarus': 'eu',
    'belgium': 'eu',
    'bermuda': 'mea',
    'bolivia': 'la',
    'botswana': 'mea',
    'brazil': 'la',
    'bulgaria': 'eu',
    'burkina faso': 'mea',
    'cambodia': 'mea',
    'canada': 'na',
    'central african republic': 'mea',
    'chad': 'mea',
    'chile': 'la',
    'china': 'gcg',
    'colombia': 'la',
    'columbia': 'la',
    'congo': 'mea',
    'costa rica': 'la',
    'croatia': 'eu',
    'curacao': 'na',
    'cyprus': 'eu',
    'czech': 'eu',
    'czech republic': 'eu',
    'czechia': 'eu',
    "côte d'ivoire": 'mea',
    'd.r.': 'la',
    'denmark': 'eu',
    'djibouti': 'mea',
    'dominica': 'la',
    'ecuador': 'la',
    'egypt': 'mea',
    'estonia': 'eu',
    'finland': 'eu',
    'france': 'eu',
    'french guiana': 'la',
    'frenchpolynesia': 'eu',
    'gabon': 'mea',
    'georgia': 'eu',
    'germany': 'eu',
    'ghana': 'mea',
    'gibraltar': 'eu',
    'gnbissau': 'mea',
    'greece': 'eu',
    'guadeloupe': 'la',
    'guam': 'ap',
    'guatemala': 'la',
    'guinea': 'mea',
    'guyana': 'la',
    'haiti': 'la',
    'hong kong': 'gcg',
    'hungary': 'eu',
    'hungery': 'eu',
    'iceland': 'eu',
    'india': 'ap',
    'indonesia': 'ap',
    'iran': 'mea',
    'iraq': 'mea',
    'ireland': 'eu',
    'israel': 'mea',
    'italy': 'eu',
    'jamaica': 'la',
    'jamaika': 'la',
    'japan': 'jp',
    'jersey': 'eu',
    'jordan': 'mea',
    'kazakhstan': 'mea',
    'kenya': 'mea',
    'korea': 'ap',
    'kuwait': 'mea',
    'laos': 'ap',
    'latvia': 'eu',
    'lebanon': 'mea',
    'lesotho': 'mea',
    'libya': 'mea',
    'liechtenstein': 'eu',
    'lithuania': 'eu',
    'luxembourg': 'eu',
    'macao': 'mea',
    'madagascar': 'mea',
    'malawi': 'mea',
    'malaysia': 'ap',
    'malta': 'eu',
    'martinique': 'la',
    'mauritius': 'mea',
    'mexico': 'na',
    'moldova': 'eu',
    'monaco': 'eu',
    'morocco': 'mea',
    'mozambique': 'mea',
    'namibia': 'mea',
    'nepal': 'ap',
    'netherlands': 'eu',
    'nevis': 'eu',
    'new caledonia': 'ap',
    'new zealand': 'ap',
    'niger': 'mea',
    'nigeria': 'mea',
    'norway': 'eu',
    'oman': 'mea',
    'pakistan': 'mea',
    'panama': 'la',
    'peru': 'la',
    'philippines': 'ap',
    'poland': 'eu',
    'portugal': 'eu',
    'prc': 'gcg',
    'puerto rico': 'na',
    'qatar': 'mea',
    'reunion': 'la',
    'romania': 'eu',
    'rsa': 'mea',
    'russia': 'eu',
    'rwanda': 'mea',
    'saint vincent': 'eu',
    'saudi arabia': 'mea',
    'senegal': 'mea',
    'serbia': 'eu',
    'seychelles': 'mea',
    'sierra leone': 'mea',
    'singapore': 'gcg',
    'slovakia': 'eu',
    'slovenia': 'eu',
    'somalia': 'mea',
    'south africa': 'mea',
    'south korea': 'ap',
    'spain': 'eu',
    'sri lanka': 'ap',
    'surinam': 'na',
    'suriname': 'la',
    'swaziland': 'mea',
    'sweden': 'eu',
    'switzerland': 'eu',
    'syria': 'mea',
    'taiwan': 'gcg',
    'tajikistan': 'mea',
    'tanzania': 'mea',
    'thailand': 'ap',
    'the bahamas': 'la',
    'the netherlands': 'eu',
    'tobago': 'la',
    'tonga': 'mea',
    'trinidad': 'la',
    'trinidad and tobago': 'la',
    'tunisia': 'mea',
    'turkey': 'mea',
    'tw': 'ap',
    'uae': 'mea',
    'uganda': 'mea',
    'uk': 'eu',
    'ukraine': 'eu',
    'united arab emirates': 'mea',
    'united states': 'na',
    'united states of america': 'na',
    'united states of america (french frigate shoals)': 'na',
    'uruguay': 'la',
    'usa': 'na',
    'utd.arab.emir.': 'mea',
    'uzbekistan': 'mea',
    'venezuela': 'la',
    'vietnam': 'ap',
    'virgin is(brit)': 'eu',
    'virgin islands': 'eu',
    'yemen': 'mea',
    'zambia': 'mea',
    'zimbabwe': 'mea'}
