
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_dimesionality_learning_dict = {
    'account delivery management': [   'account delivery management',
                                       'project executive',
                                       'service availability manager'],
    'agile': ['agile', 'scrum'],
    'architect': [   'architect',
                     'architect',
                     'solution design',
                     'integrate',
                     'implement',
                     'micro service'],
    'backup': ['backup', 'backup and restore', 'backup as a service'],
    'big data': ['big data', 'big data', 'spark', 'hadoop'],
    'blockchain': ['blockchain'],
    'build and decomission': ['build and decomission', 'build and decomission'],
    'certification': [   'certification',
                         'itil foundation certification',
                         'itil certification',
                         'isc certification',
                         'pmi agile certified practitioner'],
    'cloud': [   'cloud',
                 'cloud',
                 'network skill',
                 'network',
                 'security',
                 'monitoring',
                 'cloud provider',
                 'cloud skill',
                 'private cloud',
                 'kubernetes',
                 'cloud computing platform',
                 'public cloud',
                 'journey to cloud',
                 'docker'],
    'data science': [   'data science',
                        'python',
                        'data scientist',
                        'data analyst',
                        'natural language processing',
                        'machine learning',
                        'python library',
                        'cognitive skill',
                        'math skill',
                        'analytics',
                        'data',
                        'analysis skill',
                        'search engine',
                        'watson',
                        'statistical algorithm',
                        'tensorflow',
                        'competitive analysis'],
    'database': [   'database',
                    'oracle sql developer',
                    'query',
                    'db2',
                    'data warehouse',
                    'database skill',
                    'data modeling skill',
                    'database administrator',
                    'data model'],
    'design thinking': [   'design thinking',
                           'design thinking',
                           'user research',
                           'usability skill',
                           'visualization skill',
                           'critical thinking'],
    'finances': [   'finances',
                    'finance',
                    'bank',
                    'human resources',
                    'microsoft excel',
                    'document',
                    'contract'],
    'hard skill': [   'hard skill',
                      'problem solving',
                      'upskill',
                      'innovation',
                      'subject matter expert',
                      'technical specialist',
                      'big data',
                      'data science',
                      'programming',
                      'cloud',
                      'blockchain',
                      'security',
                      'storage',
                      'architect',
                      'resiliency',
                      'mainframe',
                      'system administrator',
                      'certification'],
    'hires': [   'hires',
                 'new employee',
                 'human resourses',
                 'project transfer',
                 'talent acquisition',
                 'new manager'],
    'leadership': [   'leadership',
                      'leadership role',
                      'team lead',
                      'negotiation skill',
                      'communication skill',
                      'strategy',
                      'executive role',
                      'Team Skill',
                      'IBM Team',
                      'Coaching Skill',
                      'business process',
                      'manage',
                      'coach',
                      'mentor',
                      'focus',
                      'communication'],
    'mainframe': ['mainframe', 'mainframe operating system'],
    'management skill': ['management skill', 'project management'],
    'mandatory': [   'mandatory',
                     'data privacy',
                     'ginni rometty',
                     'guidline',
                     'compliance',
                     'harassment',
                     'password',
                     'ibm business process',
                     'think40',
                     'business conduct guideline',
                     'human resources',
                     'general data protection regulation',
                     'labor claim'],
    'middleware': ['middleware', 'middleware'],
    'office administration': [   'office administration',
                                 'office',
                                 'communication',
                                 'change management',
                                 'microsoft powerpoint',
                                 'microsoft',
                                 'microsoft excel',
                                 'document'],
    'programming': [   'programming',
                       'api',
                       'programming language',
                       'python',
                       'd3js',
                       'developer',
                       'angular',
                       'angularjs',
                       'sql',
                       'java',
                       'html',
                       'c_language',
                       'shell script',
                       'perl',
                       'visualization skill',
                       'Web Server',
                       'Programming Skill',
                       'application developer',
                       'IT Specialist',
                       'framework'],
    'project management': [   'project management',
                              'project manager',
                              'project plan',
                              'project management software',
                              'manufacturing method',
                              'management skill',
                              'plan',
                              'manager',
                              'customer',
                              'team lead',
                              'team',
                              'lead',
                              'management',
                              'business skill',
                              'marketing role',
                              'business process',
                              'Methodology',
                              'sap solution manager',
                              'marketing',
                              'sap solution manager',
                              'focus',
                              'microsoft powerpoint',
                              'microsoft',
                              'project management professional',
                              'bpm'],
    'resiliency': ['resiliency', 'scalability', 'availability'],
    'sales enablement': [   'sales enablement',
                            'sales role',
                            'sale',
                            'sales manager',
                            'retail',
                            'offering',
                            'marketing',
                            'customer',
                            'industry',
                            'contract'],
    'security': ['security', 'data security'],
    'service management': [   'service management',
                              'itil',
                              'configuration management',
                              'service management skill',
                              'support',
                              'service',
                              'Service Skill',
                              'Service Team',
                              'service level agreement',
                              'support',
                              'maintenance',
                              'license',
                              'Deployment Skill',
                              'compliance',
                              'itil',
                              'sap',
                              'change management'],
    'service now': ['service now', 'servicenow'],
    'soft skill': [   'soft skill',
                      'communication',
                      'assessment',
                      'conversation',
                      'collaboration',
                      'client skill',
                      'presentation',
                      'workshop',
                      'documentation',
                      'knowledge share',
                      'presentation skill'],
    'software': [   'software',
                    'sap erp',
                    'lotus notes',
                    'cognos',
                    'maximo',
                    'sap hana',
                    'microsoft excel',
                    'microsoft powerpoint',
                    'adobe photoshop',
                    'sap ariba',
                    'microsoft visual studio',
                    'spss',
                    'cognos',
                    'peoplesoft',
                    'powerbi',
                    'netezza',
                    'ibm q'],
    'storage': ['storage'],
    'system administrator': [   'system administrator',
                                'active directory',
                                'kubernetes',
                                'Deployment Skill',
                                'mainframe',
                                'server skill',
                                'migration',
                                'network skill',
                                'system',
                                'server',
                                'operating system',
                                'device',
                                'asset',
                                'environment',
                                'hardware',
                                'hardware skill',
                                'systems management specialist',
                                'infrastructure',
                                'infrastructure specialist',
                                'file system',
                                'protocol',
                                'routing protocol',
                                'network protocol',
                                'data communication hardware',
                                'vtam',
                                'monitor',
                                'systems management',
                                'network standard',
                                'system administrator',
                                'deployment skill'],
    'technical os': ['technical os', 'operating system'],
    'vmware': ['vmware', 'vmware company']}
