
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_dimesionality_supply_dict = {
    'academic': [   'academic',
                    'high_school',
                    'secondary_school',
                    'secondary_education',
                    'associate_degree',
                    'bachelor_degree',
                    'bachelor_of_science',
                    'bachelor_of_engineering',
                    'bachelor_of_technology',
                    'bachelor_of_computer_science',
                    'bachelor_of_other',
                    'bachelor_of_arts',
                    'masters_degree',
                    'master_of_arts',
                    'master_of_science',
                    'master_of_business',
                    'master_of_engineering',
                    'master_of_computer_science',
                    'phd'],
    'blockchain': [   'blockchain',
                      'Blockchain',
                      'Blockchain Company',
                      'Blockchain Infrastructure',
                      'Mining Protocol',
                      'Cryptocurrency',
                      'Hyperledger Fabric',
                      'Bitmain',
                      'Bitcoin Mining',
                      'ASIC Mining Protocol',
                      '51% Attack',
                      'Smart Contract',
                      'Distributed Ledger',
                      'Hyperledger',
                      'Blockchain Project',
                      'Altcoin',
                      'Ethereum'],
    'cloud': [   'cloud',
                 'cloud',
                 'network skill',
                 'network',
                 'security',
                 'cloud provider',
                 'cloud skill',
                 'private cloud',
                 'cloud computing platform',
                 'public cloud',
                 'internet of things',
                 'ibm cloud and smarter infrastructure',
                 'citrix',
                 'vmware company',
                 'citrix certified administrator',
                 'vmware software',
                 'vmware infrastructure',
                 'redhat',
                 'redhat company',
                 'kubernetes'],
    'database': [   'database',
                    'oracle sql developer',
                    'oracle',
                    'database administrator',
                    'db2',
                    'data warehouse',
                    'business intelligence',
                    'data architecture',
                    'data skill',
                    'hibernate',
                    'olap',
                    'oltp',
                    'database skill',
                    'database',
                    'data model',
                    'etl',
                    'back end',
                    'data',
                    'transaction processing',
                    'data artifact',
                    'information architecture',
                    'information developer',
                    'Knowledge Engineer',
                    'database design',
                    'query language',
                    'infosphere',
                    'python',
                    'data analyst',
                    'data scientist',
                    'natural language processing',
                    'analytical activity',
                    'analytics',
                    'data mining',
                    'process mining',
                    'data analysis skill',
                    'machine learning',
                    'cognitive training',
                    'cognitive testing',
                    'python library',
                    'cognitive skill',
                    'math skill',
                    'analysis skill',
                    'r',
                    'search engine',
                    'watson',
                    'chat bot',
                    'pig',
                    'visualization software',
                    'cognitive framework',
                    'mapreduce',
                    'hive',
                    'yarn'],
    'experience': ['experience', 'experience'],
    'hard skill': [   'hard skill',
                      'troubleshooting',
                      'debugging',
                      'software',
                      'technical framework',
                      'technical skill',
                      'architecture',
                      'software platform',
                      'software model',
                      'integration framework',
                      'information technology',
                      'solution manager',
                      'integration',
                      'product',
                      'formal language',
                      'object oriented',
                      'install',
                      'technical role',
                      'algorithm',
                      'specialist',
                      'architect',
                      'analyst',
                      'cryptography',
                      'software component',
                      'delivery role',
                      'technical services',
                      'optimization',
                      'design artifact',
                      'recovery',
                      'configuration',
                      'version control',
                      'optimization skill',
                      'research',
                      'algorithm',
                      'technical',
                      'computer science',
                      'certification',
                      'standard',
                      'cross platform',
                      'usability skill',
                      'scientific skill',
                      'testing',
                      'research skill',
                      'formal language'],
    'learning': [   'learning',
                    'learning provider',
                    'education',
                    'teaching skill',
                    'educational field',
                    'degree'],
    'other': ['other', 'domainterm', 'root', 'provenance'],
    'project management': [   'project management',
                              'project manager',
                              'management skill',
                              'plan',
                              'manager',
                              'transition manager',
                              'customer',
                              'team lead',
                              'team',
                              'lead',
                              'management',
                              'business skill',
                              'offering manager',
                              'operational role',
                              'marketing role',
                              'Project Management Software',
                              'roadmap',
                              'risk management',
                              'governance',
                              'framework',
                              'business network',
                              'assessment',
                              'estimation'],
    'quantum': [   'quantum',
                   'Quantum Computing',
                   'Majorana Fermion',
                   'Quantum Advantage',
                   'Quantum Interference',
                   'Quantum Parallelism',
                   'Quantum Entanglement',
                   'Quantum Bit',
                   'Quantum Information',
                   'Quantum Operation',
                   'Quantum Algorithms',
                   'Quantum Random Access Machine',
                   'Quantum Programming',
                   'Quantum Guarded Command Language',
                   'Qiskit',
                   'Quantum Assembly Language',
                   'Noisy Intermediate Scale Quantum',
                   'Quantum Complexity Theory',
                   'IBM Q',
                   'Libquantum',
                   'DiVincenzo Criteria',
                   'Quantum Computation Language'],
    'service management': [   'service management',
                              'support',
                              'service',
                              'asset',
                              'support',
                              'support services',
                              'monitoring',
                              'license',
                              'incident',
                              'availability',
                              'compliance',
                              'knowledge management',
                              'itil',
                              'problem',
                              'service level',
                              'service level agreement',
                              'change',
                              'maintain',
                              'kpi',
                              'manufacturing method',
                              'continuous improvement',
                              'IT Management Consultant',
                              'measurement',
                              'servicenow',
                              'ticket',
                              'performance professional',
                              'risk management',
                              'service manager',
                              'service coordinator',
                              'sap',
                              'upgrade',
                              'quality assurance',
                              'quality control',
                              'test user',
                              'end user',
                              'contract renewal',
                              'patching',
                              'risk mitigation'],
    'soft skill': [   'soft skill',
                      'appraisal',
                      'writing',
                      'document',
                      'training',
                      'proposal',
                      'People Manager',
                      'workshop',
                      'mentor',
                      'hosting',
                      'Strategy',
                      'customer',
                      'domain skill',
                      'communication',
                      'solution',
                      'natural language',
                      'organizational role',
                      'experience',
                      'methodology',
                      'administrative role',
                      'consulting',
                      'executive role',
                      'professional role',
                      'executive',
                      'strategic skill',
                      'business role',
                      'financial',
                      'revenue',
                      'leadership role',
                      'leadership',
                      'artifact',
                      'audit',
                      'business skill',
                      'business analyst',
                      'business development',
                      'insurance',
                      'teach',
                      'process management',
                      'emotional skill',
                      'solution representative',
                      'sales manager',
                      'business specialist',
                      'conversation',
                      'meeting',
                      'sales role'],
    'system administrator': [   'system administrator',
                                'mainframe',
                                'access failure',
                                'access attempt',
                                'server skill',
                                'configure',
                                'migrate',
                                'migration',
                                'network gateway',
                                'switch',
                                'business continuity',
                                'security',
                                'network skill',
                                'operating system',
                                'lightweight directory access protocol',
                                'system',
                                'performance',
                                'novell',
                                'performance management',
                                'authentication',
                                'server',
                                'operating system',
                                'device',
                                'asset',
                                'Peer-to-Peer',
                                'environment',
                                'hardware',
                                'hardware skill',
                                'systems management specialist',
                                'capacity',
                                'Cybersecurity Company',
                                'infrastructure',
                                'infrastructure specialist',
                                'file system',
                                'protocol',
                                'routing protocol',
                                'network protocol',
                                'data communication hardware',
                                'vtam',
                                'systems management',
                                'network standard',
                                'shell script',
                                'perl',
                                'infrastructure architect',
                                'linux',
                                'client server',
                                'platform',
                                'telecommunications',
                                'authorization',
                                'backup',
                                'encryption',
                                'scalability',
                                'security breach',
                                'security flaw',
                                'unavailability',
                                'resiliency',
                                'reliability',
                                'connectivity',
                                'system operator',
                                'system role',
                                'fault tolerant',
                                'platform specific']}
