
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_dimesionality_sentiment_dict = {
    'Appreciation': ['Appreciation', 'Recognition', 'Employee Appreciation'],
    'Assessments': [   'Assessments',
                       'Performance',
                       'Performance Appraisal',
                       'Performance Metric',
                       'Performance Optimization',
                       'Performance Professional',
                       'Performance Report',
                       'Assessment',
                       'Checkpoint',
                       'Checkpoint Certification',
                       'Plan Development'],
    'Behavior': [   'Behavior',
                    'Workload',
                    'Bureaucracy',
                    'Brand',
                    'Collaboration',
                    'Culture',
                    'Quality'],
    'Benefits': [   'Benefits',
                    'Benefit',
                    'Benefit Pay',
                    'Incidental Benefit',
                    'Health Care'],
    'Brand': ['Brand', 'Brand Management', 'Brand Role', 'Customer Behavior'],
    'Bureaucracy': ['Bureaucracy', 'Bad Process', 'Bad Quality', 'Defect'],
    'Career': [   'Career',
                  'Professional Growth',
                  'Role',
                  'Lateral Transfer',
                  'Enagements',
                  'Promotion',
                  'Skills'],
    'Chief Executive Officer': ['Chief Executive Officer', 'Ginni Rometty'],
    'Churn': [   'Churn',
                 'External Transfer',
                 'Job Posting',
                 'Employee Churn',
                 'Churn',
                 'External Transfer',
                 'Job Posting',
                 'Employee Churn'],
    'Clarity': ['Clarity', 'Focus', 'Vision'],
    'Client Delivery': ['Client Delivery', 'Deliverable', 'Delivery Model'],
    'Clients': [   'Clients',
                   'Client Success',
                   'Client Account',
                   'Client Environment',
                   'Client Focus',
                   'Client Growth',
                   'Client Meeting',
                   'Client Relationship',
                   'Client Request',
                   'Client Requirement',
                   'Client Role',
                   'Client Satisfaction',
                   'Client Skill',
                   'Client Transformation',
                   'Customer',
                   'Customer Benefit',
                   'Customer Engagement',
                   'Customer Service Lead',
                   'Customer Team',
                   'Client Delivery'],
    'Collaboration': [   'Collaboration',
                         'Responsiveness',
                         'Communication',
                         'Communication Skill',
                         'Knowledge Management',
                         'Knowledge Share',
                         'Conversation',
                         'Speak',
                         'Career Conversation'],
    'Colleagues': ['Colleagues', 'Employee', 'Manager', 'Senior Management'],
    'Cost Cutting': ['Cost Cutting', 'Cost Reduction', 'Credit Card'],
    'Culture': [   'Culture',
                   'Innovation',
                   'Workplace',
                   'Positive Workplace',
                   'Negative Workplace'],
    'Emotion': ['Emotion', 'Positive Emotion', 'Negative Emotion'],
    'Emotional Skill': [   'Emotional Skill',
                           'Empathy',
                           'Inspire',
                           'Listen',
                           'Mindfulness',
                           'Professionalism',
                           'Respect',
                           'Trust',
                           'Emotion',
                           'Motivation',
                           'Appreciation'],
    'Enagements': [   'Enagements',
                      'Engagement Process',
                      'Project',
                      'Project Administrator',
                      'Project Executive',
                      'Project Management',
                      'Project Management Professional',
                      'Project Plan',
                      'Project Status',
                      'Project Team',
                      'Line Management'],
    'Executive Leadership': [   'Executive Leadership',
                                'Executive',
                                'Executive Role',
                                'Chief Executive Officer',
                                'Chief Information Office'],
    'Harassment': [   'Harassment',
                      'Sexist Workplace',
                      'Sexual Harassment',
                      'Sexism',
                      'Bullying'],
    'Health': ['Health', 'Mental Health', 'Physical Health', 'Physical Health'],
    'Health Care': [   'Health Care',
                       'Medical Pay',
                       'Medical Benefit',
                       'Health Insurance',
                       'Health Informatics'],
    'Individual': ['Individual', 'Health', 'Benefits', 'Pay', 'Career'],
    'Industry': [   'Industry',
                    'Market Standard',
                    'Industry Trend',
                    'Industry',
                    'Alignment',
                    'Organizational Vision',
                    'Best Practice'],
    'Innovation': [   'Innovation',
                      'Inventor',
                      'Master Inventor',
                      'IBM Master Inventor',
                      'Innovative Role',
                      'Patent'],
    'Lateral Transfer': ['Lateral Transfer', 'Project Transfer'],
    'Leadership': [   'Leadership',
                      'Business Lead',
                      'Business Leadership',
                      'Clarity',
                      'Managers',
                      'Executive Leadership'],
    'Location': [   'Location',
                    'Offshore',
                    'Offshore Team',
                    'Remote Team',
                    'Home Office',
                    'Physical Location'],
    'Managers': ['Managers', 'Management', 'Management Skill'],
    'Motivation': ['Motivation', 'Learning Motivation', 'Passion'],
    'Negative Emotion': [   'Negative Emotion',
                            'Stress',
                            'Unsatisfied',
                            'Inadequate',
                            'Demotivated'],
    'Negative Employee Treatment': [   'Negative Employee Treatment',
                                       'Poor Workplace',
                                       'Negative Situation',
                                       'Bias',
                                       'Negative Morale',
                                       'Disagree',
                                       'Disruption',
                                       'Argument',
                                       'Demotivating',
                                       'Unsatisifed',
                                       'Employee Treatment',
                                       'Unmotivated'],
    'Negative Workplace': [   'Negative Workplace',
                              'High Workload',
                              'Overtime',
                              'Stress',
                              'Unavailability',
                              'Cost Cutting',
                              'Cost Reduction',
                              'Negative Employee Treatment',
                              'Harassment',
                              'Churn'],
    'Organization': [   'Organization',
                        'Structure',
                        'Revenue',
                        'Cost Cutting',
                        'Clients'],
    'Pay': [   'Pay',
               'Organizational Pay',
               'Bonus Pay',
               'Benefit Pay',
               'Medical Pay',
               'Severance Pay',
               'Salary',
               'Pay Level'],
    'Pay Level': [   'Pay Level',
                     'Low Pay Level',
                     'Pay Gap',
                     'Penalty',
                     'Pay Level Decrease',
                     'Pay Process',
                     'Poor Pay'],
    'Positive Emotion': ['Positive Emotion', 'Pleasure', 'Proud'],
    'Positive Workplace': [   'Positive Workplace',
                              'Positive Leadership',
                              'Collaborative Culture',
                              'Flexible Environment',
                              'Positive Morale',
                              'Positive Situation'],
    'Process': [   'Process',
                   'Process',
                   'Approval',
                   'Business Methodology',
                   'Management Methodology',
                   'Process',
                   'Regulation',
                   'Assessments'],
    'Promotion': [   'Promotion',
                     'Career Growth',
                     'Career Conversation',
                     'No Career Growth',
                     'No Change',
                     'No Promotion'],
    'Quality': [   'Quality',
                   'Good Quality',
                   'Bad Quality',
                   'Quality Assurance',
                   'Quality Control',
                   'Quality Management',
                   'Quality of Service',
                   'Quality Service'],
    'Regulation': [   'Regulation',
                      'Compliance',
                      'Audit',
                      'Contract',
                      'Contract Template',
                      'Contract Renewal',
                      'Policy',
                      'Regulation',
                      'Data Privacy',
                      'Data Quality',
                      'Data Management'],
    'Revenue': [   'Revenue',
                   'Spend Approval',
                   'Financial',
                   'Financial Measurement',
                   'Financial Plan',
                   'Financial Service',
                   'Financial Skill',
                   'Pricing Info',
                   'Pricing Process',
                   'Revenue Growth',
                   'Revenue Loss'],
    'Role': ['Role', 'Individual Role', 'Professional Role'],
    'Salary': [   'Salary',
                  'Professional Pay',
                  'Employee Pay',
                  'Cost Of Living',
                  'Low Pay Level'],
    'Skills': [   'Skills',
                  'Technical Skill',
                  'Technical Role',
                  'Skill',
                  'Skill Assessment',
                  'Skill Gap',
                  'Skill Level',
                  'Skill Set',
                  'High Skill',
                  'Experience',
                  'Low Skill',
                  'Domain Skills',
                  'No Skills Growth',
                  'Skills Growth'],
    'Skills Growth': [   'Skills Growth',
                         'Upskill',
                         'Education Policy',
                         'Training'],
    'Structure': [   'Structure',
                     'Organizational Benefit',
                     'Organizational Role',
                     'Organizational Structure'],
    'Training': [   'Training',
                    'Learning',
                    'Education',
                    'Domain Training',
                    'Tool Training',
                    'Online Training',
                    'Workshop'],
    'Workload': ['Workload', 'High Workload', 'Overtime', 'Stress'],
    'Workplace': [   'Workplace',
                     'Location',
                     'Colleagues',
                     'Resource Management',
                     'Support',
                     'IBM',
                     'Company',
                     'Environment',
                     'Awareness',
                     'Diversity',
                     'Workload',
                     'Team',
                     'Team Lead',
                     'IBM Team',
                     'Team Meeting',
                     'Team Skill',
                     'Equality',
                     'Upstander',
                     'Morale',
                     'Work Life Balance',
                     'Safety'],
    'Workshop': ['Workshop', 'Technical Workshop']}
