
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_rel_versions_dict = {
    'IBM WebSphere MQ': [   'WebSphere MQ Everyplace',
                            'WebSphere MQ Hypervisor',
                            'WebSphere MQ Hypervisor Edition',
                            'WebSphere MQ Hypervisor Edition for Red',
                            'WebSphere MQ Hypervisor Edition for Red Hat',
                            'WebSphere MQ Hypervisor Edition for Red Hat '
                            'Enterprise',
                            'WebSphere MQ Hypervisor Edition for Red Hat '
                            'Enterprise Linux',
                            'WebSphere MQ Hypervisor Edition for Red Hat '
                            'Enterprise Linux Server',
                            'WebSphere MQ Integrator',
                            'WebSphere MQ Integrator Broker',
                            'WebSphere MQ Integrator Broker for z/OS',
                            'WebSphere MQ Low',
                            'WebSphere MQ Low Latency',
                            'WebSphere MQ Low Latency Messaging',
                            'WebSphere MQ Workflow',
                            'WebSphere MQ Workflow for Multiplatforms',
                            'WebSphere MQ Workflow for z/OS',
                            'WebSphere MQ for z/OS'],
    'Lotus Connector': [   'Lotus Connector for SAP',
                           'Lotus Connector for SAP Solutions'],
    'Lotus Domino': [   'Lotus Domino Access',
                        'Lotus Domino Access for Microsoft',
                        'Lotus Domino Access for Microsoft Outlook',
                        'Lotus Domino Designer',
                        'Lotus Domino Document',
                        'Lotus Domino Document Manager'],
    'Lotus End': ['Lotus End of Support', 'Lotus End of Support Products'],
    'Lotus Enterprise': [   'Lotus Enterprise Integrator',
                            'Lotus Enterprise Integrator for Domino'],
    'Lotus Foundations': [   'Lotus Foundations Branch',
                             'Lotus Foundations Branch Office',
                             'Lotus Foundations Reach',
                             'Lotus Foundations Start'],
    'Lotus Protector': [   'Lotus Protector for Mail',
                           'Lotus Protector for Mail Encryption',
                           'Lotus Protector for Mail Security'],
    'Lotus Quickr': [   'Lotus Quickr Connectors',
                        'Lotus Quickr Content',
                        'Lotus Quickr Content Integrator',
                        'Lotus Quickr for Domino',
                        'Lotus Quickr for WebSphere',
                        'Lotus Quickr for WebSphere Portal'],
    'Maximo Adapter': [   'Maximo Adapter for Microsoft',
                          'Maximo Adapter for Microsoft Project',
                          'Maximo Adapter for Primavera'],
    'Maximo Archiving': [   'Maximo Archiving with Optim',
                            'Maximo Archiving with Optim Data',
                            'Maximo Archiving with Optim Data Growth',
                            'Maximo Archiving with Optim Data Growth Solution'],
    'Maximo Asset': [   'Maximo Asset Configuration',
                        'Maximo Asset Configuration Manager',
                        'Maximo Asset Management',
                        'Maximo Asset Management Essentials',
                        'Maximo Asset Management Scheduler',
                        'Maximo Asset Management for Energy',
                        'Maximo Asset Management for Energy Optimization',
                        'Maximo Asset Management for IT',
                        'Maximo Asset Navigator'],
    'Maximo Change': [   'Maximo Change Manager',
                         'Maximo Change and Corrective',
                         'Maximo Change and Corrective Action',
                         'Maximo Change and Corrective Action Manager'],
    'Maximo Compliance': ['Maximo Compliance Assistance Documentation'],
    'Maximo Contract': [   'Maximo Contract and Procurement',
                           'Maximo Contract and Procurement Manager'],
    'Maximo Data': [   'Maximo Data Center',
                       'Maximo Data Center Infrastructure',
                       'Maximo Data Center Infrastructure Management'],
    'Maximo Mobile': [   'Maximo Mobile Audit',
                         'Maximo Mobile Audit Manager',
                         'Maximo Mobile Audit Manager SE',
                         'Maximo Mobile Inventory',
                         'Maximo Mobile Inventory Manager',
                         'Maximo Mobile Inventory Manager SE',
                         'Maximo Mobile Suite',
                         'Maximo Mobile Work',
                         'Maximo Mobile Work Manager',
                         'Maximo Mobile Work Manager SE'],
    'Maximo Online': [   'Maximo Online Commerce',
                         'Maximo Online Commerce System'],
    'Maximo Space': [   'Maximo Space Management',
                        'Maximo Space Management for Facilities'],
    'Maximo Spatial': [   'Maximo Spatial Asset',
                          'Maximo Spatial Asset Management'],
    'Tivoli AF/Integrated': [   'Tivoli AF/Integrated Resource',
                                'Tivoli AF/Integrated Resource Manager'],
    'Tivoli AF/OPERATOR': ['Tivoli AF/OPERATOR on z/OS'],
    'Tivoli Access': [   'Tivoli Access Manager',
                         'Tivoli Access Manager for Business',
                         'Tivoli Access Manager for Business Integration',
                         'Tivoli Access Manager for Enterprise',
                         'Tivoli Access Manager for Enterprise Single',
                         'Tivoli Access Manager for Enterprise Single Sign-On',
                         'Tivoli Access Manager for Operating',
                         'Tivoli Access Manager for Operating Systems',
                         'Tivoli Access Manager for e-business'],
    'Tivoli Advanced': [   'Tivoli Advanced Audit',
                           'Tivoli Advanced Audit for DFSMShsm',
                           'Tivoli Advanced Backup',
                           'Tivoli Advanced Backup and Recovery',
                           'Tivoli Advanced Backup and Recovery for z/OS',
                           'Tivoli Advanced Catalog',
                           'Tivoli Advanced Catalog Management',
                           'Tivoli Advanced Catalog Management for z/OS',
                           'Tivoli Advanced Reporting',
                           'Tivoli Advanced Reporting for DFSMShsm'],
    'Tivoli Alert': [   'Tivoli Alert Adapter',
                        'Tivoli Alert Adapter for AF/REMOTE'],
    'Tivoli Allocation': [   'Tivoli Allocation Optimizer',
                             'Tivoli Allocation Optimizer for z/OS'],
    'Tivoli Analyzer': [   'Tivoli Analyzer for Lotus',
                           'Tivoli Analyzer for Lotus Domino'],
    'Tivoli Application': [   'Tivoli Application Dependency',
                              'Tivoli Application Dependency Discovery '
                              'Manager'],
    'Tivoli Asset': [   'Tivoli Asset Discovery',
                        'Tivoli Asset Discovery for Distributed',
                        'Tivoli Asset Discovery for z/OS',
                        'Tivoli Asset Management',
                        'Tivoli Asset Management for IT'],
    'Tivoli Automated': [   'Tivoli Automated Tape',
                            'Tivoli Automated Tape Allocation',
                            'Tivoli Automated Tape Allocation Manager for '
                            'z/OS'],
    'Tivoli Availability': [   'Tivoli Availability Process',
                               'Tivoli Availability Process Manager'],
    'Tivoli Business': [   'Tivoli Business Continuity',
                           'Tivoli Business Continuity Process Manager',
                           'Tivoli Business Service',
                           'Tivoli Business Service Manager',
                           'Tivoli Business Systems',
                           'Tivoli Business Systems Manager for z/OS'],
    'Tivoli Capacity': [   'Tivoli Capacity Process',
                           'Tivoli Capacity Process Manager'],
    'Tivoli Central': [   'Tivoli Central Control',
                          'Tivoli Central Control for ETEWatch'],
    'Tivoli Change': [   'Tivoli Change and Configuration Management',
                         'Tivoli Change and Configuration Management Database'],
    'Tivoli Command': [   'Tivoli Command Center',
                          'Tivoli Command Center for DB2plex',
                          'Tivoli Command Center for R/3',
                          'Tivoli Command Center for UNIX System Services'],
    'Tivoli Compliance': ['Tivoli Compliance Insight Manager'],
    'Tivoli Composite': [   'Tivoli Composite Application',
                            'Tivoli Composite Application Manager for '
                            'Application Diagnostics',
                            'Tivoli Composite Application Manager for '
                            'Applications',
                            'Tivoli Composite Application Manager for Internet',
                            'Tivoli Composite Application Manager for Internet '
                            'Service Monitoring',
                            'Tivoli Composite Application Manager for J2EE '
                            'Operations',
                            'Tivoli Composite Application Manager for '
                            'Microsoft',
                            'Tivoli Composite Application Manager for '
                            'Microsoft Applications',
                            'Tivoli Composite Application Manager for Response',
                            'Tivoli Composite Application Manager for Response '
                            'Time Tracking',
                            'Tivoli Composite Application Manager for SOA '
                            'Platform',
                            'Tivoli Composite Application Manager for '
                            'Transactions for z/OS',
                            'Tivoli Composite Application Manager for Web '
                            'Resources'],
    'Tivoli Comprehensive': ['Tivoli Comprehensive Network Address Translator'],
    'Tivoli Configuration': [   'Tivoli Configuration Manager',
                                'Tivoli Configuration Manager for Automated '
                                'Teller Machines'],
    'Tivoli Continuous': [   'Tivoli Continuous Data',
                             'Tivoli Continuous Data Protection',
                             'Tivoli Continuous Data Protection for Files'],
    'Tivoli Contract': ['Tivoli Contract Compliance Manager'],
    'Tivoli Decision': [   'Tivoli Decision Support',
                           'Tivoli Decision Support for z/OS'],
    'Tivoli Directory': [   'Tivoli Directory Integrator',
                            'Tivoli Directory Integrator General Purpose '
                            'Edition for z/OS',
                            'Tivoli Directory Server'],
    'Tivoli Dynamic': [   'Tivoli Dynamic Workload',
                          'Tivoli Dynamic Workload Broker'],
    'Tivoli ETEWatch': [   'Tivoli ETEWatch Customizer',
                           'Tivoli ETEWatch Customizer for the',
                           'Tivoli ETEWatch Customizer for the Enterprise',
                           'Tivoli ETEWatch Customizer for the Single',
                           'Tivoli ETEWatch Customizer for the Single User',
                           'Tivoli ETEWatch Enterprise',
                           'Tivoli ETEWatch Enterprise Edition',
                           'Tivoli ETEWatch Starter',
                           'Tivoli ETEWatch Starter Kit',
                           'Tivoli ETEWatch Starter Kit - Professional',
                           'Tivoli ETEWatch Starter Kit - Professional Edition',
                           'Tivoli ETEWatch for Citrix',
                           'Tivoli ETEWatch for Citrix Metaframe',
                           'Tivoli ETEWatch for Citrix Metaframe Starter',
                           'Tivoli ETEWatch for Citrix Metaframe Starter Kit',
                           'Tivoli ETEWatch for Citrix Sessions',
                           'Tivoli ETEWatch for Custom',
                           'Tivoli ETEWatch for Custom Applications',
                           'Tivoli ETEWatch for Networked Applications '
                           'Behavior Module',
                           'Tivoli ETEWatch for Networked Applications '
                           'Behavior Module for Citrix Metaframe',
                           'Tivoli ETEWatch for TN3270'],
    'Tivoli Endpoint': [   'Tivoli Endpoint Manager',
                           'Tivoli Endpoint Manager for Core',
                           'Tivoli Endpoint Manager for Core Protection',
                           'Tivoli Endpoint Manager for Software',
                           'Tivoli Endpoint Manager for Software Use',
                           'Tivoli Endpoint Manager for Software Use Analysis'],
    'Tivoli Event': ['Tivoli Event Pump', 'Tivoli Event Pump for z/OS'],
    'Tivoli Federated': [   'Tivoli Federated Identity',
                            'Tivoli Federated Identity Manager',
                            'Tivoli Federated Identity Manager Business',
                            'Tivoli Federated Identity Manager Business '
                            'Gateway',
                            'Tivoli Federated Identity Manager for z/OS'],
    'Tivoli Foundations': [   'Tivoli Foundations Application',
                              'Tivoli Foundations Application Manager',
                              'Tivoli Foundations Service',
                              'Tivoli Foundations Service Manager'],
    'Tivoli Identity': [   'Tivoli Identity Manager',
                           'Tivoli Identity Manager Express',
                           'Tivoli Identity and Access',
                           'Tivoli Identity and Access Assurance',
                           'Tivoli Identity and Access Manager'],
    'Tivoli Information': [   'Tivoli Information Management',
                              'Tivoli Information Management for z/OS'],
    'Tivoli IntelliWatch': [   'Tivoli IntelliWatch Pinnacle',
                               'Tivoli IntelliWatch Pinnacle for Distributed',
                               'Tivoli IntelliWatch Pinnacle for Distributed '
                               'Systems'],
    'Tivoli Key': [   'Tivoli Key Lifecycle',
                      'Tivoli Key Lifecycle Manager',
                      'Tivoli Key Lifecycle Manager for Storage',
                      'Tivoli Key Lifecycle Manager for z/OS'],
    'Tivoli License': [   'Tivoli License Compliance Manager',
                          'Tivoli License Compliance Manager for z/OS'],
    'Tivoli Management': [   'Tivoli Management Framework',
                             'Tivoli Management Solution',
                             'Tivoli Management Solution for Exchange',
                             'Tivoli Management Solution for Microsoft',
                             'Tivoli Management Solution for Microsoft SQL'],
    'Tivoli Monitoring': [   'Tivoli Monitoring Active',
                             'Tivoli Monitoring Active Directory',
                             'Tivoli Monitoring Active Directory Option',
                             'Tivoli Monitoring Express',
                             'Tivoli Monitoring V6',
                             'Tivoli Monitoring for Applications',
                             'Tivoli Monitoring for Business',
                             'Tivoli Monitoring for Business Integration',
                             'Tivoli Monitoring for Cluster',
                             'Tivoli Monitoring for Cluster Managers',
                             'Tivoli Monitoring for Energy',
                             'Tivoli Monitoring for Energy Management',
                             'Tivoli Monitoring for Messaging',
                             'Tivoli Monitoring for Messaging and '
                             'Collaboration',
                             'Tivoli Monitoring for Microsoft',
                             'Tivoli Monitoring for Microsoft .NET',
                             'Tivoli Monitoring for Network Performance',
                             'Tivoli Monitoring for Virtual',
                             'Tivoli Monitoring for Virtual Environments',
                             'Tivoli Monitoring for Virtual Servers'],
    'Tivoli NetView': [   'Tivoli NetView Access',
                          'Tivoli NetView Access Services',
                          'Tivoli NetView Distribution',
                          'Tivoli NetView Distribution Manager',
                          'Tivoli NetView File',
                          'Tivoli NetView File Transfer',
                          'Tivoli NetView File Transfer Program',
                          'Tivoli NetView Performance',
                          'Tivoli NetView Performance Monitor',
                          'Tivoli NetView for z/OS'],
    'Tivoli Netcool': [   'Tivoli Netcool Carrier',
                          'Tivoli Netcool Carrier VoIP',
                          'Tivoli Netcool Carrier VoIP Manager',
                          'Tivoli Netcool Configuration',
                          'Tivoli Netcool Configuration Manager',
                          'Tivoli Netcool Network Mediation',
                          'Tivoli Netcool Performance',
                          'Tivoli Netcool Performance Flow',
                          'Tivoli Netcool Performance Flow Analyzer',
                          'Tivoli Netcool Performance Manager',
                          'Tivoli Netcool Performance Manager for Wireless',
                          'Tivoli Netcool Service',
                          'Tivoli Netcool Service Quality',
                          'Tivoli Netcool Service Quality Manager'],
    'Tivoli Network': [   'Tivoli Network Manager Entry Edition',
                          'Tivoli Network Manager IP Edition',
                          'Tivoli Network Manager Transmission Edition'],
    'Tivoli OMEGACENTER': [   'Tivoli OMEGACENTER Gateway',
                              'Tivoli OMEGACENTER Gateway on z/OS'],
    'Tivoli OMEGAMON': [   'Tivoli OMEGAMON Alert',
                           'Tivoli OMEGAMON Alert Manager',
                           'Tivoli OMEGAMON DE',
                           'Tivoli OMEGAMON DE for Distributed',
                           'Tivoli OMEGAMON DE for Distributed and z/OS',
                           'Tivoli OMEGAMON DE for Distributed and z/OS '
                           'Systems',
                           'Tivoli OMEGAMON DE for WebSphere',
                           'Tivoli OMEGAMON DE for WebSphere Application',
                           'Tivoli OMEGAMON DE for WebSphere Application '
                           'Server',
                           'Tivoli OMEGAMON DE for WebSphere Application '
                           'Server on Distributed Systems',
                           'Tivoli OMEGAMON DE for WebSphere Application '
                           'Server on OS/390',
                           'Tivoli OMEGAMON DE for WebSphere MQ',
                           'Tivoli OMEGAMON DE for WebSphere MQ Integrator',
                           'Tivoli OMEGAMON DE for WebSphere MQ Integrator on '
                           'Distributed Systems',
                           'Tivoli OMEGAMON DE on z/OS',
                           'Tivoli OMEGAMON II',
                           'Tivoli OMEGAMON II for DB2',
                           'Tivoli OMEGAMON Monitoring',
                           'Tivoli OMEGAMON Monitoring Agent',
                           'Tivoli OMEGAMON Monitoring Agent for MQSeries',
                           'Tivoli OMEGAMON Monitoring Agent for MQSeries on '
                           'Distributed Systems',
                           'Tivoli OMEGAMON XE',
                           'Tivoli OMEGAMON XE Management',
                           'Tivoli OMEGAMON XE Management Pac',
                           'Tivoli OMEGAMON XE Management Pac for WebSphere',
                           'Tivoli OMEGAMON XE Management Pac for WebSphere MQ '
                           'on Distributed Systems',
                           'Tivoli OMEGAMON XE for CICS',
                           'Tivoli OMEGAMON XE for CICS Transaction',
                           'Tivoli OMEGAMON XE for CICS Transaction Gateway on '
                           'z/OS',
                           'Tivoli OMEGAMON XE for CICS on z/OS',
                           'Tivoli OMEGAMON XE for DB2',
                           'Tivoli OMEGAMON XE for DB2 Performance',
                           'Tivoli OMEGAMON XE for DB2 Performance Expert on '
                           'z/OS',
                           'Tivoli OMEGAMON XE for DB2 Performance Monitor on '
                           'z/OS',
                           'Tivoli OMEGAMON XE for DB2 on z/OS',
                           'Tivoli OMEGAMON XE for DB2plex',
                           'Tivoli OMEGAMON XE for Distributed',
                           'Tivoli OMEGAMON XE for Distributed Systems',
                           'Tivoli OMEGAMON XE for IBM',
                           'Tivoli OMEGAMON XE for IBM Cryptographic',
                           'Tivoli OMEGAMON XE for IBM Cryptographic '
                           'CoProcessors',
                           'Tivoli OMEGAMON XE for IMS',
                           'Tivoli OMEGAMON XE for IMS on z/OS',
                           'Tivoli OMEGAMON XE for IMSplex',
                           'Tivoli OMEGAMON XE for Linux',
                           'Tivoli OMEGAMON XE for Linux on zSeries',
                           'Tivoli OMEGAMON XE for Mainframe',
                           'Tivoli OMEGAMON XE for Mainframe Networks',
                           'Tivoli OMEGAMON XE for Messaging',
                           'Tivoli OMEGAMON XE for Messaging for Distributed '
                           'Systems',
                           'Tivoli OMEGAMON XE for Messaging for z/OS',
                           'Tivoli OMEGAMON XE for Microsoft',
                           'Tivoli OMEGAMON XE for Microsoft .NET',
                           'Tivoli OMEGAMON XE for OS/390',
                           'Tivoli OMEGAMON XE for OS/390 USS',
                           'Tivoli OMEGAMON XE for Storage',
                           'Tivoli OMEGAMON XE for Storage on z/OS',
                           'Tivoli OMEGAMON XE for Sysplex',
                           'Tivoli OMEGAMON XE for WebSphere',
                           'Tivoli OMEGAMON XE for WebSphere Application',
                           'Tivoli OMEGAMON XE for WebSphere Application '
                           'Server',
                           'Tivoli OMEGAMON XE for WebSphere Application '
                           'Server for Linux',
                           'Tivoli OMEGAMON XE for WebSphere Application '
                           'Server for Linux on zSeries',
                           'Tivoli OMEGAMON XE for WebSphere Application '
                           'Server on z/OS',
                           'Tivoli OMEGAMON XE for WebSphere Integration',
                           'Tivoli OMEGAMON XE for WebSphere Integration '
                           'Brokers',
                           'Tivoli OMEGAMON XE for WebSphere Integration '
                           'Brokers for Distributed Systems',
                           'Tivoli OMEGAMON XE for WebSphere Integration '
                           'Brokers on Linux',
                           'Tivoli OMEGAMON XE for WebSphere Integration '
                           'Brokers on Linux on zSeries',
                           'Tivoli OMEGAMON XE for WebSphere InterChange',
                           'Tivoli OMEGAMON XE for WebSphere InterChange '
                           'Server',
                           'Tivoli OMEGAMON XE for WebSphere MQ',
                           'Tivoli OMEGAMON XE for WebSphere MQ on z/OS',
                           'Tivoli OMEGAMON XE on z/OS',
                           'Tivoli OMEGAMON XE on z/VM',
                           'Tivoli OMEGAMON XE on z/VM and Linux'],
    'Tivoli OMNIbus': ['Tivoli OMNIbus and Network Manager'],
    'Tivoli Output': [   'Tivoli Output Manager',
                         'Tivoli Output Manager for z/OS'],
    'Tivoli Performance': [   'Tivoli Performance Analyzer',
                              'Tivoli Performance Modeler',
                              'Tivoli Performance Modeler for z/OS'],
    'Tivoli Policy': [   'Tivoli Policy Driven',
                         'Tivoli Policy Driven Software',
                         'Tivoli Policy Driven Software Distribution'],
    'Tivoli Privacy': [   'Tivoli Privacy Manager',
                          'Tivoli Privacy Manager for e-business'],
    'Tivoli Provisioning': [   'Tivoli Provisioning Manager',
                               'Tivoli Provisioning Manager Express',
                               'Tivoli Provisioning Manager Express for '
                               'Inventory',
                               'Tivoli Provisioning Manager Express for '
                               'Software Distribution',
                               'Tivoli Provisioning Manager for Images',
                               'Tivoli Provisioning Manager for Images System '
                               'x',
                               'Tivoli Provisioning Manager for OS',
                               'Tivoli Provisioning Manager for OS Deployment',
                               'Tivoli Provisioning Manager for OS Deployment '
                               'IBM Systems Director Edition',
                               'Tivoli Provisioning Manager for Software'],
    'Tivoli Release': [   'Tivoli Release Process',
                          'Tivoli Release Process Manager'],
    'Tivoli Security': [   'Tivoli Security Compliance',
                           'Tivoli Security Compliance Manager',
                           'Tivoli Security Information',
                           'Tivoli Security Information and Event',
                           'Tivoli Security Information and Event Manager',
                           'Tivoli Security Management',
                           'Tivoli Security Management for z/OS',
                           'Tivoli Security Operations',
                           'Tivoli Security Operations Manager',
                           'Tivoli Security Policy',
                           'Tivoli Security Policy Manager'],
    'Tivoli Service': [   'Tivoli Service Automation',
                          'Tivoli Service Automation Manager',
                          'Tivoli Service Level',
                          'Tivoli Service Level Advisor',
                          'Tivoli Service Manager',
                          'Tivoli Service Manager Quick',
                          'Tivoli Service Manager Quick Install',
                          'Tivoli Service Request',
                          'Tivoli Service Request Manager'],
    'Tivoli Storage': [   'Tivoli Storage FlashCopy',
                          'Tivoli Storage FlashCopy Manager',
                          'Tivoli Storage Manager',
                          'Tivoli Storage Manager Express',
                          'Tivoli Storage Manager Express for Microsoft',
                          'Tivoli Storage Manager Express for Microsoft '
                          'Exchange',
                          'Tivoli Storage Manager Express for Microsoft SQL',
                          'Tivoli Storage Manager Extended',
                          'Tivoli Storage Manager Extended Edition',
                          'Tivoli Storage Manager FastBack',
                          'Tivoli Storage Manager FastBack Center',
                          'Tivoli Storage Manager FastBack for Bare',
                          'Tivoli Storage Manager FastBack for Bare Machine',
                          'Tivoli Storage Manager FastBack for Bare Machine '
                          'Recovery',
                          'Tivoli Storage Manager FastBack for Microsoft',
                          'Tivoli Storage Manager FastBack for Microsoft '
                          'Exchange',
                          'Tivoli Storage Manager FastBack for Workstations',
                          'Tivoli Storage Manager HSM',
                          'Tivoli Storage Manager HSM for Windows',
                          'Tivoli Storage Manager Suite',
                          'Tivoli Storage Manager Suite for Unified',
                          'Tivoli Storage Manager Suite for Unified Recovery',
                          'Tivoli Storage Manager Suite for Unified Recovery '
                          'Entry',
                          'Tivoli Storage Manager for Advanced',
                          'Tivoli Storage Manager for Advanced Copy',
                          'Tivoli Storage Manager for Advanced Copy Services',
                          'Tivoli Storage Manager for Copy',
                          'Tivoli Storage Manager for Copy Services',
                          'Tivoli Storage Manager for Databases',
                          'Tivoli Storage Manager for Enterprise',
                          'Tivoli Storage Manager for Enterprise Resource',
                          'Tivoli Storage Manager for Enterprise Resource '
                          'Planning',
                          'Tivoli Storage Manager for Hardware',
                          'Tivoli Storage Manager for Mail',
                          'Tivoli Storage Manager for Microsoft',
                          'Tivoli Storage Manager for Microsoft SharePoint',
                          'Tivoli Storage Manager for Space',
                          'Tivoli Storage Manager for Space Management',
                          'Tivoli Storage Manager for Storage',
                          'Tivoli Storage Manager for Storage Area',
                          'Tivoli Storage Manager for Storage Area Networks',
                          'Tivoli Storage Manager for System',
                          'Tivoli Storage Manager for System Backup',
                          'Tivoli Storage Manager for System Backup and '
                          'Recovery',
                          'Tivoli Storage Manager for Virtual',
                          'Tivoli Storage Manager for Virtual Environments',
                          'Tivoli Storage Optimizer',
                          'Tivoli Storage Optimizer for z/OS',
                          'Tivoli Storage Process',
                          'Tivoli Storage Process Manager',
                          'Tivoli Storage Productivity',
                          'Tivoli Storage Productivity Center',
                          'Tivoli Storage Productivity Center Advanced',
                          'Tivoli Storage Productivity Center Basic',
                          'Tivoli Storage Productivity Center Basic Edition',
                          'Tivoli Storage Productivity Center Select',
                          'Tivoli Storage Productivity Center Select Edition',
                          'Tivoli Storage Productivity Center Standard',
                          'Tivoli Storage Productivity Center Standard Edition',
                          'Tivoli Storage Productivity Center for Data',
                          'Tivoli Storage Productivity Center for Disk',
                          'Tivoli Storage Productivity Center for Disk Select',
                          'Tivoli Storage Productivity Center for Replication',
                          'Tivoli Storage Resource',
                          'Tivoli Storage Resource Manager',
                          'Tivoli Storage Resource Manager for Chargeback',
                          'Tivoli Storage Resource Manager for Databases'],
    'Tivoli System': [   'Tivoli System Automation',
                         'Tivoli System Automation Application',
                         'Tivoli System Automation Application Manager',
                         'Tivoli System Automation for Integrated',
                         'Tivoli System Automation for Integrated Operations',
                         'Tivoli System Automation for Integrated Operations '
                         'Management',
                         'Tivoli System Automation for Multiplatforms',
                         'Tivoli System Automation for z/OS'],
    'Tivoli Tape': ['Tivoli Tape Optimizer', 'Tivoli Tape Optimizer on z/OS'],
    'Tivoli Unified': [   'Tivoli Unified Process',
                          'Tivoli Unified Process Composer',
                          'Tivoli Unified Single',
                          'Tivoli Unified Single Sign-On'],
    'Tivoli Usage': [   'Tivoli Usage and Accounting',
                        'Tivoli Usage and Accounting Manager',
                        'Tivoli Usage and Accounting Manager Enterprise',
                        'Tivoli Usage and Accounting Manager Enterprise '
                        'Edition',
                        'Tivoli Usage and Accounting Manager for z/OS'],
    'Tivoli Web': [   'Tivoli Web Access',
                      'Tivoli Web Access for Information',
                      'Tivoli Web Access for Information Management',
                      'Tivoli Web Availability',
                      'Tivoli Web Availability Monitor',
                      'Tivoli Web Response',
                      'Tivoli Web Response Monitor',
                      'Tivoli Web Segment',
                      'Tivoli Web Segment Analyzer',
                      'Tivoli Web Site',
                      'Tivoli Web Site Analyzer'],
    'Tivoli Workload': [   'Tivoli Workload Scheduler',
                           'Tivoli Workload Scheduler LoadLeveler',
                           'Tivoli Workload Scheduler for Applications',
                           'Tivoli Workload Scheduler for Virtualized',
                           'Tivoli Workload Scheduler for Virtualized Data',
                           'Tivoli Workload Scheduler for Virtualized Data '
                           'Centers',
                           'Tivoli Workload Scheduler for z/OS'],
    'Tivoli zSecure': [   'Tivoli zSecure Admin',
                          'Tivoli zSecure Alert',
                          'Tivoli zSecure Alert for ACF2',
                          'Tivoli zSecure Alert for RACF',
                          'Tivoli zSecure Audit',
                          'Tivoli zSecure Audit for ACF2',
                          'Tivoli zSecure Audit for RACF',
                          'Tivoli zSecure Audit for Top',
                          'Tivoli zSecure Audit for Top Secret',
                          'Tivoli zSecure CICS',
                          'Tivoli zSecure CICS Toolkit',
                          'Tivoli zSecure Command',
                          'Tivoli zSecure Command Verifier',
                          'Tivoli zSecure Manager',
                          'Tivoli zSecure Manager for RACF',
                          'Tivoli zSecure Manager for RACF z/VM',
                          'Tivoli zSecure Visual'],
    'WebSphere Adapter': [   'WebSphere Adapter for File',
                             'WebSphere Adapter for File Transfer',
                             'WebSphere Adapter for File Transfer Protocol',
                             'WebSphere Adapter for JD',
                             'WebSphere Adapter for JD Edwards',
                             'WebSphere Adapter for JD Edwards EnterpriseOne',
                             'WebSphere Adapter for Oracle',
                             'WebSphere Adapter for Oracle E-Business',
                             'WebSphere Adapter for Oracle E-Business Suite'],
    'WebSphere Appliance': [   'WebSphere Appliance Management',
                               'WebSphere Appliance Management Center'],
    'WebSphere Application': [   'WebSphere Application Accelerator',
                                 'WebSphere Application Accelerator for Hybrid',
                                 'WebSphere Application Accelerator for Hybrid '
                                 'Networks',
                                 'WebSphere Application Accelerator for Public '
                                 'Networks',
                                 'WebSphere Application Server',
                                 'WebSphere Application Server - Express',
                                 'WebSphere Application Server Community',
                                 'WebSphere Application Server Community '
                                 'Edition',
                                 'WebSphere Application Server Hypervisor',
                                 'WebSphere Application Server Hypervisor '
                                 'Edition',
                                 'WebSphere Application Server Network '
                                 'Deployment',
                                 'WebSphere Application Server for z/OS'],
    'WebSphere Business': [   'WebSphere Business Compass',
                              'WebSphere Business Events',
                              'WebSphere Business Integration',
                              'WebSphere Business Integration Connect',
                              'WebSphere Business Integration Connect '
                              'Enterprise',
                              'WebSphere Business Integration Connect '
                              'Enterprise Edition',
                              'WebSphere Business Integration Express',
                              'WebSphere Business Integration Express for Item',
                              'WebSphere Business Integration Express for Item '
                              'Synchronization',
                              'WebSphere Business Integration Server',
                              'WebSphere Business Integration Server Express',
                              'WebSphere Business Integration Server '
                              'Foundation',
                              'WebSphere Business Integration Server '
                              'Foundation for z/OS',
                              'WebSphere Business Integration Toolset',
                              'WebSphere Business Integration Workbench',
                              'WebSphere Business Integration Workbench Server',
                              'WebSphere Business Integration for Financial',
                              'WebSphere Business Integration for Financial '
                              'Networks',
                              'WebSphere Business Modeler',
                              'WebSphere Business Modeler Advanced',
                              'WebSphere Business Modeler Basic',
                              'WebSphere Business Modeler Publishing',
                              'WebSphere Business Modeler Publishing Server',
                              'WebSphere Business Monitor',
                              'WebSphere Business Services',
                              'WebSphere Business Services Fabric'],
    'WebSphere Cast': [   'WebSphere Cast Iron',
                          'WebSphere Cast Iron Cloud',
                          'WebSphere Cast Iron Cloud integration'],
    'WebSphere Commerce': [   'WebSphere Commerce - Express',
                              'WebSphere Commerce Enterprise',
                              'WebSphere Commerce Professional'],
    'WebSphere Data': [   'WebSphere Data Interchange',
                          'WebSphere Data Interchange for z/OS'],
    'WebSphere DataPower': [   'WebSphere DataPower B2B',
                               'WebSphere DataPower B2B Appliance',
                               'WebSphere DataPower B2B Appliance XB60',
                               'WebSphere DataPower Edge',
                               'WebSphere DataPower Edge Appliance',
                               'WebSphere DataPower Edge Appliance XE82',
                               'WebSphere DataPower Integration',
                               'WebSphere DataPower Integration Appliance',
                               'WebSphere DataPower Integration Appliance XI50',
                               'WebSphere DataPower Low',
                               'WebSphere DataPower Low Latency',
                               'WebSphere DataPower Low Latency Appliance',
                               'WebSphere DataPower Low Latency Appliance XM70',
                               'WebSphere DataPower SOA',
                               'WebSphere DataPower SOA Appliances',
                               'WebSphere DataPower Service',
                               'WebSphere DataPower Service Gateway',
                               'WebSphere DataPower Service Gateway XG45',
                               'WebSphere DataPower XC10',
                               'WebSphere DataPower XC10 Appliance',
                               'WebSphere DataPower XML',
                               'WebSphere DataPower XML Accelerator',
                               'WebSphere DataPower XML Accelerator XA35',
                               'WebSphere DataPower XML Security',
                               'WebSphere DataPower XML Security Gateway',
                               'WebSphere DataPower XML Security Gateway XS40'],
    'WebSphere Decision': [   'WebSphere Decision Center',
                              'WebSphere Decision Center for z/OS',
                              'WebSphere Decision Server',
                              'WebSphere Decision Server for z/OS'],
    'WebSphere Developer': [   'WebSphere Developer Debugger',
                               'WebSphere Developer Debugger for System',
                               'WebSphere Developer Debugger for System z',
                               'WebSphere Developer for System',
                               'WebSphere Developer for System z',
                               'WebSphere Developer for z/Series'],
    'WebSphere Development': [   'WebSphere Development Studio',
                                 'WebSphere Development Studio Client Advanced '
                                 'Edition for iSeries',
                                 'WebSphere Development Studio Client for '
                                 'System i',
                                 'WebSphere Development Studio for System i'],
    'WebSphere Digital': [   'WebSphere Digital Media',
                             'WebSphere Digital Media Enabler'],
    'WebSphere Dynamic': [   'WebSphere Dynamic Process',
                             'WebSphere Dynamic Process Edition'],
    'WebSphere End': [   'WebSphere End of Support',
                         'WebSphere End of Support Products'],
    'WebSphere Enterprise': [   'WebSphere Enterprise Service',
                                'WebSphere Enterprise Service Bus',
                                'WebSphere Enterprise Service Bus Registry',
                                'WebSphere Enterprise Service Bus Registry '
                                'Edition'],
    'WebSphere Event': [   'WebSphere Event Broker',
                           'WebSphere Event Broker for Multiplatforms',
                           'WebSphere Event Broker for z/OS'],
    'WebSphere Everyplace': [   'WebSphere Everyplace Client',
                                'WebSphere Everyplace Client Toolkit',
                                'WebSphere Everyplace Custom',
                                'WebSphere Everyplace Custom Environment',
                                'WebSphere Everyplace Micro',
                                'WebSphere Everyplace Micro Environment',
                                'WebSphere Everyplace Server',
                                'WebSphere Everyplace Server for Telecom'],
    'WebSphere Front': [   'WebSphere Front Office',
                           'WebSphere Front Office for Financial',
                           'WebSphere Front Office for Financial Markets'],
    'WebSphere Host': [   'WebSphere Host Access',
                          'WebSphere Host Access Transformation',
                          'WebSphere Host Access Transformation Services',
                          'WebSphere Host Publisher'],
    'WebSphere ILOG': [   'WebSphere ILOG Decision',
                          'WebSphere ILOG Decision Validation',
                          'WebSphere ILOG Decision Validation Services',
                          'WebSphere ILOG JRules',
                          'WebSphere ILOG Rule',
                          'WebSphere ILOG Rule Solutions',
                          'WebSphere ILOG Rule Solutions for Office',
                          'WebSphere ILOG Rule Team',
                          'WebSphere ILOG Rule Team Server',
                          'WebSphere ILOG Rule Team Server for .NET',
                          'WebSphere ILOG Rules',
                          'WebSphere ILOG Rules for .NET',
                          'WebSphere ILOG Rules for COBOL'],
    'WebSphere IP': [   'WebSphere IP Multimedia',
                        'WebSphere IP Multimedia Subsystem',
                        'WebSphere IP Multimedia Subsystem Connector'],
    'WebSphere Industry': [   'WebSphere Industry Content',
                              'WebSphere Industry Content Packs'],
    'WebSphere MQ': [   'WebSphere MQ Everyplace',
                        'WebSphere MQ Hypervisor',
                        'WebSphere MQ Hypervisor Edition',
                        'WebSphere MQ Hypervisor Edition for Red',
                        'WebSphere MQ Hypervisor Edition for Red Hat',
                        'WebSphere MQ Hypervisor Edition for Red Hat '
                        'Enterprise',
                        'WebSphere MQ Hypervisor Edition for Red Hat '
                        'Enterprise Linux',
                        'WebSphere MQ Hypervisor Edition for Red Hat '
                        'Enterprise Linux Server',
                        'WebSphere MQ Integrator',
                        'WebSphere MQ Integrator Broker',
                        'WebSphere MQ Integrator Broker for z/OS',
                        'WebSphere MQ Low',
                        'WebSphere MQ Low Latency',
                        'WebSphere MQ Low Latency Messaging',
                        'WebSphere MQ Workflow',
                        'WebSphere MQ Workflow for Multiplatforms',
                        'WebSphere MQ Workflow for z/OS',
                        'WebSphere MQ for z/OS'],
    'WebSphere Message': [   'WebSphere Message Broker',
                             'WebSphere Message Broker Connectivity Pack for '
                             'Healthcare',
                             'WebSphere Message Broker File',
                             'WebSphere Message Broker File Extender',
                             'WebSphere Message Broker for z/OS',
                             'WebSphere Message Broker with Rules',
                             'WebSphere Message Broker with Rules and '
                             'Formatter',
                             'WebSphere Message Broker with Rules and '
                             'Formatter Extension',
                             'WebSphere Message Broker with Rules and '
                             'Formatter Extension for Multiplatforms'],
    'WebSphere Multichannel': [   'WebSphere Multichannel Bank Transformation '
                                  'Toolkit'],
    'WebSphere Operational': [   'WebSphere Operational Decision',
                                 'WebSphere Operational Decision Management',
                                 'WebSphere Operational Decision Management '
                                 'for z/OS'],
    'WebSphere Partner': [   'WebSphere Partner Gateway',
                             'WebSphere Partner Gateway - Express',
                             'WebSphere Partner Gateway Advanced',
                             'WebSphere Partner Gateway Advanced Edition',
                             'WebSphere Partner Gateway Enterprise',
                             'WebSphere Partner Gateway Enterprise Edition'],
    'WebSphere Portal': [   'WebSphere Portal End',
                            'WebSphere Portal End of Support',
                            'WebSphere Portal End of Support Products'],
    'WebSphere Process': [   'WebSphere Process Server',
                             'WebSphere Process Server Hypervisor',
                             'WebSphere Process Server Hypervisor Edition',
                             'WebSphere Process Server for z/OS'],
    'WebSphere Service': [   'WebSphere Service Registry',
                             'WebSphere Service Registry and Repository'],
    'WebSphere Studio': [   'WebSphere Studio Application',
                            'WebSphere Studio Application Developer',
                            'WebSphere Studio Application Developer '
                            'Integration',
                            'WebSphere Studio Application Developer '
                            'Integration Edition',
                            'WebSphere Studio Application Monitor',
                            'WebSphere Studio Asset',
                            'WebSphere Studio Asset Analyzer',
                            'WebSphere Studio Enterprise',
                            'WebSphere Studio Enterprise Developer',
                            'WebSphere Studio Site',
                            'WebSphere Studio Site Developer',
                            'WebSphere Studio Workload',
                            'WebSphere Studio Workload Simulator',
                            'WebSphere Studio Workload Simulator for z/OS',
                            'WebSphere Studio Workload Simulator for z/OS and '
                            'OS/390',
                            'WebSphere Studio family'],
    'WebSphere Telecom': ['WebSphere Telecom Web Services Server'],
    'WebSphere Transaction': [   'WebSphere Transaction Cluster',
                                 'WebSphere Transaction Cluster Facility'],
    'WebSphere Translation': [   'WebSphere Translation Server',
                                 'WebSphere Translation Server for '
                                 'Multiplatforms'],
    'WebSphere Voice': [   'WebSphere Voice Response',
                           'WebSphere Voice Response for AIX',
                           'WebSphere Voice Server',
                           'WebSphere Voice Toolkit'],
    'WebSphere XML': [   'WebSphere XML Document',
                         'WebSphere XML Document Management',
                         'WebSphere XML Document Management Server'],
    'WebSphere eXtended': [   'WebSphere Extended Deployment',
                              'WebSphere Extended Deployment for z/OS',
                              'WebSphere eXtended Transaction',
                              'WebSphere eXtended Transaction Runtime']}
