
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_rel_requires_dict = {
    'Accounts Payable': ['Invoice'],
    'Activity Diagram': ['UML'],
    'Administrative Role': ['Typing Skill'],
    'Android': ['Android Mobile Device'],
    'AngularJS': ['Javascript'],
    'Application Performance Analyzer for z/OS': ['z/OS'],
    'Application Recovery Tool for IMS': ['IMS', 'Recovery'],
    'Application Recovery Tool for IMS and DB2': ['DB2', 'IMS', 'Recovery'],
    'Application Recovery Tool for IMS and DB2 Databases': ['IMS', 'Recovery'],
    'Application Time Facility for z/OS': ['z/OS'],
    'Azure Developer': ['Red Hat'],
    'BPEL': ['Business Process'],
    'BlackBerry Enterprise Server': ['Blackberry Mobile Device'],
    'Blockchain': ['Distributed Ledger'],
    'Breeze for SCLM for z/OS': ['z/OS'],
    'Business Monitor for z/OS': ['z/OS'],
    'Business Opportunity': ['Value Proposition'],
    'Business Process Integration with SAP S/4HANA 1610': ['Business Process'],
    'Business Process Integration with SAP S/4HANA 1709': ['Business Process'],
    'Business Process Manager Advanced': ['Business Process'],
    'Business Process Manager Advanced for z/OS': ['Business Process', 'z/OS'],
    'Business Process Manager Express': ['Business Process'],
    'Business Process Manager Industry': ['Business Process'],
    'Business Process Manager Industry Packs': ['Business Process'],
    'Business Process Manager Standard': ['Business Process'],
    'Business Process Manager Tools': ['Business Process'],
    'Business Process Manager Tools and Add-Ons': ['Business Process'],
    'Business Rules for z/OS': ['z/OS'],
    'CICS': ['IBM System Z'],
    'CICS Batch Application Control for z/OS': ['z/OS'],
    'CICS Configuration Manager for z/OS': ['z/OS'],
    'CICS Deployment Assistant for z/OS': ['z/OS'],
    'CICS Interdependency Analyzer for z/OS': ['z/OS'],
    'CICS Performance Analyzer for z/OS': ['z/OS'],
    'CICS Performance Monitor for z/OS': ['z/OS'],
    'CICS Transaction Gateway for z/OS': ['z/OS'],
    'CICS Transaction Server for z/OS': ['z/OS'],
    'CICS Transaction Server for z/OS Developer': ['z/OS'],
    'CICS Transaction Server for z/OS Developer Trial': ['z/OS'],
    'CICS VSAM Copy for z/OS': ['z/OS'],
    'CICS VSAM Transparency for z/OS': ['z/OS'],
    'COBOL for AIX': ['COBOL'],
    'CPLEX Optimizer for z/OS': ['z/OS'],
    'Capacity': ['Capacity Plan'],
    'Change Management Database': ['Change Management'],
    'Change Management Software': ['Change Management Database'],
    'Circuit': ['Voltage'],
    'Cloud 9 for SCLM for z/OS': ['z/OS'],
    'Cloud Migration': ['Cloud Application'],
    'Cluster Systems Management for Linux': ['Linux'],
    'Communication Controller for Linux': ['Linux'],
    'Communication Controller for Linux on System': ['Linux'],
    'Communication Controller for Linux on System z': ['Linux'],
    'Communications Server for Linux': ['Linux'],
    'Communications Server for Linux on zSeries': ['Linux'],
    'Content Manager OnDemand for z/OS': ['z/OS'],
    'Content Manager for z/OS': ['z/OS'],
    'Contrail SDWAN': ['Contrail Service Orchestration'],
    'Credit Card': ['Credit Card Company'],
    'Cryptocurrency': ['Blockchain', 'Smart Contract'],
    'D3.js': ['BSD License', 'Javascript'],
    'DB2 Administration Tool for z/OS': ['z/OS'],
    'DB2 Analytics Accelerator': ['DB2'],
    'DB2 Analytics Accelerator for z/OS': ['DB2', 'z/OS'],
    'DB2 Audit Management Expert for z/OS': ['z/OS'],
    'DB2 Automation Tool for z/OS': ['z/OS'],
    'DB2 Bind Manager for z/OS': ['z/OS'],
    'DB2 Buffer Pool Analyzer for z/OS': ['z/OS'],
    'DB2 Change Accumulation Tool for z/OS': ['z/OS'],
    'DB2 Cloning Tool for z/OS': ['z/OS'],
    'DB2 High Performance Unload for z/OS': ['z/OS'],
    'DB2 ImagePlus for z/OS': ['z/OS'],
    'DB2 Log Analysis Tool for z/OS': ['z/OS'],
    'DB2 Merge Backup': ['DB2'],
    'DB2 Merge Backup for Linux': ['DB2', 'Linux'],
    'DB2 Merge Backup for Linux UNIX and Windows': ['Linux', 'Unix', 'Windows'],
    'DB2 Object Comparison Tool for z/OS': ['z/OS'],
    'DB2 Object Restore for z/OS': ['z/OS'],
    'DB2 Optimization Expert for z/OS': ['z/OS'],
    'DB2 Path Checker for z/OS': ['z/OS'],
    'DB2 Performance Monitor for z/OS': ['z/OS'],
    'DB2 Query Monitor for z/OS': ['z/OS'],
    'DB2 Recovery Expert for Linux and UNIX and Windows': [   'DB2',
                                                              'Linux',
                                                              'Recovery',
                                                              'Unix',
                                                              'Windows'],
    'DB2 Recovery Expert for z/OS': ['z/OS'],
    'DB2 SQL Performance Analyzer for z/OS': ['z/OS'],
    'DB2 Test Database Generator for z/OS': ['z/OS'],
    'DB2 Tools for Linux': ['Linux'],
    'DB2 Tools for Linux and UNIX and Windows': ['Linux', 'Unix', 'Windows'],
    'DB2 Tools for z/OS': ['z/OS'],
    'DB2 Utilities Enhancement Tool for z/OS': ['z/OS'],
    'DB2 Utilities Solution Pack for z/OS': ['z/OS'],
    'DB2 Utilities Suite for z/OS': ['z/OS'],
    'Data At Rest Encryption': ['Data at Rest'],
    'Data Encryption for IMS': ['IMS'],
    'Data Encryption for IMS and DB2': ['DB2', 'IMS'],
    'Data Encryption for IMS and DB2 Databases': ['DB2', 'IMS'],
    'Data Scientist': ['Storytelling'],
    'Database Design': ['Database'],
    'Database Index': ['Database'],
    'Debug Tool for z/OS': ['z/OS'],
    'Decision Center for z/OS': ['z/OS'],
    'Decision Server for z/OS': ['z/OS'],
    'Device Programming Skill': ['Mobile Device'],
    'Distributed Ledger': ['Peer-to-Peer'],
    'Engagement Process': ['Project Plan'],
    'Engineering and Scientific Subroutine Library for Linux': ['Linux'],
    'Engineering and Scientific Subroutine Library for Linux on POWER': [   'Linux',
                                                                            'Power '
                                                                            'Server'],
    'Enhanced Access Control for SCLM for z/OS': ['z/OS'],
    'Enterprise COBOL for z/OS': ['z/OS'],
    'Enterprise PL/I for z/OS': ['z/OS'],
    'Event Processing': ['Log File'],
    'Fact Table': ['Relational Database'],
    'Fault Analyzer for z/OS': ['z/OS'],
    'Fiber over Ethernet': ['Ethernet'],
    'File Manager for z/OS': ['z/OS'],
    'FileNet Business Process': ['Business Process'],
    'FileNet Business Process Framework': ['Business Process'],
    'FileNet Business Process Manager': ['Business Process'],
    'Financial Instrument': ['Financial Company'],
    'General Parallel File System for Linux': ['Linux'],
    'General Parallel File System for Linux on POWER': [   'Linux',
                                                           'Power Server'],
    'Google Cloud Dataflow': ['Workflow'],
    'Grafana': ['Open Source License'],
    'Hadoop': ['MapReduce'],
    'Hardware Troubleshooting': ['Hardware Skill'],
    'High Availability': ['Load Balancer'],
    'Human Resources Policy': ['Human Resources'],
    'Hyperledger Fabric': ['Blockchain', 'Hyperledger'],
    'IBM Q Certification': ['Quantum Ready Workshop'],
    'IMS Audit Management': ['IMS'],
    'IMS Audit Management Expert': ['IMS'],
    'IMS Audit Management Expert for z/OS': ['z/OS'],
    'IMS Batch Backout': ['IMS'],
    'IMS Batch Backout Manager': ['IMS'],
    'IMS Batch Backout Manager for z/OS': ['z/OS'],
    'IMS Batch Terminal': ['IMS'],
    'IMS Batch Terminal Simulator': ['IMS'],
    'IMS Batch Terminal Simulator for z/OS': ['z/OS'],
    'IMS Buffer Pool': ['IMS'],
    'IMS Buffer Pool Analyzer': ['IMS'],
    'IMS Buffer Pool Analyzer for z/OS': ['z/OS'],
    'IMS Cloning Tool': ['IMS'],
    'IMS Cloning Tool for z/OS': ['z/OS'],
    'IMS Command Control': ['IMS'],
    'IMS Command Control Facility': ['IMS'],
    'IMS Command Control Facility for z/OS': ['z/OS'],
    'IMS Configuration Manager': ['IMS'],
    'IMS Configuration Manager for z/OS': ['z/OS'],
    'IMS Connect Extensions': ['IMS'],
    'IMS Connect Extensions for z/OS': ['z/OS'],
    'IMS DEDB Fast': ['IMS'],
    'IMS DEDB Fast Recovery for z/OS': ['z/OS'],
    'IMS DataPropagator for z/OS': ['z/OS'],
    'IMS Database Control': ['IMS'],
    'IMS Database Control Suite': ['IMS'],
    'IMS Database Control Suite for z/OS': ['z/OS'],
    'IMS Database Recovery': ['IMS'],
    'IMS Database Recovery Facility': ['IMS'],
    'IMS Database Recovery Facility for z/OS': ['z/OS'],
    'IMS Database Repair': ['IMS'],
    'IMS Database Repair Facility': ['IMS'],
    'IMS Database Repair Facility for z/OS': ['z/OS'],
    'IMS Database Solution': ['IMS'],
    'IMS Database Solution Pack': ['IMS'],
    'IMS Database Solution Pack for z/OS': ['z/OS'],
    'IMS Extended Terminal Option Support for z/OS': ['z/OS'],
    'IMS Fast Path Solution Pack for z/OS': ['z/OS'],
    'IMS High Performance Change Accumulation Utility for z/OS': ['z/OS'],
    'IMS High Performance Fast Path Utilities for z/OS': ['z/OS'],
    'IMS High Performance Image Copy for z/OS': ['z/OS'],
    'IMS High Performance Load for z/OS': ['z/OS'],
    'IMS High Performance Pointer Checker for z/OS': ['z/OS'],
    'IMS High Performance Prefix Resolution for z/OS': ['z/OS'],
    'IMS High Performance Unload for z/OS': ['z/OS'],
    'IMS Index Builder for z/OS': ['z/OS'],
    'IMS Library Integrity Utilities for z/OS': ['z/OS'],
    'IMS Network Compression Facility for z/OS': ['z/OS'],
    'IMS Online Reorganization Facility for z/OS': ['z/OS'],
    'IMS Parallel Reorganization for z/OS': ['z/OS'],
    'IMS Parameter Manager for z/OS': ['z/OS'],
    'IMS Performance Analyzer for z/OS': ['z/OS'],
    'IMS Performance Monitor for z/OS': ['z/OS'],
    'IMS Performance Solution Pack for z/OS': ['z/OS'],
    'IMS Problem Investigator for z/OS': ['z/OS'],
    'IMS Program Restart Facility for z/OS': ['z/OS'],
    'IMS Queue Control Facility for z/OS': ['z/OS'],
    'IMS Recovery Expert for z/OS': ['z/OS'],
    'IMS Recovery Solution Pack for z/OS': ['z/OS'],
    'IMS Sysplex Manager for z/OS': ['z/OS'],
    'IMS Tools Knowledge Base for z/OS': ['z/OS'],
    'ISPF Productivity Tool for z/OS': ['z/OS'],
    'ISPF for z/OS': ['z/OS'],
    'Identity Governance': ['Identity'],
    'Impala': ['Hadoop'],
    'Ims High Availability Large Database (Haldb) Toolkit For Z/Os': ['z/OS'],
    'Incident Ticket': ['Incident'],
    'InfoSphere Change Data Capture for Oracle': ['Oracle'],
    'InfoSphere Change Data Capture for Oracle Replication': ['Oracle'],
    'InfoSphere Classic Connector for z/OS': ['z/OS'],
    'InfoSphere Classic Data Event Publisher for z/OS': ['z/OS'],
    'InfoSphere Classic Federation Server for z/OS': ['z/OS'],
    'InfoSphere Classic Replication Server for z/OS': ['z/OS'],
    'InfoSphere Data Event Publisher for z/OS': ['z/OS'],
    'InfoSphere Optim High Performance Unload for DB2': ['DB2'],
    'InfoSphere Optim High Performance Unload for DB2 for Linux and UNIX and Windows': [   'DB2',
                                                                                           'Linux',
                                                                                           'Unix',
                                                                                           'Windows'],
    'InfoSphere Optim Query Tuner for DB2': ['DB2'],
    'InfoSphere Optim Query Tuner for DB2 for Linux and UNIX and Windows': [   'DB2',
                                                                               'Linux',
                                                                               'Unix'],
    'InfoSphere Optim Query Tuner for DB2 for z/OS': ['DB2', 'z/OS'],
    'InfoSphere Optim Query Workload Tuner for DB2': ['DB2'],
    'InfoSphere Optim Query Workload Tuner for DB2 for Linux and UNIX and Windows': [   'DB2',
                                                                                        'Linux',
                                                                                        'Unix'],
    'InfoSphere Optim Query Workload Tuner for DB2 for z/OS': ['DB2', 'z/OS'],
    'InfoSphere Optim pureQuery Runtime for Linux and UNIX and Windows': [   'Linux',
                                                                             'Unix'],
    'InfoSphere Optim pureQuery Runtime for z/OS': ['z/OS'],
    'InfoSphere Replication Server for z/OS': ['z/OS'],
    'Initial Coin Offering': ['Cryptocurrency'],
    'Inventory Management': ['Inventory'],
    'Java': ['Object Oriented'],
    'Kafka Messaging': ['Kafka'],
    'Language Integrated Query': ['Net Framework'],
    'Listening Skill': ['Listen'],
    'Living Organism': ['Enzyme'],
    'Load Leveler for Linux': ['Linux'],
    'LoadLeveler for Linux on POWER': ['Linux', 'Power Server'],
    'LoadLeveler for Linux on x86 Architecture': ['Linux'],
    'Lotus Workflow': ['Workflow'],
    'MDA': ['Database Dimension'],
    'Marketing Role': ['Marketing'],
    'Mentor': ['Coaching Skill'],
    'Merge Tool for z/OS': ['z/OS'],
    'Merge Tool for z/OS and OS/390': ['z/OS'],
    'Migration Utility for z/OS': ['z/OS'],
    'Mobile Operating System': ['Mobile Device'],
    'Multicloud Enabler': ['Contrail Enterprise Multicloud'],
    'Natural Language Processing': ['Natural Language'],
    'Neo4J': ['GPL3 License'],
    'Network Downtime': ['Network'],
    'OMEGAMON z/OS': ['z/OS'],
    'OMEGAMON z/OS Management': ['z/OS'],
    'OMEGAMON z/OS Management Console': ['z/OS'],
    'OpenShift Dedicated': ['Google Cloud'],
    'OpenShift Origin': ['Apache License'],
    'OpenStack': ['Apache License'],
    'Operating System Environment Manager for z/OS': ['z/OS'],
    'Operational Decision Manager for z/OS': ['z/OS'],
    'Optim Database Administrator for DB2': ['DB2'],
    'Optim Database Administrator for DB2 for Linux and UNIX and Windows': [   'DB2',
                                                                               'Linux',
                                                                               'Unix'],
    'Optim High Performance Unload for DB2': ['DB2'],
    'Optim High Performance Unload for DB2 for Linux and UNIX and Windows': [   'DB2',
                                                                                'Linux',
                                                                                'Unix'],
    'Optim Move for DB2': ['DB2'],
    'Optim Performance Manager for DB2 for Linux and UNIX and Windows': [   'DB2',
                                                                            'Linux',
                                                                            'Unix'],
    'Optim pureQuery Runtime for Linux and UNIX and Windows': ['Linux', 'Unix'],
    'Optim pureQuery Runtime for z/OS': ['z/OS'],
    'Optim z/OS': ['z/OS'],
    'Oracle Business Process Management Suite 12c Essentials': [   'Business '
                                                                   'Process'],
    'Parallel Engineering And Scientific Subroutine Library (Essl) For Linux On Power': [   'Linux',
                                                                                            'Power '
                                                                                            'Server'],
    'Parallel Environment Developer Edition for Linux on x86 Architecture': [   'Linux'],
    'Parallel Environment Runtime Edition for Linux': ['Linux'],
    'Parallel Environment Runtime Edition for Linux on x86 Architecture': [   'Linux'],
    'Parallel Environment for Linux': ['Linux'],
    'Parse Tree': ['Parse'],
    'Password Compliance': ['Password'],
    'Portfolio Alignment': ['Portfolio'],
    'PostgreSQL': ['Open Source License'],
    'PowerDNS': ['GPL License'],
    'Presales Skill': ['Negotiation Skill'],
    'Process Mining': ['Business Process', 'Log File'],
    'Project': ['Project Scope'],
    'Proposition': ['Presentation Skill'],
    'Python Library': ['Python'],
    'Quantum Computing': ['Quantum Computing Platform'],
    'RACF Database': ['z/OS'],
    'Rational Purify for Linux': ['Linux'],
    'Rational Purify for Linux and UNIX': ['Linux', 'Unix'],
    'Rational PurifyPlus for Linux': ['Linux'],
    'Rational PurifyPlus for Linux and UNIX': ['Linux', 'Unix'],
    'Rational Rose Developer for Java': ['Java'],
    'Rational Rose Developer for UNIX': ['Unix'],
    'Rational Suite DevelopmentStudio for UNIX': ['Unix'],
    'Red Hat Developer': ['Red Hat'],
    'Redhat Business Process Design Certification': ['Business Process'],
    'Redhat Fuse': ['Camel'],
    'Release Process': ['Release Strategy'],
    'Revenue Forecast': ['Revenue'],
    'SAP Project': ['SAP'],
    'SCLM Advanced Edition for z/OS': ['z/OS'],
    'SQLAlchemy': ['SQL'],
    'Sales Conversion': ['Sales Skill'],
    'Sales Role': ['Sales'],
    'Security Key Lifecycle Manager for z/OS': ['z/OS'],
    'Sensu': ['Workflow'],
    'Sequence Diagram': ['UML'],
    'Service Level Agreement': ['Service Level'],
    'Service Oriented Architecture': ['Software Service'],
    'Service Provider': ['Service Offering'],
    'Session Manager for z/OS': ['z/OS'],
    'Smart Analytics Optimizer for DB2': ['DB2'],
    'Smart Analytics Optimizer for DB2 for z/OS': ['DB2', 'z/OS'],
    'Social Media Company': ['Social Media'],
    'Software Deployment': ['Deployment Environment'],
    'Software Portfolio Alignment': ['Software Portfolio'],
    'Software Quality': ['Software'],
    'Software Troubleshooting': ['Software Skill'],
    'Solution Design': ['Solution Skill'],
    'Stakeholder Role': ['Business Stakeholder'],
    'Star Schema': ['Relational Database'],
    'State Diagram': ['UML'],
    'Sterling Connect:Direct for UNIX': ['Unix'],
    'Sterling Connect:Direct for z/OS': ['z/OS'],
    'Sterling Connect:Enterprise for UNIX': ['Unix'],
    'Sterling Connect:Enterprise for z/OS': ['z/OS'],
    'Sterling Connect:Express for UNIX': ['Unix'],
    'Sterling Connect:Express for z/OS': ['z/OS'],
    'Sterling Gentran for z/OS': ['z/OS'],
    'Storage Administration Workbench for z/OS': ['z/OS'],
    'Storage Administration Workbench for z/OS and OS/390': ['z/OS'],
    'Switch Failover': ['Switch'],
    'Switch Failure': ['Switch'],
    'Team': ['Team Member'],
    'Tivoli AF/OPERATOR on z/OS': ['z/OS'],
    'Tivoli Advanced Catalog Management for z/OS': ['z/OS'],
    'Tivoli Allocation Optimizer for z/OS': ['z/OS'],
    'Tivoli Asset Discovery for z/OS': ['z/OS'],
    'Tivoli Automated Tape Allocation Manager for z/OS': ['z/OS'],
    'Tivoli Business Systems Manager for z/OS': ['z/OS'],
    'Tivoli Command Center for DB2plex': ['DB2'],
    'Tivoli Composite Application Manager for Transactions for z/OS': ['z/OS'],
    'Tivoli Decision Support for z/OS': ['z/OS'],
    'Tivoli Directory Integrator General Purpose Edition for z/OS': ['z/OS'],
    'Tivoli Event Pump for z/OS': ['z/OS'],
    'Tivoli Federated Identity Manager for z/OS': ['z/OS'],
    'Tivoli Information Management for z/OS': ['z/OS'],
    'Tivoli Key Lifecycle Manager for z/OS': ['z/OS'],
    'Tivoli License Compliance Manager for z/OS': ['z/OS'],
    'Tivoli NetView for z/OS': ['z/OS'],
    'Tivoli OMEGACENTER Gateway on z/OS': ['z/OS'],
    'Tivoli OMEGAMON DE for Distributed and z/OS': ['z/OS'],
    'Tivoli OMEGAMON DE for Distributed and z/OS Systems': ['z/OS'],
    'Tivoli OMEGAMON DE on z/OS': ['z/OS'],
    'Tivoli OMEGAMON II for DB2': ['DB2'],
    'Tivoli OMEGAMON XE for CICS Transaction Gateway on z/OS': ['z/OS'],
    'Tivoli OMEGAMON XE for CICS on z/OS': ['z/OS'],
    'Tivoli OMEGAMON XE for DB2': ['DB2'],
    'Tivoli OMEGAMON XE for DB2 Performance': ['DB2'],
    'Tivoli OMEGAMON XE for DB2 Performance Expert on z/OS': ['DB2', 'z/OS'],
    'Tivoli OMEGAMON XE for DB2 Performance Monitor on z/OS': ['DB2', 'z/OS'],
    'Tivoli OMEGAMON XE for DB2 on z/OS': ['DB2', 'z/OS'],
    'Tivoli OMEGAMON XE for DB2plex': ['DB2'],
    'Tivoli OMEGAMON XE for IMS': ['IMS'],
    'Tivoli OMEGAMON XE for IMS on z/OS': ['z/OS'],
    'Tivoli OMEGAMON XE for IMSplex': ['IMS'],
    'Tivoli OMEGAMON XE for Linux': ['Linux'],
    'Tivoli OMEGAMON XE for Linux on zSeries': ['Linux'],
    'Tivoli OMEGAMON XE for Messaging for z/OS': ['z/OS'],
    'Tivoli OMEGAMON XE for WebSphere Application Server for Linux': ['Linux'],
    'Tivoli OMEGAMON XE for WebSphere Application Server for Linux on zSeries': [   'Linux'],
    'Tivoli OMEGAMON XE for WebSphere Application Server on z/OS': ['z/OS'],
    'Tivoli OMEGAMON XE for WebSphere MQ on z/OS': ['z/OS'],
    'Tivoli OMEGAMON XE on z/OS': ['z/OS'],
    'Tivoli Output Manager for z/OS': ['z/OS'],
    'Tivoli Performance Modeler for z/OS': ['z/OS'],
    'Tivoli Security Management for z/OS': ['z/OS'],
    'Tivoli Storage Optimizer for z/OS': ['z/OS'],
    'Tivoli System Automation for z/OS': ['z/OS'],
    'Tivoli Tape Optimizer on z/OS': ['z/OS'],
    'Tivoli Usage and Accounting Manager for z/OS': ['z/OS'],
    'Tivoli Workload Scheduler for z/OS': ['z/OS'],
    'Transaction Data': ['Structured Data'],
    'Transformation Role': ['Transformation Skill'],
    'Translation': ['Natural Language'],
    'Unix Administrator': ['Unix'],
    'Usability Engineer': ['Usability Skill'],
    'VMWare NSX': ['Virtual Network'],
    'VeloCloud': ['VMWare NSX'],
    'Visualization': ['Visualization Skill'],
    'Voltage Regulator': ['Voltage'],
    'Web Application Framework': ['Web Application'],
    'WebSphere Adapter for Oracle': ['Oracle'],
    'WebSphere Adapter for Oracle E-Business': ['Oracle'],
    'WebSphere Adapter for Oracle E-Business Suite': ['Oracle'],
    'WebSphere Application Server for z/OS': ['z/OS'],
    'WebSphere Business Integration Server Foundation for z/OS': ['z/OS'],
    'WebSphere Data Interchange for z/OS': ['z/OS'],
    'WebSphere Decision Center for z/OS': ['z/OS'],
    'WebSphere Decision Server for z/OS': ['z/OS'],
    'WebSphere Event Broker for z/OS': ['z/OS'],
    'WebSphere Extended Deployment for z/OS': ['z/OS'],
    'WebSphere MQ Integrator Broker for z/OS': ['z/OS'],
    'WebSphere MQ Workflow': ['Workflow'],
    'WebSphere MQ Workflow for Multiplatforms': ['Workflow'],
    'WebSphere MQ Workflow for z/OS': ['Workflow', 'z/OS'],
    'WebSphere MQ for z/OS': ['z/OS'],
    'WebSphere Message Broker for z/OS': ['z/OS'],
    'WebSphere Operational Decision Management for z/OS': ['z/OS'],
    'WebSphere Process Server for z/OS': ['z/OS'],
    'WebSphere Studio Workload Simulator for z/OS': ['z/OS'],
    'WebSphere Studio Workload Simulator for z/OS and OS/390': ['z/OS'],
    'Workflow Language': ['Workflow'],
    'Workflow Software': ['Workflow'],
    'Workload Deployer Pattern for DB2 Workgroup Server Edition': ['DB2'],
    'Workload Simulator for z/OS': ['z/OS'],
    'Workload Simulator for z/OS and OS/390': ['z/OS'],
    'iOS': ['Apple Mobile Device']}
