
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_rel_implies_dict = {
    '51% Attack': ['Cryptocurrency'],
    'AWS': ['Public cloud', 'Technical Services'],
    'AWS Certification': ['AWS'],
    'AWS Certified Big Data': ['Big Data'],
    'AWS Certified Machine Learning': ['Machine Learning'],
    'Ace Insurance': ['Insurance'],
    'Activity Report': ['Project Plan'],
    'Adobe Visual Communicator': ['Visualization Skill'],
    'Advanced Analytics': ['Data Scientist'],
    'Advanced Identity Manager': ['Biometrics', 'Identity Management'],
    'Agile Artifact': ['Agile'],
    'Air Canada': ['Transportation'],
    'Algorithm': ['Programming Skill'],
    'Alpine Linux': ['BusyBox'],
    'Amazon': ['Manufacturing', 'Retail', 'Technical Services'],
    'Ameriprise': ['Financial', 'Insurance'],
    'Amex': ['Financial'],
    'Analysis Skill': ['Analytics'],
    'Analytics Asset': ['Analysis Skill'],
    'Android Mobile Device': ['Android'],
    'AngularJS': ['MIT License'],
    'Apple Mobile Device': ['iOS'],
    'Application Recovery Tool': ['Recovery'],
    'Approval': ['Process'],
    'Architect': ['Design Skill'],
    'Argument': ['Negative Emotion'],
    'Arizona State': ['Government'],
    'Artifact': ['Soft Skill'],
    'Assistant': ['Soft Skill'],
    'Assurance': ['Compliance'],
    'Astrazeneca': ['Health Care'],
    'Asynchronous Transfer Mode': ['Integrated Services Digital Network'],
    'Australia Bank': ['Bank'],
    'Authentication': ['Security Skill'],
    'Authorization': ['Security Skill'],
    'Authorization Code': ['Authorization'],
    'Avis': ['Automotive'],
    'Award': ['Appreciation'],
    'Azure AI Engineer Associate': [   'Computer Vision',
                                       'Machine Learning',
                                       'Natural Language Processing'],
    'Azure Data Scientist Associate': ['Data Scientist', 'Machine Learning'],
    'Azure Developer Associate': ['Cloud Skill'],
    'BPM Advanced Pattern': ['BPM', 'Business Analyst'],
    'BPM Advanced Pattern on Red Hat Enterprise Linux': ['Business Analyst'],
    'BPM Advanced Pattern on Red Hat Enterprise Linux Server': [   'Business '
                                                                   'Analyst'],
    'Back End': ['Database'],
    'Backup and Restore': ['Backup'],
    'Backup and Restore Manager': ['Backup'],
    'Backup and Restore Manager for z/VM': ['Backup'],
    'Bandwidth': ['Network', 'Quality of Service'],
    'Bank Of America': ['Bank'],
    'Banking Process and Service': ['Bank'],
    'Banking Process and Service Models': ['Bank'],
    'Banking and Financial': ['Bank'],
    'Banking and Financial Markets Data Warehouse': ['Bank'],
    'Barclays': ['Bank'],
    'Bell Canada': ['Telecommunications'],
    'Bezel': ['Mobile Device'],
    'Big Data': ['Analysis Skill', 'Big Data'],
    'Bitcoin Mining': ['Bitcoin'],
    'Bitmain': ['Bitcoin Mining'],
    'Blockchain Company': ['Blockchain'],
    'Blockchain Infrastructure': ['Blockchain'],
    'Bluemix': ['Technical Services'],
    'Brand': ['Marketing'],
    'Build Automation': ['Deployment Skill', 'Release Strategy'],
    'Business Intelligence with SAP BW 7.4 & SAP BI 4.1': [   'Business '
                                                              'Intelligence'],
    'Business Leader': ['Business Skill'],
    'Business Model': ['Business Skill'],
    'Business Opportunity': ['Industry Insight'],
    'Business Role': ['Business Skill'],
    'CA State': ['Government'],
    'CAMS': [   'Analysis Skill',
                'Cloud Skill',
                'Mobile Skill',
                'Social Media Skill'],
    'CAP Certification': ['Authorization Security'],
    'CCNA Cloud Certification': ['Cloud Skill'],
    'CCNP Cloud Certification': ['Cloud Skill'],
    'CCSP Certification': ['Cloud Security'],
    'CICS': ['Mainframe Operating System'],
    'CICS Deployment': ['Deployment Skill'],
    'CICS Deployment Assistant': ['Deployment Skill'],
    'CICS Deployment Assistant for z/OS': ['Deployment Skill'],
    'CICS Interdependency Analyzer': ['Deployment Skill'],
    'CICS VSAM': ['VSAM'],
    'CICS VSAM Copy': ['VSAM'],
    'CICS VSAM Copy for z/OS': ['VSAM'],
    'CICS VSAM Recovery': ['Recovery', 'VSAM'],
    'CICS VSAM Recovery for z/OS': ['Recovery', 'VSAM', 'z/OS'],
    'CICS VSAM Transparency': ['VSAM'],
    'CICS VSAM Transparency for z/OS': ['VSAM'],
    'COBOL for Windows': ['Windows'],
    'CSSLP Certification': ['Software Design'],
    'Call Monitoring': ['Service Desk'],
    'Canada Bank': ['Bank'],
    'Capability Maturity Model': ['Software Design'],
    'Capacity Plan': ['Capacity'],
    'Capacity Skill': ['Capacity Plan'],
    'Caterpillar': ['Manufacturing'],
    'Centurylink': ['Telecommunications'],
    'Chanel': ['Retail'],
    'Change Management': ['Service Management Skill'],
    'Change Request': ['Change Management'],
    'Chat Bot': ['Cognitive Skill', 'statistical algorithm'],
    'Chief Diversity Officer': ['Diversity'],
    'Chrysler': ['Automotive'],
    'Cibc': ['Bank'],
    'Circuit Design': ['Electrical Engineering'],
    'Cisco': ['Hardware Skill', 'Network Skill'],
    'Cisco Cloud Certification': ['Cloud Skill'],
    'Citrix Cloud': ['Cloud Skill'],
    'Client Focus': ['Client Skill'],
    'Client Meeting': ['Client Skill'],
    'Client Skill': ['Customer'],
    'Client Technical Architect': ['Client Skill'],
    'Client Technical Specialist': ['Client Skill'],
    'Cloud 9': ['Cloud Skill'],
    'Cloud Access Security Broker': ['Cloud Skill'],
    'Cloud Analytics': ['Analytics', 'Cloud Skill'],
    'Cloud Application': ['Cloud Skill'],
    'Cloud Backup': ['Cloud Storage'],
    'Cloud CMS': ['Cloud Skill'],
    'Cloud Computing Company': ['Cloud computing platform'],
    'Cloud Gateway': ['Cloud computing platform'],
    'Cloud Provider': ['Cloud computing platform'],
    'Cloud Tool': ['Cloud Skill'],
    'Cloud computing platform': ['Cloud Skill'],
    'Cloudera Data Analyst Certification': ['Hive', 'Impala'],
    'Cloudera Spark and Hadoop Certification': ['Hadoop', 'Spark'],
    'Cluster Systems Management': ['Cluster'],
    'Cluster Systems Management for Linux': ['Cluster'],
    'Coaching Skill': ['Mentor'],
    'Coca Cola': ['Manufacturing'],
    'Cognitive Framework': ['Cognitive Skill', 'statistical algorithm'],
    'Cognitive Testing': ['Cognitive Skill', 'statistical algorithm'],
    'Cognitive Training': ['Cognitive Skill', 'statistical algorithm'],
    'Cognos 8 Go! Mobile': ['Mobile Skill'],
    'Cognos Analysis for Microsoft': ['Microsoft'],
    'Cognos Analysis for Microsoft Excel': ['Microsoft'],
    'Cognos Customer Performance Sales': ['Sales'],
    'Cognos Customer Performance Sales Analytics': ['Analytics', 'Sales Skill'],
    'Cognos Mobile': ['Mobile Skill'],
    'Cognos Statistics': ['Statistics'],
    'Cognos Supply Chain Performance Procurement Analytics': ['Analytics'],
    'Cognos for Microsoft': ['Microsoft'],
    'Cognos for Microsoft Office': ['Microsoft'],
    'Communication Security': ['Communication Protocol'],
    'Communications Server for Windows': ['Windows'],
    'Competitive Analysis': ['Business Skill'],
    'Competitive Research': ['Business Analysis Skill'],
    'Compliance Lead': ['Compliance'],
    'Computational Linguistics': ['Natural Language Processing', 'Statistics'],
    'Concurrency': ['Optimization Skill'],
    'Conda': ['Python'],
    'Configuration Management': ['Service Management Skill'],
    'Consumer Good': ['Retail'],
    'Content Analytics with Enterprise': ['Analytics'],
    'Content Analytics with Enterprise Search': ['Analytics'],
    'Continental Casualty': ['Insurance'],
    'Continuous Deployment': ['Deployment Skill'],
    'Continuous Integration': ['Integration Skill'],
    'Contract': ['Negotiation Skill'],
    'Contract Renewal': ['Contract'],
    'Contrail Edge Cloud': ['Internet of Things'],
    'Coordinator': ['Management Skill'],
    'Correlation': ['Statistical Model'],
    'Credit Card Company': ['Credit Card'],
    'Cross Platform Software': ['Cross Platform'],
    'Cryptographic Protocol': ['Cryptography'],
    'Cybersecurity Company': ['Computer Security'],
    'DB2 Analytics Accelerator': ['Analytics'],
    'DB2 Analytics Accelerator for z/OS': ['Analytics'],
    'DB2 Audit Management': ['Audit Skill'],
    'DB2 Audit Management Expert': ['Audit Skill'],
    'DB2 Audit Management Expert for z/OS': ['Audit Skill'],
    'DB2 Merge Backup': ['Backup'],
    'DB2 Merge Backup for Linux': ['Backup'],
    'DB2 Merge Backup for Linux UNIX and Windows': ['Backup'],
    'DB2 Recovery': ['Recovery'],
    'DB2 Recovery Expert': ['Recovery'],
    'DB2 Storage': ['Storage Skill'],
    'DB2 Storage Management': ['Storage Skill'],
    'DB2 Storage Management Utility for z/OS': ['Storage Skill', 'z/OS'],
    'DB2 Test': ['Testing Skill'],
    'DB2 Test Database': ['Testing Skill'],
    'DB2 Test Database Generator': ['Testing Skill'],
    'DB2 XML Extender': ['XML'],
    'Danske Bank': ['Bank'],
    'Data Encryption for IMS': ['Encryption'],
    'Data Encryption for IMS and DB2': ['Encryption'],
    'Data Encryption for IMS and DB2 Databases': ['Encryption'],
    'Data Integration with SAP Data Services 4.2': ['Data Integration Skill'],
    'Data Lake': ['Database Skill'],
    'Data Migration': ['Database Skill'],
    'Data Mining': ['Data Scientist'],
    'Data Modeling Skill': ['Database Skill'],
    'Data Privacy Regulation': ['Data Privacy'],
    'Data Scientist': ['Cognitive Skill', 'statistical algorithm'],
    'Data Scientist Workbench': ['Data Scientist'],
    'Data Storage Library': ['Data Storage'],
    'Data Warehouse': ['Database Skill'],
    'Database': ['Database Skill'],
    'Database Administrator': ['Database Skill'],
    'Database Skill': ['Data Modeling Skill'],
    'Decentralized Application': ['Distributed Ledger'],
    'Deep Learning Design': ['Deep Learning'],
    'Defra': ['Government'],
    'Deliverable': ['Delivery Skill'],
    'Deployment Environment': ['Deployment Skill'],
    'Design Artifact': ['Design Skill'],
    'Designer': ['Design Skill'],
    'Deutsche Bank': ['Bank'],
    'Developer': ['Programming Skill'],
    'Device Programming Skill': ['Mobile Operating System'],
    'DiVincenzo Criteria': ['Quantum Computing'],
    'Diageo': ['Retail'],
    'Disaster Recovery': ['Recovery'],
    'DisplayWrite/370 for MVS/CICS': ['MVS'],
    'Distributed File System': ['Distributed Environment'],
    'Distributed Memory': ['Distributed Computing'],
    'Distributed Software': ['Distributed Computing'],
    'Doctoral Degree': ['Masters Degree'],
    'Document': ['Soft Skill'],
    'Domain Driven Data Mining': ['Domain Skill'],
    'Drug Entrepreneur': ['Health Care'],
    'EC2': ['Public cloud', 'Technical Services'],
    'ETL': ['Database Skill'],
    'Education Policy': ['Education'],
    'Elections Canada': ['Government'],
    'Electrical Regulator': ['Electric Circuit'],
    'Employee Appreciation': ['Employee'],
    'Employee Benefit': ['Employee'],
    'Employee Training': ['Employee'],
    'Encryption': ['Security Skill'],
    'Encryption Software': ['Encryption'],
    'Etihad': ['Transportation'],
    'Expert System': ['Artificial Intelligence'],
    'Extreme Programming': ['Programming Skill'],
    'Fannie Mae': ['Financial'],
    'Feature Engineering': ['Machine Learning'],
    'File System': ['Storage'],
    'FileNet Connectors for Microsoft': ['Microsoft'],
    'FileNet Connectors for Microsoft SharePoint': ['Microsoft'],
    'Financial': ['Financial Skill'],
    'Financial Company': ['Financial Skill'],
    'Financial Service': ['Financial Instrument'],
    'Finite Element Method': ['Engineering'],
    'Firmware': ['Hardware Skill'],
    'Fixed Asset': ['Accounting'],
    'Flume': ['Big Data'],
    'Formal Language': ['Programming Skill'],
    'Frame Relay': ['Packet Switching', 'Wide Area Network'],
    'Front End': ['User Interface'],
    'Full Stack Developer': [   'Hardware Skill',
                                'Software Skill',
                                'Testing Skill'],
    'GASF Certification': ['Forsensics'],
    'GAWN Certification': ['Computer Security'],
    'GCCC Certification': ['Computer Security'],
    'GCDA Certification': ['Computer Security'],
    'GCED Certification': ['Computer Security'],
    'GCFA Certification': ['Forsensics'],
    'GCFE Certification': ['Forsensics'],
    'GCIA Certification': ['Computer Security'],
    'GCTI Certification': ['Forsensics'],
    'GCUX Certification': ['Computer Security'],
    'GCWN Certification': ['Computer Security'],
    'GDAT Certification': ['Computer Security'],
    'GDSA Certification': ['Computer Security'],
    'GISF Certification': ['Computer Security'],
    'GMON Certification': ['Computer Security'],
    'GNFA Certification': ['Forsensics'],
    'GPPA Certification': ['Computer Security'],
    'GREM Certification': ['Forsensics'],
    'GSEC Certification': ['Computer Security'],
    'Georgia Tech': ['Education'],
    'Google': [   'Manufacturing',
                  'Professional Services',
                  'Retail',
                  'Technical Services'],
    'Google Cloud': ['Technical Services'],
    'Google Cloud Certification': ['Cloud Skill'],
    'Gradient Descent': ['Machine Learning'],
    'Graduate Degree': ['Undergraduate Degree'],
    'Grafana': ['Time Series'],
    'Graph Database': [   'Cognitive Skill',
                          'Graph Theory',
                          'Unstructured Data',
                          'statistical algorithm'],
    'Green Hat Tester': ['Testing Skill'],
    'Ground Truth': ['Cognitive Skill', 'statistical algorithm'],
    'HCISPP Certification': ['Health Care Security'],
    'HDFS': ['Hadoop'],
    'HIPPA': ['Health Care'],
    'Hadoop': ['Big Data', 'HDFS'],
    'Hardware': ['Hardware Skill'],
    'Hartford': ['Insurance'],
    'Health Care Company': ['Health Care'],
    'Health Care Security': ['Health Care'],
    'Health Net': ['Health Care'],
    'Healthcare Provider': ['Health Care'],
    'Healthcare Provider Data Warehouse': ['Health Care'],
    'Hibernate': ['Java', 'Relational Database'],
    'High Avaiability Cluster': ['Cluster'],
    'High Availability Cluster Multi-Processing': [   'Cluster',
                                                      'High Availability'],
    'High Performance Microprocessor': ['High Performance Computing'],
    'Home Office': ['Flexible Environment'],
    'Honda': ['Automotive'],
    'Hortonworks Certified Administrator': ['Big Data'],
    'Hortonworks Certified Developer': ['Hive', 'Pig', 'Sqoop'],
    'Hortonworks Spark Certification': ['Spark'],
    'Hyperledger': ['Distributed Ledger'],
    'Hypothesis': ['Research Skill'],
    'IBM Employee': ['IBM'],
    'IBM Q': ['Quantum Computing'],
    'IBM Q Certification': ['Quantum Computing'],
    'ILOG JViews Telecom Graphic Objects': ['Telecommunications'],
    'ILOG Telecom': ['Telecommunications'],
    'ILOG Telecom Graphic Objects': ['Telecommunications'],
    'IMS Audit': ['Audit Skill'],
    'IMS Audit Management': ['Audit Skill'],
    'IMS Audit Management Expert': ['Audit Skill'],
    'IMS Audit Management Expert for z/OS': ['Audit Skill'],
    'IMS High Availability': ['High Availability'],
    'IMS High Availability Large': ['High Availability'],
    'IMS High Availability Large Database': ['High Availability'],
    'IMS Network': ['Network'],
    'IMS Network Compression Facility for z/OS': ['Network Skill'],
    'IMS Recovery': ['Recovery'],
    'ISC Certification': ['Computer Security', 'Security Skill'],
    'ISMS': ['ISO 27001'],
    'ISO 9001 Certification': ['Quality Management'],
    'IT Management Consultant': ['Management Skill'],
    'ITIL': ['Configuration Management', 'Service Management'],
    'Ims High Availability Large Database (Haldb)': ['High Availability'],
    'Ims High Availability Large Database (Haldb) Toolkit For Z/Os': [   'High '
                                                                         'Availability'],
    'Incident': ['Incident Ticket'],
    'Incident Reduction': ['Incident Manager'],
    'InfoSphere Data Architect': ['Data Analyst'],
    'InfoSphere Data Event': ['Data Analyst'],
    'InfoSphere Data Event Publisher': ['Data Analyst'],
    'InfoSphere Data Event Publisher for z/OS': ['Data Analyst'],
    'InfoSphere Data Replication': ['Data Analyst'],
    'InfoSphere Guardium': [   'Audit Skill',
                               'Compliance',
                               'Database Skill',
                               'Security Skill'],
    'InfoSphere Guardium Data': ['Data Analyst'],
    'InfoSphere Guardium Data Encryption': ['Data Analyst', 'Encryption'],
    'InfoSphere Master Data': ['Data Analyst'],
    'InfoSphere Master Data Management': ['Data Analyst'],
    'InfoSphere Master Data Management Collaboration Server': ['Data Analyst'],
    'InfoSphere Master Data Management Custom': ['Data Analyst'],
    'InfoSphere Master Data Management Custom Domain Hub Stand Alone': [   'Data '
                                                                           'Analyst'],
    'InfoSphere Master Data Management Server': ['Data Analyst'],
    'InfoSphere Master Data Management Server for Product Information Management': [   'Data '
                                                                                       'Analyst'],
    'Information Architect': ['Information Architecture'],
    'Information Lifecycle Management': ['Information Architecture'],
    'Information Server Data Quality': ['Data Quality'],
    'Information Server Data Quality Module': ['Data Quality'],
    'Information Server Data Quality Module for SAP': ['Data Quality'],
    'Informix Data': ['Database Skill'],
    'Infrastructure': ['Hardware Skill', 'Network Skill'],
    'Infrastructure Architect': ['Infrastructure'],
    'Infrastructure Specialist': ['Infrastructure'],
    'Initiate Master Data': ['Data Analyst'],
    'Initiate Master Data Service': ['Data Analyst'],
    'Insurance Company': ['Insurance'],
    'Integration': ['Integration Skill'],
    'Integration Architect': ['Integration Skill'],
    'Integration Framework': ['Integration Skill'],
    'Ireland Bank': ['Bank'],
    'JCL': ['Mainframe'],
    'JMP Statistical Thinking for Industrial Problem Solving': ['Statistics'],
    'Java': ['Cross Platform'],
    'Jenkins': ['Continuous Integration', 'Deployment Skill'],
    'Journey to Cloud': ['Cloud Skill'],
    'Jython': ['Java'],
    'Kaiser': ['Health Care'],
    'Kbank': ['Bank'],
    'Knowledge Graph': ['Expert System'],
    'Libquantum': ['Quantum Computing'],
    'Linus Torvalds': ['Linux'],
    'Linux': ['Open Source License'],
    'Linux Certification': ['Linux'],
    'Lloyds Bank': ['Bank'],
    'Loblaw': ['Retail'],
    'Long Term Focus': ['Positive Team Culture'],
    'Lotus Domino Access for Microsoft': ['Microsoft'],
    'Lotus Domino Access for Microsoft Outlook': ['Microsoft'],
    'Lotus Mobile Connect': ['Mobile Skill'],
    'Lotus Protector for Mail Encryption': ['Encryption'],
    'Lotus Workforce Management': ['Workforce Management'],
    'Lufthansa': ['Transportation'],
    'MQSeries': ['Integration Skill'],
    'MVS': ['Mainframe'],
    'Machine Learning': ['Linear Algebra', 'Statistics'],
    'Mainframe Operating System': ['Mainframe'],
    'Majorana Fermion': ['Quantum Computing'],
    'Management': ['Governance', 'Management Skill'],
    'Management Methodology': ['Management Skill'],
    'Management Skill': ['Soft Skill'],
    'Manager': ['Management Skill'],
    'Manufacturing Method': ['Manufacturing'],
    'Manulife': ['Life Insurance'],
    'Markup Language': ['Usability Skill'],
    'Masters Degree': ['Bachelors Degree'],
    'Maximo Adapter for Microsoft': ['Microsoft'],
    'Maximo Adapter for Microsoft Project': ['Microsoft'],
    'Maximo Archiving with Optim Data': ['Data Analyst'],
    'Maximo Archiving with Optim Data Growth': ['Data Analyst'],
    'Maximo Archiving with Optim Data Growth Solution': ['Data Analyst'],
    'Maximo Asset Management': ['Asset Management', 'Resource Management'],
    'Maximo Business Object': ['Programming Skill'],
    'Maximo Compliance Assistance Documentation': ['Compliance'],
    'Maximo Data Center': ['Data Analyst'],
    'Maximo Data Center Infrastructure': ['Data Analyst', 'Infrastructure'],
    'Maximo Data Center Infrastructure Management': [   'Data Analyst',
                                                        'Infrastructure'],
    'Maximo Mobile': ['Mobile Skill'],
    'Maximo Mobile Audit': ['Audit Skill', 'Mobile Skill'],
    'Maximo Mobile Audit Manager': ['Audit Skill', 'Mobile Skill'],
    'Maximo Mobile Audit Manager SE': ['Audit Skill', 'Mobile Skill'],
    'Maximo Mobile Inventory': ['Mobile Skill'],
    'Maximo Mobile Inventory Manager': ['Mobile Skill'],
    'Maximo Mobile Inventory Manager SE': ['Mobile Skill'],
    'Maximo Mobile Suite': ['Mobile Skill'],
    'Maximo Mobile Work': ['Mobile Skill'],
    'Maximo Mobile Work Manager': ['Mobile Skill'],
    'Maximo Mobile Work Manager SE': ['Mobile Skill'],
    'Mediate': ['Negative Workplace'],
    'Meeting Minutes': ['Team Meeting'],
    'Metadata': ['Database Schema'],
    'Metro Life': ['Life Insurance'],
    'Michelin': ['Automotive'],
    'Microcode': ['Hardware Skill'],
    'Microsoft': ['Professional Services', 'Retail', 'Technical Services'],
    'Microsoft Azure': ['Technical Services'],
    'Microsoft Certified BI Development': ['Business Intelligence'],
    'Microsoft Certified BI Reporting': ['Business Intelligence'],
    'Microsoft Certified Cloud Fundamentals': ['Cloud Skill'],
    'Migration': ['Migration Skill'],
    'Migration Support': ['Migration'],
    'Miller Coors': ['Retail'],
    'Mimix': ['Disaster Recovery', 'High Availability'],
    'Mining Protocol': ['Blockchain'],
    'Mitsui': ['Manufacturing'],
    'Mobile Device': ['Mobile Operating System'],
    'Mobile Skill': ['Mobility Computing Platform'],
    'Monitor': ['Monitoring'],
    'Monitoring': ['Security Skill'],
    'Montreal Bank': ['Bank'],
    'Motiva': ['Energy'],
    'Motivation': ['Positive Emotion'],
    'NY State': ['Government'],
    'National Railroad': ['Government', 'Transportation'],
    'Natural Language Classification': ['Natural Language Processing'],
    'Natural Language Toolkit': ['Natural Language Processing'],
    'Negative Emotion': ['Negative Situation'],
    'Negative Team Culture': ['Negative Emotion'],
    'NetBackup': ['Backup and Restore'],
    'Netcool Network Management': ['Network'],
    'Netcool Realtime Active Dashboards': ['Dashboard'],
    'Netcool/Service Monitor Reporter': ['Network Skill'],
    'Netcool/Service Monitor for Network Usage': ['Network Skill'],
    'Network': ['Network Skill'],
    'Network Configuration and Change Management': ['Network Skill'],
    'Network Design': ['Network Architect', 'Network Skill'],
    'Network Device': ['Network Skill'],
    'Network Drive': ['Storage Skill'],
    'Network Packet': ['Bandwidth'],
    'Network Product': ['Network'],
    'Network Protocol': ['Network Skill'],
    'Network Provisioning': ['Network'],
    'Network Security Policy': ['Network Security'],
    'Network Specialist': ['Network Skill'],
    'Network Standard': ['Network Skill'],
    'Network Support Specialist': ['Network Support'],
    'Network Tool': ['Network Skill'],
    'Noisy Intermediate Scale Quantum': ['Quantum Computing'],
    'Nordea': ['Financial'],
    'Novartis': ['Health Care'],
    'Novia Scotia Bank': ['Bank'],
    'Nuage Networks': ['Software Defined Network'],
    'Ohio State': ['Government'],
    'Open Source Framework': ['Open Source License'],
    'Open Source NLP Software': ['Natural Language Processing'],
    'Open Source Software': ['Open Source License'],
    'OpenStack': ['Infrastructure as a Service'],
    'Operational Model': ['Business Skill'],
    'Optim Database Administrator': ['Data Analyst'],
    'Optim Database Administrator for DB2': ['Data Analyst'],
    'Optim Database Administrator for DB2 for Linux and UNIX and Windows': [   'Data '
                                                                               'Analyst'],
    'Optimization Skill': ['Optimization'],
    'Oracle Big Data Appliance': ['Big Data'],
    'Oracle Customer Hub and Oracle Data Quality Essentials': ['Data Quality'],
    'Oracle SQL Developer': ['Database Skill'],
    'Order Management': ['Invoice'],
    'Overwork': ['Overtime'],
    'Palo Alto Networks': ['Incident Manager'],
    'Parse': ['Compiler'],
    'Patching': ['Maintenance'],
    'Penetration Test': ['Security Skill'],
    'People Manager': ['Management Skill'],
    'Performance Report': ['Measurement'],
    'Plan': ['Management Skill'],
    'Platform Analytics': ['Analytics'],
    'Platform Cluster Manager': ['Cluster'],
    'Platform HDFS Support': ['HDFS'],
    'Platform RTM Data': ['Data Analyst'],
    'Platform RTM Data Collectors': ['Data Analyst'],
    'Platform RTM Data Collectors for LSF': ['Data Analyst'],
    'Policy': ['Governance'],
    'Post Graduate': ['Graduate Degree'],
    'PowerBI': ['Business Intelligence'],
    'PowerVM Lx86 for x86 Linux': ['Linux'],
    'Presentation Skill': ['Presentation'],
    'Privacy Regulation': ['Privacy'],
    'Product Manager': ['Product Management'],
    'Professional Role': ['Professional Services'],
    'Programming Skill': ['Software', 'Technical Skill'],
    'Project Plan': ['Project Manager'],
    'Proof of Concept': ['Technical Skill'],
    'Proposal': ['Project Manager'],
    'Proventia Network Active Bypass': ['Network Skill'],
    'Proventia Network Anomaly Detection System': ['Network Skill'],
    'Proventia Network Enterprise Scanner': ['Network Skill'],
    'Proventia Network Intrusion Detection System': ['Network Skill'],
    'Proventia Network Intrusion Prevention System for Crossbeam': [   'Network '
                                                                       'Skill'],
    'Proventia Network Mail Filter': ['Network Skill'],
    'Proventia Network Mail Security': ['Network Skill'],
    'Proventia Network Mail Security System': ['Network Skill'],
    'Proventia Network Multi-Function': ['Network Skill'],
    'Proventia Network Multi-Function Security': ['Network Skill'],
    'Proventia Network Security Controller': ['Network Skill'],
    'Proventia Virtualized Network Security Platform': ['Network Skill'],
    'Provisioning Skill': ['Provisioning'],
    'Proxmox Virtual Environment': ['Deployment Skill'],
    'Proxy': ['Distributed Computing'],
    'PureData System for Operational Analytics': ['Analytics'],
    'Python': ['Cognitive Skill', 'statistical algorithm'],
    'Qiskit': ['IBM Quantum Computing'],
    'Quality of Service': ['Quality Assurance'],
    'Quantum Advantage': ['Quantum Computing'],
    'Quantum Algorithms': ['Quantum Computing'],
    'Quantum Assembly Language': ['Quantum Computing'],
    'Quantum Bit': ['Quantum Computing'],
    'Quantum Complexity Theory': ['Quantum Computing'],
    'Quantum Computation Language': ['Quantum Computing'],
    'Quantum Computing': ['Quantum Physics'],
    'Quantum Computing Platform': ['Quantum Computing'],
    'Quantum Entanglement': ['Quantum Computing'],
    'Quantum Guarded Command Language': ['Quantum Computing'],
    'Quantum Interference': ['Quantum Computing'],
    'Quantum Operation': ['Quantum Computing'],
    'Quantum Parallelism': ['Quantum Computing'],
    'Quantum Programming': ['Quantum Computing'],
    'Quantum Random Access Machine': ['Quantum Computing'],
    'Quantum Ready Workshop': ['Quantum Computing'],
    'Quantum Research': ['Quantum Computing', 'Quantum Physics'],
    'Query Disambigutation': ['Expert System'],
    'Query Language': ['Data Skill', 'Database'],
    'QuickEdd': ['Disaster Recovery', 'High Availability'],
    'Rackspace': ['Technical Services'],
    'Rackspace Cloud': ['Technical Services'],
    'Rational ClearQuest and Functional Testing': ['Testing Skill'],
    'Rational Dashboard': ['Dashboard'],
    'Rational Development and Test': ['Testing Skill'],
    'Rational Development and Test Environment for System z': ['Testing Skill'],
    'Rational Functional Tester': ['Testing Skill'],
    'Rational Functional Tester Plus': ['Testing Skill'],
    'Rational Manual Tester': ['Testing Skill'],
    'Rational Modeling Extension for Microsoft': ['Microsoft'],
    'Rational Modeling Extension for Microsoft .NET': ['Microsoft'],
    'Rational Performance Test': ['Testing Skill'],
    'Rational Performance Test Server': ['Testing Skill'],
    'Rational Performance Tester': ['Testing Skill'],
    'Rational Policy Tester': ['Testing Skill'],
    'Rational Policy Tester family': ['Testing Skill'],
    'Rational Purify for Windows': ['Windows'],
    'Rational PurifyPlus for Windows': ['Windows'],
    'Rational Service Tester': ['Testing Skill'],
    'Rational Service Tester for SOA': ['Testing Skill'],
    'Rational Service Tester for SOA Quality': ['Testing Skill'],
    'Rational Systems Tester': ['Testing Skill'],
    'Rational Test': ['Testing Skill'],
    'Rational Test RealTime': ['Testing Skill'],
    'Rational Test Virtualization': ['Testing Skill'],
    'Rational Test Virtualization Server': ['Testing Skill'],
    'Rational Test Workbench': ['Testing Skill'],
    'Rational TestManager': ['Testing Skill'],
    'Rational Tester for SOA': ['Testing Skill'],
    'Rational Tester for SOA Quality': ['Testing Skill'],
    'Rational Visual Test': ['Testing Skill'],
    'Recruiting Document': ['Recruiting Role'],
    'Recruiting Role': ['Recruiting'],
    'Redhat Certification': ['RedHat Linux'],
    'Redhat Deployment and Systems Management Certification': [   'Deployment '
                                                                  'Skill'],
    'Rembo Auto-Backup': ['Backup'],
    'Requirements Document': ['Requirement', 'Requirements Gathering'],
    'Requirements Gathering': ['Requirement'],
    'Retail Data Warehouse': ['Retail'],
    'Retirement Plan': ['Retirement'],
    'Revenue': ['Financial Skill'],
    'Risk Manager': ['Risk Management Skill'],
    'SAP Ariba SNAP Deployment': ['Deployment Skill'],
    'SAP BI Accelerator': ['Business Intelligence'],
    'SAP Cloud Platform Integration': ['Cloud Skill'],
    'SAP Cloud for Customer': ['Cloud Skill'],
    'SAP Hybris Cloud for Customer 1711': ['Cloud Skill'],
    'SAP Migration': ['Migration'],
    'SAP Rapid Deployment Solutions': ['Deployment Skill'],
    'SAS AI and Machine Learning Professional': [   'Artificial Intelligence',
                                                    'Machine Learning'],
    'SAS Advanced Analytics Certification': ['Advanced Analytics'],
    'SAS Certified Advanced Analytics Professional Using SAS 9': [   'Advanced '
                                                                     'Analytics'],
    'SAS Certified BI Content Developer for SAS 9': ['Business Intelligence'],
    'SAS Certified Big Data Professional Using SAS 9': ['Big Data'],
    'SAS Certified Data Integration Developer for SAS 9': [   'Data '
                                                              'Integration '
                                                              'Skill'],
    'SAS Certified Data Quality Steward for SAS 9': ['Data Quality'],
    'SAS Certified Data Scientist Using SAS 9': ['Data Scientist'],
    'SAS Certified Deployment Specialist for Visual Analytics 7.3': [   'Analytics',
                                                                        'Deployment '
                                                                        'Skill'],
    'SAS Certified Deployment and Implementation Specialist for SAS Grid Manager 9.4': [   'Deployment '
                                                                                           'Skill'],
    'SAS Certified Intelligence Platform Deployment Professional for SAS 9': [   'Deployment '
                                                                                 'Skill'],
    'SAS Certified Predictive Modeler Using SAS Enterprise Miner 14': [   'Data '
                                                                          'Mining',
                                                                          'Statistics'],
    'SAS Certified Specialist: Machine Learning Using SAS Viya 3.4': [   'Machine '
                                                                         'Learning'],
    'SAS Certified Statistical Business Analyst Using SAS 9: Regression and Modeling': [   'Statistics'],
    'SAS Certified Technical Specialist for Visual Analytics 7.4': [   'Analytics'],
    'SAS Certified Visual Business Analyst: Exploration and Design Using SAS Visual Analytics': [   'Analytics',
                                                                                                    'Visualization '
                                                                                                    'Skill'],
    'SAS Certified Visual Modeler Using SAS Visual Statistics 7.4': [   'Analytics',
                                                                        'Statistics',
                                                                        'Visualization '
                                                                        'Skill'],
    'SAS Natural Language and Computer Vision Specialist': [   'Computer '
                                                               'Vision',
                                                               'Natural '
                                                               'Language '
                                                               'Processing'],
    'SASS': ['Javascript'],
    'SNIA Certification': ['Storage Skill'],
    'SNIA Certified Storage Networking Expert': ['Network Skill'],
    'SOA': ['Architect'],
    'SOA Architect': ['SOA'],
    'SPARQL': ['Graph Database', 'RDF', 'RDFS'],
    'SPSS': ['Statistics'],
    'SPSS Collaboration and Deployment': ['Deployment Skill'],
    'SPSS Collaboration and Deployment Services': ['Deployment Skill'],
    'SPSS Risk': ['Risk Management Skill'],
    'SPSS Risk Control': ['Risk Management Skill'],
    'SPSS Risk Control Builder': ['Risk Management Skill'],
    'SPSS Statistics': ['Statistics'],
    'SPSS Text': ['Unstructured Data'],
    'SPSS Text Analytics': ['Analytics', 'Unstructured Data'],
    'SPSS Text Analytics for Surveys': ['Analytics', 'Unstructured Data'],
    'SPSS Visualization Designer': ['Visualization Skill'],
    'SQL': ['Database Skill'],
    'SSCP Certification': ['Infrastructure Security'],
    'Salary': ['Employee'],
    'Sales Role': ['Sales Skill'],
    'Sandvik': ['Manufacturing'],
    'Sap Successfactors Recruiting Marketing (Career Site&Advanced Analytics) Q1/2019': [   'Advanced '
                                                                                            'Analytics'],
    'Satoshi Nakamoto': ['Blockchain'],
    'Scrum Master': ['Agile', 'Scrum'],
    'Security': ['Security Skill'],
    'Security Architect': ['Security Skill'],
    'Security Network Active': ['Network Skill'],
    'Security Network Active Bypass': ['Network Skill'],
    'Security Network Controller': ['Network Skill'],
    'Security Network Intrusion Prevention System': ['Network Skill'],
    'Security Network Protection': ['Network Skill'],
    'Security Policy': ['Security'],
    'Security Product': ['Security'],
    'Security Team': ['Security Skill'],
    'Security zSecure Audit': ['Audit Skill'],
    'Security zSecure Audit for ACF2': ['Audit Skill'],
    'Security zSecure Audit for RACF': ['Audit Skill'],
    'Security zSecure Audit for Top': ['Audit Skill'],
    'Security zSecure Audit for Top Secret': ['Audit Skill'],
    'Security zSecure Compliance and Administration': ['Compliance'],
    'Security zSecure Compliance and Auditing': ['Audit Skill', 'Compliance'],
    'Semantic Web': ['Ontology'],
    'Sensu': ['Kubernetes'],
    'Server Consolidation': ['Data Center'],
    'Server Resource Management': ['Server'],
    'Server Support': ['Server'],
    'Server Support Specialist': ['Server Support'],
    'Service Integration Leader': ['Integration Skill'],
    'Service Manager': ['Service Management'],
    'ServiceNow': ['Service Desk', 'Software as a Service'],
    'Sexist Workplace': ['Sexism'],
    'Shell': ['Shell Script'],
    'Six Sigma': ['Manufacturing'],
    'Smalltalk': ['Object Oriented'],
    'Smart Analytic Optimizer': ['Analytics'],
    'Smart Analytics Optimizer for DB2': ['Analytics'],
    'Smart Analytics Optimizer for DB2 for z/OS': ['Analytics'],
    'Smart Analytics System': ['Analytics'],
    'Social Media': ['Social Media Company'],
    'Social Media Skill': ['Social Media'],
    'Softlayer': ['Hybrid cloud'],
    'Software Compliance': ['License'],
    'Software License': ['Software'],
    'Software Migration': ['Software'],
    'Software Service': ['Service Oriented Architecture'],
    'Solution Architect': ['Solution Design'],
    'Solution Manager': ['Solution Skill'],
    'Solution Value': ['Solution Design'],
    'Sony': ['Retail'],
    'Spark': ['Big Data'],
    'Speech Recognition System': ['Speech Recognition'],
    'Spend Approval': ['Financial Plan'],
    'Splunk': ['Big Data'],
    'Statistical Software': ['Statistics'],
    'Sterling Connect:Direct for Microsoft': ['Microsoft'],
    'Sterling Connect:Direct for Microsoft Windows': ['Microsoft', 'Windows'],
    'Sterling Connect:Express for Microsoft': ['Microsoft'],
    'Sterling Connect:Express for Microsoft Windows': ['Microsoft', 'Windows'],
    'Storage': ['Storage Skill'],
    'Storage Access Method': ['Mainframe'],
    'Storage Administration Workbench': ['Storage Skill'],
    'Storage Administration Workbench for z/OS': ['Storage Skill'],
    'Storage Administration Workbench for z/OS and OS/390': ['Storage Skill'],
    'Storage Architect': ['Storage Skill'],
    'Storage Enterprise Resource': ['Storage Skill'],
    'Storage Enterprise Resource Planner': ['Storage Skill'],
    'Storage Manager': ['Storage Skill'],
    'Storage Skill': ['Hardware Skill'],
    'Storage Software': ['Storage'],
    'Storage Specialist': ['Storage Skill'],
    'Stored Procedure': ['Database'],
    'Strategy Document': ['Strategic Skill'],
    'Structured Data': ['Database Skill'],
    'Support Specialist': ['User Support'],
    'Symantec NetBackup': ['Backup and Restore'],
    'System Programmer': ['Programming Skill'],
    'Systems Management': ['Server Skill'],
    'Tableau': ['Data Analyst', 'Visualization Skill'],
    'Tape Library': ['Tape'],
    'Td Bank': ['Bank'],
    'Technical Framework': ['Technical Skill'],
    'Technical Role': ['Technical Services'],
    'Technical Solution Architect': ['Solution Design'],
    'Telco Cloud Computing Platform': ['Telecommunications'],
    'Telecommunications Data Warehouse': ['Telecommunications'],
    'Test': ['Testing Skill'],
    'Test Architect': ['Testing Skill'],
    'Test Manager': ['Testing Skill'],
    'Test Plan': ['Testing Skill'],
    'Test Specialist': ['Testing Skill'],
    'Test Strategy': ['Testing Skill'],
    'Testing': ['Testing Skill'],
    'Text Mining': ['Data Scientist', 'Unstructured Data'],
    'Ticket': ['Service Desk'],
    'Time Series Database': ['Time Series'],
    'Tivoli Advanced Audit': ['Audit Skill'],
    'Tivoli Advanced Audit for DFSMShsm': ['Audit Skill'],
    'Tivoli Advanced Backup': ['Backup'],
    'Tivoli Advanced Backup and Recovery': ['Backup'],
    'Tivoli Advanced Backup and Recovery for z/OS': [   'Backup',
                                                        'Recovery',
                                                        'z/OS'],
    'Tivoli Compliance': ['Compliance'],
    'Tivoli Compliance Insight Manager': ['Compliance'],
    'Tivoli Composite Application Manager for Microsoft': ['Microsoft'],
    'Tivoli Comprehensive Network Address Translator': ['Network Skill'],
    'Tivoli Contract Compliance Manager': ['Compliance'],
    'Tivoli ETEWatch for Networked Applications Behavior Module': [   'Network '
                                                                      'Skill'],
    'Tivoli ETEWatch for Networked Applications Behavior Module for Citrix Metaframe': [   'Network '
                                                                                           'Skill'],
    'Tivoli Key Lifecycle Manager for Storage': ['Storage Skill'],
    'Tivoli License Compliance Manager': ['Compliance'],
    'Tivoli License Compliance Manager for z/OS': ['Compliance'],
    'Tivoli Monitoring for Cluster': ['Cluster'],
    'Tivoli Monitoring for Cluster Managers': ['Cluster'],
    'Tivoli Monitoring for Microsoft': ['Microsoft'],
    'Tivoli Monitoring for Network Performance': ['Network Skill'],
    'Tivoli Netcool Network Mediation': ['Network Skill'],
    'Tivoli Network Manager Entry Edition': ['Network Skill'],
    'Tivoli Network Manager IP Edition': ['Network Skill'],
    'Tivoli Network Manager Transmission Edition': ['Network Skill'],
    'Tivoli OMEGAMON XE for Mainframe': ['Mainframe'],
    'Tivoli OMEGAMON XE for Mainframe Networks': ['Mainframe', 'Network Skill'],
    'Tivoli OMEGAMON XE for Microsoft': ['Microsoft'],
    'Tivoli OMEGAMON XE for Storage': ['Storage Skill'],
    'Tivoli OMEGAMON XE for Storage on z/OS': ['Storage Skill', 'z/OS'],
    'Tivoli OMNIbus and Network Manager': ['Network Skill'],
    'Tivoli Provisioning Manager for OS Deployment': ['Deployment Skill'],
    'Tivoli Provisioning Manager for OS Deployment IBM Systems Director Edition': [   'Deployment '
                                                                                      'Skill'],
    'Tivoli Risk Manager': ['Risk Management Skill'],
    'Tivoli Security Compliance': ['Compliance'],
    'Tivoli Security Compliance Manager': ['Compliance'],
    'Tivoli Storage FlashCopy': ['Storage Skill'],
    'Tivoli Storage FlashCopy Manager': ['Storage Skill'],
    'Tivoli Storage Manager': ['Storage Skill'],
    'Tivoli Storage Manager Express': ['Storage Skill'],
    'Tivoli Storage Manager Express for Microsoft': [   'Microsoft',
                                                        'Storage Skill'],
    'Tivoli Storage Manager Express for Microsoft Exchange': ['Storage Skill'],
    'Tivoli Storage Manager Express for Microsoft SQL': ['Storage Skill'],
    'Tivoli Storage Manager Extended': ['Storage Skill'],
    'Tivoli Storage Manager Extended Edition': ['Storage Skill'],
    'Tivoli Storage Manager FastBack': ['Storage Skill'],
    'Tivoli Storage Manager FastBack Center': ['Storage Skill'],
    'Tivoli Storage Manager FastBack for Bare': ['Storage Skill'],
    'Tivoli Storage Manager FastBack for Bare Machine': ['Storage Skill'],
    'Tivoli Storage Manager FastBack for Bare Machine Recovery': [   'Recovery',
                                                                     'Storage '
                                                                     'Skill'],
    'Tivoli Storage Manager FastBack for Microsoft': [   'Microsoft',
                                                         'Storage Skill'],
    'Tivoli Storage Manager FastBack for Microsoft Exchange': [   'Microsoft',
                                                                  'Storage '
                                                                  'Skill'],
    'Tivoli Storage Manager FastBack for Workstations': ['Storage Skill'],
    'Tivoli Storage Manager HSM for Windows': ['Windows'],
    'Tivoli Storage Manager Suite for Unified Recovery': ['Recovery'],
    'Tivoli Storage Manager Suite for Unified Recovery Entry': ['Recovery'],
    'Tivoli Storage Manager for Microsoft': ['Microsoft'],
    'Tivoli Storage Manager for Microsoft SharePoint': ['Microsoft'],
    'Tivoli Storage Manager for Storage Area Networks': ['Network Skill'],
    'Tivoli Storage Manager for System Backup': ['Backup'],
    'Tivoli Storage Manager for System Backup and Recovery': [   'Backup',
                                                                 'Recovery'],
    'Tivoli zSecure Audit': ['Audit Skill'],
    'Tivoli zSecure Audit for ACF2': ['Audit Skill'],
    'Tivoli zSecure Audit for RACF': ['Audit Skill'],
    'Tivoli zSecure Audit for Top': ['Audit Skill'],
    'Tivoli zSecure Audit for Top Secret': ['Audit Skill'],
    'Tomcat': ['Java'],
    'TotalStorage Productivity': ['Storage Skill'],
    'TotalStorage Productivity Center': ['Storage Skill'],
    'TotalStorage Productivity Center for Fabric': ['Storage Skill'],
    'Trade Off': ['Negotiation Skill'],
    'Triple Store': ['RDF'],
    'Troubleshooting': ['Technical Skill'],
    'Typing Skill': ['Administrative Role'],
    'UML': ['Application Architecture', 'Design Pattern'],
    'Unicredit': ['Financial'],
    'Upgrade': ['Hardware Skill', 'Software Skill'],
    'Usability Skill': ['Usability'],
    'User': ['Customer'],
    'User Acceptance Test': ['Testing Skill'],
    'User Guide': ['Technical Writing'],
    'VERSA Analytics': ['Analytics'],
    'VERSA CSG': ['Software Defined Wide Area Network'],
    'VMWare Software': ['Hypervisor'],
    'VeloCloud': ['Virtual Cloud'],
    'Versa Networks': ['Enterprise Network'],
    'Viptela': ['Software Defined Wide Area Network'],
    'Virtual Server': ['Hardware Virtualization'],
    'Virtualization Software': ['Virtualization'],
    'Visual Dashboard': ['Visualization Skill'],
    'VisualAge': ['Programming Skill'],
    'Visualization Software': ['Visualization Skill'],
    'Watson': ['Cognitive Skill', 'statistical algorithm'],
    'Watson Wealth Advisor': ['Financial Skill'],
    'Web Application': ['Web Application Framework'],
    'WebSphere Application Accelerator for Hybrid Networks': ['Network Skill'],
    'WebSphere Application Accelerator for Public Networks': ['Network Skill'],
    'WebSphere Application Server Network Deployment': [   'Deployment Skill',
                                                           'Network Skill'],
    'WebSphere Business Integration for Financial Networks': ['Network Skill'],
    'WebSphere Dashboard Framework': ['Dashboard'],
    'WebSphere DataPower XML': ['XML'],
    'WebSphere DataPower XML Accelerator': ['XML'],
    'WebSphere DataPower XML Accelerator XA35': ['XML'],
    'WebSphere DataPower XML Security': ['XML'],
    'WebSphere DataPower XML Security Gateway': ['XML'],
    'WebSphere DataPower XML Security Gateway XS40': ['XML'],
    'WebSphere Everyplace Server for Telecom': ['Telecommunications'],
    'WebSphere Extended Deployment': ['Deployment Skill'],
    'WebSphere Extended Deployment for z/OS': ['Deployment Skill'],
    'WebSphere Message Broker Connectivity Pack for Healthcare': [   'Health '
                                                                     'Care'],
    'WebSphere Multichannel Bank Transformation Toolkit': ['Bank'],
    'WebSphere Telecom': ['Telecommunications'],
    'WebSphere Telecom Web Services Server': ['Telecommunications'],
    'WebSphere Transaction Cluster': ['Cluster'],
    'WebSphere Transaction Cluster Facility': ['Cluster'],
    'WebSphere XML': ['XML'],
    'WebSphere XML Document': ['XML'],
    'WebSphere XML Document Management': ['XML'],
    'WebSphere XML Document Management Server': ['XML'],
    'Wellpoint': ['Health Care'],
    'Westpac Bank': ['Bank'],
    'Wildfly': ['Java'],
    'Williams Glyn': ['Financial'],
    'Workshop': ['Communication Skill'],
    'Writing Skill': ['Document', 'Soft Skill'],
    'XML Standard': ['XML'],
    'Xcel Energy': ['Energy'],
    'Yara': ['Agricultural'],
    'libxml2': ['XML'],
    'z/OS': ['Mainframe Operating System'],
    'z/VSE': ['Mainframe Operating System']}
