
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_rel_owns_dict = {
    'Alibaba': ['Aliababa Certification'],
    'Amazon': ['AWS', 'AWS Certification', 'EC2', 'Redshift'],
    'Apache Software Foundation': ['Apache Software'],
    'Apple': ['Apple Mobile Device', 'iOS'],
    'Atlassian': ['Trello'],
    'Axelos': ['ITIL', 'ITIL Certification', 'PRINCE2 Certification'],
    'Bitmain': ['ASIC Mining Protocol'],
    'Cisco': ['Cisco ACI', 'Cisco Certification'],
    'Citrix': [   'Citrix Certification',
                  'Citrix Cloud',
                  'Citrix Software',
                  'XenApp'],
    'Cloud Security Alliance': ['CSA Certification'],
    'Cloudera': ['Cloudera Certification'],
    'Dell': ['Dell Certification'],
    'Facebook': ['GraphQL'],
    'Fortinet': ['FortiGate'],
    'GIAC': ['GIAC Certification'],
    'Google': ['Google Certification', 'Google Cloud'],
    'HP': ['HP Cloud', 'HP-UX'],
    'HashiCorp': ['Terraform'],
    'Hortonworks': [   'Hortonworks Certification',
                       'Hortonworks Certified Professional'],
    'IBM': [   'AIX',
               'Adabas',
               'Advanced Identity Manager',
               'Algo',
               'Alloy',
               'Alloy by IBM',
               'Alloy by IBM and SAP',
               'Application Manager',
               'Application Performance',
               'Application Recovery',
               'Application Support Facility',
               'Application Time',
               'Application Workload Modeler',
               'Archive Manager for z/VM',
               'Atlas eDiscovery',
               'Bluemix',
               'Bluemix NLC',
               'Branch Transformation',
               'Brava!',
               'Brava! Enterprise Viewer for IBM',
               'Brava! Enterprise Viewer for IBM TRIRIGA',
               'Business Monitor for z/OS',
               'Business Rules for z/OS',
               'C for VM/ESA',
               'CICS',
               'COBOL Report Writer',
               'COBOL and CICS',
               'COBOL for Systems',
               'CPLEX',
               'Clarity',
               'Cloud 9',
               'CloudBurst',
               'Cluster Systems',
               'Cognos',
               'CommonStore',
               'Communication Controller',
               'Communications Server',
               'Compiler and Library for REXX',
               'Connections Enterprise',
               'Content Analytics',
               'Content Analyzer',
               'Content Classification',
               'Content Collector',
               'Content Integrator',
               'Content Manager',
               'Content Navigator',
               'DB2',
               'DB2 Certified Database Administrator',
               'DB2 Certified Database Associate',
               'Data Encryption for IMS',
               'Data Scientist Workbench',
               'Data Server',
               'Data Studio',
               'Datacap',
               'Debug Tool for VSE/ESA',
               'Debug Tool for z/OS',
               'Decision Center',
               'DisplayWrite/370',
               'Enterprise COBOL for z/OS',
               'Enterprise Content Manager',
               'Enterprise PL/I for z/OS',
               'Enterprise Records',
               'Fault Analyzer for z/OS',
               'File Manager for z/OS',
               'FileNet',
               'Forms Designer',
               'Forms Server',
               'Forms Turbo',
               'Forms Viewer',
               'Global Data',
               'Global Retention',
               'Green Hat',
               'HTTP Server',
               'Healthcare Provider',
               'Host Access',
               'IBM Agile',
               'IBM Business Process',
               'IBM Certification',
               'IBM Corporate Division',
               'IBM Platform Software',
               'IBM Private Cloud',
               'IBM Product',
               'IBM Q',
               'IBM Quantum Computing',
               'ILOG',
               'IMS',
               'ISPF',
               'InfoSphere',
               'Information Server',
               'Informix',
               'Initiate Address',
               'Initiate Master',
               'Insurance Process',
               'Lotus',
               'MQSeries',
               'Maximo',
               'Merge Tool',
               'Messaging Extension',
               'Metrica',
               'Migration Utility for z/OS',
               'NetNOVO',
               'Netcool',
               'Netezza',
               'Network Configuration and Change Management',
               'PQEdit',
               'PointBase',
               'PowerHA',
               'PowerSC',
               'PowerVM',
               'Proventia',
               'PureApplication',
               'PureData',
               'Qiskit',
               'R-Series',
               'REXX',
               'Rational',
               'Redhat',
               'Redhat Certification',
               'Rembo',
               'Retail Data Warehouse',
               'SAN Data',
               'SCLM',
               'SOA Policy',
               'SPSS',
               'Sametime',
               'Scotia',
               'Scotia SmartModel Device',
               'Security AppScan',
               'Security Identity Manager',
               'Security Key',
               'Security Network',
               'Security Privileged',
               'Security Server Protection',
               'Security SiteProtector System',
               'Security Virtual',
               'Security zSecure',
               'Session Manager for z/OS',
               'ShowCase',
               'SmartCloud',
               'Softlayer',
               'Sterling',
               'SurePOS',
               'TPF',
               'TRIRIGA',
               'TXSeries',
               'Tape Manager for z/VM',
               'Telecommunications Data Warehouse',
               'Teleprocessing Network Simulator',
               'Tivoli',
               'Tivoli OMEGAMON XE for IBM',
               'Tivoli OMEGAMON XE for IBM Cryptographic',
               'Tivoli OMEGAMON XE for IBM Cryptographic CoProcessors',
               'Tivoli Provisioning Manager for OS Deployment IBM Systems '
               'Director Edition',
               'TotalStorage',
               'Unica',
               'Unified Messaging',
               'VS FORTRAN',
               'VTAM',
               'Virtual Desktop',
               'Virtuo',
               'VisualAge',
               'Websphere',
               'Work Optimization',
               'Work Optimization for Water Utilities on IBM',
               'Work Optimization for Water Utilities on IBM SmartCloud',
               'Workload Deployer',
               'Workload Simulator',
               'X.25',
               'eDiscovery Analyzer',
               'eDiscovery Manager',
               'i2',
               'z/OS',
               'z/VSE'],
    'ISACA': ['ISACA Certification'],
    'ISC': ['ISC Certification'],
    'ISMS': ['ISMS Certification'],
    'Juniper Networks': [   'Contrail Product',
                            'Juniper Certification',
                            'NFX Series Network Services'],
    'Microsoft': [   'Active Directory',
                     'Exchange Server',
                     'GitHub',
                     'Internet Explorer',
                     'LinkedIn',
                     'Microsoft Application Virtualization',
                     'Microsoft Azure',
                     'Microsoft Basic',
                     'Microsoft Certification',
                     'Microsoft Office',
                     'Microsoft Visual Studio',
                     'Net Framework',
                     'Outlook',
                     'Powershell',
                     'Sharepoint',
                     'Silverlight',
                     'T-SQL',
                     'Windows'],
    'Mozilla': ['Firefox'],
    'Nuage Networks': ['Nokia Nuage SDN'],
    'Oracle': [   'Endeca',
                  'Oracle Certification',
                  'Oracle Cloud',
                  'Oracle Developer Suite',
                  'Oracle Enterprise Resource Planning Cloud',
                  'Oracle SQL Developer',
                  'Oracle Secure Global Desktop',
                  'Oracle database',
                  'PL/SQL',
                  'Weblogic'],
    'PCI': ['PCI Certification'],
    'PMI': ['Project Management Professional'],
    'Palo Alto Networks': ['Palo Alto Network Certification'],
    'Rackspace': ['Rackspace Cloud'],
    'Recruiting Role': ['Candidate Pool'],
    'RedHat Linux': ['Ansible', 'OpenShift', 'Wildfly'],
    'Redhat': [   'Ceph Storage',
                  'OpenShift Platform',
                  'RedHat CloudForms',
                  'RedHat Linux',
                  'Redhat Fuse',
                  'Redhat Portfolio',
                  'Redhat Virtualization'],
    'SAP': [   'Crystal Report',
               'SAP Cloud',
               'SAP Cloud Platform',
               'SAP Converged Cloud',
               'SAP HANA Cloud Platform',
               'Sybase'],
    'SAS': ['SAS Certification'],
    'SUSE': [   'SUSE Cloud Application Platform',
                'SUSE OpenStack Cloud',
                'Suse Linux'],
    'Salesforce.com': [   'Salesforce Cloud',
                          'Salesforce Commerce Cloud',
                          'Salesforce Marketing Cloud'],
    'Storage Networking Industry Association': ['SNIA Certification'],
    'Sybase': ['SybaseIQ', 'T-SQL'],
    'Symantec': ['Symantec Workspace Virtualization'],
    'Syncsort': ['Mimix', 'QuickEdd'],
    'Teradata': ['Teradata Aster'],
    'VMWare Company': [   'VMWare Certification',
                          'VMWare Software',
                          'VMware Cloud Foundation'],
    'Versa Networks': ['VERSA Cloud', 'Versa Product'],
    'infosec': ['Infosec Certification']}
