
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# pylint:disable=bad-whitespace
# pylint:disable=line-too-long
# pylint:disable=too-many-lines
# pylint:disable=invalid-name

# #########################################################
#
#       ************** !! WARNING !! ***************
#       ******* THIS FILE WAS AUTO-GENERATED *******
#       ********* DO NOT MODIFY THIS FILE **********
#
# #########################################################


the_seealso_dict = {
    '1337X': ['1337'],
    'Abbvie Inc.': [   'Abbvie',
                       'American Publicly Traded Biopharmaceutical Company'],
    'Acceptance Testing': ['Acceptance Test'],
    'Accounting': ['Accountant'],
    'Active Record Pattern': ['Activerecord'],
    'Activity Provenance': ['Claim Of'],
    'Aesthetics': ['Design Aesthetics'],
    'Agile': ['Agile Software Development'],
    'Agricultural': ['Agricultural Industry'],
    'Aix': ['Ibm Aix'],
    'Algorithm': ['Algorithmic'],
    'Almirall': ['Spanish Pharmaceutical Company'],
    'Amgen': ['American Multinational Biopharmaceutical Company'],
    'Analysis Skill': ['Analysis And Design', 'Analytical Skill'],
    'Anthropology': ['Anthropology Course'],
    'Apache Software': ['Apache', 'Apache Software Foundation'],
    'Argument': ['Disagree'],
    'Artificial Intelligence': ['Ai'],
    'Artificial Neural Network': ['Neural Nets'],
    'Asset Management': ['Decommission'],
    'Astellas Pharma': ['Astellas'],
    'Astrazeneca': ['British-Swedish Multinational Pharmaceutical'],
    'Asv Certification': ['Approved Scanning Vendors'],
    'Automotive': ['Automotive Industry'],
    'Awareness': ['Cognizant'],
    'Aws': ['Amazon Web Services'],
    'Back End': ['Backend', 'Data Access Layer'],
    'Biological Anthropology': ['Physical Anthropology'],
    'Biology': ['Biological Science'],
    'Biotechnology': ['Biotech'],
    'Bitcoin Mining': ['Cryptomining'],
    'Blackberry Enterprise Server': ['Bes'],
    'Blackberry Mobile Device': ['Blackberry'],
    'Blade Server': ['Blade'],
    'Bluemix': ['Ibm Cloud'],
    'Bonus Pay': ['Bonus'],
    'Botnet': ['Bot Net'],
    'Brand Specialist': ['Brand Management'],
    'Bristol-Myers Squibb': ['Bristol-Myers Squibb (Bms)'],
    'Business Leader': ['Business Lead'],
    'Business Requirement': ['Business Logic'],
    'Business Skill': ['Strategic Skill'],
    'C Language': ['C Plus Plus'],
    'C#': ['C Sharp'],
    'Career Growth': ['Professional Growth'],
    'Ccsk Certification': ['Certificate Of Cloud Security Knowledge'],
    'Certified Desktop Administrator': [   'Microsoft 365 Certified: Modern '
                                           'Desktop Administrator Associate'],
    'Certified Enterprise Administrator': [   'Microsoft 365 Certified: '
                                              'Enterprise Administrator '
                                              'Expert'],
    'Certified Messaging Administrator': [   'Microsoft 365 Certified: '
                                             'Messaging Administrator '
                                             'Associate'],
    'Certified Microsoft Access': ['Mos: Microsoft Access 2016'],
    'Certified Microsoft Excel': ['Mos: Microsoft Excel 2016'],
    'Certified Microsoft Office': [   'Mos: Microsoft Office 2016 Master '
                                      'Specialist'],
    'Certified Microsoft Outlook': ['Mos: Microsoft Outlook 2016'],
    'Certified Microsoft Powerpoint': ['Mos: Microsoft Powerpoint 2016'],
    'Certified Security Administrator': [   'Microsoft 365 Certified: Security '
                                            'Administrator Associate'],
    'Certified Teamwork Administrator': [   'Microsoft 365 Certified: Teamwork '
                                            'Administrator Associate'],
    'Certified Windows Server 2012': ['Windows Server 2012'],
    'Certified Windows Server 2016': ['Windows Server 2016'],
    'Cheat Engine': ['New Cheat'],
    'Cheating In Online Games': [   'Aimbot',
                                    'Aimbotting',
                                    'Fairfight',
                                    'Triggerbot',
                                    'Wall Hacks',
                                    'Wallhacking'],
    'Citi': ['Citibank', 'Citigroup'],
    'Citrix Certified Mobility Professional': [   'Citrix Certified '
                                                  'Professional – Mobility '
                                                  '(Ccp-M)'],
    'Citrix Certified Networking Associate': [   'Citrix Certified Associate – '
                                                 'Networking (Cca-N)'],
    'Citrix Certified Networking Expert': [   'Citrix Certified Expert - '
                                              'Networking (Cce - N)'],
    'Citrix Certified Networking Professional': [   'Citrix Certified '
                                                    'Professional – Networking '
                                                    '(Ccp-N)'],
    'Citrix Certified Virtualization Associate': [   'Citrix Certified '
                                                     'Associate – '
                                                     'Virtualization (Cca-V)'],
    'Citrix Certified Virtualization Expert': [   'Citrix Certified Expert – '
                                                  'Virtualization (Cce-V)'],
    'Citrix Certified Virtualization Professional': [   'Citrix Certified '
                                                        'Professional – '
                                                        'Virtualization '
                                                        '(Ccp-V)'],
    'Citrix Cloud Certification': [   'Citrix Virtual Apps And Desktops '
                                      'Service On Citrix Cloud Certified'],
    'Citrix Endpoint Management Certified': [   'Citrix Endpoint Management '
                                                'Certified (Cc-Cem)'],
    'Citrix Microsoft Azure Certified': [   'Citrix Virtual Apps And Desktops '
                                            'Service Integration With '
                                            'Microsoft Azure Certified'],
    'Citrix Netscaler Certification': [   'Citrix Netscaler Sd-Wan Certified '
                                          '(Cc-Sdwan)'],
    'Citrix Sharefile Certified': ['Citrix Sharefile Certified (Cc-Sharefile)'],
    'Classics': ['Classical Study'],
    'Client Skill': [   'Client Relationship',
                        'Client Request',
                        'Client Satisfaction',
                        'Customer Engagement',
                        'Customer Team'],
    'Cloud Computing Platform': ['Cloud', 'Cloud Computing'],
    'Cloud Security Alliance': ['Csa'],
    'Cluster Computing': ['Parallel Computing'],
    'Coaching Skill': ['Coach', 'Mentor'],
    'Cognitive Testing': ['Cognitive Test'],
    'Commerce': ['E Commerce'],
    'Communication Protocol': ['Technical Communication'],
    'Communication Skill': [   'Communication',
                               'Evangelize',
                               'Presentation',
                               'Speak'],
    'Competitive Research': ['Consumer Research', 'Marketing Research'],
    'Compliance Testing': ['Compliance Test'],
    'Computational Science': ['Scientific Computing'],
    'Computer Configuration': ['Configurability'],
    'Computer Security': ['Cyberdefense'],
    'Computer Vision': ['Image Recognition'],
    'Consulting Skill': ['Consulting'],
    'Content Management Framework': ['Content Management'],
    'Cssa Certification': ['Scada Security Architect Certification'],
    'Cultural Studies': ['Cultural Study'],
    'Customer': ['Corporate Customer'],
    'Customer Behavior': ['Customer Experience'],
    'Customer Service': ['Customer Support'],
    'Dashboard': ['Business Dashboard'],
    'Data Analysis Skill': ['Analytics', 'Data Analysis', 'Data Wrangling'],
    'Data Encryption': ['Disk Encryption'],
    'Data Privacy': ['Data Security'],
    'Data Scientist': ['Data Science'],
    'Data Warehouse': ['Warehouse'],
    'Database Dimension': ['Data Dimension', 'Dimension', 'Multi Dimension'],
    'Db2': ['Ibm Db2'],
    'Delivery Model': ['Delivery Time'],
    'Delivery Skill': ['Deadline'],
    'Delphi': ['Object Pascal'],
    'Denial-Of-Service Attack': [   'Ddos',
                                    'Ddos Attack',
                                    'Ddosed',
                                    'Ddoser',
                                    'Ddosing'],
    'Deployment Skill': ['Deployment', 'Devop'],
    'Design Pattern': ['Architectural Pattern'],
    'Design Skill': ['Analysis And Design'],
    'Device Programming Skill': ['Device Programming'],
    'Disk Drive': ['Hard Disk'],
    'Display Resolution': ['Screen Quality'],
    'Distributed Computing': ['Distribute System'],
    'Distributed File System': ['Clustered File System'],
    'Diversity': ['Inclusive'],
    'Docker': ['Container', 'Dockercon'],
    'Doctoral Degree': ['Phd'],
    'Document Manager': ['Document Management System'],
    'Domain Skill': ['Best Practice', 'Subject Matter Expert'],
    'Dow Chemical Company': [   'American Multinational Chemical Corporation',
                                'German Chemical Company'],
    'Downtime': ['Outage'],
    'Dynamics 365 For Customer Service': [   'Dynamics 365 For Customer '
                                             'Service Functional Consultant '
                                             'Associate'],
    'Dynamics 365 For Finance And Operations': [   'Financials Functional '
                                                   'Consultant Associate'],
    'Dynamics 365 For Marketing': [   'Dynamics 365 For Marketing Functional '
                                      'Consultant Associate'],
    'Dynamics 365 For Sales': [   'Microsoft Certified: Dynamics 365 For Sales '
                                  'Functional Consultant Associate'],
    'Earth Science': ['Geosciences'],
    'Economics': ['Economic'],
    'Elasticsearch': ['Logstash'],
    'Emerging Technologies': ['Emerging Technology'],
    'Empathy': ['Encourage', 'Supportive'],
    'Energy': ['Energy Industry'],
    'Ethernet': ['Ieee 802.3'],
    'Etl': ['Extract Transform Load'],
    'Exchange Server': ['Exchange', 'Microsoft Exchange Server'],
    'Feasibility Study': ['Feasibility'],
    'Field-Programmable Gate Array': ['Fpga', 'Fpgas'],
    'Financial': ['Finance'],
    'Financial Plan': ['Budget'],
    'Financial Technology': ['Fintech'],
    'Finite Element Method': ['Finite Element Analysis'],
    'Fixed Asset': ['Capital Asset'],
    'Flexible Environment': ['Flexible Work'],
    'Focus': ['Vision'],
    'Front End': ['Presentation Layer'],
    'Full Stack Developer': ['Full Stack'],
    'Gasf Certification': ['Giac Advanced Smartphone Forensics'],
    'Gateway': ['Network Gateway'],
    'Gawn Certification': ['Giac Assessing And Auditing Wireless Networks'],
    'Gccc Certification': ['Giac Critical Controls Certification'],
    'Gcda Certification': ['Giac Certified Detection Analyst'],
    'Gced Certification': ['Giac Certified Enterprise Defender'],
    'Gcfa Certification': ['Giac Certified Forensic Analyst'],
    'Gcfe Certification': ['Giac Certified Forensic Examiner'],
    'Gcia Certification': ['Giac Certified Intrusion Analyst'],
    'Gcih Certification': ['Giac Certified Incident Handler'],
    'Gcip Certification': ['Giac Critical Infrastructure Protection'],
    'Gcpm Certification': ['Giac Certified Project Manager'],
    'Gcti Certification': ['Giac Cyber Threat Intelligence'],
    'Gcux Certification': ['Giac Certified Unix Security Administrator'],
    'Gcwn Certification': ['Giac Certified Windows Security Administrator'],
    'Gdat Certification': ['Giac Defending Advanced Threats'],
    'Gdpr': ['General Data Protection Regulation'],
    'Gdsa Certification': ['Giac Defensible Security Architecture'],
    'General-Purpose Computing On Graphics Processing Units': ['Gpgpu'],
    'Geographic Information System': ['Gis'],
    'Geva Certification': ['Giac Enterprise Vulnerability Assessor'],
    'Giscp Certification': ['Global Industrial Cyber Security Professional'],
    'Gisf Certification': ['Giac Reverse Engineering Malware'],
    'Gisp Certification': ['Giac Information Security Professional'],
    'Gleg Certification': ['Giac Law Of Data Security & Investigations'],
    'Glossary Of Video Game Terms': ['Aim Bot'],
    'Gmob Certification': ['Giac Mobile Device Security Analyst'],
    'Gmon Certification': ['Giac Continuous Monitoring Certification'],
    'Gnfa Certification': ['Giac Network Forensic Analyst'],
    'Google Cardboard': ['Vr App'],
    'Google Certified Android Developer': [   'Associate Android Developer '
                                              'Certification'],
    'Google Certified Associate Cloud Engineer': [   'Associate Cloud Engineer '
                                                     'Certification'],
    'Google Certified Mobile Web Specialist': [   'Mobile Web Specialist '
                                                  'Certification'],
    'Google Certified Professional Cloud Architect': [   'Professional Cloud '
                                                         'Architect '
                                                         'Certification'],
    'Google Certified Professional Data Engineer': [   'Professional Data '
                                                       'Engineer '
                                                       'Certification'],
    'Gpen Certification': ['Giac Penetration Tester'],
    'Gppa Certification': ['Giac Certified Firewall Analyst'],
    'Gpyc Certification': ['Giac Python Coder'],
    'Greeting': ['Hello'],
    'Grem Certification': ['Giac Reverse Engineering Malware'],
    'Grid Certification': ['Giac Response And Industrial Defense'],
    'Groupware': ['Collaborative Software', 'Social Software'],
    'Gse Certification': ['Giac Security Expert'],
    'Gsec Certification': ['Giac Security Essentials'],
    'Gslc Certification': ['Giac Security Leadership'],
    'Gsna Certification': ['Giac Systems And Network Auditor'],
    'Gssp Certification': ['Giac Secure Software Programmer'],
    'Gstrt Certification': [   'And Leadership',
                               'Giac Strategic Planning',
                               'Policy'],
    'Gwapt Certification': ['Giac Web Application Penetration Tester'],
    'Gweb Certification': ['Giac Certified Web Application Defender'],
    'Gxpn Certification': [   'Giac Exploit Researcher And Advanced '
                              'Penetration Tester'],
    'Hacker': ['Hackability', 'So Many Hackers'],
    'Harassment': ['Crossing The Line', 'Workplace Harassment'],
    'Hardware Test': ['Hardware Testing'],
    'Hdfs': ['Platform Hdfs'],
    'Heuristic': ['Heuristics'],
    'Hikma Pharmaceuticals': ['German Multinational Pharmaceutical'],
    'Home Office': ['Mobile Office', 'Work From Home'],
    'Human Factors And Ergonomics': ['Ergonomics'],
    'Ibm Product': ['Ibm Internal'],
    'Implementation Role': ['Implement'],
    'Industry Insight': ['Industry Context'],
    'Influxdb': ['Telegraf'],
    'Information Architect': ['Data Architect'],
    'Information Architecture': ['Data Architecture'],
    'Information Governance': ['Data Governance'],
    'Information Security': ['Infosec'],
    'Infrastructure As A Service': ['Infrastructure Service'],
    'Install': ['Uninstall'],
    'Insurance': ['Insurance Industry'],
    'Internal Transfer': ['Project Transfer'],
    'Interview Skill': ['Interview'],
    'Intuition': ['Intuitiveness'],
    'Inventory Process': ['Inventory Tracking'],
    'Ip Address Blocking': ['Ip Ban'],
    'Isa Certification': ['Internal Security Assessor'],
    'Isaca': ['Information Systems Audit And Control Association'],
    'Iso Standard': ['International Standards Organization'],
    'Java Database Connectivity': ['Jdbc'],
    'Java Platform, Enterprise Edition': ['J2Ee'],
    'Just-In-Time Manufacturing': ['Jit'],
    'Keystroke Logging': ['Combat Logger', 'Keylogged', 'Keylogger'],
    'Killer Application': ['Killer App'],
    'Knowledge Management': ['Data Management', 'Information Management'],
    'Kpi': ['Performance Indicator'],
    'Leadership Role': ['Leadership'],
    'Learning Presentation': ['Show What You Know'],
    'Leet': ['L33T'],
    'Level 1 Customer Service': ['Level 1'],
    'Level 2 Customer Service': ['Level 2'],
    'Level 3 Customer Service': ['Level 3'],
    'Lightweight Directory Access Protocol': ['Ldap'],
    'Line Manager': ['Line Management'],
    'Load Testing': ['Load Test'],
    'Log File': ['Event Log'],
    'Lotus Notes': ['Ibm Notes'],
    'Low Pay Level': ['Poor Pay'],
    'Mainframe': ['Mainframe Computer'],
    'Management': ['Senior Management'],
    'Managment Training': ['Managment Enablement'],
    'Manufacturing Company': ['Network Equipment Provider'],
    'Market Standard': ['Industry Trend'],
    'Master Data Management': ['Master Data'],
    'Master Inventor': ['Ibm Master Inventor'],
    'Master Of Business': ['Mba'],
    'Mathematical Finance': ['Quantitative Finance'],
    'Mathematical Logic': ['Symbolic Logic'],
    'Mcdba Certification': ['Microsoft Certified Database Administrator'],
    'Measurement': ['Metric'],
    'Memory-Mapped I/O': ['I O'],
    'Mentor': ['Knowledge Share'],
    'Microservices': ['Micro Service'],
    'Microsoft Certification': ['Microsoft Certified Professional'],
    'Microsoft Certified Bi Development': ['Sql 2016 Bi Development'],
    'Microsoft Certified Bi Reporting': ['Bi Reporting'],
    'Microsoft Certified Blockbased Languages': [   'Mta: Introduction To '
                                                    'Programming Using '
                                                    'Block-Based Languages'],
    'Microsoft Certified Cloud Fundamentals': ['Mta: Cloud Fundamentals'],
    'Microsoft Certified Database Administration': [   'Sql 2016 Database '
                                                       'Administration'],
    'Microsoft Certified Database Development': [   'Sql 2016 Database '
                                                    'Development'],
    'Microsoft Certified Database Fundamentals': ['Mta: Database Fundamentals'],
    'Microsoft Certified Development Fundamentals': [   'Mta: Software '
                                                        'Development '
                                                        'Fundamentals'],
    'Microsoft Certified Html And Css': [   'Mta: Introduction To Programming '
                                            'Using Html And Css'],
    'Microsoft Certified Html5': [   'Mta: Html5 Application Development '
                                     'Fundamentals'],
    'Microsoft Certified Java Programmer': [   'Mta: Introduction To '
                                               'Programming Using Java'],
    'Microsoft Certified Javascript Programmer': [   'Mta: Introduction To '
                                                     'Programming Using '
                                                     'Javascript'],
    'Microsoft Certified Mobility Fundamentals': [   'Mta: Mobility And Device '
                                                     'Fundamentals'],
    'Microsoft Certified Networking Fundamentals': [   'Mta: Networking '
                                                       'Fundamentals'],
    'Microsoft Certified Professional': ['Mcp'],
    'Microsoft Certified Security Fundamentals': ['Mta: Security Fundamentals'],
    'Microsoft Certified Sql Server': ['Sql Server 2012/2014'],
    'Microsoft Certified Web Applications': ['Web Applications'],
    'Microsoft Certified Windows Fundamentals': [   'Mta: Windows Operating '
                                                    'System Fundamentals'],
    'Microsoft Certified Windows Server Fundamentals': [   'Mta: Windows '
                                                           'Server '
                                                           'Administration '
                                                           'Fundamentals'],
    'Microsoft Hololens': ['Hololens'],
    'Migration Skill': ['Migration'],
    'Mindfulness': ['Mindful'],
    'Minecraft': ['Minechat'],
    'Minority Employee': ['Minority'],
    'Mobile Device': ['Handheld Computer'],
    'Mobility Computing Platform': ['Mobile Computing'],
    'Model Testing': ['Model Test'],
    'Motivation': ['Motivate'],
    'Name Server': ['Domain Name Server'],
    'Natural Language Toolkit': ['Nltk'],
    'Negative Team Culture': [   'Blame Culture',
                                 'No Conversation',
                                 'Unapproachable'],
    'Negotiation Skill': ['Alliance', 'Negotiation'],
    'Network Database': ['Network Model'],
    'Network Downtime': ['Network Outage'],
    'Network Protocol': ['Internet Protocol'],
    'Network Security': ['Cybersecurity'],
    'Network Specialist': ['Network Administrator'],
    'Network Support Specialist': ['Network Management'],
    'Neuroscience': ['Neurobiology'],
    'New Employee': ['New Hire'],
    'Oculus Vr': ['Vr Technology'],
    'Offering': ['Ibm Offering'],
    'Offshore Team': ['Offshore'],
    'Onsite Training': ['Class Training'],
    'Open Source Software': ['Open Source'],
    'Openstack': ['Open_Stack'],
    'Operational Analytics': ['It Operations Analytics'],
    'Operational Role': ['Operational'],
    'Operations Analyst': ['Operation Analyst'],
    'Operations Manager': ['Operations Management'],
    'Operations Research': ['Operation Research'],
    'Oracle Customer Care And Billing': ['Oracle Ccb'],
    'Oracle Database': ['Oracle'],
    'Organizational Pay': ['Salary'],
    'P2P Encryption': ['Point-To-Point Encryption'],
    'P2Pe Assessor Certification': [   'Point-To-Point Encryption Qualified '
                                       'Security Assessors'],
    'Paleontology': ['Palaeontology'],
    'Paqsa Certification': ['Payment Application Qualified Security Assessors'],
    'Pay Level': ['Pay Process'],
    'Pay Level Increase': ['Pay Raise'],
    'Pci': ['Pci Security Standards Council'],
    'Peer-To-Peer': ['Peertopeer'],
    'Penalty': ['Pay Penalty'],
    'Personal Computer': ['Personal Pc'],
    'Petroleum': ['Petroleum Industry'],
    'Philology': ['Philologist'],
    'Philosophy': ['Philosophy Student'],
    'Phish': ['Phished', 'Phisher'],
    'Phishing': ['Phishing Link'],
    'Plan': ['Plan Development'],
    'Pleasure': ['Glad'],
    'Political Philosophy': ['Political Theory'],
    'Political Science': ['Poli Science'],
    'Positive Emotion': ['Positive'],
    'Postgresql': ['Postgres'],
    'Power Server': ['Ibm Power', 'Ibm System I', 'Ibm System P'],
    'Powerpc': ['Pc Power'],
    'Powershell': ['Windows Powershell'],
    'Presales Role': ['Presales'],
    'Price Optimization': ['Pricing Info'],
    'Prince2 Certification': ['Projects In Controlled Environments'],
    'Process': ['Internal Process'],
    'Production Environment': ['Go Live'],
    'Programming Skill': ['Programmer'],
    'Project Scope': ['Scope'],
    'Provisioning Skill': ['Provisioning'],
    'Proxmox Virtual Environment': ['Proxmox'],
    'Proxy': ['Proxy Server'],
    'Pyspark': ['Apache Spark'],
    'Qir Certification': ['Qualified Integrators And Resellers'],
    'Qsa Certification': ['Qualified Security Assessor'],
    'Quality Improvement': ['Corrective Action'],
    'Query Language': ['Query'],
    'Recruiting Document': ['Recruitment System'],
    'Recruiting Role': [   'Recruiter',
                           'Recruitment Strategy',
                           'Talent Acquisition'],
    'Redhat Certified Engineer': ['Rhce'],
    'Redhat Certified System Administrator': ['Rhcsa'],
    'Redhat Linux': ['Redhat'],
    'Regression Testing': ['Regression Test'],
    'Regulation': ['Legislation'],
    'Relational Database': ['Relational'],
    'Release Strategy': ['Release Schedule'],
    'Remediate': ['Remediation'],
    'Remote Procedure Call': ['Rpc'],
    'Remote Team': ['Virtual Team'],
    'Reporting Software': ['Business Reporting', 'Reporting'],
    'Requirement': ['Raci'],
    'Resource Management': ['Decommission'],
    'Rfp': ['Request For Proposal'],
    'Rfs': ['Request For Service'],
    'Risk Management Skill': ['Risk Management'],
    'Robotic Device': ['Robotics'],
    'Salary': ['Earning', 'Employee Pay'],
    'Sales Skill': ['Business Development', 'Business Pitch'],
    'Sametime': ['Ibm Sametime'],
    'Sap Project': ['Sap Implementation'],
    'Scientific Programming Language': ['Scientific Programming'],
    'Script Kiddie': ['Script Kiddy', 'Skiddie'],
    'Securities Offering': ['Funding Round'],
    'Security Account Manager': ['Dummy Account'],
    'Security Skill': ['Vulnerability Management'],
    'Serial Peripheral Interface': ['Spi'],
    'Server Message Block': ['Cifs'],
    'Server Support Specialist': ['Server Operation'],
    'Service': ['It Service'],
    'Service Desk': ['Call Management System', 'Customer Support', 'Help Desk'],
    'Service Management': ['It Service Management'],
    'Service Oriented Architecture': ['Soa'],
    'Sexism': ['Sexist'],
    'Signal Processing': ['Signal Process'],
    'Silverlight': ['Microsoft Silverlight'],
    'Sizing Skill': ['Sizing'],
    'Snia Certification': ['Storage Networking Certification Program'],
    'Social Science': ['Social Scientist'],
    'Social Studies': ['Social Study'],
    'Software Development Lifecycle': ['Software Development Process'],
    'Software Methodology': ['Development Methodology'],
    'Software Migration': ['Application Migration; Migrate Applications'],
    'Software Quality': ['Code Quality'],
    'Software Testing': ['Software Test'],
    'Solution Skill': ['Solution Strategy'],
    'Sql': ['Database Query'],
    'Sql Server Integration Services': ['Ssis'],
    'Sql Server Management Studio': ['Ssms'],
    'Static Program Analysis': ['Static Analysis'],
    'Static Testing': ['Static Test'],
    'Statistics': [   'Probability',
                      'Statistic',
                      'Statistical Algorithm',
                      'Statistical Application'],
    'Storage': ['Ibm Storage'],
    'Storage Platform': ['Storage Product'],
    'Suggestion': ['Request Find'],
    'Sun Pharmaceutical': [   'Indian Multinational Pharmaceutical Company',
                              'Multinational Pharmaceutical Company With'],
    'Supercomputer': ['Supercomputers', 'Supercomputing'],
    'Suse Linux': ['Suse Linux Distributions'],
    'System Administrator': ['Systems Management Specialist'],
    'System Programming Skill': ['System Programming', 'Systems Expert'],
    'System Role': ['System Operator'],
    'Systems Design': ['System Design'],
    'Tabular Database': ['Tabular'],
    'Takeda Pharmaceutical Company': ['Japanese Pharmaceutical Company'],
    'Team': ['Ibm Team'],
    'Team Culture': ['Work Environment', 'Work Experience'],
    'Team Skill': ['Collaborate', 'Team Building'],
    'Technical Role': ['Engineer'],
    'Technical Team Lead': ['Lead Developer', 'Technical Lead'],
    'Technical Training': ['Technical Enablement'],
    'Technical Writing': ['Technical Writer'],
    'Telecommunications': ['Communication Player', 'Telecommunication'],
    'Test Plan': ['Test Script'],
    'Testing Skill': ['Testing'],
    'Trade Off': ['Trade Offs'],
    'Training': ['Think40', 'Train'],
    'Troubleshooting': ['Problem Solving'],
    'Twitter Bot': ['Bot Account'],
    'Unsatisfied': ['Demotivating', 'Inadequate'],
    'Usability Skill': ['User Management'],
    'User Interface Design': ['Ui Design'],
    'User Research': ['User Centered Design'],
    'User Support': ['Pc Support'],
    'Value Proposition': ['Business Value Statement'],
    'Venture Round': ['Series C Financing Round'],
    'Video Game Exploit': ['Speedhacking'],
    'Virtualization Software': ['Virtualization Tool'],
    'Visual Basic': ['Visual Basic For Applications'],
    'Visual Designer': [   'Communication Designer',
                           'Graphic Artist',
                           'Graphic Designer'],
    'Visualization': ['Graphic'],
    'Vmware Vsphere': ['Vsphere'],
    'Vsam': ['Virtual Storage Access Method'],
    'Web Application': ['Web App', 'Webapps'],
    'Web Developer': ['Web Developers'],
    'Weblogic': ['Oracle Weblogic Server'],
    'Westpac Bank': ['Westpac'],
    'Wifi': ['Ieee 802.11'],
    'Wildfly': ['Jboss'],
    'Windows Management Instrumentation': ['Wmi'],
    'Windows Server': ['Windows Nt'],
    'Work Culture': ['Work Environment', 'Work Experience'],
    'Work Life Balance': ['Personal Life'],
    'Workflow Language': ['Process Automation'],
    'Workplace': ['Office'],
    'Writing Skill': ['Publish', 'Writing'],
    'Xen': ['Xenserver'],
    'Yaml': ['Yml']}
